#1053 Translate Backstories.xml
Ludeon/RimWorld-ru pull request #1074
Opened 2020-05-15 17:05 UTC by kamadz

PamperedLordling37-RoyalBastard3

2020-08-24 21:59 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? поддерживал : поддерживала} мир на улицах города как обычный сотрудник полиции.\n\n{PAWN_pronoun} {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} раз
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? поддерживал : поддерживала} порядок на улицах города как обычный сотрудник полиции.\n\n{PAWN_pronoun} {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} разрешению конфликтных ситуаций, силовому контролю, стрельбе и другим важным для полицейских навыкам.</desc>
```

2020-08-24 22:00 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>В свободное от тренировок или битвы время, {PAWN_nameDef} часто {PAWN_gender ? находился : находилась} рядом с капелланом. {PAWN_pronoun} {PAWN_gender ? посвятил : посвятила} свою жизнь служб
```suggestion
		<desc>В свободное от тренировок или битвы время, {PAWN_nameDef} {PAWN_gender ? проводил : проводила} много времени рядом с капелланом. {PAWN_pronoun} {PAWN_gender ? посвятил : посвятила} свою жизнь службе и своему лорду, и религии.</desc>
```

2020-08-25 13:49 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
```suggestion
		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо ребёнка.\n\n{PAWN_pronoun} {PAWN_gender ? занимался : занималась} многими вопросами знатной семьи, начиная финансами и заканчивая жадными родственниками, желавшими узурпировать престол. {PAWN_nameDef} никогда не {PAWN_gender ? злоупотреблял : злоупотребляла} своим положением.</desc>
```

2020-09-28 23:12 UTC, Elevator89 requested changes

2020-09-28 23:12 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} от лорда и проститутки.\n\nЛиния наследования {PAWN_possessive} отца была надежной, а власть — значительна. Никто так и не пришёл рассказать
```suggestion
		<desc>{PAWN_nameDef} — {PAWN_gender ? сын : дочь} лорда и проститутки.\n\nЛиния наследования {PAWN_possessive} отца была надежной, а власть — значительной, поэтому никто так и не пришёл рассказать {PAWN_nameDef} о {PAWN_possessive} правах на престол. {PAWN_pronoun} {PAWN_gender ? зарабатывал : зарабатывала} на жизнь, убираясь в борделе, но всегда {PAWN_gender ? чувствовал : чувствовала} что заслуживает большего.</desc>
```

2020-09-29 08:30 UTC, Blinnna commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} от лорда и проститутки.\n\nЛиния наследования {PAWN_possessive} отца была надежной, а власть — значительна. Никто так и не пришёл рассказать
надёжной?

2020-09-29 08:32 UTC, Blinnna commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
отвечал за многие дела знатной  - тут же тоже надо на гендер поделить?

2020-09-29 13:00 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShort>каприза</titleShort>
уйдёт в батч

2020-09-29 13:00 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<!-- EN: [PAWN_nameDef] was a mining eng нетineer for a major planetary mining corporation. [PAWN_pronoun] work kept [PAWN_objective] underground for weeks at a time, and [PAWN_pronoun] grew to app
упс

2020-09-29 13:04 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>офицер полиции</titleShortFemale>
Слово "полицейская" в русском языке используется в основном как субстантивированное прилагательное. "Полицейская", как офицер полиции женского пола - низкий стиль.

2020-09-29 13:07 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} профессиональным военным снайпером. {PAWN_pronoun} {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} быстро занимать неожиданные огневые по
Не вижу смысла замены одного пассива на другой.
"Уходить" добавлю.

2020-09-29 13:09 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
"Гуглоперевод во все поля. Хоть и местами подпудренный." - Можно обойтись и без подобных пассажей, Андрей.
Можно просто сказать что и почему конкретно тебя не устраивает.

2020-09-29 13:13 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} профессиональным военным снайпером. {PAWN_pronoun} {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} быстро занимать неожиданные огневые по
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} профессиональным военным снайпером. {PAWN_pronoun} {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} быстро занимать неожиданные огневые позиции, меткими выстрелами устранять поставленные цели и уходить, прежде чем противник мог раскрыть {PAWN_possessive} местоположение.</desc>
```

2020-09-29 13:20 UTC, AndreyLemin commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
Так я уже сказал. Меня не устраивает использование машинного перевода. Принципиально. Даже если его скорректировать, получается заметная потеря в качестве.

2020-09-29 13:21 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
Так я уже сказал. Меня не устраивает использование машинного перевода. Принципиально. Даже если его скорректировать, получается заметная потеря в качестве.

2020-09-29 13:23 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
@Blinnna , исправил

2020-09-29 13:24 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} от лорда и проститутки.\n\nЛиния наследования {PAWN_possessive} отца была надежной, а власть — значительна. Никто так и не пришёл рассказать
да

2020-09-29 13:24 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
Не знаю, из какого пальца ты это высосал, но я машинными переводчиками в работе не пользуюсь.
Не буду спорить, что, возможно, исходник не ахти. Это всегда можно исправить.

2020-09-29 13:26 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} профессиональным военным снайпером. {PAWN_pronoun} {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} быстро занимать неожиданные огневые по
Смысл в устранении повторения слова "был". Да и смысла в нём во втором случае нет от слова совсем.

2020-09-29 13:31 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
```suggestion
		<desc>После того, как глава дружественной {PAWN_nameDef} семьи был убит, его наследником стал несовершеннолетний сын, а {PAWN_nameDef} {PAWN_gender ? был назначен: была назначена} его регентом.\n\n{PAWN_nameDef} {PAWN_gender ? отвечал : отвечала} за многие дела знатной семьи: от составления бюджета и ведения военных дел до противостояния попыткам узурпации власти жадными родственниками. {PAWN_pronoun} никогда не {PAWN_gender ? злоупотреблял : злоупотребляла} своим положением.</desc>
```

2020-09-29 13:33 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} профессиональным военным снайпером. {PAWN_pronoun} {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} быстро занимать неожиданные огневые по
Стилистическая разница в высказываниях "он был обучен убивать" и "он обучен убивать", особенно в контексте перечисления важных событий из прошлого - есть.

2020-09-29 13:35 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
Подскажи мне, как ты в этом куске предложения увидел то, что увидел?
"from finances to war to greedy relatives intent on usurping the throne."
Перечисление:
1. Финансы
2. Война
3. Родственники
У тебя это:
1. Военные финансы
2. Родственники

Удивительные метаморфозы.

2020-09-30 21:49 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} профессиональным военным снайпером. {PAWN_pronoun} {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} быстро занимать неожиданные огневые по
Не игнорируй сути. Смысловой разницы между "его обучили увивать" и "он умеет убивать" в данном контексте - ноль. 
А повтор "был"-"был" в двух предложениях подряд выглядит очень криво.

2020-09-30 21:53 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
> Не знаю, из какого пальца ты это высосал

И это говорит тот, кто критикует за "пассажи" в его адрес.

Примерно из этого пальца:

![изображение](https://user-images.githubusercontent.com/21694533/94743627-fd43c280-0377-11eb-9d84-69295b92409d.png)

Сравни со своим переводом.

2020-09-30 21:57 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
А чего в отдельном треде?

2020-09-30 22:06 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>офицер полиции</titleShortFemale>
https://ru.wiktionary.org/wiki/%D0%BF%D0%BE%D0%BB%D0%B8%D1%86%D0%B5%D0%B9%D1%81%D0%BA%D0%B0%D1%8F
https://www.bbc.com/russian/news-49920609
Не вижу, чем плохо слово "полицейская" именно в нашем смысле. Где ты увидел низкий стиль?

2020-09-30 22:08 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
Метаморфозы начались, когда в конструкции from...to... встретилась вдруг вторая to. Логично предположить, что одна из этих to относится не к этой конструкции, а к словосочетанию "finances to war".

2020-09-30 22:40 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
выделил предложение, которое уедет в батч

2020-09-30 22:40 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
То есть Тайнен совершил типовую ашипку на своём языке, а ты это воспринимаешь какую-то фичу?
![image](https://user-images.githubusercontent.com/57110948/94746730-09368100-0386-11eb-88a6-9cc16b06f093.png)

Про переводчик мне тебе нечего сказать. Гуглом не пользуюсь, дикси.

2020-09-30 22:40 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} профессиональным военным снайпером. {PAWN_pronoun} {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} быстро занимать неожиданные огневые по
Для меня - существенная разница.
Повтор "был" меняется на "служил" в первом случае.

2020-09-30 22:40 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>офицер полиции</titleShortFemale>
![image](https://user-images.githubusercontent.com/57110948/94746915-78ac7080-0386-11eb-92e7-eaebe6f3c75c.png)
![image](https://user-images.githubusercontent.com/57110948/94746937-85c95f80-0386-11eb-8582-3b3b9051fa2c.png)

В том, что это слово не используется ни в официально-деловом стиле, ни в публицистике, ни вообще где либо ещё кроме бытового общения. То, что ты нашёл, лишь исключение, подтверждающее правило.

2020-09-30 22:44 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>офицер полиции</titleShortFemale>
Я даже больше скажу, на русский язык policewoman так обычно и переводится, калькой, как полисвумен. Обычно, в контексте английской полиции, если читать прессу или современную литературу по данному контексту.

2020-09-30 23:12 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} профессиональным военным снайпером. {PAWN_pronoun} {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} быстро занимать неожиданные огневые по
Заменяй на "служил", но всё равно поясни мне непонятливому, в чём конкретно ты тут видишь принципиальную разницу.

2020-09-30 23:15 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
Куда уж мне до лингвистов, которые не моргнув глазом видят типовые ошибки носителей другого языка.

2020-09-30 23:18 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
А мне есть что сказать про переводчик. Ты скопировал синтаксическую структуру оригинала слово в слово. Поэтому и получилось у тебя машинное качество и перевод один в один.

2020-09-30 23:20 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
Предложения можно брать в батч откуда угодно, в том числе из комментариев в оригинальном треде.

2020-09-30 23:26 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
> Куда уж мне до лингвистов, которые не моргнув глазом видят типовые ошибки носителей другого языка.

Ой, да ладно тебе. 
Я просто тупой гуманитарий, которому лишь бы поспорить. 

>А мне есть что сказать про переводчик. Ты скопировал синтаксическую структуру оригинала слово в слово. Поэтому и получилось у тебя машинное качество и перевод один в один.

Открою тебе маленькую истину, хороший подстрочник редко возможно отличить от машинного перевода. Только тсс. Мы закрываем эту тему.

2020-09-30 23:28 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>офицер полиции</titleShortFemale>
С каких это пор контрпример в вида статьи СМИ с мировым именем и словарная статья является исключением?

Свою же позицию ты основываешь на выдаче по запросу, текст которого гугл морфлогически меняет как хочет. Слово "полицейская" он будет воспринимать как что угодно, сочетая со всем подряд. Плохой пруф.

2020-09-30 23:30 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} профессиональным военным снайпером. {PAWN_pronoun} {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} быстро занимать неожиданные огневые по
Объясняю:
Ваня служил в армии. В армии Ваня был обучен убивать. Это получалось у него хорошо. (Из этого можно понять, как именно прошлое Вани повлияло на его статы.)

Ваня служил в армии. Ваня обучен убивать. Это у него получалось хорошо. (Из этого можно понять, что переводчик не совсем понимает стилистическую разницу в употреблении разных форм страдательного залога.)

2020-09-30 23:35 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>офицер полиции</titleShortFemale>
Ок, как тебе такой пример?
![image](https://user-images.githubusercontent.com/57110948/94750431-b44b3880-038e-11eb-94b3-bc7552938d2c.png)

2020-09-30 23:48 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>офицер полиции</titleShortFemale>
Про словарную статью тоже добавлю:
- примеров употребления нет
- синоним - разговорное слово
- это вики-словарь
- и это единственная словарная статья

2020-09-30 23:57 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>офицер полиции</titleShortFemale>
> по-серьёзнее

Э - экспертиза
С серьёзной прозой ты хватил. Ничего, что русские классики жили в то время, когда женщин в полиции не было от слова совсем?
В местечковых СМИ ошибок может и пруд пруди, но тут, чёрт возьми, BBC. По каким таким критериям ты определил, что лексема неправильная?
Словарную статью, которая явно говорит о корректности слова, ты предпочёл игнорировать?

2020-10-01 00:01 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>офицер полиции</titleShortFemale>
А серьёзная проза закончилась на русских классиках?

И что, что это BBC? Никто не застрахован от ошибок.Даже я, который в 3 ночи написал "по-серьёзнее". Какой ужас. Мало того, что тупой гуманитарий, так ещё и что-то из себя строит, спешите видеть.

Я тебе только рассказал, насколько это достоверная статья.

2020-10-01 00:01 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} профессиональным военным снайпером. {PAWN_pronoun} {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} быстро занимать неожиданные огневые по
Примерно понял, что ты имеешь в виду, хотя оба примера выглядят одинаково хреново.
Гораздо лучше будет неопределённо-личное "Ваню научили убивать".

2020-10-01 00:04 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>офицер полиции</titleShortFemale>
Про твоё э-экспертиза, кстати
![image](https://user-images.githubusercontent.com/57110948/94752039-bfa06300-0392-11eb-96cd-6be3a2b3b6b8.png)

2020-10-01 00:06 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} профессиональным военным снайпером. {PAWN_pronoun} {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} быстро занимать неожиданные огневые по
Как вариант.

2020-10-01 00:07 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Когда союзник {PAWN_nameDef} был убит, а его молодой сын унаследовал престол, {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? назначен : назначена} регентом, чтобы править вместо реб
Подстрочник хоршим не бывает. Ручной вдумчивый перевод всегда будет лучше машинного или дословного. За это я и борюсь тут.

2020-10-01 00:26 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>офицер полиции</titleShortFemale>
Статья недостоверная, в BBC ошиблись, если я буду ещё ссылки на прозу кидать - ты скажешь, что проза недостаточно серьёзная. 

Лексема неправильная, потому что она неправильная? Опять же, где критерии?
Или потому что частотность низкая? Так это абсолитно логично, ибо женщин-полицейских в русскоговорящих странах не так много.

Вот тебе примеры употребления:
https://context.reverso.net/%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4/%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9/policewoman#%D0%BF%D0%BE%D0%BB%D0%B8%D1%86%D0%B5%D0%B9%D1%81%D0%BA%D0%B0%D1%8F
Этого всё ещё мало?

2020-10-01 00:35 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>офицер полиции</titleShortFemale>
Статья, может, и достоверная, но слово там выбрано не то.
А ты попробуй покидать, там посмотрим.

Лексема неправильная, потому что это разговорное слово и низкий стиль, ты вообще читаешь то, что я тебе пишу?
Банально, потому что я носитель языка и я понимаю, к какому стилю это слово принадлежит, не говоря уже про отсутствие каких-либо словарных статей, кроме огрызка в вики-словаре.  С единственным синоним "милиционершой". Bruh.

Почему женщин-полицейских? Просто полицейских, или полицеек, или как там...
Замечательно, можем поднять наши разговоры из телеги, где я тоже приводил аргументацию, опираясь на контексто, а ты мне отвечал "ну это просто гуглоперевод". 
По твоему запросу 12 результатов, непонятно откуда. Пикрил вообще атас - профессорша.
![image](https://user-images.githubusercontent.com/57110948/94753536-26278000-0397-11eb-9744-85b49bc886b5.png)
Какая-то сомнительная релевантность у твоей выборки.

2020-10-01 00:37 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>офицер полиции</titleShortFemale>
"Этих полицейских сегодня не было на посту" - это про сотрудников полиции какого пола, кстати?
:D

2020-10-01 00:53 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>офицер полиции</titleShortFemale>
![image](https://user-images.githubusercontent.com/57110948/94754298-8c150700-0399-11eb-8310-ac5a026e2607.png)
![image](https://user-images.githubusercontent.com/57110948/94754304-90412480-0399-11eb-882e-45c58bd7ce12.png)
![image](https://user-images.githubusercontent.com/57110948/94754323-99ca8c80-0399-11eb-8705-63aa202c0e9e.png)
![image](https://user-images.githubusercontent.com/57110948/94754332-9f27d700-0399-11eb-9a0a-809d1fad97a3.png)

брух-момент

2020-10-01 21:42 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>офицер полиции</titleShortFemale>
Что такое "брух-момент", я не знаю. Возможно, мы и правда на разных русских языках разговариваем.

> По твоему запросу 12 результатов, непонятно откуда

Релультатов 97, и для каждого указан источник. Судя по тому, что Гугл policewoman "переводит" как "поллицейск**ий**", это явно не он. 

> "Этих полицейских сегодня не было на посту" - это про сотрудников полиции какого пола, кстати?
:D

Смешной вопрос. Видно же, что множественное число, и пол не определяется. Что ты этим хочешь доказать?

> разговорное слово и низкий стиль

"Низкий стиль" - это что? В русском языке такого нет. Разве что такой термин упоминался в контексте попытки систематизировать язык ещё в петровские времена. Если ты про это, то термин уже 300 лет как устарел.

Разговорное слово? Ты посмотри на другие краткие заголовки, и увидишь, что такое там повсеместно (в том числе в оригинале) и не вызывает отторжения.

2020-10-02 10:02 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>офицер полиции</titleShortFemale>
Еще раз. 
Я против слова "полицейская" в данном контексте. 
Всю свою аргументацию я предоставил.

2020-10-02 23:31 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>офицер полиции</titleShortFemale>
Хорошо, значит я сам исправлю краткий заголовок после мерджа.

2020-10-04 23:10 UTC, merged