#1054 Translate Backstories.xml (RoyalCook18-Spymaster41)
Ludeon/RimWorld-ru pull request #1097
Opened 2020-05-25 02:12 UTC by kamadz

Close #1054

2020-05-25 11:43 UTC, Elevator89 commented
За Close в описании спасибо. Так и надо делать.
Бэкстори посмотрю, как закончим с обновлениями

2020-08-25 13:50 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? работал : работала} массажистом при дворе известного и знатного рода, обслуживая множество членов знатной семьи и их гостей.\n\n{PAWN_nameDef} иногда {PAWN_gende
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? работал : работала} {PAWN_gender ? массажистом : массажисткой}при дворе известного и знатного рода, обслуживая множество членов знатной семьи и их гостей.\n\n{PAWN_nameDef} иногда {PAWN_gender ? предлагал : предлагала} «особенные» услуги, если лорд или леди в {PAWN_gender ? пребывал : пребывала} в соответствующем расположении духа. Совершенствование в этом роде деятельности помогало оттачивать социальные навыки.</desc>
```

2020-08-25 13:54 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Основным оплотом семьи {PAWN_nameDef} был огромный древний космический корабль. {PAWN_nameDef} {PAWN_gender ? родился : родилась} и {PAWN_gender ? рос : росла} на нём и не понаслышке {PAWN_ge
```suggestion
		<desc>Основным оплотом семьи {PAWN_nameDef} был огромный древний космический корабль. {PAWN_nameDef} {PAWN_gender ? родился : родилась} и {PAWN_gender ? рос : росла} на нём и не понаслышке {PAWN_gender ? знал : знала} о всей строгости корабельной жизни, политике, методах ведения боя в космосе и орбитальных десантах.\n\n{PAWN_pronoun} {PAWN_gender ? привык : привыкла} чувствовать себя как дома только в тесном окружении крепких стен и мягкого шипения атмосферных регуляторов где-то рядом.</desc>
```

2020-09-30 23:07 UTC, Elevator89 requested changes

2020-09-30 23:07 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<title>ребёнок военных</title>
```suggestion
		<title>сын военного</title>
		<titleFemale>дочь военного</titleFemale>
```

2020-09-30 23:07 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShort>ребёнок военных</titleShort>
```suggestion
		<titleShort>сын военного</titleShort>
		<titleShortFemale>дочь военного</titleShortFemale>
```

2020-09-30 23:07 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? рос : росла} на древнем космическом корабле, где служили {PAWN_possessive} родители. От солдат на борту {PAWN_pronoun} {PAWN_gender ? научился : научилась} основ
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? рос : росла} на древнем космическом корабле, где служили {PAWN_possessive} родители. У солдат на борту {PAWN_pronoun} {PAWN_gender ? научился : научилась} основам обращения с оружием и ухода за ним. {PAWN_nameDef} {PAWN_gender ? привык : привыкла} к жёсткой рутине и частым наказаниям.</desc>
```

2020-09-30 23:07 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Как только {PAWN_nameDef} {PAWN_gender ? достиг : достигла} нужного возраста, {PAWN_possessive} назначили шпионом-мейстером своего знатного семейства. Холодная и расчётливая натура сделали {P
```suggestion
		<desc>Как только {PAWN_nameDef} {PAWN_gender ? достиг : достигла} нужного возраста, {PAWN_possessive} назначили шпионом-мейстером своего знатного семейства. Холодная и расчётливая натура сделали {PAWN_possessive} искусным мастером клинка, яда и предательства.</desc>
```

2020-09-30 23:15 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье придворных слуг, и {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} всем обязанностям своих родителей.\n\n{PAWN_pronoun} п
Я могу понять, чем тебе не понравилось слово "имение", но зачем его на "дом"-то было менять?
Дом у простолюдина. У господ усадьбы, особняки, виллы или поместья

2020-09-30 23:16 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Основным оплотом семьи {PAWN_nameDef} был огромный древний космический корабль. {PAWN_nameDef} {PAWN_gender ? родился : родилась} и {PAWN_gender ? рос : росла} на нём и не понаслышке {PAWN_ge
PAWN, как дворянин, разбирался в тонкостях **политики** _и_ **военного дела**
Сомневаюсь, что у ребёнка дворянина могут быть "тяготы".

2020-09-30 23:17 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? охранял : охраняла} личный дворец могущественного лорда.\n\nХотя насилие было довольно редким зрелищем, дворец кишел интригами. Работа научила {PAWN_nameDef} мас
Придирка к стилистике

2020-09-30 23:20 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье низкосортной прислуги на древнем космическом корабле. Корабельный ИИ стал {PAWN_objective} третьим родителем, а команда по сборке зап
Это вопрос экуменического порядка.
Младшая прислуга, это как? Прислуживающая менее влиятельной аристократии?
Или несовершеннолетняя?

2020-09-30 23:22 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? готовил : готовила} различные блюда для знатных особ.\n\nДля работы требовалось исключительное качество продуктов, поэтому, {PAWN_nameDef} {PAWN_gender ? ухажива
Второе уедет.

2020-10-01 22:34 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Основным оплотом семьи {PAWN_nameDef} был огромный древний космический корабль. {PAWN_nameDef} {PAWN_gender ? родился : родилась} и {PAWN_gender ? рос : росла} на нём и не понаслышке {PAWN_ge
Читай внимательно. Нет там политики.

Строгая дисциплина, строгая упорядоченность - может быть. Строгая жизнь - нет.

Тяготы - от слова "тяжело". Тяжело может быть всем, даже детям дворян. Дворяне - они разные бывают.

2020-10-01 22:47 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? охранял : охраняла} личный дворец могущественного лорда.\n\nХотя насилие было довольно редким зрелищем, дворец кишел интригами. Работа научила {PAWN_nameDef} мас
Не придирка к стилистике, а исправление некорректного перевода.

2020-10-01 22:52 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье придворных слуг, и {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} всем обязанностям своих родителей.\n\n{PAWN_pronoun} п
Ты специально делаешь одно спорное утверждение за гругим? Хочешь поспорить? Тебе некуда девать время?

Дом - у кого угодно. Особняк, вилла, лачуга, шалаш - это всё частные случаи дома.
А имение и поместье - это не только дом, а ещё и территория, иногда очень большая.

2020-10-01 22:55 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье низкосортной прислуги на древнем космическом корабле. Корабельный ИИ стал {PAWN_objective} третьим родителем, а команда по сборке зап
Отвечу вопросом на вопрос.
Младший научный сотрудник - это сотрудник, работающий в менее влиятельных НИИ?
Или несовершеннолетний научный сотрудник?

2020-10-02 10:05 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? охранял : охраняла} личный дворец могущественного лорда.\n\nХотя насилие было довольно редким зрелищем, дворец кишел интригами. Работа научила {PAWN_nameDef} мас
Не соглашусь.

2020-10-02 10:06 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье придворных слуг, и {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} всем обязанностям своих родителей.\n\n{PAWN_pronoun} п
Стилистика не выдержана, слово дом нужно менять.

2020-10-02 10:07 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье низкосортной прислуги на древнем космическом корабле. Корабельный ИИ стал {PAWN_objective} третьим родителем, а команда по сборке зап
Сейчас бы сравнивать иерархию в научных званиях и должностях с организацией феодальной прислуги.

2020-10-02 10:16 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Основным оплотом семьи {PAWN_nameDef} был огромный древний космический корабль. {PAWN_nameDef} {PAWN_gender ? родился : родилась} и {PAWN_gender ? рос : росла} на нём и не понаслышке {PAWN_ge
Нужно будет сказать, что Тайнен ошибся - скажу, не переживай. 
Хорошо, доводы твои принял по поводу компетенций дворянтна. 

Тяготы - нет. Просто нет, и все. Тяготы у солдатни. Ты тут, давеча, русских классиков вспоминал. Ну вот и какие тяготы были у дворянских отпрысков в "Капитанской дочке" Пушкина? Скукота и отсутсвие борделей? 

Строгость жизни можно поменять на строгость порядков, если тебе так не нравится это словосочетание.

2020-10-02 23:07 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Основным оплотом семьи {PAWN_nameDef} был огромный древний космический корабль. {PAWN_nameDef} {PAWN_gender ? родился : родилась} и {PAWN_gender ? рос : росла} на нём и не понаслышке {PAWN_ge
Тяготы заключаются в суровых условиях корабельного быта, которому подчиняются все: от матросов до офицеров. Дворянский титул, судя по оригиналу, далеко не гарантия царских условий. PAWN не предаётся лени и не мается от скуки, а служит, как положено дворянину при феодальном строе.
Сравнение с "Капитанской дочкой" тут абсолютно неуместно.

2020-10-02 23:17 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? охранял : охраняла} личный дворец могущественного лорда.\n\nХотя насилие было довольно редким зрелищем, дворец кишел интригами. Работа научила {PAWN_nameDef} мас
Гитхаб - это платформа для командной работы над проектами, а не дискуссионная площадка.
Цель замечаний - указывать автору на ошибки и недочёты, для скорейшего исправления, а не начинать долгие дискуссии.
Я рад, что ты критически относишься в том числе к замечаниям, но надо и меру знать. Тебе не кажется, что ты тратишь слишком много сил и времени на своё несоглашание и споры в коментариях. На всякий случай напомню, что есть и другие задачи, например, перевод новых предысторий и поиск ошибок в уже переведённых текстах.

Теперь по теме. PAWN - стражник. Насилие и противодействие чужому насилию - это его работа, а не то, что он может воспринимать как "зрелище". "Зрелище" здесь абсолюно неуместно.

2020-10-02 23:24 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье придворных слуг, и {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} всем обязанностям своих родителей.\n\n{PAWN_pronoun} п
С какого перепугу универсальное слово "дом" её не соответствует твоей стилистике? По каким-таким критериям ты это определяешь? Ответ в духе "я лингвист, мне виднее", меня не устроит.

2020-10-02 23:27 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье низкосортной прислуги на древнем космическом корабле. Корабельный ИИ стал {PAWN_objective} третьим родителем, а команда по сборке зап
Вполне корректно сравнивать.
В термин "низкосортный" к людям вообще неприменим.

2020-10-03 08:02 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? охранял : охраняла} личный дворец могущественного лорда.\n\nХотя насилие было довольно редким зрелищем, дворец кишел интригами. Работа научила {PAWN_nameDef} мас
Андрей, зрелище здесь - контекстуальный синоним явления. Меру надо знать в своих "критических замечаниях", когда дело доходит, мать-перемать, до одного слова, которое по какой-то необъяснимой причине тебе не нравится.
Не нравятся длинные дискуссии? Вспомни, как мы вымучивали стрелковый визор, вместо стрельбовизора, за который ты бодался полдня.

Я не понимаю, как работает твоя избирательность. В одних био книжные синонимы можно, в других - обязательно запихнуть как можно больше канцелярита и стилистической несуразности.
Слово зрелище здесь можно спокойно оставить, оно не выбивается из стиля.
![image](https://user-images.githubusercontent.com/57110948/94986479-db109700-0567-11eb-8cee-9f35a1822cd3.png)

2020-10-03 08:11 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье придворных слуг, и {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} всем обязанностям своих родителей.\n\n{PAWN_pronoun} п
Смотри, Андрей. 
Здесь живут дворяне: 
![image](https://user-images.githubusercontent.com/57110948/94986651-1495d200-0569-11eb-80cd-6fcf1f9f2ca1.png)

2020-10-03 08:11 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье придворных слуг, и {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} всем обязанностям своих родителей.\n\n{PAWN_pronoun} п
![image](https://user-images.githubusercontent.com/57110948/94986665-28413880-0569-11eb-8f63-7ee2a1b2ca91.png)

2020-10-03 08:13 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье придворных слуг, и {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} всем обязанностям своих родителей.\n\n{PAWN_pronoun} п
А здесь - все остальные:
![image](https://user-images.githubusercontent.com/57110948/94986693-62123f00-0569-11eb-8d71-c5501f347094.png)

2020-10-03 08:15 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье придворных слуг, и {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} всем обязанностям своих родителей.\n\n{PAWN_pronoun} п
"Какой ещё стилистике? С какого перепугу универсальное слово "дом" ей не соответствует, а "строгость жизни" и "низкосортная прислуга" - соответствует? По каким-таким критериям ты это определяешь? Ответ в духе "я лингвист, мне виднее", меня не устроит." 
А чем тебе не понравилось универсальное "офицер полиции"/"сотрудник(ца) полиции?". По каким критериям т ты отбраковал те варианты? Ответ в духе "я лучше знаю всяких лингвистов" меня тоже не устроит.

2020-10-03 08:17 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье низкосортной прислуги на древнем космическом корабле. Корабельный ИИ стал {PAWN_objective} третьим родителем, а команда по сборке зап
В контексте "плохой", "никудышный" ещё как употребим. 
Вариант с "младшей" прислугой лично для несодержателен, например.

2020-10-03 09:37 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Основным оплотом семьи {PAWN_nameDef} был огромный древний космический корабль. {PAWN_nameDef} {PAWN_gender ? родился : родилась} и {PAWN_gender ? рос : росла} на нём и не понаслышке {PAWN_ge
Еще как уместно это сравнение. 
Есть разница между "привыкнуть к строгим порядкам" и "привыкнуть к тяготам", во-первых, потому что первый вариант содержательнее показывает контекст, во-вторых, потому что нет у офицеров, тем более дворянского происхождения "тягот". Есть трудности и неудобства, но, согласись, немного разная содержательная окраска.

2020-10-03 09:39 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Основным оплотом семьи {PAWN_nameDef} был огромный древний космический корабль. {PAWN_nameDef} {PAWN_gender ? родился : родилась} и {PAWN_gender ? рос : росла} на нём и не понаслышке {PAWN_ge
"Солдат обязан стойко и мужественно переносить все тяготы и лишения военной службы" из дисциплинарного устава ВС РФ ты берешь, как прецедент?

2020-10-04 21:57 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? охранял : охраняла} личный дворец могущественного лорда.\n\nХотя насилие было довольно редким зрелищем, дворец кишел интригами. Работа научила {PAWN_nameDef} мас
Я тоже не понимаю твоего упорства в отстаивании спорных вещей. По поводу "необъяснимых причин" советую тебе посмотреть на себя. Я же своей позиции привожу агрументы, а не просто что-либо безаппеляционно утверждаю на основании собственной принадлежности определённой профессии.
Читай, пожалуйста, внимательнее, что я пишу. Причём тут, чёрт возьми, стиль, когда я говорю о том, что слово "зрелище" в этом контексте не подходит и искажает **смысл** оргинала?

2020-10-04 22:09 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье придворных слуг, и {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} всем обязанностям своих родителей.\n\n{PAWN_pronoun} п
О боже мой! Ты судишь о понятии по одной лишь картинке?
Я помогу тебе с логикой, используя твой же скриншот.
![изображение](https://user-images.githubusercontent.com/21694533/95028053-c9311000-069d-11eb-98b9-9d640afbb68e.png)
Отношение - "частное-общее". Слово "дом" может обозначать пятиэтажку на третьем скриншоте так же, как и особняк на втором. Не любой дом - это особняк. Но каждый особняк - это дом. Так понятнее?
Я использовал именно это слово, потому что в оригинале "house", а не "mansion".
Считаешь, что знаешь больше автора - пожалуйста, пиши "особняк". Но это, побери, ни в коем случае не "имение".

2020-10-04 22:13 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Основным оплотом семьи {PAWN_nameDef} был огромный древний космический корабль. {PAWN_nameDef} {PAWN_gender ? родился : родилась} и {PAWN_gender ? рос : росла} на нём и не понаслышке {PAWN_ge
Специально для тех, кому не нравится слово "тяготы"
```suggestion
		<desc>Основным оплотом семьи {PAWN_nameDef} был огромный древний космический корабль. {PAWN_nameDef} {PAWN_gender ? родился : родилась} и {PAWN_gender ? рос : росла} на нём и не понаслышке {PAWN_gender ? знал : знала} о всей суровости корабельного быта, политике, методах ведения боя в космосе и орбитальных десантах.\n\n{PAWN_pronoun} {PAWN_gender ? привык : привыкла} чувствовать себя как дома только в тесном окружении крепких стен и мягким шипением атмосферных регуляторов где-то рядом.</desc>
```

2020-10-04 22:14 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Основным оплотом семьи {PAWN_nameDef} был огромный древний космический корабль. {PAWN_nameDef} {PAWN_gender ? родился : родилась} и {PAWN_gender ? рос : росла} на нём и не понаслышке {PAWN_ge
> "Солдат обязан стойко и мужественно переносить все тяготы и лишения военной службы" из дисциплинарного устава ВС РФ ты берешь, как прецедент?

Да, почему нет?

2020-10-04 22:21 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье низкосортной прислуги на древнем космическом корабле. Корабельный ИИ стал {PAWN_objective} третьим родителем, а команда по сборке зап
Причём тут "плохой" и "никудышний"? Речь про прислугу, выполняющую более чёрную работу и стояющую ниже других в иерархии прислуги.

2020-10-04 22:29 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье придворных слуг, и {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} всем обязанностям своих родителей.\n\n{PAWN_pronoun} п
> А чем тебе не понравилось универсальное "офицер полиции"/"сотрудник(ца) полиции?"

Тем, что "сотрудница полиции?" не подходит для краткого заголовка, а "полицейская" подходит. Упомянутая тобой разговорность (и отсутствие так нелюбимого тобой канцелярита), учитывая контекст появления краткого заголовка на UI, здесь только на руку.

2020-10-05 00:07 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Основным оплотом семьи {PAWN_nameDef} был огромный древний космический корабль. {PAWN_nameDef} {PAWN_gender ? родился : родилась} и {PAWN_gender ? рос : росла} на нём и не понаслышке {PAWN_ge
А почему нельзя было сразу предложить поискать промежуточный вариант или самостоятельно его обдумать? 
"
Да, почему нет? Можно подумать, у боевых офицеров, в отличие от солдат, тягот никаких не бывает.
"
Не у отпрыска семейства, владеющего огромным космическим кораблëм. Это же не какой-то галимый поручик, верно?

2020-10-05 00:09 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? охранял : охраняла} личный дворец могущественного лорда.\n\nХотя насилие было довольно редким зрелищем, дворец кишел интригами. Работа научила {PAWN_nameDef} мас
В каком месте это слово искажает смысл, по-подробнее, пожалуйста.

2020-10-05 00:16 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье придворных слуг, и {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} всем обязанностям своих родителей.\n\n{PAWN_pronoun} п
"Отношение - "частное-общее"."
Гиперонимия называется, ага. Уже рассказывал тебе про неë :D

Я сразу согласился с тем, что "имение" - плохой вариант и предложил выбрать что-то более подходящее статусу владельца, чем просто "дом". Зачем переходить на эмоции-то сразу?

2020-10-05 00:26 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье низкосортной прислуги на древнем космическом корабле. Корабельный ИИ стал {PAWN_objective} третьим родителем, а команда по сборке зап
Предлагаю два других варианта:
Челядь - идеальный вариант. 
Ходом - чуть меньше. 
Подëнщик - подëнщица (почти полностью соответствует по смыслу) . 
Батрак - батрачка (меньше подходит по смыслу, но коннотационно - вполне). 

Все - люди низкого социального статуса и без квалификации, которые часто вовлекались в обслуживание господ. единственная

2020-10-05 00:41 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье придворных слуг, и {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} всем обязанностям своих родителей.\n\n{PAWN_pronoun} п
"Тем, что "сотрудница полиции?" не подходит для краткого заголовка, а "полицейская" подходит."

Можно вообще "мент" написать, так ещë короче будет. Но не правильно от того.

2020-10-05 12:02 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? охранял : охраняла} личный дворец могущественного лорда.\n\nХотя насилие было довольно редким зрелищем, дворец кишел интригами. Работа научила {PAWN_nameDef} мас
Вот прям тут:
![изображение](https://user-images.githubusercontent.com/21694533/95077182-ba893e00-071b-11eb-9a98-c5074002f7ed.png)

2020-10-05 13:57 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье придворных слуг, и {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} всем обязанностям своих родителей.\n\n{PAWN_pronoun} п
> Гиперонимия называется, ага. Уже рассказывал тебе про неë :D

Я рад, что ты меня наконец-то правильно понял.

> Зачем переходить на эмоции-то сразу?

Не сразу, а не третий вечер малопродуктивных дискуссий. Как ты понимаешь, это не единственный тред, в котором мы общаемся. Негативных эмоций за это время мягко говоря не убавилось.

> Можно вообще "мент" написать, так ещë короче будет. Но не правильно от того.

Ну вот потому не "мент" и не "сотрудница полиции", а промежуточное по длине и "разговорности" слово "полицейская".

2020-10-05 13:59 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье придворных слуг, и {PAWN_gender ? был : была} {PAWN_gender ? обучен : обучена} всем обязанностям своих родителей.\n\n{PAWN_pronoun} п
Меняй на "особняка" и заканчивай этот тред.
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье придворных слуг, и {PAWN_gender ? был обучен : была обучена} всем обязанностям своих родителей.\n\n{PAWN_pronoun} {PAWN_gender ? носил : носила} вещи и {PAWN_gender ? полировал : полировала} серебряную посуду, но никогда не {PAWN_gender ? заходил : заходила} в «господскую» часть особняка.</desc>
```

2020-10-05 14:05 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье низкосортной прислуги на древнем космическом корабле. Корабельный ИИ стал {PAWN_objective} третьим родителем, а команда по сборке зап
> Единственная проблема - это все славянизмы и они довольно странно смотрятся на фоне всего остального.

И это большая проблема. А ещё "батраки" и "подёнщики" не подходят от слова совсем. По смыслу.

Предлагаю вариант @EcherArt:
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье прислуги низшего звена на древнем космическом корабле. Корабельный ИИ стал {PAWN_objective} третьим родителем, а команда по сборке запчастей, в которой {PAWN_nameDef} {PAWN_gender ? работал : работала} — второй семьёй.\n\n{PAWN_nameDef} редко {PAWN_gender ? видел : видела} растения или животных и до сих пор слегка боится к ним прикасаться.</desc>
```

2020-10-05 14:09 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Основным оплотом семьи {PAWN_nameDef} был огромный древний космический корабль. {PAWN_nameDef} {PAWN_gender ? родился : родилась} и {PAWN_gender ? рос : росла} на нём и не понаслышке {PAWN_ge
Потому что этот вариант родился у меня лишь на пятый день обсуждения.

Заливай изменение и заканчивай тред.

2020-10-05 16:35 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? охранял : охраняла} личный дворец могущественного лорда.\n\nХотя насилие было довольно редким зрелищем, дворец кишел интригами. Работа научила {PAWN_nameDef} мас
Вот ещë контекстуальные синонимы, а при синонимии смысл никуда не искажается. Ватевар, заливаю твой вариант, надоело.

2020-10-05 20:15 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>В задачи {PAWN_nameDef} входили полёт со своего корабля сквозь пустоту космоса в сторону вражеского корабля, приземление на его поверхность, создание проходных отверстий и его последующий зах
```suggestion
		<desc>В задачи {PAWN_nameDef} входили полёт со своего корабля сквозь пустоту космоса в сторону вражеского корабля, приземление на его поверхность, создание проходных отверстий и его последующий захват в тесном бою. {PAWN_nameDef} {PAWN_gender ? добился : добилась} больших успехов в обращении с тяжелым катафрактарским арсеналом, позволявшим прорубаться как сквозь сталь, так и сквозь людей.\n\n{PAWN_pronoun} также {PAWN_gender ? выработал : выработала} тягу к наркотикам, которые {PAWN_pronoun} {PAWN_gender ? употреблял : употреблял}, чтобы справиться с непреодолимым стрессом.</desc>
```

2020-10-05 20:15 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>В задачи {PAWN_nameDef} входили полёт со своего корабля сквозь пустоту космоса в сторону вражеского корабля, приземление на его поверхность, создание проходных отверстий и его последующий зах
Благодвучнее?

2020-10-05 20:49 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>В задачи {PAWN_nameDef} входили полёт со своего корабля сквозь пустоту космоса в сторону вражеского корабля, приземление на его поверхность, создание проходных отверстий и его последующий зах
Да. Только давай тогда "принимал" вместо "употреблял". И лаконичнее, и не так по-канцелярски

2020-10-08 21:52 UTC, merged