#1055 Translate Backstories.xml (StewKeeper95-Warmonger35)
Ludeon/RimWorld-ru pull request #1127
Opened 2020-07-12 18:11 UTC by kamadz

Close #1055

2020-08-25 14:07 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} в своём племени {PAWN_gender ? должен : должна} {PAWN_gender ? был : была} заниматься единением с миром природы - особенно с животными. {PAWN_pronoun} не только {PAWN_gender ?
```suggestion
		<desc>{PAWN_nameDef} в своём племени {PAWN_gender ? должен : должна} {PAWN_gender ? был : была} заниматься единением с миром природы — особенно с животными. {PAWN_pronoun} не только {PAWN_gender ? исполнял : исполняла} свою духовную роль, но также {PAWN_gender ? приручал : приручала} диких зверей для работы в племени и {PAWN_gender ? заботился : заботилась} о них.</desc>
```

2020-10-06 15:10 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Знатная семья {PAWN_nameDef} не хотела {PAWN_objective}, но не могла позволить себе откровенное убийство ребёнка. Вместо этого, они решили подстроить {PAWN_possessive} смерть с помощью опасны
```suggestion
		<desc>В своей знатной семье {PAWN_nameDef} {PAWN_gender ? был : была} нежеланным ребёнком, однако никто не мог позволить себе пойти на откровенное убийство. Вместо этого, было решено подстроить {PAWN_possessive} смерть с помощью опасных тренировок без должной защиты в слишком раннем возрасте.\n\nНесмотря ни на что, {PAWN_nameDef} {PAWN_gender ? пережил : пережила} вcе пешие и конные боевые турниры, опасные речные заплывы и участие в различных «горячих точках». Это, в итоге, сделало {PAWN_possessive} только сильнее.</desc>
```

2020-10-06 15:13 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в знатном семействе, располагавшим великолепным поместьем в огромном городе. Всё своё детство {PAWN_pronoun} {PAWN_gender ? провёл : провела}
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в знатном семействе, располагавшим великолепным поместьем в огромном городе. Всё своё детство {PAWN_pronoun} {PAWN_gender ? провёл : провела} изучая политику.\n\nПри малейшей возможности, {PAWN_pronoun} {PAWN_gender ? сбегал : сбегала} со своими друзьями, чтобы исследовать катакомбы столичного города.</desc>
```

2020-10-06 15:16 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} через девять месяцев после того, как город {PAWN_possessive} матери был захвачен вражескими солдатами. Дитя насилия без признанного отца, {PA
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} через девять месяцев после того, как город {PAWN_possessive} матери был захвачен вражескими солдатами. Дитя, порождённое насилием, без признанного отца, {PAWN_nameDef} {PAWN_gender ? рос : росла} на самом дне социальной лестницы.\n\n{PAWN_possessive} мать привила {PAWN_nameDef} неприязнь к мужчинам и войне. Ручной кролик приносил {PAWN_objective} больше тепла, чем любой другой человек за всю жизнь.</desc>
```

2020-10-17 14:56 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Знатная семья {PAWN_nameDef} не хотела {PAWN_objective}, но не могла позволить себе откровенное убийство ребёнка. Вместо этого, они решили подстроить {PAWN_possessive} смерть с помощью опасны
Исправил исправление
"смерть с помощью опасных тренировок" - это 10/10.
```suggestion
		<desc>В своей знатной семье {PAWN_nameDef} {PAWN_gender ? был : была} нежеланным ребёнком, однако никто не мог позволить себе пойти на прямое убийство. Вместо этого было решено подстроить {PAWN_possessive} смерть, проводя с {PAWN_gender ? ним : ней} опасные тренировки без должной защиты в слишком раннем возрасте.\n\nНесмотря ни на что, {PAWN_nameDef} {PAWN_gender ? пережил : пережила} вcе пешие и конные боевые турниры, опасные речные заплывы и участие в различных локальных конфликтах. Это всё в итоге сделало {PAWN_possessive} только сильнее.</desc>
```

2020-10-17 16:30 UTC, Elevator89 requested changes

2020-10-17 16:30 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShort>военная советница</titleShort>
Заголовок должен быть кратким и соответствовать полу
```suggestion
		<titleShort>советник</titleShort>
		<titleShortFemale>советница</titleShortFemale>
```

2020-10-17 16:30 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<!-- EN: [PAWN_nameDef] was warmaster to a mid-level royal house. [PAWN_pronoun] oversaw military aspects of the famil's strategy.\n\nOn the rare occasion a battle occurred, [PAWN_nameDef] directed
```suggestion
		<!-- EN: [PAWN_nameDef] was warmaster to a mid-level royal house. [PAWN_pronoun] oversaw military aspects of the family's strategy.\n\nOn the rare occasion a battle occurred, [PAWN_nameDef] directed the military commanders. -->
```

2020-10-17 16:30 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? военным : военной} {PAWN_gender ? советником : советницей} знатного рода. {PAWN_pronoun} {PAWN_gender ? занимался : занималась} всеми
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? был военным советником : была военной советницей} при знатной семье. {PAWN_pronoun} {PAWN_gender ? занимался : занималась} всеми военными делами при дворе.\n\nВ тех редких случаях, когда происходили сражения, {PAWN_nameDef} {PAWN_gender ? руководил : руководила} офицерским составом.</desc>
```

2020-10-17 16:30 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? упивался : упивалась} кровопролитием. Бойцы, служившие с {PAWN_gender ? ним : ней} ужасались {PAWN_possessive} жестокости. Они редко общались с {PAWN_nameDef}, н
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? упивался : упивалась} кровопролитием. Бойцы, служившие с {PAWN_gender ? ним : ней}, ужасались {PAWN_possessive} жестокости. Они редко общались с {PAWN_nameDef}, но {PAWN_objective} было хорошо и {PAWN_gender ? одному : одной}.</desc>
```

2020-10-17 16:30 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShort>свирепый воин</titleShort>
```suggestion
		<titleShort>воин</titleShort>
		<titleShortFemale>воительница</titleShortFemale>
```

2020-10-17 17:56 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} в своём племени {PAWN_gender ? должен : должна} {PAWN_gender ? был : была} заниматься единением с миром природы - особенно с животными. {PAWN_pronoun} не только {PAWN_gender ?
Завидую твоей фантазии

2020-10-17 18:11 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShort>городской лорд</titleShort>
```suggestion
		<titleShort>лорд</titleShort>
```

2020-10-17 18:11 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>городская леди</titleShortFemale>
```suggestion
		<titleShortFemale>леди</titleShortFemale>
```

2020-10-17 18:15 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<title>свирепый воин</title>
```suggestion
		<title>свирепый воин</title>
		<titleFemale>свирепый воин</titleFemale>
```

2020-10-17 18:17 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<title>военный советник</title>
```suggestion
		<title>военный советник</title>
		<titleFemale>военная советница</titleFemale>
```

2020-10-18 21:59 UTC, merged