#1056 Translate Backstories.xml (RebelliousStudent74-HypnocultLeader61)
Ludeon/RimWorld-ru pull request #1128
Opened 2020-07-14 22:37 UTC by kamadz

Close #1056

+minor fixes

2020-08-25 14:19 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Желая лучше понимать людей, {PAWN_nameDef} {PAWN_gender ? обучился : обучилась} искусству гипноза, к которому позже {PAWN_gender ? обнаружил : обнаружила} у себя настоящий талант.\n\n{PAWN_na
```suggestion
		<desc>Желая лучше понимать людей, {PAWN_nameDef} {PAWN_gender ? обучился : обучилась} искусству гипноза, к которому позже {PAWN_gender ? обнаружил : обнаружила} у себя настоящий талант.\n\n{PAWN_nameDef} {PAWN_gender ? смог : смогла} собрать вокруг своей энергичной личности культ, состоящий из {PAWN_possessive} поклонников. Власти узнали о {PAWN_possessive} незаконной деятельности, но {PAWN_nameDef} {PAWN_gender ? успел : успела} сбежать до ареста.\n</desc>
```

2020-08-25 14:21 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>После многих лет подготовки и практики, {PAWN_gender} {PAWN_gender ? поступил : поступила} в академию искусств, чтобы и дальше развивать свои художественные навыки. После выпуска с хорошими о
```suggestion
		<desc>После многих лет подготовки и практики, {PAWN_gender} {PAWN_gender ? поступил : поступила} в академию искусств, чтобы и дальше развивать свои художественные навыки. После выпуска с хорошими оценками {PAWN_pronoun} {PAWN_gender ? искал : искала} работу в сфере искусств. В итоге, у н{PAWN_possessive} получилось наладить достойный и приятный душе заработок на выполнении частных заказов.</desc>
```

2020-10-06 15:19 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +    <titleFemale>студентка-бунтарка</titleFemale>
```suggestion
		<title>школьный бунтарь</title>
    <titleFemale>школьная бунтарка</titleFemale>
```

2020-10-06 15:19 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +    <titleShortFemale>студентка</titleShortFemale>
```suggestion
		<titleShort>школьник</titleShort>
    <titleShortFemale>школьница</titleShortFemale>
```

2020-10-06 15:20 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_gender ? Росший : Росшая} под влиянием насилия в своём окружении, {PAWN_nameDef} {PAWN_gender ? изучал : изучала} боевые искусства и, в конечном итоге, {PAWN_gender ? начал : начала} уч
```suggestion
		<desc>{PAWN_gender ? Росший : Росшая} под влиянием насилия, {PAWN_nameDef} {PAWN_gender ? изучал : изучала} боевые искусства и, в конечном итоге, {PAWN_gender ? начал : начала} участвовать в соревнованиях по рукопашному бою.\n\nВ отличие от своих противников, {PAWN_nameDef} {PAWN_gender ? брал : брала} пример с различных воинов древности. {PAWN_pronoun} {PAWN_gender ? упражнялся : упражнялась} каждый день от рассвета до заката, оттачивая свои навыки.\n</desc>
```

2020-10-06 15:22 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Будучи ребёнком, {PAWN_nameDef} {PAWN_gender ? создавал : создавала} сложные вычислительные алгоритмы. Всё детство{PAWN_possessive} использовали как «человеческий компьютер». Из-за этого {PAW
```suggestion
		<desc>Будучи ребёнком, {PAWN_nameDef} {PAWN_gender ? создавал : создавала} сложные вычислительные алгоритмы. Всё детство{PAWN_possessive} использовали как «человеческий компьютер». Из-за этого {PAWN_nameDef} {PAWN_gender ? рос : росла} социально {PAWN_gender ? неадаптированным : неадаптированной} и довольно {PAWN_gender ? тощим : тощей}.\n\nНесмотря на постоянное одиночество, {PAWN_nameDef} {PAWN_gender ? выработал : выработала} богатое воображение, чтобы занимать себя в свободное время.\n</desc>
```

2020-10-06 15:23 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Руководствуясь своим детским опытом, {PAWN_nameDef} {PAWN_gender ? стал : стала} компьютерным инженером. {PAWN_pronoun} {PAWN_gender ? научился : научилась} так же мастерить изощрённые скульп
```suggestion
		<desc>Руководствуясь своим детским опытом, {PAWN_nameDef} {PAWN_gender ? стал : стала} компьютерным инженером. {PAWN_pronoun} также {PAWN_gender ? научился : научилась} мастерить изощрённые скульптуры и различную электронику.\n\n{PAWN_nameDef} очень {PAWN_gender ? увлёкся : увлеклась} технологиями и почти {PAWN_gender ? перестал : перестала} общаться с людьми. Единственные друзья в виде компьютеров не научили {PAWN_possessive} заботиться о других.\n</desc>
```

2020-10-06 15:24 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_gender ? Родившийся : Родившаяся} в семье кочевников в средневековом мире, {PAWN_nameDef} с самого детства {PAWN_gender ? обучался : обучалась} красноречию, ловкости рук и верховой езде
```suggestion
		<desc>{PAWN_gender ? Родившийся : Родившаяся} в семье кочевников в средневековом мире, {PAWN_nameDef} с самого детства {PAWN_gender ? обучался : обучалась} красноречию, ловкости рук и верховой езде.\n\n{PAWN_pronoun} всегда {PAWN_gender ? носился : носилась} по лагерю, выполняя разнообразные, порой необычные поручения, помогая своей большой семье.\n</desc>
```

2020-10-06 15:25 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>После отказа выполнить безумные требования короля-тирана, {PAWN_nameDef} и {PAWN_possessive} кочевую группу объявили преступниками. На них развернулась настоящая охота.\n\nВ конце концов {PAW
```suggestion
		<desc>После отказа выполнить безумные требования короля-тирана, {PAWN_nameDef} и {PAWN_possessive} кочевую группу объявили преступниками. На них развернулась настоящая охота.\n\nВ конце концов {PAWN_possessive} семью схватили. Тех, кого не убили, обратили в рабство. {PAWN_nameDef} {PAWN_gender ? был : была} {PAWN_gender ? продан : продана} владельцу фабрики и в тот же день {PAWN_gender ? поклялся : поклялась} отомстить.\n      </desc>
```

2020-10-17 13:55 UTC, Elevator89 requested changes

2020-10-17 13:55 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_gender ? Росший : Росшая} под влиянием насилия, {PAWN_nameDef} {PAWN_gender ? изучал : изучала} боевые искусства и, в конечном итоге, {PAWN_gender ? начал : начала} участвовать в соревн
Это биография взрослого человека. Он уже не растёт
```suggestion
		<desc>Живя в окружении, полном насилия, {PAWN_nameDef} {PAWN_gender ? изучал : изучала} боевые искусства и, в конечном итоге, {PAWN_gender ? начал : начала} участвовать в соревнованиях по рукопашному бою.\n\nВ отличие от своих противников, {PAWN_nameDef} {PAWN_gender ? брал : брала} пример с различных воинов древности. {PAWN_pronoun} {PAWN_gender ? упражнялся : упражнялась} каждый день от рассвета до заката, оттачивая свои навыки.</desc>
```

2020-10-17 13:55 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Будучи ребёнком, {PAWN_nameDef} {PAWN_gender ? создавал : создавала} сложные вычислительные алгоритмы. Всё детство{PAWN_possessive} использовали как «человеческий компьютер». Из-за этого {PAW
```suggestion
		<desc>Будучи ребёнком, {PAWN_nameDef} {PAWN_gender ? создавал : создавала} сложные вычислительные алгоритмы. Всё детство {PAWN_possessive} использовали как «человеческий компьютер». Из-за этого {PAWN_nameDef} {PAWN_gender ? вырос : выросла} социально {PAWN_gender ? неадаптированным : неадаптированной} и слабо {PAWN_gender ? развитым : развитой} физически.\n\nНесмотря на постоянное одиночество, {PAWN_nameDef} {PAWN_gender ? выработал : выработала} богатое воображение, чтобы занимать себя в свободное время.</desc>
```

2020-10-17 13:55 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Руководствуясь своим детским опытом, {PAWN_nameDef} {PAWN_gender ? стал : стала} компьютерным инженером. {PAWN_pronoun} также {PAWN_gender ? научился : научилась} мастерить изощрённые скульпт
Криворукий автор наоставлял в конце переносы строк. Не надо их переносить в перевод.
```suggestion
		<desc>Руководствуясь своим детским опытом, {PAWN_nameDef} {PAWN_gender ? стал : стала} компьютерным инженером. {PAWN_pronoun} также {PAWN_gender ? научился : научилась} мастерить изощрённые скульптуры и различную электронику.\n\n{PAWN_nameDef} очень {PAWN_gender ? увлёкся : увлеклась} технологиями и почти {PAWN_gender ? перестал : перестала} общаться с людьми. Единственные друзья в виде компьютеров не научили {PAWN_possessive} заботиться о других.</desc>
```

2020-10-17 13:55 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_gender ? Родившийся : Родившаяся} в семье кочевников в средневековом мире, {PAWN_nameDef} с самого детства {PAWN_gender ? обучался : обучалась} красноречию, ловкости рук и верховой езде
Два деепричастных оборота - не айс.
"Всегда носился по лагерю" - слишком дословный перевод. Тут имелось в виду, что он был мальчиком на побегушках "подай-принеси".
```suggestion
		<desc>{PAWN_gender ? Родившийся : Родившаяся} в семье кочевников в средневековом мире, {PAWN_nameDef} с самого детства {PAWN_gender ? обучался : обучалась} красноречию, ловкости рук и верховой езде.\n\n{PAWN_pronoun} всё время {PAWN_gender ? хлопотал : хлопотала} в лагере, выполняя разнообразные, порой необычные, поручения на пользу своей большой семье.</desc>
```

2020-10-17 13:55 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>После отказа выполнить безумные требования короля-тирана, {PAWN_nameDef} и {PAWN_possessive} кочевую группу объявили преступниками. На них развернулась настоящая охота.\n\nВ конце концов {PAW
Несогласованное по смыслу предложение. Тот кто отказался выполнять требования и тот, кто объявил группу преступниками - явно разные субъекты.
Band - это здесь не банда, и не группа, а род или племя.
```suggestion
		<desc>Кочевое племя, которому {PAWN_gender ? принадлежал : принадлежала} {PAWN_nameDef}, однажды отказалось выполнять требования короля-тирана, в результате чего их объявили преступниками и развернули настоящую охоту.\n\nВ конце концов семью {PAWN_nameDef} схватили. Тех, кого не убили, обратили в рабство. {PAWN_gender ? Сам : Сама} {PAWN_nameDef} {PAWN_gender ? был продан : была продана} владельцу фабрики и в тот же день {PAWN_gender ? поклялся : поклялась} отомстить.</desc>
```

2020-10-17 13:55 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в маленькой и бедной семье. {PAWN_possessive} жестоко травили, били и презирали. Взрослея, {PAWN_nameDef} {PAWN_gender ? приобрёл : приобрела
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в маленькой бедной семье. {PAWN_possessive} жестоко травили, били и презирали. Взрослея, {PAWN_nameDef} {PAWN_gender ? приобрёл : приобрела} интерес к огнестрельному оружию. Всё новое {PAWN_pronoun} {PAWN_gender ? узнавал : узнавала} из книжек, но иногда у н{PAWN_possessive} была возможность по-настоящему попрактиковаться. Позже {PAWN_nameDef} {PAWN_gender ? обнаружил : обнаружила} в себе талант к искусству и самостоятельно {PAWN_gender ? научился : научилась} рисовать.</desc>
```

2020-10-17 13:55 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>После многих лет подготовки и практики, {PAWN_gender} {PAWN_gender ? поступил : поступила} в академию искусств, чтобы и дальше развивать свои художественные навыки. После выпуска с хорошими о
```suggestion
		<desc>После многих лет подготовки и практики {PAWN_nameDef} {PAWN_gender ? поступил : поступила} в академию искусств, чтобы и дальше развивать свои художественные навыки. После выпуска с хорошими оценками {PAWN_pronoun} {PAWN_gender ? искал : искала} работу в творческой отрасли. В итоге {PAWN_nameDef} начала зарабатывать на достойную жизнь, выполняя частные заказы.</desc>
```

2020-10-17 13:55 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} перевозил богатых предпринимателей и политиков.\n\nПостоянно наблюдая за тем, в какие пучины гедонизма эти люди опускались, {PAWN_nameDef} {PAWN_gender ? изменился : изменилась
> Witnessing the depths of hedonism these people descended to changed him in ways not even he understood.

Мда, какой оригинал, такой и перевод...
```suggestion
		<desc>{PAWN_nameDef} перевозил богатых предпринимателей и политиков.\n\nПостоянно наблюдая за тем, в какие пучины гедонизма эти люди опускались, {PAWN_nameDef}, не осознавая того, сильно {PAWN_gender ? изменился сам : изменилась сама}.</desc>
```

2020-10-17 13:55 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +    <titleFemale>школьная бунтарка</titleFemale>
Здесь и во всему реквесту какая-то беда с форматированием. Явно надо использовать табы вместо пробелов.

2020-10-17 13:55 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Желая лучше понимать людей, {PAWN_nameDef} {PAWN_gender ? обучился : обучилась} искусству гипноза, к которому позже {PAWN_gender ? обнаружил : обнаружила} у себя настоящий талант.\n\n{PAWN_na
```suggestion
		<desc>Желая лучше понимать людей, {PAWN_nameDef} {PAWN_gender ? обучился : обучилась} искусству гипноза, к которому позже {PAWN_gender ? обнаружил : обнаружила} у себя настоящий талант.\n\n{PAWN_nameDef} {PAWN_gender ? смог : смогла} собрать вокруг своей энергичной личности культ её поклонников. Власти узнали о {PAWN_possessive} незаконной деятельности, но {PAWN_nameDef} {PAWN_gender ? успел : успела} сбежать до ареста.</desc>
```

2020-10-17 18:29 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Будучи ребёнком, {PAWN_nameDef} {PAWN_gender ? создавал : создавала} сложные вычислительные алгоритмы. Всё детство{PAWN_possessive} использовали как «человеческий компьютер». Из-за этого {PAW
![image](https://user-images.githubusercontent.com/57110948/96350652-799c0c80-10bf-11eb-9523-428a460e67d6.png)
Не вижу здесь physically underdeveloped
По контексту больше будет подходить "хилый". Поменяй - залью.

2020-10-17 18:30 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Руководствуясь своим детским опытом, {PAWN_nameDef} {PAWN_gender ? стал : стала} компьютерным инженером. {PAWN_pronoun} также {PAWN_gender ? научился : научилась} мастерить изощрённые скульпт
Ну так не переноси. 
Да и вообще, с каких это пор Тайнен делает что-то неправильно?

2020-10-17 18:33 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>После многих лет подготовки и практики, {PAWN_gender} {PAWN_gender ? поступил : поступила} в академию искусств, чтобы и дальше развивать свои художественные навыки. После выпуска с хорошими о
А куда ты потерял "from heart"?
Так не пойдёт.

2020-10-17 18:38 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} перевозил богатых предпринимателей и политиков.\n\nПостоянно наблюдая за тем, в какие пучины гедонизма эти люди опускались, {PAWN_nameDef} {PAWN_gender ? изменился : изменилась
Тогда уж: Постоянно наблюдая за тем, в какие пучины гедонизма эти люди опускались, {PAWN_nameDef} сильно {PAWN_gender ? изменился : изменилась }, {PAWN_gender ? сам : сама} не осознавая, насколько.

Лучше передаёт степень отчуждённости человека от своего прежнего "я"

2020-10-17 18:44 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Руководствуясь своим детским опытом, {PAWN_nameDef} {PAWN_gender ? стал : стала} компьютерным инженером. {PAWN_pronoun} также {PAWN_gender ? научился : научилась} мастерить изощрённые скульпт
Если что, это не Тайнен придумывает истории, а сами игроки, за отдельную плату. И переносит их в игру, думаю, тоже не Тайнен.
В любом случае, перенос строки в конце - это косяк форматирования, переносить его не надо.

2020-10-17 18:45 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} перевозил богатых предпринимателей и политиков.\n\nПостоянно наблюдая за тем, в какие пучины гедонизма эти люди опускались, {PAWN_nameDef} {PAWN_gender ? изменился : изменилась
Хорошо, пусть будет твой последний вариант.

2020-10-17 18:49 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Будучи ребёнком, {PAWN_nameDef} {PAWN_gender ? создавал : создавала} сложные вычислительные алгоритмы. Всё детство{PAWN_possessive} использовали как «человеческий компьютер». Из-за этого {PAW
Я хотел бы оставить акцент на том, что он был неразвит и **социально**, и **физически**.

2020-10-17 18:56 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>После многих лет подготовки и практики, {PAWN_gender} {PAWN_gender ? поступил : поступила} в академию искусств, чтобы и дальше развивать свои художественные навыки. После выпуска с хорошими о
Там или "make from heart", или "living from heart".
Первое близко по значению к "делать с душой", второе - к "жить от души".
Второе лучше подходит по смыслу, но синонимично с "достойной жизнью", потому я решил не повторяться.

2020-10-17 19:01 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Будучи ребёнком, {PAWN_nameDef} {PAWN_gender ? создавал : создавала} сложные вычислительные алгоритмы. Всё детство{PAWN_possessive} использовали как «человеческий компьютер». Из-за этого {PAW
А я хотел бы, чтобы в местах, где используются слова нормального и пока живого языка, стояла не полу-терминологическая лексика.
Читатель - не идиот и прекрасно поймёт желанный тобою акцент в более красиво оформленных речевых конструкциях, правда.

2020-10-17 19:08 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>После многих лет подготовки и практики, {PAWN_gender} {PAWN_gender ? поступил : поступила} в академию искусств, чтобы и дальше развивать свои художественные навыки. После выпуска с хорошими о
То есть, авторская игра слов для нас теперь является непреодолимым препятствием и нам её нужно выкинуть?
Здесь она, кстати, вполне корректна и мною изначально переведена правильно.

Добавь хотя бы "с удовольствием" или "счастливо" куда-нибудь в последнее предложение, чтобы смысл не терялся. Смысл того, что человек нашёл себе какую-то нишу, где он получает достойную плату и **счастлив**.

2020-10-17 19:09 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} перевозил богатых предпринимателей и политиков.\n\nПостоянно наблюдая за тем, в какие пучины гедонизма эти люди опускались, {PAWN_nameDef} {PAWN_gender ? изменился : изменилась
Исправь, пожалуйста, у себя и я залью

2020-10-17 19:24 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>После многих лет подготовки и практики, {PAWN_gender} {PAWN_gender ? поступил : поступила} в академию искусств, чтобы и дальше развивать свои художественные навыки. После выпуска с хорошими о
> мною изначально переведена правильно.

"Родной душе заработок"? Ну такое, если честно
Добавил "с удовольствием"

2020-10-17 19:29 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Будучи ребёнком, {PAWN_nameDef} {PAWN_gender ? создавал : создавала} сложные вычислительные алгоритмы. Всё детство{PAWN_possessive} использовали как «человеческий компьютер». Из-за этого {PAW
"Из-за этого Вася вырос социально неадаптированным и физически хилым"
"Из-за этого Вася вырос социально неадаптированным и хилым"
Во втором варианте "социально неадаптированным и хилым" воспринимается как "социально неадаптированным и социально хилым". Только через секунду становится понятно, что имел в виду автор.
Второй вариант как-то получше будет в этом плане .

2020-10-17 21:09 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Будучи ребёнком, {PAWN_nameDef} {PAWN_gender ? создавал : создавала} сложные вычислительные алгоритмы. Всё детство{PAWN_possessive} использовали как «человеческий компьютер». Из-за этого {PAW
Не знаю, Андрей, откуда у тебя такие проблемы.
Лично у меня и ещё пары игроков прямо за моей спиной никакой проблемы в понимании обоих предложенных мною вариантов не было.

Если тебе не нравится сочетание "социально неадаптированный" и "хилый", можно использовать "малообщительный"/"неловкий в общении"/"необщительный" вместо первого - это, кстати, более распространённая практика чем мой изначальный вариант.

2020-10-17 21:10 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} перевозил богатых предпринимателей и политиков.\n\nПостоянно наблюдая за тем, в какие пучины гедонизма эти люди опускались, {PAWN_nameDef} {PAWN_gender ? изменился : изменилась
```suggestion
		<desc>{PAWN_nameDef} перевозил богатых предпринимателей и политиков.\n\nПостоянно наблюдая за тем, в какие пучины гедонизма эти люди опускались, {PAWN_nameDef}, не осознавая того, насколько сильно {PAWN_gender ? изменился сам : изменилась сама}.
```

2020-10-17 21:31 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Будучи ребёнком, {PAWN_nameDef} {PAWN_gender ? создавал : создавала} сложные вычислительные алгоритмы. Всё детство{PAWN_possessive} использовали как «человеческий компьютер». Из-за этого {PAW
> "малообщительный"/"неловкий в общении"/"необщительный" вместо первого - это, кстати, более распространённая практика чем мой изначальный вариант.

Соглашусь

2020-10-17 21:33 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} перевозил богатых предпринимателей и политиков.\n\nПостоянно наблюдая за тем, в какие пучины гедонизма эти люди опускались, {PAWN_nameDef} {PAWN_gender ? изменился : изменилась
Исправил

2020-10-18 21:57 UTC, merged