Update Backstories translation
Ludeon/RimWorld-ru pull request #1191
Opened 2020-11-28 18:06 UTC by EcherArt

Update translation of a backstories added in .2747: <OrphanedAcrobat84>, <MercenaryCaptain56>, <ArtSlave57>, <ModDesigner85>.

2020-11-28 18:07 UTC, EcherArt commented on Core/Backstories/Backstories.xml
> +								<desc>Городской мир, на котором [PAWN_gender ? родился : родилась] [PAWN_nameDef], всегда был обращён одной стороной к солнцу.  [PAWN_pronoun] [PAWN_gender ? жил : жила] в сумеречной обитаемо
```suggestion
<desc>Городской мир, на котором [PAWN_gender ? родился : родилась] [PAWN_nameDef], всегда был обращён одной стороной к солнцу.  [PAWN_pronoun] [PAWN_gender ? жил : жила] в сумеречной обитаемой зоне. [PAWN_possessive] продали местному правителю после семейной ссоры. [PAWN_pronoun] [PAWN_gender ? стал : стала] рабом-художником. n\n[PAWN_nameDef] [PAWN_gender ? был вынужден : была вынуждена] создавать произведения искусства — или понести наказание. [PAWN_pronoun] [PAWN_gender ? отрешился : отрешилась] от реальности и не умеет налаживать отношения с другими людьми.</desc>
```

2020-11-28 18:09 UTC, EcherArt commented on Core/Backstories/Backstories.xml
> +	<desc>Городской мир, на котором [PAWN_gender ? родился : родилась] [PAWN_nameDef], всегда был обращён одной стороной к солнцу.  [PAWN_pronoun] [PAWN_gender ? жил : жила] в сумеречной обитаемой зоне.
```suggestion
	<desc>Городской мир, на котором [PAWN_gender ? родился : родилась] [PAWN_nameDef], всегда был обращён одной стороной к солнцу.  [PAWN_pronoun] [PAWN_gender ? жил : жила] в сумеречной обитаемой зоне. [PAWN_possessive] продали местному правителю после семейной ссоры. [PAWN_pronoun] [PAWN_gender ? стал : стала] рабом-художником. n\n[PAWN_nameDef] [PAWN_gender ? был вынужден : была вынуждена] создавать произведения искусства — или понести наказание. [PAWN_pronoun] [PAWN_gender ? отрешился : отрешилась] от реальности и не умеет налаживать отношения с другими людьми.</desc>
```

2020-11-29 19:16 UTC, Elevator89 requested changes

2020-11-29 19:16 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>[PAWN_nameDef] [PAWN_gender ? разрабатывал : разрабатывала] боевые модификации для солдат на передовой.\n\nОднажды ночью, в кошмаре, перед [PAWN_possessive] глазами предстали все люди, убитые
"One night, in a nightmare, " переводить слово в слово было необязательно.
А вот эмоциональную окраску с "men and women" стоило бы сохранить. Сравни:
"перед его глазами предстали все люди, убитые при помощи его творений" или
"перед его глазами предстали все мужчины и женщины, убитые при помощи его творений".

```suggestion
		<desc>[PAWN_nameDef] [PAWN_gender ? разрабатывал : разрабатывала] боевые модификации для солдат на передовой.\n\nОднажды в кошмарном сне перед [PAWN_possessive] глазами предстали все мужчины и женщины, убитые при помощи [PAWN_possessive] творений. [PAWN_nameDef] [PAWN_gender ? решил : решила] отправиться в путешествие по окраинным мирам и использовать свои навыки во благо.</desc>
```

2020-11-29 20:05 UTC, EcherArt commented on Core/Backstories/Backstories.xml
> +		<desc>[PAWN_nameDef] [PAWN_gender ? разрабатывал : разрабатывала] боевые модификации для солдат на передовой.\n\nОднажды ночью, в кошмаре, перед [PAWN_possessive] глазами предстали все люди, убитые
я не знаю, почему мужчины и женщины страшнее, чем люди, но ок

2020-11-29 20:06 UTC, EcherArt commented on Core/Backstories/Backstories.xml
> +		<title><title>раб-художник</title></title>
```suggestion
		<title>раб-художник</title>
```

2020-11-29 20:10 UTC, EcherArt commented on Core/Backstories/Backstories.xml
> +	<desc>Городской мир, на котором [PAWN_gender ? родился : родилась] [PAWN_nameDef], всегда был обращён одной стороной к солнцу.  [PAWN_pronoun] [PAWN_gender ? жил : жила] в сумеречной обитаемой зоне.
```suggestion
	<desc>[PAWN_nameDef] [PAWN_gender ? родился : родилась] в городском мире, в обитаемой сумеречной зоне планеты, обращённой одной стороной к солнцу. Однажды в семье разгорелась ссора, и отец продал [PAWN_possessive] местному правителю в качестве раба-художника.\n\n[PAWN_nameDef] [PAWN_gender ? был вынужден : была вынуждена] создавать произведения искусства под страхом наказания. В результате [PAWN_pronoun] [PAWN_gender ? отрешился : отрешилась] от реальности и [PAWN_gender ? разучился : разучилась] налаживать отношения с другими людьми.</desc></desc>
```

2020-11-29 20:30 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +	<desc>Городской мир, на котором [PAWN_gender ? родился : родилась] [PAWN_nameDef], всегда был обращён одной стороной к солнцу.  [PAWN_pronoun] [PAWN_gender ? жил : жила] в сумеречной обитаемой зоне.
Я старался чтобы было ясно, что отец продавал именно персонажа, а не мир или солнце, поэтому перед местоимением [PAWN_possessive] я поставил имя персонажа. О чём речь, по контексту догадаться просто, но с именем звучит как-то лучше.
А "разгорелась ссора" - это хорошо и литературно. Если сможешь совместить с идеей выше - будет здорово.

2020-11-30 19:17 UTC, Elevator89 approved these changes

2020-12-01 21:34 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +	<desc>[PAWN_nameDef] [PAWN_gender ? родился : родилась] в городском мире, в обитаемой сумеречной зоне планеты, обращённой одной стороной к солнцу. Однажды в семье разгорелась ссора, и  [PAWN_nameDef
```suggestion
	<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в перенаселённой сумеречной зоне планеты, обращённой одной стороной к солнцу. Однажды в семье разгорелась ссора, и {PAWN_nameDef} {PAWN_gender ? был продан : была продана} в рабство собственным отцом. {PAWN_posessive} заставляли создавать произведения искусства для местного правителя под страхом наказания. В результате {PAWN_pronoun} {PAWN_gender ? отрешился : отрешилась} от реальности и {PAWN_gender ? разучился : разучилась} налаживать отношения с другими людьми.</desc>
```

2020-12-01 21:54 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>[PAWN_nameDef] [PAWN_gender ? рос : росла] тихой сиротой в городском мире, когда [PAWN_possessive] пригласили в странствующий цирк. [PAWN_possessive] небольшой рост и наблюдательность помогли
```suggestion
		<desc>[PAWN_nameDef] [PAWN_gender ? рос : росла] тихой сиротой в городском мире, когда [PAWN_possessive] пригласили в странствующий цирк. [PAWN_possessive] небольшой рост и наблюдательность помогли [PAWN_objective] стать известным акробатом.\n\nК сожалению, [PAWN_possessive] склонности к насилию привели к преждевременному окончанию акробатической карьеры.</desc>
```

2020-12-01 22:01 UTC, merged