Fix for Backstories.xml pt.3
Ludeon/RimWorld-ru pull request #1195
Opened 2020-12-31 13:30 UTC by kamadz

Happy New Year! Fixed tenses (lines 2000-3003)

2021-01-01 20:30 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_possessive} отстранили от работы всей жизни после того, как были опубликованы данные по {PAWN_possessive} экспериментам, проведённым над выжившими в инциденте на Каллосе IX. В изгнании
>{PAWN_possessive} отстраняют от работы всей жизни ...

Такое начало - вынужденная мера, потому что в противном случае получилось бы: "Вася отстраняют от работы всей жизни после того, как...". 
Вариант "Вася был отстранён от работы всей жизни после того, как ..." был невозможен, так как не было gender-оператора. Теперь дела обстоят иначе, и можно всё сформулировать по-нормальному:
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? был отстранён : была отстранена} от работы всей жизни после публикации данные по {PAWN_possessive} экспериментам, проведённым над выжившими в инциденте на Каллосе IX. В изгнании {PAWN_nameDef} {PAWN_gender ? освоил : освоила} все навыки, необходимые для выживания на окраинных мирах.\n\nПоскольку {PAWN_objective} было больше нечего  терять, {PAWN_nameDef} {PAWN_gender ? продолжил : продолжила} свои исследования, создав себе слуг для выполнения рутинной работы.</desc>
```


Старый вариант - вынужд

2021-01-01 21:30 UTC, Elevator89 requested changes

2021-01-01 21:30 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>В возрасте семи лет {PAWN_nameDef} {PAWN_gender ? потерял : потеряла} своих родителей в результате пожара. {PAWN_pronoun} {PAWN_gender ? рос : росла} на ферме дяди, занимаясь ручным трудом и
Не очень понял новый вариант. Смысл оригинала исказился.
```suggestion
		<desc>В возрасте семи лет {PAWN_nameDef} {PAWN_gender ? потерял : потеряла} своих родителей в результате пожара. {PAWN_pronoun} {PAWN_gender ? рос : росла} на ферме дяди, занимаясь ручным трудом и вспахивая поля.\n\nОбщение с окружающими {PAWN_nameDef} {PAWN_gender ? заменил : заменила} тяжёлой работой, чтобы не слышать вопросы о своих родителях, — отвечать на них для н{PAWN_possessive} было невыносимым.</desc>
```

2021-01-01 21:30 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} хорошо известным инженером-строителем. {PAWN_possessive} работа включала в себя проектирование и обслуживание укреплённых сооружений из камня. {PAWN_
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} хорошо известным инженером-строителем. {PAWN_possessive} работа включала в себя проектирование и обслуживание укреплённых сооружений из камня. {PAWN_nameDef} {PAWN_gender ? проводил : проводила} много статистических анализов, что позволяло {PAWN_objective} сохранять остроту ума.</desc>
```

2021-01-01 21:30 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? записался : записалась} рабочим в армию и большую часть времени {PAWN_gender ? проводил : проводила}, готовя еду и занимаясь ремонтными работами. Во время пребыв
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? записался : записалась} рабочим в армию и большую часть времени {PAWN_gender ? проводил : проводила}, готовя еду и занимаясь ремонтными работами. Во время пребывания на опасной планете {PAWN_pronoun} {PAWN_gender ? был обучен : была обучена} основам стрельбы и выживания.</desc>
```

2021-01-01 21:30 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>В окружении заботы своих родителей {PAWN_nameDef} благополучно {PAWN_gender ? жил : жила} в среднем мире. {PAWN_pronoun} {PAWN_gender ? рос общительным и жизнерадостным мальчиком : росла общи
Старый перевод - очередной пример вынужденного синтаксического извращения. Надо исправить:
```suggestion
		<desc>{PAWN_nameDef} благополучно {PAWN_gender ? жил : жила} в среднем мире, {PAWN_gender ? окружённый : окружённая} заботой своих родителей. {PAWN_pronoun} {PAWN_gender ? рос общительным и жизнерадостным мальчиком : росла общительной и жизнерадостной девочкой}, {PAWN_gender ? обожающим : обожающей} заводить друзей и слушать их истории. {PAWN_possessive} богатое воображение постоянно давало жизнь новым идеям и вопросам.</desc>
```

2021-01-01 21:30 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Интерес к художественному самовыражению в конце концов привёл {PAWN_possessive} к профессии дизайнера. Внимание к деталям принесло {PAWN_objective} немалую известность на своей планете, однак
Начинать текст с местоимения было раньше суровой необходимостью. Сейчас - по большей части нет.
```suggestion
		<desc>Реализуя своё стремление к художественному самовыражению, {PAWN_nameDef} {PAWN_gender ? стал : стала} дизайнером. Характерное для н{PAWN_possessive} внимание к деталям принесло {PAWN_objective} немалую известность на своей планете, но в то же время приводило к тому, что {PAWN_nameDef} {PAWN_gender ? тратил : тратила} слишком много времени на доведение каждого проекта до совершенства.</desc>
```

2021-01-01 21:30 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} наконец {PAWN_gender ? сбежал : сбежала} от преступной жизни, устроившись в штат техобслуживания космической станции, где {PAWN_pronoun} {PAWN_gender ? выполнял : выполняла} ра
```suggestion
		<desc>{PAWN_nameDef} наконец {PAWN_gender ? сбежал : сбежала} от преступной жизни, устроившись в штат техобслуживания космической станции, где {PAWN_pronoun} {PAWN_gender ? выполнял : выполняла} различные ремонтные и строительные работы. {PAWN_nameDef} иногда {PAWN_gender ? помогал : помогала} проводить исследования и часто {PAWN_gender ? разрешал : разрешала} споры между коллегами. Тем не менее, заниматься искусством {PAWN_pronoun} не {PAWN_gender ? любил : любила} никогда.</desc>
```

2021-01-01 21:30 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShort>ботан</titleShort>
Слишком разговорное слово. Старый вариант был лучше.

2021-01-01 21:30 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>После окончания «Демрийской войны» {PAWN_possessive} родителей захватили в плен, и {PAWN_nameDef} {PAWN_gender ? родился и рос : родилась и росла} в рабстве. {PAWN_possessive} заставляли чист
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? родился и рос : родилась и росла} в рабстве, потому что {PAWN_possessive} родители были захвачены в плен в результате «Демрийской войны». {PAWN_possessive} заставляли чистить арены колизеев после кровопролитных боёв. Арена стала всем, что {PAWN_nameDef} {PAWN_gender ? успел : успела} узнать и увидеть.\n\nОднажды ночью, во время очередной уборки, {PAWN_possessive} семью убили.</desc>
```

2021-01-07 15:53 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Применяя знания и навыки, полученные за многие годы от бойцов арены, {PAWN_nameDef} {PAWN_gender ? сам стал : сама стала} успешным гладиатором в колизее, который раньше {PAWN_gender ? убирал
```suggestion
		<desc>Применив знания и навыки, полученные за многие годы от бойцов арены, {PAWN_nameDef} {PAWN_gender ? сам стал : сама стала} успешным гладиатором в колизее, который раньше {PAWN_gender ? убирал : убирала}.</desc>
```

2021-01-07 16:41 UTC, Elevator89 requested changes
Новая порция комментов. Будут ещё.

2021-01-07 16:41 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Будучи {PAWN_gender ? молодым : молодой} {PAWN_nameDef} не сомневается, что {PAWN_possessive} планета и люди приближаются к трансценденции.\n\nТвёрдая убеждённость в том, что {PAWN_possessive
Вот тут вообще непонятно, что хотел сказать автор. Типа, уверенными в скорой трансценденции могуть быть только молодые люди?
Но всё равно непонятно, почему тут именно такая замена. Чем "В совершеннолетнем возрасте" было хуже?
```suggestion
		<desc>В совершеннолетнем возрасте {PAWN_nameDef} не {PAWN_gender ? сомневался : сомневалась}, что {PAWN_possessive} планета и люди приближаются к трансценденции.\n\nТвёрдая убеждённость в том, что {PAWN_possessive} исследование станет катализатором, в конце концов привела {PAWN_possessive} к действиям, вызвавшим большой общественный резонанс. Бюрократы и комитеты по биоэтике начали чинить многочисленные препятствия на {PAWN_possessive} пути.</desc>
```

2021-01-07 16:41 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>На планете, где {PAWN_gender ? жил : жила} {PAWN_nameDef}, вспыхивает война.\n\nСобрав еду и вещи, какие удалось найти, {PAWN_pronoun} со своим отцом {угнали космический корабль и покинули ро
```suggestion
		<desc>На планете, где {PAWN_gender ? жил : жила} {PAWN_nameDef}, вспыхнула война.\n\nСобрав еду и вещи, какие удалось найти, {PAWN_pronoun} со своим отцом угнали космический корабль и покинули родную планету.</desc>
```

2021-01-07 16:41 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Покинув родную планету, {PAWN_nameDef} со своим отцом сотни лет сражались в бесчисленных битвах. В конце концов {PAWN_nameDef} {PAWN_gender ? стал : стала} закалённым ветераном, не знающим пр
Двойной пробел
```suggestion
		<desc>Покинув родную планету, {PAWN_nameDef} со своим отцом сотни лет сражались в бесчисленных битвах. В конце концов {PAWN_nameDef} {PAWN_gender ? стал : стала} закалённым ветераном, не знающим промаха.\n\nКогда {PAWN_possessive} отец погиб в бою, {PAWN_nameDef} в одиночку {PAWN_gender ? отправился : отправилась} мстить за его смерть.</desc>
```

2021-01-07 16:41 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? рос : росла}  в рабстве у очень скверной дворянской семьи в средневековом мире.\n\n{PAWN_pronoun} не {PAWN_gender ? получил : получила} общепринятого образования
Ещё один
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? рос : росла} в рабстве у очень скверной дворянской семьи в средневековом мире.\n\n{PAWN_pronoun} не {PAWN_gender ? получил : получила} общепринятого образования, зато тяжёлый труд закалил {PAWN_possessive} тело.</desc>
```

2021-01-07 16:41 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} самым мускулистым и устрашающим среди рабов своего господина. {PAWN_pronoun} {PAWN_gender ? посвящал : посвящала} всё своё время изнурительным тренир
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? был самым мускулистым и устрашающим : была самой мускулистой и устрашающей} среди рабов своего господина. {PAWN_pronoun} {PAWN_gender ? посвящал : посвящала} всё своё время изнурительным тренировкам. И упорный труд был вознаграждён, когда {PAWN_possessive} господин предложил {PAWN_objective} работу личного телохранителя.\n\nОднако, когда {PAWN_nameDef} {PAWN_gender ? попытался : попыталась} использовать своё положение, чтобы убить господина и освободить рабов, — {PAWN_possessive} план раскрыли, и {PAWN_objective} пришлось бежать.</desc>
```

2021-01-07 16:41 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Поскольку {PAWN_possessive} искусственно вырастили и натренировали для лечения солдат в бою, {PAWN_nameDef} обращается с винтовкой столь же искусно, сколь и с аптечкой первой помощи. Подходя
Уберём синтаксические ухищрения:
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? был искусственно выращен : была искусственно выращена} для работы полевым врачом и {PAWN_gender ? обучен : обучена} обращаться с винтовкой столь же искусно, сколь и с аптечкой первой помощи. Подходя к раненому бойцу, {PAWN_pronoun} {PAWN_gender ? обожал : обожала} спрашивать «Жизнь или смерть?». Большинство выбирало жизнь.</desc>
```

2021-01-07 16:41 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_possessive} с детства учили петь и танцевать, проча карьеру поп-звезды. Всё это время {PAWN_possessive} опекали кураторы из компании.\n\n{PAWN_nameDef} не {PAWN_gender ? занимался : зан
Уберём изврат
```suggestion
		<desc>{PAWN_nameDef} с детства {PAWN_gender ? обучался : обучалась} пению и танцам: {PAWN_objective} прочили карьеру поп-звезды. Всё это время {PAWN_possessive} опекали кураторы из компании.\n\n{PAWN_nameDef} не {PAWN_gender ? занимался : занималась} физическим трудом, зато очень много {PAWN_gender ? узнал : узнала} о музыке и этикете.</desc>
```

2021-01-07 16:41 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} всегда {PAWN_gender ? находился : находилась} в центре внимания и даёт множество интервью. {PAWN_pronoun} {PAWN_gender ? отточил : отточила} до совершенства свои умения танцева
```suggestion
		<desc>{PAWN_nameDef} всегда {PAWN_gender ? находился : находилась} в центре внимания и {PAWN_gender ? давал : давала} множество интервью. {PAWN_pronoun} {PAWN_gender ? отточил : отточила} до совершенства свои умения танцевать и петь и {PAWN_gender ? стал : стала} настоящим мастером публичных выступлений.</desc>
```

2021-01-07 16:41 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? влачил : влачила} своё сиротское безденежное существование на космической станции. {PAWN_pronoun} {PAWN_gender ? занимался : занималась} воровством и грязной раб
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? влачил : влачила} сиротское безденежное существование на космической станции. {PAWN_pronoun} {PAWN_gender ? занимался : занималась} воровством и грязной работой и едва {PAWN_gender ? сводил : сводила} концы с концами. Со временем из-за плохого обращения {PAWN_nameDef} настолько на всех {PAWN_gender ? озлобился : озлобилась}, что {PAWN_possessive} изгнали со станции. {PAWN_possessive} тут же забрали к себе космические пираты.</desc>
```

2021-01-07 16:41 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? рос и учился : росла и училась} в лаборатории своего отца, ведя жизнь интеллектуальной элиты. {PAWN_pronoun} {PAWN_gender ? получил : получила} всё, что пожелает
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? рос и учился : росла и училась} в лаборатории своего отца, ведя жизнь интеллектуальной элиты. {PAWN_pronoun} {PAWN_gender ? получал : получала} всё, что {PAWN_gender ? желал : желала}, без оглядки на ценник.\n\nОднако в какой-то момент {PAWN_nameDef} {PAWN_gender ? решил : решила} отказаться от роскошной жизни. Вместо этого {PAWN_pronoun} {PAWN_gender ? начал : начала} заниматься физическим и, в глазах {PAWN_possessive} отца, более низкопробным трудом.</desc>
```

2021-01-07 19:49 UTC, Elevator89 requested changes
Закончил ревью

2021-01-07 19:49 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Вырвавшись из родного мира, {PAWN_nameDef} {PAWN_gender ? продолжил : продолжила} применять и совершенствовать свои навыки.\n\n{PAWN_pronoun} {PAWN_gender ? был : была} наёмником для различны
```suggestion
		<desc>Вырвавшись из родного мира, {PAWN_nameDef} {PAWN_gender ? продолжил : продолжила} применять и совершенствовать свои навыки.\n\n{PAWN_pronoun} {PAWN_gender ? стал : стала} наёмником для различных повстанческих организаций, притесняемых групп и торговых анклавов. {PAWN_possessive} специализацией были переговоры в боевой обстановке.</desc>
```

2021-01-07 19:49 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<title>ботан</title>
Ну не надо "ботанов"!
```suggestion
		<title>ботаник</title>
```

2021-01-07 19:49 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShort>ботан</titleShort>
```suggestion
		<titleShort>ботаник</titleShort>
```

2021-01-07 19:49 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<title>робкий ботан</title>
```suggestion
		<title>робкий ботаник</title>
```

2021-01-07 19:49 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShort>ботан</titleShort>
```suggestion
		<titleShort>ботаник</titleShort>
```

2021-01-07 19:49 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был известным исследователем : была известной исследовательницей} в области искусственного интеллекта, робототехники и интерактивной голографии. {PAWN_possessive
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? стал известным исследователем : стала известной исследовательницей} в области искусственного интеллекта, робототехники и интерактивной голографии. {PAWN_possessive} дружба с искусственным интеллектом собственной разработки придала {PAWN_objective} уверенности, и {PAWN_pronoun} вскоре {PAWN_gender ? начал : начала} преуспевать в общении с реальными людьми.</desc>
```

2021-01-07 20:05 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShort>ботан</titleShort>
и как это сочетать с ботаником, который учёный-ботаник?
должно быть деление

2021-01-07 20:06 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShort>ботан</titleShort>
Особенное учитывая тот вариант, что nerd в английском тоже далеко не высокий стиль, а такой же коллоквиализм

2021-01-07 20:08 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Применяя знания и навыки, полученные за многие годы от бойцов арены, {PAWN_nameDef} {PAWN_gender ? сам стал : сама стала} успешным гладиатором в колизее, который раньше {PAWN_gender ? убирал
в чём смысл замены?

2021-01-07 20:30 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? влачил : влачила} своё сиротское безденежное существование на космической станции. {PAWN_pronoun} {PAWN_gender ? занимался : занималась} воровством и грязной раб
неа

2021-01-07 20:32 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<title>ботан</title>
придумай альтернативу

2021-01-07 20:34 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>В возрасте семи лет {PAWN_nameDef} {PAWN_gender ? потерял : потеряла} своих родителей в результате пожара. {PAWN_pronoun} {PAWN_gender ? рос : росла} на ферме дяди, занимаясь ручным трудом и
ближе по смыслу и окраске 

Заменил /= избегал (которое есть в контексте)

2021-01-07 21:26 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>В возрасте семи лет {PAWN_nameDef} {PAWN_gender ? потерял : потеряла} своих родителей в результате пожара. {PAWN_pronoun} {PAWN_gender ? рос : росла} на ферме дяди, занимаясь ручным трудом и
В оригинале персонаж не хотел с людьми общаться, и потому стал много работать. А по твоей формулировке он просто работает молча: не болтает за работой. Видишь разницу?

2021-01-07 23:37 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>В возрасте семи лет {PAWN_nameDef} {PAWN_gender ? потерял : потеряла} своих родителей в результате пожара. {PAWN_pronoun} {PAWN_gender ? рос : росла} на ферме дяди, занимаясь ручным трудом и
В моей формулировке он избегает общения РАБОТАЯ. Разницу не вижу.

2021-01-08 20:09 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>В возрасте семи лет {PAWN_nameDef} {PAWN_gender ? потерял : потеряла} своих родителей в результате пожара. {PAWN_pronoun} {PAWN_gender ? рос : росла} на ферме дяди, занимаясь ручным трудом и
Можно перефразировать: занимаясь тяжёлой работой, он избегал общения...

2021-01-10 12:09 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? влачил : влачила} своё сиротское безденежное существование на космической станции. {PAWN_pronoun} {PAWN_gender ? занимался : занималась} воровством и грязной раб
Как "неа"? Персонаж не может влачить чьё-то ещё сиротское безденежное существование, кроме своего. Слово - лишнее.

2021-01-10 12:13 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Применяя знания и навыки, полученные за многие годы от бойцов арены, {PAWN_nameDef} {PAWN_gender ? сам стал : сама стала} успешным гладиатором в колизее, который раньше {PAWN_gender ? убирал
Мне резанула слух рассогласованность времён и видов. Глагол "стал" говорит о прошедшем времени, а деепричастие - "применяя" - несовершенного вида. Но мы говорим о факте, свершившемся в прошлом: "он стал гладиатором". Потому считаю более уместным деепричастие совершенного вида.

2021-01-10 12:22 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>В возрасте семи лет {PAWN_nameDef} {PAWN_gender ? потерял : потеряла} своих родителей в результате пожара. {PAWN_pronoun} {PAWN_gender ? рос : росла} на ферме дяди, занимаясь ручным трудом и
Персонаж не избегал общения за работой, он именно заменил (replaced) общение тяжёлой работой. Он не хотел болтать о родителях в свободное время, потому сознательно сократил себе его.
Во время тяжёлого физического труда общаться в принципе весьма непросто, а у тебя фраза звучит так, словно у него был выбор: совмещать ли общение со вспахиванием поля или нет.

2021-01-10 12:37 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShort>ботан</titleShort>
Пару лет назад этот же вопрос уже обсуждался. Пришли к тому, что игрок не дурак, и сможет отличить ботаника-нерда от ботаника-биолога по полному заголовку или описанию. И решили оставить "ботаников" везде.
Кстати, ботаник-учёный, среди всех предысторий всего один ).

2021-01-10 14:10 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShort>ботан</titleShort>
```suggestion
		<titleShort>ботаник</titleShort>
```

2021-01-10 20:48 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>В возрасте семи лет {PAWN_nameDef} {PAWN_gender ? потерял : потеряла} своих родителей в результате пожара. {PAWN_pronoun} {PAWN_gender ? рос : росла} на ферме дяди, занимаясь ручным трудом и
Нет, он именно что упредительно затрахался отвечать на вопросы о своих родителях, поэтому сбегал на поле, где его никто не доставал бы. И таким образом он избегал общения за работой. Я понимаю, что эту фразу можно прочитать как "за работой он старался не общаться", но это не значит, что все так прочитают, особенно в этом контексте, поэтому это контрпродуктивная придирка и мы на ней уже тратим очень много времени.

2021-01-10 20:54 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Применяя знания и навыки, полученные за многие годы от бойцов арены, {PAWN_nameDef} {PAWN_gender ? сам стал : сама стала} успешным гладиатором в колизее, который раньше {PAWN_gender ? убирал
Только применяя (каждый день на протяжении продолжительного периода времени) на практике определённый навык, он добился успеха. 

 А мы здесь говорим именно не о том, что павн один раз применил навыки в какой-то конкретный момент времени, а _применЯЛ_ их долгое время на регулярной основе, чтобы достичь результата. Всё логично, ничего не режет и, на самом деле, единственный правильный в таком контексте вариант.

2021-01-10 20:58 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? влачил : влачила} своё сиротское безденежное существование на космической станции. {PAWN_pronoun} {PAWN_gender ? занимался : занималась} воровством и грязной раб
В данном случае притяжательное местоимение "свой" используется для придания лёгкой эмоционально-стилистической окраски. Это довольно распространённый приём и ни в коей мере слово здесь это не лишнее. Оба варианта корректны в равной степени и я не вижу смысла замены одного на другой.

2021-01-21 20:41 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>В возрасте семи лет {PAWN_nameDef} {PAWN_gender ? потерял : потеряла} своих родителей в результате пожара. {PAWN_pronoun} {PAWN_gender ? рос : росла} на ферме дяди, занимаясь ручным трудом и
Аргумент "не все так прочитают" не принимается, поскольку уже предполагает наличие разночтения, и вряд ли я буду единственным, кто поймёт твою фразу неверно. Тем не менее, предлагаемый мной вариант это разночтение исключает, и потому является более правильным.
А насчёт "контрпродуктивных придирок" - прошу оставить оценочные суждения при себе. Вместо этого предлагаю ознакомиться с best practices от Гугла по код-ревью: https://github.com/google/eng-practices/blob/master/review/developer/handling-comments.md. В документе речь прежде всего идёт про код, но думаю, что смысл сказанного ты легко сможешь экстраполировать и на текст.

2021-01-21 20:42 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Применяя знания и навыки, полученные за многие годы от бойцов арены, {PAWN_nameDef} {PAWN_gender ? сам стал : сама стала} успешным гладиатором в колизее, который раньше {PAWN_gender ? убирал
Окей, соглашусь.

2021-01-21 20:45 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? влачил : влачила} своё сиротское безденежное существование на космической станции. {PAWN_pronoun} {PAWN_gender ? занимался : занималась} воровством и грязной раб
Ну ладно.

2021-01-21 20:55 UTC, merged