Fix for Backstories.xml pt.4
Ludeon/RimWorld-ru pull request #1197
Opened 2021-01-16 22:20 UTC by kamadz

Fixed tenses and other (lines 3000-4000)

2021-01-21 20:58 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? летал : летала} с бандой разбойников, которых {PAWN_gender ? считал : считала} своими друзьями. У н{PAWN_possessive} даже есть собственный корабль — «Навозовоз-2
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? летал : летала} с бандой разбойников, которых {PAWN_gender ? считал : считала} своими друзьями. У н{PAWN_possessive} даже был собственный корабль — «Навозовоз-2000».</desc>
```

2021-01-21 21:02 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Однажды {PAWN_nameDef} {PAWN_gender ? был : была} пассажиром на обычном межзвёздном рейсе, когда корабль потерпел крушение. {PAWN_pronoun} {PAWN_gender ? спасся : спаслась} и несколько лет жи
```suggestion
		<desc>Однажды {PAWN_nameDef} {PAWN_gender ? был : была} пассажиром на обычном межзвёздном рейсе, когда корабль потерпел крушение. {PAWN_pronoun} {PAWN_gender ? спасся : спаслась} и несколько лет {PAWN_pronoun} {PAWN_gender ? жил : жила} на необитаемой планете.</desc>
```

2021-01-21 21:03 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? остался : осталась} без крыши над головой, когда {PAWN_possessive} бросают родители. Однако вскоре {PAWN_possessive} подобрал один фермер. Этот фермер не мог име
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? остался : осталась} без крыши над головой, когда {PAWN_possessive} бросили родители. Однако вскоре {PAWN_possessive} подобрал один фермер. Этот фермер не мог иметь детей и держал {PAWN_gender ? бывшего беспризорника : бывшую беспризорницу} на положении раба. {PAWN_possessive} тело покрылось рубцами от постоянных побоев. {PAWN_nameDef} не {PAWN_gender ? мог : могла} дать отпор и совладать с насилием и через несколько лет {PAWN_gender ? сбежал : сбежала}.</desc>
```

2021-02-13 13:52 UTC, Elevator89 requested changes
Пока всё. Будет продолжение.

2021-02-13 13:52 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Оставаясь всегда на шаг впереди закона, {PAWN_nameDef} {PAWN_gender ? был легальным предпринимателем : была легальной предпринимательницей}, {PAWN_gender ? заставлявшим : заставлявшей} замолч
Он не стал предпринимателем, затыкающим всем рот. Он стал предпринимателем, **потому что** заставил замолчать тех, кто знал о его бандитском прошлом.
Много слов, однокоренных слову "стать", тоже хорошо бы убрать:
```suggestion
		<desc>Будучи всегда на шаг впереди закона, {PAWN_nameDef} {PAWN_gender ? получил : получила} статус легального предпринимателя, заставив замолчать всех, кто смел сказать что-либо против этого. {PAWN_gender ? Владелец : Владелица} борделей, подпольных баров и забегаловок, {PAWN_pronoun} {PAWN_gender ? жил : жила} в своё удовольствие, пока {PAWN_possessive} дело не разрушила необъяснимая цепь случайностей.</desc>
```

2021-02-13 13:52 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>подопечная</titleShortFemale>
Чем "подкидыш" был плох?

2021-02-13 13:52 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Совсем крохой {PAWN_possessive} бросили на планете, полной диких зверей. Оставили лишь одеяло с вышитым именем — {PAWN_nameDef}. Со временем {PAWN_pronoun} {PAWN_nameDef ? стал : стала} едины
Здесь извращение с местоимением в начале текста превратили в фичу с именем на одеяле. Менять не хотелось бы

2021-02-13 13:52 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>После похищения в подростковом возрасте {PAWN_nameDef} на долгие шесть лет {PAWN_gender ? стал : стала} подопытным кроликом для экспериментальной генетической терапии. Лаборатории и учёные вн
```suggestion
		<desc>После похищения в подростковом возрасте {PAWN_nameDef} на долгие шесть лет {PAWN_gender ? стал : стала} подопытным кроликом для экспериментальной генетической терапии. С тех пор лаборатории и учёные внушают {PAWN_objective} страх.</desc>
```

2021-02-13 13:52 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был брошен : была брошена} на токсичной планете, полной опасных форм растительной жизни. {PAWN_pronoun} рано {PAWN_gender ? привык : привыкла} к жестокому холоду
Хорошо получилось

2021-02-13 13:52 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} единственным ребёнком в семье состоятельных хирургов. Они долго настаивали на том, чтобы {PAWN_pronoun} {PAWN_gender ? обучался : обучалась} медицине
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} единственным ребёнком в семье состоятельных хирургов. Они долго настаивали на том, чтобы {PAWN_pronoun} {PAWN_gender ? обучался : обучалась} медицине, и в конце концов {PAWN_nameDef} не {PAWN_gender ? выдержал : выдержала}. {PAWN_pronoun} {PAWN_gender ? сбежал : сбежала}, прихватив своё наследство, чтобы учиться взламывать компьютерные сети. {PAWN_nameDef} быстро {PAWN_gender ? стал : стала} одним из самых опасных хакеров своего родного мира.</desc>
```

2021-02-13 13:52 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был завербован : была завербована} правительством родного мира в качестве агента разведки, благодаря {PAWN_possessive} хакерским навыкам. {PAWN_nameDef} {PAWN_ge
```suggestion
		<desc>Благодаря своим хакерским навыкам, {PAWN_nameDef} {PAWN_gender ? был завербован : была завербована} правительством родного мира в качестве агента разведки. {PAWN_pronoun} {PAWN_gender ? получил : получила} хорошую боевую подготовку, но больше {PAWN_gender ? предпочитал : предпочитала} использовать приёмы психологической войны.\n\nПравительственные законы оказались для н{PAWN_possessive} слишком строги, и {PAWN_nameDef} {PAWN_gender ? дезертировал : дезертировала}. {PAWN_possessive} нынешняя деятельность неизвестна.</desc>
```

2021-02-13 13:52 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? рос : росла} в нищете на равнинах первобытной планеты. {PAWN_pronoun} {PAWN_gender ? нашёл : нашла} вдохновение в учении сломленного старого учёного.\n\n{PAWN_na
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? рос : росла} в нищете на равнинах первобытной планеты. {PAWN_pronoun} {PAWN_gender ? нашёл : нашла} вдохновение в учении сломленного старого учёного.\n\n{PAWN_nameDef} быстро {PAWN_gender ? научился : научилась} играть на страхах людей, за что {PAWN_gender ? получил : получила} прозвище «безумный учёный».</desc>
```

2021-02-13 13:52 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} на холодной захолустной планете, населённой в основном ксенолюдьми, и {PAWN_gender ? рос : росла} под звуки барных драк и перестрелок. Хотя {
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} на холодной захолустной планете, населённой в основном ксенолюдьми, и {PAWN_gender ? рос : росла} под звуки барных драк и перестрелок. Хотя {PAWN_possessive} детство прошло за игрой на банджо и работой механиком, неугомонный разум подталкивал {PAWN_possessive} к чему-то большему. В молодом возрасте лет {PAWN_nameDef} {PAWN_gender ? поступил : поступила} в медицинскую школу.</desc>
```

2021-02-13 13:52 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? записался : записалась} врачом на проходящее мимо научное судно. Странствуя меж звёзд с большим экипажем ксенолюдей и трансптиц, {PAWN_pronoun} {PAWN_gender ? пр
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? записался : записалась} врачом на проходящее мимо научное судно. Странствуя меж звёзд с большим экипажем ксенолюдей и трансптиц, {PAWN_pronoun} {PAWN_gender ? проводил : проводила} генетические исследования на встреченных видах. {PAWN_nameDef} {PAWN_gender ? завязал : завязала} тесную дружбу с одной из трансптиц, но {PAWN_objective} пришлось покинуть корабль, когда капитан уволил всех бескрылых.</desc>
```

2021-02-13 13:52 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Родившись на погружающемся в упадок утопическом мире, {PAWN_nameDef} {PAWN_gender ? получал : получала} любую дорогую игрушку, какую {PAWN_gender ? желал : желала}.\n\nИз-за такого изнеженног
```suggestion
		<desc>Родившись на погружающемся в упадок утопическом мире, {PAWN_nameDef} {PAWN_gender ? получал : получала} любую дорогую игрушку, какую {PAWN_gender ? желал : желала}.\n\nИз-за такого изнеженного образа жизни основные жизненные уроки прошли мимо н{PAWN_possessive}. Отвращение к готовке приводило к тому, что {PAWN_pronoun} всегда {PAWN_gender ? возлагал : возлагала} эту работу на прислугу.</desc>
```

2021-02-13 13:52 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} самостоятельно {PAWN_gender ? разрабатывал : разрабатывала} программное обеспечение, имеющее конкурентное преимущество перед продуктами корпораций {PAWN_possessive} урбанизиров
```suggestion
		<desc>{PAWN_nameDef} в одиночку {PAWN_gender ? разрабатывал : разрабатывала} программное обеспечение, имеющее конкурентное преимущество перед продуктами корпораций {PAWN_possessive} урбанизированного мира.\n\nОднако {PAWN_possessive} юридически сомнительные методы привели к увеличению числа нераскрытых дел о хищении интеллектуальной собственности.</desc>
```

2021-02-14 13:16 UTC, Elevator89 requested changes
Теперь всё

2021-02-14 13:16 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье охотников за сокровищами и с детства {PAWN_gender ? увлёкся : увлеклась} древней историей.\n\n{PAWN_nameDef} {PAWN_gender ? был : был
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в семье охотников за сокровищами и с детства {PAWN_gender ? увлёкся : увлеклась} древней историей.\n\n{PAWN_nameDef} не {PAWN_gender ? был : была} ни задиристым, ни общительным ребёнком, а больше {PAWN_gender ? предпочитал : предпочитала} копаться в книгах по истории и в земле.</desc>
```

2021-02-14 13:16 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? стал : стала} профессором ксенобиологии в университете утопического мира. {PAWN_pronoun} {PAWN_gender ? посещал : посещала} конференции и руководит галереей иску
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? стал : стала} профессором ксенобиологии в университете утопического мира. {PAWN_pronoun} {PAWN_gender ? посещал : посещала} конференции и {PAWN_gender ? руководил : руководила} галереей искусств.\n\nОднако {PAWN_pronoun} так и не {PAWN_gender ? прекратил : прекратила} ваять садовых гномов, считая это своим истинным призванием.</desc>
```

2021-02-14 13:16 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? вырос : выросла} в цирке, {PAWN_gender ? обучился : обучилась} множеству интересных вещей. В частности, жонглировать шарами казалось {PAWN_objective} менее интер
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? вырос : выросла} в цирке и {PAWN_gender ? обучился : обучилась} множеству интересных вещей. В частности, жонглировать шарами казалось {PAWN_objective} менее интересным, чем обчищать чужие карманы между представлениями.\n\nПосле одного неудачного трюка с факелами {PAWN_nameDef} смертельно боится огня.</desc>
```

2021-02-14 13:16 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? обнаружил : обнаружила}  в себе дар — люди делали то, что {PAWN_pronoun} им {PAWN_gender ? говорил : говорила} и когда {PAWN_pronoun} им об этом {PAWN_gender ? г
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? обнаружил : обнаружила} в себе дар: люди делали то, что {PAWN_pronoun} им {PAWN_gender ? говорил : говорила}, тогда, когда {PAWN_pronoun} скажет. Пользуясь этим, {PAWN_pronoun} {PAWN_gender ? отправился : отправилась} на окраинные миры, чтобы сделать себе имя в преступном мире.\n\nКогда люди постоянно делают что-то за тебя, поневоле станешь любой ценой избегать ручного труда.</desc>
```

2021-02-14 13:16 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был продан : была продана} в сексуальное рабство в городском мире. Так как {PAWN_pronoun} {PAWN_gender ? был искусственно выращен божественно красивым : была иск
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? был продан : была продана} в сексуальное рабство в городском мире. Так как {PAWN_pronoun} {PAWN_gender ? был искусственно выращен божественно красивым : была искусственно выращена божественно красивой}, {PAWN_gender ? но слабым : но слабой}, у н{PAWN_possessive} не было возможности противостоять своим хозяевам. {PAWN_nameDef} {PAWN_gender ? сменил : сменила} десятки хозяев и ничего не {PAWN_gender ? знал : знала} о свободной жизни.</desc>
```

2021-02-14 13:16 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? вырос : выросла} в феодальном мире, бывшим частью многопланетной империи. Как потомок верховного лорда {PAWN_pronoun} {PAWN_gender ? пользовался : пользовалась}
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? вырос : выросла} в феодальном мире, бывшем частью многопланетной империи. Как потомок верховного лорда {PAWN_pronoun} {PAWN_gender ? пользовался : пользовалась} многими привилегиями.\n\n{PAWN_pronoun} {PAWN_gender ? освоил : освоила} особые приёмы как на политической арене, так и в ближнем бою.</desc>
```

2021-02-14 13:16 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>После внезапного появления кровожадных, генетически модифицированных диких животных {PAWN_nameDef} {PAWN_gender ? защищал : защищала} своё поселение во имя короля.\n\nНесмотря на все {PAWN_po
Речь про **про**звище - Redfields
```suggestion
		<desc>После внезапного появления кровожадных, генетически модифицированных диких животных {PAWN_nameDef} {PAWN_gender ? защищал : защищала} своё поселение во имя короля.\n\nНесмотря на все {PAWN_possessive} усилия, королевство было разрушено. {PAWN_nameDef} {PAWN_gender ? приобрёл : приобрёл} посттравматическое расстройство, ненависть к животным и тяжёлую технофобию. {PAWN_possessive} прозвали в честь места, где нашли.</desc>
```

2021-02-15 21:14 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? провёл : провела} свои молодые годы, работая наёмником, убивая и калеча других людей. {PAWN_pronoun} {PAWN_gender ? мог : могла} внушить страх в сердце любого вс
![image](https://user-images.githubusercontent.com/57110948/107993632-f4cceb00-6feb-11eb-81dd-0ddb2716abca.png)

2021-02-15 21:16 UTC, kamadz commented on Core/Backstories/Backstories.xml
>  		<titleShort>дитя улья</titleShort>
мальчик из города / девочка из города - звучит получше

2021-02-15 21:19 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} с отличием {PAWN_gender ? закончил : закончила} Звёздную Академию и {PAWN_gender ? показал : показала} себя пилотом-асом в трёх кампаниях против превосходящего противника.\n\nН
![image](https://user-images.githubusercontent.com/57110948/107993843-7cb2f500-6fec-11eb-8415-cd3915aae60e.png)

Повреждён - несодержательно и не объясняет, почему именно пешке пришлось бежать на спасательной капсуле с корабля

2021-02-15 21:30 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был воспитан : была воспитана} в изоляции в одном из городов-ульев урбанизированного мира. Неприязнь к высоте держала {PAWN_possessive} в закрытых помещениях, и
Подразумевают-то подразумевают, только вот что-то мне подсказывает, что автор бекстори либо этого не знал, либо не совсем англоговорящий. Для простого человека, которому незнаком конкретный термин, "военная игрушка" - это "игрушка про войну".

Но возможно тут и правда референс на что-то сродни тренировочному (холодное при этом, всё-таки, обычно называется "practice weapon", а не "simulation weapon") оружию из, например, буткемпа в Starship Troopers, как ты сказал. 
Твой вариант мне кажется менее очевидным в данной ситуации. Hight tech - low life развлечения обычно в любой фантастике находят отображение в виде цифровых симуляций, а не "аналоговых".

2021-02-15 21:31 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был : была} свидетелем того, как чума свирепствовала в {PAWN_possessive} родном мире. Вскоре {PAWN_nameDef} с командой исследователей {PAWN_gender ? выяснил : вы
Помню, что думал вписать правильную формулировку, но забыл, капец

2021-02-15 21:38 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>подопечная</titleShortFemale>
Ward - это не просто какой-то там подкидыш в семье пейзанина. Для подкидышей есть foundling или waif. Здесь же молодой человек находился **на попечении** у влиятельной семьи, у таких "подкидышей" не бывает. 
TL;DR - неправильный перевод.

2021-02-15 21:38 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Совсем крохой {PAWN_possessive} бросили на планете, полной диких зверей. Оставили лишь одеяло с вышитым именем — {PAWN_nameDef}. Со временем {PAWN_pronoun} {PAWN_nameDef ? стал : стала} едины
Ну и не надо, пусть остаётся. Это уместное разнообразие.

2021-02-15 21:39 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был брошен : была брошена} на токсичной планете, полной опасных форм растительной жизни. {PAWN_pronoun} рано {PAWN_gender ? привык : привыкла} к жестокому холоду
Спасибо!

2021-02-15 21:40 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} на холодной захолустной планете, населённой в основном ксенолюдьми, и {PAWN_gender ? рос : росла} под звуки барных драк и перестрелок. Хотя {
упс

2021-02-15 21:40 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? записался : записалась} врачом на проходящее мимо научное судно. Странствуя меж звёзд с большим экипажем ксенолюдей и трансптиц, {PAWN_pronoun} {PAWN_gender ? пр
ой-ой

2021-02-15 21:42 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>подопытный</titleShortFemale>
```suggestion
		<titleShortFemale>подопытная</titleShortFemale>
```

2021-02-15 21:43 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? рос : провела} активным ребёнком с непримечательным детством, пока не {PAWN_gender ? упал : упала} в костёр, а {PAWN_possessive} руки не покрыли ужасные ожоги. Х
копировал, забыл поменять, пардон
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? рос : росла} активным ребёнком с непримечательным детством, пока не {PAWN_gender ? упал : упала} в костёр, а {PAWN_possessive} руки не покрыли ужасные ожоги. Хотя шрамы со временем залечились, {PAWN_nameDef} не может находиться близко к огню.</desc>
```

2021-02-15 21:45 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был брошен : была брошена} родителями и {PAWN_gender ? рос : росла} в монастыре Ново-Мостейро-дос-Херонимос на Аракене VI.\n\nМонахи учили {PAWN_possessive} дисц
Поручать "мотаться" звучит более деревянно, чем если кому-то "приходилось мотаться", ИМХО.

2021-02-15 21:48 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? вступил : вступила} в отряд космодесантников, известных своей методичной смертоносностью. Фамилия и хладнокровность в бою предопределили {PAWN_possessive} прозви
Нуу, нет, конечно, ты неправ, но твой вариант мне всё равно нравится больше.
![image](https://user-images.githubusercontent.com/57110948/107996119-ac63fc00-6ff0-11eb-99c3-fc29e63f6e1c.png)

2021-02-15 22:06 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? вырос : выросла} в феодальном мире, бывшим частью многопланетной империи. Как потомок верховного лорда {PAWN_pronoun} {PAWN_gender ? пользовался : пользовалась}
Почему предложный падеж? Не понимаю. 
_Бывшим (кем?) частью_

2021-02-15 22:19 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? вырос : выросла} в феодальном мире, бывшим частью многопланетной империи. Как потомок верховного лорда {PAWN_pronoun} {PAWN_gender ? пользовался : пользовалась}
Локатив совпадает с предложным падежом, причастие имеет падеж главного слова, получается "родился (где?) в **мире** (п.п.), _бывшем_ (п.п.) частью..."
Такое ни один спеллчекер не знает.

2021-02-21 14:08 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? провёл : провела} свои молодые годы, работая наёмником, убивая и калеча других людей. {PAWN_pronoun} {PAWN_gender ? мог : могла} внушить страх в сердце любого вс
Да, действительно. Тогда вот так:
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? провёл : провела} свои молодые годы, работая наёмником, убивая и калеча других людей. С {PAWN_possessive} высоким ростом, а также грозным и пугающим видом {PAWN_nameDef} {PAWN_gender ? мог : могла} внушить страх в сердце любого вставшего на {PAWN_possessive} пути и убить кого {PAWN_gender ? захотел : захотела} бы.</desc>
```

2021-02-21 14:09 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
>  		<titleShort>дитя улья</titleShort>
Согласен с комментарием

2021-02-21 14:11 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был воспитан : была воспитана} в изоляции в одном из городов-ульев урбанизированного мира. Неприязнь к высоте держала {PAWN_possessive} в закрытых помещениях, и
В любом случае, надо выбрать что-то одно: или "игры про войну" с "оружием в симуляторах", или "военные игры" с "симуляционным оружием".

2021-02-21 14:17 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} с отличием {PAWN_gender ? закончил : закончила} Звёздную Академию и {PAWN_gender ? показал : показала} себя пилотом-асом в трёх кампаниях против превосходящего противника.\n\nН
Убедил, пусть останется "обездвижен".

2021-02-21 14:27 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>подопечная</titleShortFemale>
Твой перевод, конечно, несколько более точный, чем тот, что был. Но.
1. Он не просто там находился, а его "у двери оставила мать". Потому "подкидыш" вполне к месту. 
2. Представь, как этот заголовок будет выглядеть в игре для несовершеннолетнего персонажа.
"Вася Пупкин, подкидыш" всяко будет лучше, чем "Вася Пупкин, подопечный". Почему подопечный? Чей подопечный? Всё потому, что "подопечный" - слишком общее слово, которым могут обозначать кого угодно, например, школьника по отношению к учителю. Или стажёра, прикреплённого к опытному сотруднику на каком-нибудь предприятии.

2021-02-21 14:40 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был брошен : была брошена} родителями и {PAWN_gender ? рос : росла} в монастыре Ново-Мостейро-дос-Херонимос на Аракене VI.\n\nМонахи учили {PAWN_possessive} дисц
Вот том и дело, что вряд ли ему именно **приходилось** это делать. 
1. После монастыря со строгой дисциплиной и тяжёлой работой возможность смотаться куда-нибудь подальше от всего этого - это привилегия, а не обязанность.
2. Если бы ему "приходилось", от в оригинале стояло бы "had to".
3. В оригинале есть вводная фраза "In return", что подразумевает наличие некого обстоятельства, хотя бы частично компенсирующего персонажу его тяготы и лишения.

2021-02-21 14:43 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? вступил : вступила} в отряд космодесантников, известных своей методичной смертоносностью. Фамилия и хладнокровность в бою предопределили {PAWN_possessive} прозви
Ох уж эти попытки дословно переводить названия фильмов. 
Я рад, что тебе мой вариант понравился больше них ).

2021-02-21 14:51 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? вырос : выросла} в феодальном мире, бывшим частью многопланетной империи. Как потомок верховного лорда {PAWN_pronoun} {PAWN_gender ? пользовался : пользовалась}
Я обычно пользуюсь вопросительным словом: "в мире (каком?), бывшем".
Падеж должен быть один, следовательно окончания должны совпадать. С учётом возможных вариаций типа "ом"-"ем".

2021-02-21 15:12 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
>  		<titleShort>дитя улья</titleShort>
Для полного заголовка Гитхаб не позволяет преложить вариант - нужно будет сделать локальный пулл-коммит-пуш.
По краткому заголовку "urbkid" предлагаю варианты "горожанин" и "горожанка". А "мальчик из города / девочка из города" сделать длинными заголовками.

2021-02-21 15:14 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>подопытный</titleShortFemale>
```suggestion
		<titleShortFemale>подопытная</titleShortFemale>
```

2021-02-21 20:37 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? провёл : провела} свои молодые годы, работая наёмником, убивая и калеча других людей. {PAWN_pronoun} {PAWN_gender ? мог : могла} внушить страх в сердце любого вс
Мне не очень нравится. В био, конечно, говорится, что пешка "была" высокая и грозная, но разве это означает, что на момент игры она уже не такая? Может, так?
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? провёл : провела} свои молодые годы, работая наёмником, убивая и калеча других людей. {PAWN_pronoun} {PAWN_gender ? мог : могла} внушить страх в сердце любого вставшего на {PAWN_possessive} пути и убить кого {PAWN_gender ? захотел : захотела} бы — {PAWN_pronoun} высокий рост, а также грозный и пугающий вид этому хорошо способствовали.</desc>
```

2021-02-21 20:39 UTC, kamadz commented on Core/Backstories/Backstories.xml
>  		<titleShort>дитя улья</titleShort>
Согласен

2021-02-21 20:42 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? рос : росла} подмастерьем на литейном производстве в индустриальном мире. Этот опыт дал {PAWN_objective} навыки металлообработки и сильные мышцы, но не предостав
Всё верно, я забыл переписать черновой вариант. Так норм?

```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? рос : росла} подмастерьем на литейном производстве в индустриальном мире. Такая жизнь дала {PAWN_objective} навыки металлообработки и сильные мышцы, но не оставляла времени на какое-либо творческое развитие.</desc>
```

2021-02-21 20:45 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был брошен : была брошена} родителями и {PAWN_gender ? рос : росла} в монастыре Ново-Мостейро-дос-Херонимос на Аракене VI.\n\nМонахи учили {PAWN_possessive} дисц
Я и не спорил здесь, поставил пальчик вверх же. 
Просто ремарка о стилистической взаимной употребимости, мне немного режет глаз.

2021-02-21 21:00 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>подопечная</titleShortFemale>
Мне кажется, что сам факт того, что ребёнка подкинули, менее важен, чем факт того, что ребёнок рос в очень влиятельной семье (и, собственно, от этого получает свои бонусы). Именно этим и обусловлен выбор лексемы в оригинале, не просто "foundling", а "ward", потому что целый этап его жизни определяет взросление в чужой  семье элит, а не то, что его подбросили кому-то под дверь. 
Более того, с незапамятных времён влиятельные семьи, правители и прочие сливки общества практиковали обмен своими младшими в рамках различных "союзов" и просто так, отдавая кого-то из детишек в семьи родственников и даже в чужие семьи. Как **"подопечных"**. 
Представь себе ситуацию с другой стороны. Вот приезжают в особняк этой влиятельной семьи люди (родственники, друзья, коллеги по партии, начальство, неважно) и видят, что в особняке внезапно на одного члена семьи больше. Все знают, что это не ребёнок семьи, потому что был бы - знали бы. Возникает сразу вопрос, а это кто и почему он живёт с вами? Что проще сказать, что 
-"эм-м, ну это так, **_подкидыш_**. Тут, у двери подобрали" 
или 
-"это племянник нашей троюродной прабабушки из соседней звёздной системы (эту прабабушку, одну из сотен прабабушек, разумеется, никто не знает, , как и её племянника, как и его родителей, а выяснять никто не будет), прилетел к нам, так как его матушка захворала и попросила последить за ним/скончалась и мы решили взять ребёнка себе"?

2021-02-21 21:04 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был воспитан : была воспитана} в изоляции в одном из городов-ульев урбанизированного мира. Неприязнь к высоте держала {PAWN_possessive} в закрытых помещениях, и
Предлагаю "...открыл для себя мир военных симуляторов, в которых {PAWN_gender ? научился : научилась} мастерски обращаться с различным виртуальным оружием.

2021-02-21 22:20 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? провёл : провела} свои молодые годы, работая наёмником, убивая и калеча других людей. {PAWN_pronoun} {PAWN_gender ? мог : могла} внушить страх в сердце любого вс
Можно и так.

2021-02-21 22:21 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был воспитан : была воспитана} в изоляции в одном из городов-ульев урбанизированного мира. Неприязнь к высоте держала {PAWN_possessive} в закрытых помещениях, и
Вполне.

2021-02-21 22:22 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? рос : росла} подмастерьем на литейном производстве в индустриальном мире. Этот опыт дал {PAWN_objective} навыки металлообработки и сильные мышцы, но не предостав
Так даже лучше

2021-02-21 22:27 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был воспитан : была воспитана} в изоляции в одном из городов-ульев урбанизированного мира. Неприязнь к высоте держала {PAWN_possessive} в закрытых помещениях, и
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? был воспитан : была воспитана} в изоляции в одном из городов-ульев урбанизированного мира. Неприязнь к высоте держала {PAWN_possessive} в закрытых помещениях, и в результате превратила в очень замкнутого ребёнка.\n\nКогда {PAWN_nameDef} наконец {PAWN_gender ? начал : начала} выходить из дома, {PAWN_pronoun} {PAWN_gender ? открыл : открыл} для себя мир военных симуляторов, в которых {PAWN_gender ? научился : научилась} мастерски обращаться с различным виртуальным оружием.</desc>
```

2021-02-21 23:03 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>подопечная</titleShortFemale>
Я прекрасно понимаю, что ты хочешь перевести слово "ward", подчеркнув благородный статус принявшей его семьи. Но какие слова в русском языке для этого есть? Кроме безликого "подопечного"?
Твой пример с гостями понятен. Но игрок-то - не гость, ему можно сказать как есть.

2021-02-22 00:15 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>подопечная</titleShortFemale>
Нужно подумать, через день-два я постараюсь что-нибудь родить. Не получится - зальём твой вариант

2021-03-08 20:24 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<titleShortFemale>подопечная</titleShortFemale>
```suggestion
		<titleShort>воспитанник</titleShort>
		<titleShortFemale>воспитанница</titleShortFemale>
```

2021-03-08 20:25 UTC, merged