Fix for Backstories.xml pt.5
Ludeon/RimWorld-ru pull request #1198
Opened 2021-01-30 02:27 UTC by kamadz

fixed translation for Backstories.xml (lines 4k-5k)
yada-yada

2021-02-15 22:26 UTC, kamadz commented on Core/Backstories/Backstories.xml
> -		<title>зловещий пацан</title>
Поток больного сознания автора этой бекстори НЕ переводится нормально на русский язык.

2021-02-15 22:28 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Единственным полезным навыком, которым {PAWN_nameDef} {PAWN_gender ? овладел : овладела} к окончанию военного училища, была подтасовка карт. Мухлюя в казино, {PAWN_pronoun} {PAWN_gender ? наж
```suggestion
		<desc>Единственным полезным навыком, которым {PAWN_nameDef} {PAWN_gender ? овладел : овладела} к окончанию военного училища, была подтасовка карт. Мухлюя в казино, {PAWN_pronoun} {PAWN_gender ? нажил : нажила} себе немало врагов. По мере роста угрозы возмездия {PAWN_nameDef} {PAWN_gender ? становился : становилась} лишь резче и наглее.\n\nВ конце концов {PAWN_possessive} поймали и подвергли пыткам, которые оставили {PAWN_objective} ожоги по всему телу. С тех пор {PAWN_nameDef} больше не хочет связываться ни с огнём, ни с насилием.</desc>
```

2021-02-15 22:29 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>В юном возрасте {PAWN_nameDef} {PAWN_gender ? впал : впала} в кому и много лет {PAWN_gender ? видел : видела} сны о стрельбе. Когда {PAWN_pronoun} {PAWN_gender ? пришёл : пришла} в сознание,
```suggestion
		<desc>В юном возрасте {PAWN_nameDef} {PAWN_gender ? впал : впала} в кому и много лет {PAWN_gender ? видел : видела} сны, в которых {PAWN_gender ? стрелял : стреляла} из оружия. Когда {PAWN_pronoun} {PAWN_gender ? пришёл : пришла} в сознание, то ни на что не {PAWN_gender ? годился : годилась} в большинстве задач, но зато {PAWN_gender ? умел : умела} весьма метко стрелять.</desc>
```

2021-04-03 17:48 UTC, Elevator89 requested changes
Первая часть ревью

2021-04-03 17:48 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? рос : росла} в постапокалиптическом мире. С юного возраста {PAWN_pronoun} {PAWN_gender ? боролся : боролась} за выживание на планете, где доверие не было в цене.
Не очень понятно из оригинала, в каком времени ему не везёт
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? рос : росла} в постапокалиптическом мире. С юного возраста {PAWN_pronoun} {PAWN_gender ? боролся : боролась} за выживание на планете, где доверие не было в цене.\n\n{PAWN_nameDef} {PAWN_gender ? говорил : говорила} всем, что {PAWN_objective} не повезло.</desc>
```

2021-04-03 17:48 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был «спасён» : была «спасена»} с родного мира космическими работорговцами. Затем {PAWN_possessive} продали криминальному авторитету из городского мира, где {PAWN
Тут, по всей видмости имеется в виду незатейливость самого процесса избиений, а не их обыденность.
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? был «спасён» : была «спасена»} с родного мира космическими работорговцами. Затем {PAWN_possessive} продали криминальному авторитету из городского мира, где {PAWN_nameDef} {PAWN_gender ? стал : стала} подручным в банде. В {PAWN_possessive} обязанности входили простые избиения и запугивание.</desc>
```

2021-04-03 17:48 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} почти всё своё время {PAWN_gender ? ухаживал : ухаживала} за ядовитым садом, что отдалило {PAWN_possessive}.\n\nЗа этот срок {PAWN_pronoun} {PAWN_gender ? обучился : обучилась}
```suggestion
		<desc>{PAWN_nameDef} почти всё своё время {PAWN_gender ? ухаживал : ухаживала} за ядовитым садом, что отдалило {PAWN_possessive} от общества.\n\nЗа этот срок {PAWN_pronoun} {PAWN_gender ? обучился : обучилась} кое-какому безопасному кулинарному и лекарственному применению разных смертоносных растений.</desc>
```

2021-04-03 17:48 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Когда {PAWN_nameDef} не {PAWN_gender ? копался : копалась} в библиотеке, то {PAWN_gender ? разбирал : разбирала} вещи, чтобы понять, как они работают, не обращая внимания на границу между мех
```suggestion
		<desc>Когда {PAWN_nameDef} не {PAWN_gender ? копался : копалась} в библиотеке, то {PAWN_gender ? разбирал : разбирала} вещи, чтобы понять, как они работают, не обращая внимания на границу между механическим и органическим. «Знание — сила», — эти слова воодушевляли и мотивировали {PAWN_possessive}.</desc>
```

2021-04-03 17:48 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Поддавшись азарту открытий и собственной мании величия, {PAWN_nameDef} {PAWN_gender ? работал : работала} над созданием новых устройств и улучшением существующих, по мере надобности нарушая з
Действие "работал" было продолжительным, поэтому совершенный вид деепричастия "поддавашись" не подходит.
```suggestion
		<desc>Поддаваясь азарту открытий и собственной мании величия, {PAWN_nameDef} {PAWN_gender ? работал : работала} над созданием новых устройств и улучшением существующих, по мере надобности нарушая законы и обычаи.\n\n{PAWN_pronoun} {PAWN_gender ? собрал : собрала} команду, чтобы собирать материалы для своей работы и разбираться с теми, кто пытался {PAWN_objective} мешать.</desc>
```

2021-04-03 17:48 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>В раннем возрасте, стоя в детском скафандре на корпусе корабля рядом со своим отцом, {PAWN_nameDef} {PAWN_gender ? влюбился : влюбилась} в открытый космос.\n\n{PAWN_pronoun} {PAWN_gender ? по
Попадают в аварию или пробку. А тут - космическая академия.
```suggestion
		<desc>В раннем возрасте, стоя в детском скафандре на корпусе корабля рядом со своим отцом, {PAWN_nameDef} {PAWN_gender ? влюбился : влюбилась} в открытый космос.\n\n{PAWN_pronoun} {PAWN_gender ? записался : записалась} в Гражданскую Академическую Программу. Подражая отцу, {PAWN_nameDef} {PAWN_gender ? разводил : разводила} растения в своей грязной комнате. Своё прозвище {PAWN_pronoun} {PAWN_gender ? получил : получила} за любовь к кругам.</desc>
```

2021-04-03 17:48 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Пойдя по стопам отца, {PAWN_nameDef} {PAWN_gender ? стал : стала} системным инженером, способным работать как на космических кораблях, так и в наземных поселениях.\n\nВ свободное от работы вр
```suggestion
		<desc>Пойдя по стопам отца, {PAWN_nameDef} {PAWN_gender ? стал : стала} системным инженером, способным работать как на космических кораблях, так и в наземных поселениях.\n\nВ свободное от работы время {PAWN_pronoun} {PAWN_gender ? делал : делала} механические фигурки, {PAWN_gender ? читал : читала} старые книги, а иногда {PAWN_gender ? путешествовал : путешествовала} на неизведанные миры. Будучи интровертом, в основном {PAWN_pronoun} {PAWN_gender ? делал : делала} это в одиночестве.</desc>
```

2021-04-03 17:48 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? прошёл : прошла} долгий путь в иерархии пиратского корабля, в конце концов став капитаном. {PAWN_pronoun} {PAWN_gender ? вёл : вела} свою команду между мирами, з
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? прошёл : прошла} долгий путь по пиратской иерархии, в конце концов став капитаном. {PAWN_pronoun} {PAWN_gender ? вёл : вела} свою команду между мирами, заставляя всех трепетать от одного лишь своего имени.</desc>
```

2021-04-03 17:48 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} назначили главным управляющим хедж-фондама в перенаселённом городском мире. {PAWN_possessive} портфель ценных бумаг быстро рос по мере того, как {PAWN_pronoun} {PAWN_gender ? о
```suggestion
		<desc>{PAWN_nameDef} назначили главным управляющим хедж-фондами в перенаселённом городском мире. {PAWN_possessive} портфель ценных бумаг быстро рос по мере того, как {PAWN_pronoun} {PAWN_gender ? очаровывал : очаровывала} клиентов приятным голосом и изощрёнными замыслами. Когда сумма сделок превысила все мыслимые пределы, {PAWN_nameDef}, узнав о награде за свою голову, спешно {PAWN_gender ? покинул : покинула} планету.\n\nВ своих скитаниях по звёздам у н{PAWN_possessive} появилось увлечение в сфере искусства — подбирать шедевры для покупателей из высшего света.</desc>
```

2021-05-09 16:27 UTC, Elevator89 requested changes

2021-05-09 16:27 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? рос : росла} на захолустной планете, где, чтобы выжить, приходилось охотиться и выращивать еду.\n\nНа {PAWN_possessive} семью часто нападали банды мародёров, из-
Повторение
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? рос : росла} на захолустной планете, где, чтобы выжить, приходилось охотиться и выращивать еду.\n\nНа {PAWN_possessive} семью часто нападали банды мародёров, из-за чего {PAWN_nameDef} {PAWN_gender ? был : была} крайне подозрительным и недоверчивым подростком.</desc>
```

2021-05-09 16:27 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>С самого раннего возраста {PAWN_nameDef} {PAWN_gender ? считал : считала} свои домом лишь корабль своих родителей. Они были бродягами, а их скитания обеспечивали {PAWN_objective} постоянную с
```suggestion
		<desc>С самого раннего возраста {PAWN_nameDef} {PAWN_gender ? не знал : не знала} дома, кроме корабля своих родителей. Они были бродягами, а их скитания обеспечивали {PAWN_objective} постоянную смену обстановки. {PAWN_possessive} жизнь часто была полна опасностей, но всегда была яркой. Тяга к путешествиям — вот то, в чём одинаковы {PAWN_nameDef} и {PAWN_possessive} родители.</desc>
```

2021-05-09 16:27 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Много лет назад одно племя случайно наткнулось на заброшенный склад со стрелковым оружием. Посчитав это оружие священным даром, шаман племени решил выбрать из племени самое непорочное дитя и
Убрал повторение
```suggestion
		<desc>Много лет назад одно племя случайно наткнулось на заброшенный склад со стрелковым оружием. Посчитав это оружие священным даром, шаман решил выбрать из племени самое непорочное дитя и оказать ему честь, вручив оружие и отправив на защиту деревни. Этим ребёнком {PAWN_gender ? был : была} {PAWN_nameDef}.</desc>
```

2021-05-09 16:27 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} с детства {PAWN_gender ? воспитывался : воспитывалась} как будущий исполнительный директор корпорации, которая занималась освоением космоса и которой принадлежала {PAWN_possess
"was bred" - он не просто воспитывался, он был рождён специально для этого. Ещё слишком много "корпораций" в тексте
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? был рождён : была рождена}, чтобы стать исполнительным директором корпорации, которая занималась освоением космоса и которой принадлежала {PAWN_possessive} родная планета. {PAWN_possessive} семья работала на эту компанию четыре поколения.\n\nВ возрасте пяти лет {PAWN_nameDef} {PAWN_gender ? начал : начала} обучаться в академии корпорации. Там {PAWN_pronoun} {PAWN_gender ? научился : научилась} быть верным последователем её идей и их беспощадным исполнителем. {PAWN_nameDef} {PAWN_gender ? решал : решала} с помощью дипломатии даже те конфликты, в которых многие бы уже прибегли к насилию.</desc>
```

2021-05-30 16:26 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>После окончания гражданской войны {PAWN_nameDef} {PAWN_gender ? принялся : принялась} искать новый способ использовать свои боевые навыки. {PAWN_pronoun} {PAWN_gender ? решил : решила} выслеж
можно что-то вроде "негодяев"/"мерзавцев"

2021-05-30 16:31 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в обеспеченной семье на крупном урбанизированном мире и {PAWN_gender ? жил : жила} в шикарной квартире на верхних этажах небоскрёба, который
Да, в оригинале этого нет. Видимо, не заметил, когда правил.

Правильно "ем", предложный падеж отвечает на вопрос "в чём". Пикрил
![image](https://user-images.githubusercontent.com/57110948/120112226-a5b35c00-c17d-11eb-859b-4bc0bc57bf5f.png)

2021-05-30 16:34 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? нашёл : нашла} работу в качестве инженера-механика на торговом мире Ирифир. Жёсткая конкуренция заставила {PAWN_possessive} отточить свои навыки ведения перегово
Вообще, это типичный пример катафоры, но ладно.

2021-05-30 16:37 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? рос : росла} в постапокалиптическом мире. С юного возраста {PAWN_pronoun} {PAWN_gender ? боролся : боролась} за выживание на планете, где доверие не было в цене.
Имеется в виду, что чел считает себя невезучим. "Вася постоянно рассказывал всем, какой он невезучий (как ему постоянно не везёт)"

2021-05-30 16:39 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был «спасён» : была «спасена»} с родного мира космическими работорговцами. Затем {PAWN_possessive} продали криминальному авторитету из городского мира, где {PAWN
Тогда уже лучше "примитивные", в формате примитивности организации самой преступности. Если вводить оппозицию, то хайтек - это всякие мафиози и синдикаты, которые вполне законно владеют бизнесами и полу-легально добывают себе деньги, а лоутек - бандюганы и гопота. Мне так кажется.

2021-05-30 16:39 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Поддавшись азарту открытий и собственной мании величия, {PAWN_nameDef} {PAWN_gender ? работал : работала} над созданием новых устройств и улучшением существующих, по мере надобности нарушая з
Всё верно

2021-05-30 16:41 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>В раннем возрасте, стоя в детском скафандре на корпусе корабля рядом со своим отцом, {PAWN_nameDef} {PAWN_gender ? влюбился : влюбилась} в открытый космос.\n\n{PAWN_pronoun} {PAWN_gender ? по
Was put - явно говорит о не стопроцентной интенциональности произошедшего. Он с таким же успехом мог попасть в гос. распределение или выиграть в конкурсе.

2021-05-30 16:42 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Пойдя по стопам отца, {PAWN_nameDef} {PAWN_gender ? стал : стала} системным инженером, способным работать как на космических кораблях, так и в наземных поселениях.\n\nВ свободное от работы вр
по неизведанным мирам тогда уж

2021-05-30 16:45 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? поступил : поступила} в академию, как любой хороший будущий пилот звездолёта поступил бы. Там {PAWN_possessive} {PAWN_gender ? выделялся : выделялась} высоким ро
Кадет - офицер, который проходит обучение. Кадетом можно быть где угодно: https://en.wikipedia.org/wiki/Cadet. 
Лично мне кажется, что в данном случае имеется будущий офицер космического корабля.

2021-05-30 16:46 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? работал : работала} выездным инженером. {PAWN_pronoun} {PAWN_gender ? мог : могла} починить и наладить что угодно, начиная от простой усилительной антенны и зака
Ну здрасьте, intricate software harness - просто "вокруг"?
Давай подумаем что-ли.

2021-05-30 16:49 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} с детства {PAWN_gender ? воспитывался : воспитывалась} как будущий исполнительный директор корпорации, которая занималась освоением космоса и которой принадлежала {PAWN_possess
С первым согласен, со вторым - нет. У компании и корпорации, особенно в формате заигрывания с анти-утопическими темами корпоративизма, корпорократий и т. д. есть большая разница.

2021-05-30 17:17 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>После окончания гражданской войны {PAWN_nameDef} {PAWN_gender ? принялся : принялась} искать новый способ использовать свои боевые навыки. {PAWN_pronoun} {PAWN_gender ? решил : решила} выслеж
```suggestion
		<desc>После окончания гражданской войны {PAWN_nameDef} {PAWN_gender ? принялся : принялась} искать новый способ использовать свои боевые навыки. {PAWN_pronoun} {PAWN_gender ? решил : решила} выслеживать военных преступников и вскоре {PAWN_gender ? осознал : осознала}, что {PAWN_objective} нравится отлавливать негодяев любыми средствами.</desc>
```

2021-05-30 17:19 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? нашёл : нашла} работу в качестве инженера-механика на торговом мире Ирифир. Жёсткая конкуренция заставила {PAWN_possessive} отточить свои навыки ведения перегово
Окей, теперь я буду знать, как это называется )

2021-05-30 17:33 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} много лет {PAWN_gender ? исследовал : исследовала} новые религии и традиции и часто {PAWN_gender ? мечтал : мечтала} о далёких звёздах.\n\nЭти мечты побудили {PAWN_possessive}
Без малейшего понятия. Скорее всего речь о новых течениях, которые в густонаселённой галактике могли сотнями появляться хоть каждый день.

2021-05-30 17:33 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>По воле своих родителей {PAWN_nameDef} с детства {PAWN_gender ? перевозил : перевозила} контрабанду внутри скопления приграничных миров.\n\nБлагодаря небольшому росту {PAWN_nameDef} весьма ис
Я в основном другим занимался

2021-05-30 17:34 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? возглавлял : возглавляла} пиратский космический корабль. {PAWN_pronoun} {PAWN_gender ? скитался : скиталась} по приграничным мирам и {PAWN_gender ? стал : стала}
Ну не. "Was" не "became" же. Денотат разный.

2021-05-30 17:35 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? работал : работала} выездным инженером. {PAWN_pronoun} {PAWN_gender ? мог : могла} починить и наладить что угодно, начиная от простой усилительной антенны и зака
>Ну здрасьте, intricate software harness - просто "вокруг"?

Нет. "вокруг" здесь очевидно относится к слову "eveloping".
"the intricate software harness enveloping AI persona." -> "сложным программным обеспечением вокруг ИИ"
Что не так-то?

2021-05-30 17:37 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} с детства {PAWN_gender ? воспитывался : воспитывалась} как будущий исполнительный директор корпорации, которая занималась освоением космоса и которой принадлежала {PAWN_possess
Хорошо. Как тогда сделать повторение не так бросающимся в глаза?

2021-05-30 17:44 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>После посвящения в сан {PAWN_gender ? местного жреца : местной жрицы} {PAWN_nameDef} {PAWN_gender ? прибегал : прибегала} к интригам и дипломатии, чтобы достичь высших духовных чинов. {PAWN_p
Вообще не туда оба смотрим 
Насколько я помню, эта бекстори не tribal. Логически можем прийти к тому, что речь идёт не о каком-то из мириады языческих культов и течений (у которых обычно жрецы), а о какой-то более менее оформленной религии. Тогда, может лучше так?
```suggestion
		<desc>После посвящения в сан {PAWN_gender ? священника : священницы} и получения прихода, {PAWN_nameDef} {PAWN_gender ? прибегал : прибегала} к интригам и дипломатии, чтобы достичь высших духовных чинов. {PAWN_pronoun} {PAWN_gender ? стал обладателем : стала обладательницей} обладателем множества земель и титулов.\n\nОднажды рядом с {PAWN_possessive} домом приземлился корабль торговца, и {PAWN_nameDef} {PAWN_gender ? решил : решила} составить ему компанию в поисках новых миров и испытаний.</desc>
```

2021-05-30 19:06 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? работал : работала} выездным инженером. {PAWN_pronoun} {PAWN_gender ? мог : могла} починить и наладить что угодно, начиная от простой усилительной антенны и зака
Мне кажется, тут имеется в виду некая софтовая "оболочка", просто "вокруг" звучит странно. Софт вокруг ИИ? Надо доработать, имхо.

2021-05-30 19:09 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} с детства {PAWN_gender ? воспитывался : воспитывалась} как будущий исполнительный директор корпорации, которая занималась освоением космоса и которой принадлежала {PAWN_possess
Сложно. Может быть, если у нас есть контекст того, что корпорация занимается исследованиями и владеет целой планетой - "исследовательский гигант" или что-то в этом роде?

2022-09-11 16:23 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? работал : работала} выездным инженером. {PAWN_pronoun} {PAWN_gender ? мог : могла} починить и наладить что угодно, начиная от простой усилительной антенны и зака
Фиг с ним, пусть останется, как есть

2022-09-11 16:30 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} с детства {PAWN_gender ? воспитывался : воспитывалась} как будущий исполнительный директор корпорации, которая занималась освоением космоса и которой принадлежала {PAWN_possess
Кажется, не так чтобы сильно это повторение бросается в глаза. Вернул "корпорацию"

2022-09-11 16:45 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} с детства {PAWN_gender ? воспитывался : воспитывалась} как будущий исполнительный директор корпорации, которая занималась освоением космоса и которой принадлежала {PAWN_possess
Решил, что повторение не так чтобы сильно бросается в глаза. Оставил "корпорацию"

2022-10-08 20:45 UTC, merged