Fix for Backstories.xml pt.6
Ludeon/RimWorld-ru pull request #1200
Opened 2021-03-12 01:49 UTC by kamadz

2021-05-30 14:53 UTC, Elevator89 requested changes

2021-05-30 14:53 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? рос : росла} в богатой семье. Родители обеспечивали {PAWN_possessive} всем, что {PAWN_pronoun} {PAWN_gender ? желал : желала}. Открыв для себя чипы счастья, {PAW
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? рос : росла} в богатой семье. Родители обеспечивали {PAWN_possessive} всем, что {PAWN_pronoun} {PAWN_gender ? желал : желала}. Открыв для себя чипы счастья, {PAWN_nameDef} {PAWN_gender ? получил : получила} психологическую зависимость. Как только {PAWN_possessive} родители осознали, что произошло, они сразу же разорвали все отношения, оставив {PAWN_possessive} без содержания.\n\nБудучи эгоистичным и часто жестоким, {PAWN_nameDef} {PAWN_gender ? начал : начала} искать себе новые версии чипов, не гнушаясь ни какими способами.</desc>
```

2021-05-30 14:53 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
>  		<desc>Излечившись от зависимости, {PAWN_nameDef} принимает образ жизни без насилия и даёт обет помогать другим людям.\n\n{PAWN_pronoun} путешествует между общинами и использует свои знания в област
```suggestion
		<desc>Излечившись от зависимости, {PAWN_nameDef} {PAWN_gender ? принял : приняла} образ жизни без насилия и {PAWN_gender ? дал : дала} обет помогать другим людям.\n\n{PAWN_pronoun} {PAWN_gender ? путешествовал : путешествовала} между общинами и {PAWN_gender ? использовал : использовала} свои знания в области медицины, искусства и ремёсел, чтобы помогать тем, кто борется со своими зависимостями.</desc>
```

2021-05-30 14:53 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был прислужником : была прислужницей} короля Лотерика. {PAWN_objective} нравилось тренироваться с шестом и заниматься рукопашным боем. {PAWN_pronoun} быстро {PAW
"Умир" )
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? был прислужником : была прислужницей} короля Лотерика. {PAWN_objective} нравилось тренироваться с шестом и заниматься рукопашным боем. {PAWN_pronoun} быстро {PAWN_gender ? привык : привыкла} к пылу битв и умело {PAWN_gender ? разжигал : разжигала} это пламя.\n\n{PAWN_pronoun} честно {PAWN_gender ? служил : служила} своему повелителю, пока король не умер в результате несчастного случая.</desc>
```

2021-05-30 14:53 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_possessive} продали компании Корстарс Интертейнмент, где использовали в роли жертвы в «Кровавой игре», одном из шоу компании, транслировавшемся по всей системе.\n\n{PAWN_possessive} уме
Извращение
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? оказался : оказалась} в собственности компании Корстарс Интертейнмент, где {PAWN_possessive} использовали в роли жертвы в «Кровавой игре», одном из шоу компании, транслировавшемся по всей системе.\n\nОднако {PAWN_possessive} умение манипулировать окружающими было ужасающим даже для зрителей. {PAWN_possessive} вышвырнули на планету, полную опасных животных, преступников и вооружённых дронов с камерами.</desc>
```

2021-05-30 14:53 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в богатой семье на пустынном мире, но {PAWN_gender ? оказался : оказалась} в изгнании после того, как дом {PAWN_possessive} родителей разруши
Наёмники не изгоняют
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в богатой семье на пустынном мире. Однажды на них напал отряд наёмников, убивая всех {PAWN_possessive} родных и близких.\n\n{PAWN_nameDef} {PAWN_gender ? выжил : выжила}, спрятавшись в вентиляционной трубе под семейной виллой. {PAWN_pronoun} поклялся отомстить убийцам и тем, кто их нанял, и в одиночку {PAWN_gender ? отправился : отправилась} в пустоши.</desc>
```

2021-05-30 14:53 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Долгие годы {PAWN_nameDef} {PAWN_gender ? искал : искала} убийцу своей семьи. В конце концов {PAWN_possessive} пригласили в группу космических рейдеров. {PAWN_pronoun} {PAWN_gender ? согласил
```suggestion
		<desc>Долгие годы {PAWN_nameDef} {PAWN_gender ? искал : искала} убийцу своей семьи. В конце концов {PAWN_possessive} пригласили в группу космических рейдеров. {PAWN_pronoun} {PAWN_gender ? согласился : согласилась} в надежде, что это поможет найти убийцу.\n\nИз-за своей способности неизменно уходить от опасности в самый последний момент {PAWN_pronoun} {PAWN_gender ? получил : получила} прозвище «Блэкджек» в знак признания {PAWN_possessive} удачливости.</desc>
```

2021-05-30 14:53 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} рано понял, что в индустриальном мире, если хочешь есть — придётся работать. И {PAWN_pronoun} {PAWN_gender ? работал : работала}, помогая на кухне и по дому. Дети могут пролезт
```suggestion
		<desc>{PAWN_nameDef} рано понял, что в индустриальном мире, если хочешь есть, — придётся работать. И {PAWN_pronoun} {PAWN_gender ? работал : работала}, помогая на кухне и по дому. Дети могут пролезть в места, куда не попасть взрослым, а на {PAWN_possessive} родине техникой безопасности откровенно пренебрегали.\n\n{PAWN_possessive} всегда считали немножко {PAWN_gender ? пироманом : пироманкой}, а после несчастного случая вовсе перестали пускать на кухню.</desc>
```

2021-05-30 17:18 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был назначен : была назначена} на должность специального констебля в сети космических станций, чтобы пресекать торговлю людьми.\n\nОднажды на станции случился по
`Ну не надо такую откровенную кальку делать!`

Спокойно!

![image](https://user-images.githubusercontent.com/57110948/120113664-2d9c6480-c184-11eb-8086-24bda4da4ae4.png)

Со вторым согласен.

2021-05-30 17:19 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Долгие годы {PAWN_nameDef} {PAWN_gender ? искал : искала} убийцу своей семьи. В конце концов {PAWN_possessive} пригласили в группу космических рейдеров. {PAWN_pronoun} {PAWN_gender ? согласил
Не вижу смысла замены

2021-05-30 17:20 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? родился : родилась} в богатой семье на пустынном мире, но {PAWN_gender ? оказался : оказалась} в изгнании после того, как дом {PAWN_possessive} родителей разруши
Ну, окей. Я на это внимания не обратил.

2021-05-30 17:22 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_possessive} отвергла родная семья, зато приняли и воспитали волки. Смыслом жизни были бег, охота и защита своей стаи.\n\n{PAWN_nameDef} {PAWN_gender ? научился : научилась} эффективно с
Я в основном правил и добавлял операторы.

2021-05-30 17:23 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был мастером : была мастерицей} на все руки, {PAWN_gender ? вдохновлённым : вдохновлённой} технологиями, и {PAWN_gender ? стремился : стремилась} изобрести устро
Смысл замены?

2021-05-30 17:29 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>Когда {PAWN_nameDef} {PAWN_gender ? достиг : достигла} совершеннолетия, {PAWN_possessive} как раба продали корпорации и заставляли проводить научные исследования.\n\nБудучи не в состоянии ада
```suggestion
		<desc>После наступления совершеннолетия, {PAWN_nameDef} {PAWN_gender ? был продан : была продана} на рабских правах корпорации, где {PAWN_possessive} заставляли проводить научные исследования.\n\nБудучи не в состоянии адаптироваться к социальной среде рабочего коллектива, {PAWN_nameDef} {PAWN_gender ? окружил : окружила} себя работой и никак не {PAWN_gender ? продвигался : продвигалась} по карьерной лестнице. {PAWN_pronoun} {PAWN_gender ? хотел : хотела}, чтобы {PAWN_possessive} просто оставили в покое.</desc>
```

2022-09-11 17:16 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был назначен : была назначена} на должность специального констебля в сети космических станций, чтобы пресекать торговлю людьми.\n\nОднажды на станции случился по
Оставил "специального констебля"

2022-09-11 17:16 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Когда {PAWN_nameDef} {PAWN_gender ? достиг : достигла} совершеннолетия, {PAWN_possessive} как раба продали корпорации и заставляли проводить научные исследования.\n\nБудучи не в состоянии ада
Удалил лишнюю запятую в твоём варианте после "После наступления совершеннолетия". В остальном согласен

2022-09-11 17:16 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>Долгие годы {PAWN_nameDef} {PAWN_gender ? искал : искала} убийцу своей семьи. В конце концов {PAWN_possessive} пригласили в группу космических рейдеров. {PAWN_pronoun} {PAWN_gender ? согласил
Сравни:
```Он получил прозвище «Блэкджек» в знак признания его удачливости```
и
```Он получил прозвище «Блэкджек» в знак признания своей удачливости```
Не уверен, что там говорят правила (скорее всего, ничего), но первый вариант выглядит всяко естественнее. Плюс, он не сам сделал себе прозвище, а **ему** его придумали

2022-09-11 17:16 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? был мастером : была мастерицей} на все руки, {PAWN_gender ? вдохновлённым : вдохновлённой} технологиями, и {PAWN_gender ? стремился : стремилась} изобрести устро
Более естественное звучание. И устранение повторения

2022-10-08 20:49 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
>  		<!-- EN: chef -->
```suggestion
		<titleFemale>повариха средн. мира</titleFemale>
		<!-- EN: chef -->
```

2022-10-08 20:49 UTC, Elevator89 commented on Core/Backstories/Backstories.xml
>  		<!-- EN: [PAWN_nameDef] ran a high-class restaurant. [PAWN_pronoun] was famous among patrons for [PAWN_possessive] creative culinary specialties, and infamous among kitchen workers for [PAWN_posses
```suggestion
		<titleShortFemale>повариха</titleShortFemale>
		<!-- EN: [PAWN_nameDef] ran a high-class restaurant. [PAWN_pronoun] was famous among patrons for [PAWN_possessive] creative culinary specialties, and infamous among kitchen workers for [PAWN_possessive] casual disdain for grunt work. -->
```

2022-10-08 20:50 UTC, merged