3056 Core/Definjected-1
Ludeon/RimWorld-ru pull request #1228
Opened 2021-07-14 08:33 UTC by kamadz

#1202 
Translate pt.1 of Core/Definjected

2021-07-14 08:34 UTC, kamadz commented on Core/DefInjected/DamageDef/Damages_Misc.xml
> +  <Thump.label>удар</Thump.label>
надо уточнить, что это

2021-07-14 08:35 UTC, kamadz commented on Core/DefInjected/CultureDef/Cultures.xml
> +  <Rustican.description>Стойкая индустриальная культура, распространённая среди чужеземцев окраинных миров.</Rustican.description>
Я бы воздержался от термина "чужеземцы" здесь. Может быть
```suggestion
  <Rustican.description>Стойкая индустриальная культура, распространённая в развитых поселениях окраинных миров.</Rustican.description>
```

2021-07-15 13:44 UTC, kamadz commented on Core/DefInjected/CultureDef/Cultures.xml
> +  <Rustican.label>растикан</Rustican.label>
```suggestion
  <Rustican.label>растиканство</Rustican.label>
```

???

2021-07-15 13:44 UTC, kamadz commented on Core/DefInjected/CultureDef/Cultures.xml
> +  <Corunan.label>корунан</Corunan.label>
```suggestion
  <Corunan.label>корунанство</Corunan.label>
```
???

2021-07-15 13:45 UTC, kamadz commented on Core/DefInjected/CultureDef/Cultures.xml
> +  <Corunan.label>корунан</Corunan.label>
Для однородности можно использовать русский суффикс, всё равно слова вымышленные. Надо обдумать.

2021-07-17 16:35 UTC, Elevator89 requested changes

2021-07-17 16:35 UTC, Elevator89 commented on Core/DefInjected/CultureDef/Cultures.xml
> +  <Rustican.label>растикан</Rustican.label>
Есть стиль "рустика" https://ru.wikipedia.org/wiki/%D0%A0%D1%83%D1%81%D1%82%D0%B8%D0%BA%D0%B0
Надо через "у".

2021-07-17 16:35 UTC, Elevator89 commented on Core/DefInjected/DamageDef/Damages_Misc.xml
> +  <Thump.label>удар</Thump.label>
Есть единтсвенное оружие, обладающее типом урона "thump":
```
    <label>thump cannon</label>
    <description>A breaching explosive launcher used by mechanoids. It fires a concussion bomb that is extremely effective against walls and structures, but does much less damage to small targets.</description>
```

2021-07-17 16:35 UTC, Elevator89 commented on Core/DefInjected/CultureDef/Cultures.xml
> +  <Rustican.description>Стойкая индустриальная культура, распространённая среди чужеземцев окраинных миров.</Rustican.description>
Здесь - я не против.

Но вообще у нас во многих местах "outlanders" переведены как "чужеземцы". Что обсуждаемо

2021-07-17 16:35 UTC, Elevator89 commented on Core/DefInjected/DamageDef/Damages_Misc.xml
> +  <Thump.deathMessage>{0} {0_gender ? убит : убита : убито}</Thump.deathMessage>
Всё же "застрелен"

2021-07-17 17:48 UTC, kamadz commented on Core/DefInjected/CultureDef/Cultures.xml
> +  <Rustican.label>растикан</Rustican.label>
тогда как? 
Рустика, рустиканство?

2021-07-17 17:49 UTC, kamadz commented on Core/DefInjected/DamageDef/Damages_Misc.xml
> +  <Thump.deathMessage>{0} {0_gender ? убит : убита : убито}</Thump.deathMessage>
```suggestion
  <Thump.deathMessage>{0} {0_gender ? застрелен : застрелена : застрелено}</Thump.deathMessage>
```

2021-07-17 18:12 UTC, Elevator89 commented on Core/DefInjected/CultureDef/Cultures.xml
> +  <Rustican.label>растикан</Rustican.label>
Для единообразия лучше "рустиканство"

2021-07-17 18:12 UTC, Elevator89 commented on Core/DefInjected/CultureDef/Cultures.xml
> +  <Corunan.label>корунан</Corunan.label>
Не вижу ничего плохого в "корунанстве"

2021-07-17 18:16 UTC, kamadz commented on Core/DefInjected/BeardDef/BeardDefs.xml
> +  <Boxed.label>короткая</Boxed.label>
```suggestion
  <Boxed.label>угловатая</Boxed.label>
```
![image](https://user-images.githubusercontent.com/57110948/126046191-ea1fd024-7471-4923-88d0-7413b3a1e183.png)

2021-07-17 18:16 UTC, Elevator89 commented on Core/DefInjected/CultureDef/Cultures.xml
> +  <Rustican.label>растикан</Rustican.label>
Суффиксы предлагаю обсуждать в соседнем треде.

2021-07-17 18:25 UTC, kamadz commented on Core/DefInjected/BeardDef/BeardDefs.xml
> +  <Full.label>классическая</Full.label>
```suggestion
  <Full.label>полная</Full.label>
```

2021-07-17 18:30 UTC, kamadz commented on Core/DefInjected/CultureDef/Cultures.xml
> +  <Corunan.label>корунан</Corunan.label>
Корунизм - трайбализм: звучит логично. Берём тогда классификацию выше

2021-07-18 12:37 UTC, Elevator89 commented on Core/DefInjected/CultureDef/Cultures.xml
> +  <Corunan.label>корунан</Corunan.label>
```suggestion
  <Corunan.label>корунизм</Corunan.label>
```

2021-07-18 12:37 UTC, Elevator89 commented on Core/DefInjected/CultureDef/Cultures.xml
> +  <Rustican.label>растикан</Rustican.label>
```suggestion
  <Rustican.label>рустиканство</Rustican.label>
```

2021-07-18 12:42 UTC, merged