3056 Core/DefInjected-3
Ludeon/RimWorld-ru pull request #1230
Opened 2021-07-14 16:23 UTC by kamadz

#1204 
Translate pt. 3 of Core/Definjected

2021-07-17 19:20 UTC, Elevator89 requested changes

2021-07-17 19:20 UTC, Elevator89 commented on Core/DefInjected/HistoryEventDef/Precepts_Cannibalism.xml
> +  <ButcheredHuman.label>человек был пущен на мясо</ButcheredHuman.label>
```suggestion
  <ButcheredHuman.label>разделан человек</ButcheredHuman.label>
```
Есть такая же мысль у персонажей. Не надо отходить от привычной формулировки.
А "пущен на мясо" можно добавить в описание мысли, для пущей художественности: https://github.com/Ludeon/RimWorld-ru/pull/1234

2021-07-17 19:20 UTC, Elevator89 commented on Core/DefInjected/HistoryEventDef/Precepts_Cannibalism.xml
> +  <AteHumanMeatDirect.label>съедено человеческое мясо</AteHumanMeatDirect.label>
Надо брать перевод из ThoughtsDef
```suggestion
  <AteHumanMeatDirect.label>съедено сырая человечина</AteHumanMeatDirect.label>
```

2021-07-17 19:20 UTC, Elevator89 commented on Core/DefInjected/HistoryEventDef/Precepts_Cannibalism.xml
> +  <AteHumanMeatAsIngredient.label>съедено блюдо из человеческого мяса</AteHumanMeatAsIngredient.label>
```suggestion
  <AteHumanMeatAsIngredient.label>съедено блюдо с человечиной</AteHumanMeatAsIngredient.label>
```

2021-07-17 19:20 UTC, Elevator89 commented on Core/DefInjected/HistoryEventDef/Precepts_Corpses.xml
> +  <ObservedLayingCorpse.label>увиден труп</ObservedLayingCorpse.label>
```suggestion
  <ObservedLayingCorpse.label>вид трупа</ObservedLayingCorpse.label>
```

2021-07-17 19:20 UTC, Elevator89 commented on Core/DefInjected/HistoryEventDef/Precepts_Corpses.xml
> +  <ObservedLayingRottingCorpse.label>увиден гниющий труп</ObservedLayingRottingCorpse.label>
```suggestion
  <ObservedLayingRottingCorpse.label>вид гниющего трупа</ObservedLayingRottingCorpse.label>
```

2021-07-17 19:20 UTC, Elevator89 commented on Core/DefInjected/HistoryEventDef/Precepts_PrisonerExecution.xml
> +  <ExecutedColonist.label>поселенец казнён</ExecutedColonist.label>
По аналогии с Thoughts_Memory_Death.xml
```suggestion
  <ExecutedColonist.label>казнь поселенца</ExecutedColonist.label>
```

2021-07-17 19:20 UTC, Elevator89 commented on Core/DefInjected/HistoryEventDef/Precepts_PrisonerExecution.xml
> +  <ExecutedGuest.label>гость казнён</ExecutedGuest.label>
```suggestion
  <ExecutedGuest.label>казнь гостя</ExecutedGuest.label>
```

2021-07-17 19:20 UTC, Elevator89 commented on Core/DefInjected/HistoryEventDef/Precepts_PrisonerExecution.xml
> +  <ExecutedPrisoner.label>заключённый казнён</ExecutedPrisoner.label>
```suggestion
  <ExecutedPrisoner.label>казнь пленника</ExecutedPrisoner.label>
```

2021-07-17 19:20 UTC, Elevator89 commented on Core/DefInjected/HistoryEventDef/Precepts_PrisonerExecution.xml
> +  <ExecutedPrisonerGuilty.label>виновный заключённый казнён</ExecutedPrisonerGuilty.label>
```suggestion
  <ExecutedPrisonerGuilty.label>справедливая казнь пленника</ExecutedPrisonerGuilty.label>
```

2021-07-17 19:20 UTC, Elevator89 commented on Core/DefInjected/HistoryEventDef/Precepts_PrisonerExecution.xml
> +  <ExecutedPrisonerInnocent.label>невинный заключённый казнён</ExecutedPrisonerInnocent.label>
```suggestion
  <ExecutedPrisonerInnocent.label>казнь невиновного пленника</ExecutedPrisonerInnocent.label>
```

2021-07-17 19:20 UTC, Elevator89 commented on Core/DefInjected/IncidentDef/Incidents_Map_Misc.xml
> -  <!-- EN: A {PAWN_title} named {PAWN_nameDef} has arrived and is joining the colony.\n\n[PAWN_pronoun] is willing to contribute, but will not leave voluntarily. If you don't want {PAWN_nameDef}, you
Обычно, если английского теста нет, это свидетельствует о том, что текст в игре не нужен. Но при этом он должен быть отмечен как "unused". Здесь нет ни текста, и unused-метки. Это странно. Проверь, пожалуйста, что ты случайно её не убрал, а текст - оставил.

2021-07-17 23:36 UTC, kamadz commented on Core/DefInjected/GoodwillSituationDef/GoodwillSituations_Misc.xml
> +  <NaturalEnemy.label>естественный противник</NaturalEnemy.label>
"непримиримый враг" можно использовать

2021-07-17 23:38 UTC, kamadz commented on Core/DefInjected/HistoryEventDef/HistoryEventDefs.xml
> +  <AdministeredDrug.label>выдан препарат</AdministeredDrug.label>
Забыл, пардон

2021-07-17 23:39 UTC, kamadz commented on Core/DefInjected/HistoryEventDef/Precepts_Cannibalism.xml
> +  <AteHumanMeatDirect.label>съедено человеческое мясо</AteHumanMeatDirect.label>
```suggestion
  <AteHumanMeatDirect.label>съедена человеческое мясо</AteHumanMeatDirect.label>
```

2021-07-17 23:40 UTC, kamadz commented on Core/DefInjected/IncidentDef/Incidents_Map_Misc.xml
> -  <!-- EN: A {PAWN_title} named {PAWN_nameDef} has arrived and is joining the colony.\n\n[PAWN_pronoun] is willing to contribute, but will not leave voluntarily. If you don't want {PAWN_nameDef}, you
проверю

2021-07-18 12:58 UTC, Elevator89 commented on Core/DefInjected/GoodwillSituationDef/GoodwillSituations_Misc.xml
> +  <NaturalEnemy.label>естественный противник</NaturalEnemy.label>
Судя по скрину, как раз примиримый. Воинственные племена можно подарками задобрять и становиться их союзниками.
А "враги" даже лучше, чем "противники", судя по контексту.
```suggestion
  <NaturalEnemy.label>естественные враги</NaturalEnemy.label>
```
Не слишком сильная ассоциация с миром дикой природы?

2021-07-18 13:19 UTC, Elevator89 commented on Core/DefInjected/HistoryEventDef/HistoryEventDefs.xml
> +  <AdministeredHardDrug.label>выдан тяжёлый наркотик</AdministeredHardDrug.label>
```suggestion
  <AdministeredHardDrug.label>назначен тяжёлый наркотик</AdministeredHardDrug.label>
```

2021-07-18 13:19 UTC, Elevator89 commented on Core/DefInjected/HistoryEventDef/HistoryEventDefs.xml
> +  <AdministeredRecreationalDrug.label>выдан рекреационный наркотик</AdministeredRecreationalDrug.label>
```suggestion
  <AdministeredRecreationalDrug.label>назначен рекреационный наркотик</AdministeredRecreationalDrug.label>
```

2021-07-18 13:20 UTC, Elevator89 commented on Core/DefInjected/HistoryEventDef/HistoryEventDefs.xml
> +  <AteHumanMeat.label>съедено человеческое мясо</AteHumanMeat.label>
```suggestion
  <AteHumanMeat.label>съедена человечина</AteHumanMeat.label>
```

2021-07-18 13:27 UTC, kamadz commented on Core/DefInjected/GoodwillSituationDef/GoodwillSituations_Misc.xml
> +  <NaturalEnemy.label>естественный противник</NaturalEnemy.label>
Ну на это и делается акцент, насколько я понимаю. Как бы, задобрить-то можно, но, скажем, племя "А" всегда будет, даже если втайне, ненавидеть поселенцев игрока с имперской культурой, подразумевающей трансгуманизм и тд.
А пираты всегда будут рассматривать игрока как потенциальную жертву, даже если их завалить серебром и лечить раненых бойцов.

2021-07-18 14:01 UTC, Elevator89 commented on Core/DefInjected/GoodwillSituationDef/GoodwillSituations_Misc.xml
> +  <NaturalEnemy.label>естественный противник</NaturalEnemy.label>
Вот на скрине воинственное время - как раз пример того, кто по умолчанию враги, но с кем можно договориться и стать союзниками. При этом репутация будет постепенно падать до -80, если её систематически не улучшать. Это natural enemies
А на том же скрине есть пираты с дикарями - с ними никак нельзя ни договориться, ни торговать. Эти - PermanentEnemy, всегда враждебны.

2021-07-18 15:19 UTC, kamadz commented on Core/DefInjected/IncidentDef/Incidents_Map_Misc.xml
> -  <!-- EN: A {PAWN_title} named {PAWN_nameDef} has arrived and is joining the colony.\n\n[PAWN_pronoun] is willing to contribute, but will not leave voluntarily. If you don't want {PAWN_nameDef}, you
![image](https://user-images.githubusercontent.com/57110948/126072600-d67cab0a-4ad0-4426-810d-0d740e40cc47.png)
Плашки нет, в чём проблема не знаю.

2021-07-18 15:21 UTC, kamadz commented on Core/DefInjected/GoodwillSituationDef/GoodwillSituations_Misc.xml
> +  <NaturalEnemy.label>естественный противник</NaturalEnemy.label>
Тогда почему не перефразировать на что-то похожее по смыслу? 
Например на просто "неприязнь"?

2021-07-19 18:57 UTC, Elevator89 commented on Core/DefInjected/IncidentDef/Incidents_Map_Misc.xml
> -  <!-- EN: A {PAWN_title} named {PAWN_nameDef} has arrived and is joining the colony.\n\n[PAWN_pronoun] is willing to contribute, but will not leave voluntarily. If you don't want {PAWN_nameDef}, you
Надо убирать строку - в оригинальных Def'ах её нет

2021-07-19 18:58 UTC, Elevator89 commented on Core/DefInjected/IncidentDef/Incidents_Map_Misc.xml
> -  <!-- EN: A {PAWN_title} named {PAWN_nameDef} has arrived and is joining the colony.\n\n[PAWN_pronoun] is willing to contribute, but will not leave voluntarily. If you don't want {PAWN_nameDef}, you
Убрал

2021-07-19 19:11 UTC, Elevator89 commented on Core/DefInjected/GoodwillSituationDef/GoodwillSituations_Misc.xml
> +  <NaturalEnemy.label>естественный противник</NaturalEnemy.label>
В игре есть другие фразы со словом natural в контексте goodwill
```
  <!-- EN: This faction has a natural goodwill range from {0} to {1}. -->
  <CurrentGoodwillTip_NaturalGoodwill>Эта фракция будет стремиться сохранять с вами отношения в определённых пределах.</CurrentGoodwillTip_NaturalGoodwill>
```
```
  <!-- EN: natural tendency to reach {0} over time -->
  <GoodwillChangedReason_NaturallyOverTime>репутация стремится к {0} естественным образом</GoodwillChangedReason_NaturallyOverTime>
```
Поэтому предлагаю такой вариант:
```suggestion
  <NaturalEnemy.label>стремяться к враждебности</NaturalEnemy.label>
```
Можно конечно и так:
```suggestion
  <NaturalEnemy.label>склонны к враждебности</NaturalEnemy.label>
```
но тогда надо переделать остальные вхождения "стремления" на "склонность"

2021-07-19 20:47 UTC, kamadz commented on Core/DefInjected/GoodwillSituationDef/GoodwillSituations_Misc.xml
> +  <NaturalEnemy.label>естественный противник</NaturalEnemy.label>
Давай второе, сделаем ишью на приведение к новому переводу отдельное

2021-07-22 14:34 UTC, Elevator89 approved these changes

2021-07-22 14:35 UTC, merged