3056 Core/Definjected-4
Ludeon/RimWorld-ru pull request #1231
Opened 2021-07-15 13:39 UTC by kamadz

#1205 
Translate pt. 4 of Core/Definjected

2021-07-17 19:44 UTC, Elevator89 requested changes

2021-07-17 19:44 UTC, Elevator89 commented on Core/DefInjected/InstructionDef/Instructions.xml
> +  <CreateWorldParams.rejectInputMessage>Нажмите «создать», чтобы сгенерировать мир.</CreateWorldParams.rejectInputMessage>
```suggestion
  <CreateWorldParams.rejectInputMessage>Нажмите кнопку «Создать», чтобы сгенерировать мир.</CreateWorldParams.rejectInputMessage>
```

2021-07-17 19:44 UTC, Elevator89 commented on Core/DefInjected/InstructionDef/Instructions.xml
> +  <UnforbidStartingResources.text>Снимите запрет с разбросанных ресурсов, чтобы поселенцы перенесли их на склад.\n\n1. Для этого выберите один из отмеченных ресурсов.\n2. Щёлкните на переключатель «Р
Кнопки хорошо бы с большой буквы писать.
```suggestion
  <UnforbidStartingResources.text>Снимите запрет с разбросанных ресурсов, чтобы поселенцы перенесли их на склад.\n\n1. Для этого выберите один из отмеченных ресурсов.\n2. Щёлкните на переключатель «Разрешить» для снятия запрета на использование ресурса.\n\n(Совет: Используйте двойной щелчок на ресурсе для выделения ресурсов того же типа, видимых на экране.)\n\nДругой способ:\n1. Откройте меню «Проекты».\n2. Выберите «Приказы».\n3. Нажмите «Разрешить».\n4. Выделите все предметы, на которых стоит запрет.</UnforbidStartingResources.text>
```

2021-07-17 19:44 UTC, Elevator89 commented on Core/DefInjected/InteractionDef/Interactions_Animal.xml
> +    <li>farewell->[INITIATOR_nameDef] вспоминает хорошие моменты их общие с [RECIPIENT_nameDef] моменты</li>
```suggestion
    <li>farewell->[INITIATOR_nameDef] вспоминает их общие с [RECIPIENT_nameDef] приятные моменты</li>
```

2021-07-17 19:44 UTC, Elevator89 commented on Core/DefInjected/IssueDef/Precepts_SpouseCount.xml
> +  <SpouseCount_Male.label>брак мужчины</SpouseCount_Male.label>
В каком контексте это будет отображаться?

2021-07-17 19:44 UTC, Elevator89 commented on Core/DefInjected/JobDef/Jobs_Caravan.xml
> +  <ReturnedCaravan_PenAnimals.reportString>ведёт TargetA обратно в загон</ReturnedCaravan_PenAnimals.reportString>
```suggestion
  <ReturnedCaravan_PenAnimals.reportString>возвращает TargetA в загон</ReturnedCaravan_PenAnimals.reportString>
```

2021-07-17 23:42 UTC, kamadz commented on Core/DefInjected/IssueDef/Precepts_SpouseCount.xml
> +  <SpouseCount_Male.label>брак мужчины</SpouseCount_Male.label>
Я так понимаю, это пункты в идеологиях, а-ля, что можно, что нельзя

2021-07-18 12:28 UTC, Elevator89 approved these changes

2021-07-18 12:28 UTC, merged