3056 Core/Definjected-5
Ludeon/RimWorld-ru pull request #1232
Opened 2021-07-15 13:59 UTC by kamadz

#1206 
Translate pt. 5 of Core/Definjected

2021-07-17 19:49 UTC, Elevator89 requested changes

2021-07-17 19:49 UTC, Elevator89 commented on Core/DefInjected/KeyBindingCategoryDef/KeyBindingCategories.xml
> +  <DebugMenu.description>Управление в debug-меню. Доступно только в режиме разработчика.</DebugMenu.description>
"Меню отладки" же!

2021-07-17 19:49 UTC, Elevator89 commented on Core/DefInjected/MentalStateDef/MentalStates_Special.xml
> +  <Roaming.baseInspectLine>Душевное состояние: бесцельно бродит</Roaming.baseInspectLine>
Если я всё правильно понимаю, имеется в виду целенаправленное убредание скота за край карты.
```suggestion
  <Roaming.label>убредание</Roaming.label>
  <!-- EN: Mental state: Roaming -->
  <Roaming.baseInspectLine>Душевное состояние: убредает</Roaming.baseInspectLine>
```

2021-07-17 23:44 UTC, kamadz commented on Core/DefInjected/MentalStateDef/MentalStates_Special.xml
> +  <Roaming.baseInspectLine>Душевное состояние: бесцельно бродит</Roaming.baseInspectLine>
На данном этапе, к сожалению, невозможно точно подтвердить, в дебаг меню эта штука не вызывается. Она там есть, но стоит пометка [NO] (не вызывается ни на людях, ни на животных). Можно уточнить у девов.

2021-07-18 13:54 UTC, Elevator89 commented on Core/DefInjected/MentalStateDef/MentalStates_Special.xml
> +  <Roaming.baseInspectLine>Душевное состояние: бесцельно бродит</Roaming.baseInspectLine>
Воспроизвёл сам. Они таки реально убредают

2021-07-19 17:14 UTC, kamadz commented on Core/DefInjected/MentalStateDef/MentalStates_Special.xml
> +  <Roaming.baseInspectLine>Душевное состояние: бесцельно бродит</Roaming.baseInspectLine>
только для животных, значит?

2021-07-19 19:26 UTC, Elevator89 commented on Core/DefInjected/MentalStateDef/MentalStates_Special.xml
> +  <Roaming.baseInspectLine>Душевное состояние: бесцельно бродит</Roaming.baseInspectLine>
Да

2021-07-22 14:37 UTC, merged