3056 Core/DefInjected-6
Ludeon/RimWorld-ru pull request #1235
Opened 2021-07-18 14:19 UTC by kamadz

Close #1207 Translate Core/DefInjected-6

2021-07-18 14:29 UTC, kamadz commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_foeSoldiers->клёпкоголовые</li>
за оригинал в данном случае были взяты rivet-heads, потому что metal-heads в русском языке - это любители конкретного жанра музыки. А ривет-хеды - малоизвестная субкультура, которая в целом подходит по духу

2021-07-18 14:29 UTC, kamadz commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_foeLeader->шахтёрский гипервизор</li>
Без малейшего понятия, что тут имелось в виду

2021-07-18 14:30 UTC, kamadz commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_massWeapon->линза телескопа</li>
не уверен

2021-07-18 20:34 UTC, Elevator89 requested changes

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_foeLeader->шахтёрский гипервизор</li>
FoeLeader - это человек. Supervisor - значит главный, старший. Поэтому подойдёт перевод "главный шахтёр".
```suggestion
    <li>place_foeLeader->главный шахтёр</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_job->доктор</li>
тогда уж
```suggestion
    <li>place_job->врач</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_summary->тихий агро-мир</li>
Не слитно ли?
```suggestion
    <li>place_summary->тихий агромир</li>
```
или вообще полностью
```suggestion
    <li>place_summary->тихий аграрный мир</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_community->мега-элеватор</li>
```suggestion
    <li>place_community->мегаэлеватор</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_job->водитель транспорта</li>
Какой ещё водитель бывает?
```suggestion
    <li>place_job->водитель</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_massWeapon->линза телескопа</li>
Скорее всего, имеется в виду космическая линза, которая может как добавить солнца в холодный регион, чтобы урожай рос нормально, так и при полной фокусировке сжигать города. Как в фильме "Умри, но не сейчас" про Бонда.
```suggestion
    <li>place_massWeapon->космическая линза</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_adjective->Ильвабец</li>
```suggestion
    <li>place_adjective->ильвабец</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_job->охотник на артефакты</li>
```suggestion
    <li>place_job->охотник за артефактами</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_massWeapon->древняя «грязная» ядерная бомба</li>
Про ядерность в оригинале не было
```suggestion
    <li>place_massWeapon->древняя «грязная» бомба</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_adjective->Ивамурец</li>
```suggestion
    <li>place_adjective->ивамурец</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_community->склад-капсула</li>
```suggestion
    <li>place_community->капсула-рынок</li>
    <li>place_community->капсула-склад</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_adjective->Кемиец</li>
```suggestion
    <li>place_adjective->кемиец</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_adjective->Новароманец</li>
```suggestion
    <li>place_adjective->новаромец</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_adjective->нучадец</li>
```suggestion
    <li>place_name->Нухад</li>
    <li>place_adjective->нухадец</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_adjective->Убаньец</li>
```suggestion
    <li>place_adjective->убаньенец</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_job->козлиный патсух</li>
Патсух )
```suggestion
    <li>place_job->козий пастух</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_adjective->Райделлец</li>
Обычно когда иностранное слово приживается в русском языке, согласная теряет удвоение
```suggestion
    <li>place_name->Райдел</li>
    <li>place_adjective->райделец</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_adjective->Рогиец</li>
```suggestion
    <li>place_adjective->рогиец</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_adjective->Вавиец</li>
```suggestion
    <li>place_adjective->вавиец</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_adjective->Ксанидец</li>
Если слово начинается с буквы "X", то она при произношении превращается в "З" или "ДЗ"
```suggestion
    <li>place_name->Дзанид</li>
    <li>place_adjective->дзанидец</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_adjective->Иттакец</li>
```suggestion
    <li>place_adjective->иттакец</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_job->водитель транспорта</li>
```suggestion
    <li>place_job->водитель</li>
```

2021-07-18 20:34 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_adjective->Зоутерец</li>
```suggestion
    <li>place_adjective->зоутерец</li>
```

2021-07-18 21:29 UTC, kamadz commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_foeLeader->шахтёрский гипервизор</li>
тогда уже лучше
```suggestion
    <li>place_foeLeader->прораб</li>
```

2021-07-18 21:30 UTC, kamadz commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_summary->тихий агро-мир</li>
второе отлично

2021-07-18 21:32 UTC, kamadz commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_job->водитель транспорта</li>
Личный, например???
Погрузчика, крана, самосвала, асфальтоукладчика?

2021-07-18 21:35 UTC, kamadz commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_massWeapon->древняя «грязная» ядерная бомба</li>
в оригинале и про "грязную", что про вполне конкретный вид бомб, ничего не было
```suggestion
    <li>place_massWeapon->древняя бомба с ядом</li>
```

2021-07-18 21:45 UTC, kamadz commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_adjective->Ксанидец</li>
![image](https://user-images.githubusercontent.com/57110948/126082901-a44cb44b-df19-4c60-8e13-5ad997392a18.png)

В данном случае слово Xanides - типичный образец кальки с греческого. Суффикс -id здесь происходит от греческого eidos (образный, подобный). Хлорид, бромид, тиранид - это всё из этой же оперы.

2021-07-18 21:48 UTC, kamadz commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_adjective->Ксанидец</li>
Скорее всего, названием вдохновлялись отсюда (тоже ксаниды, кстати, в официальном переводе)
![image](https://user-images.githubusercontent.com/57110948/126083080-75ab13c1-637f-4184-a730-fccf07351ac4.png)

2021-07-19 10:48 UTC, kamadz commented on Core/DefInjected/PlaceDef/Places.xml
> +  <!-- EN:
нашел для чего это генератор
![image](https://user-images.githubusercontent.com/57110948/126148848-8ddcce78-8423-47ed-8e14-0d8e49cabb42.png)

2021-07-19 12:57 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_foeLeader->шахтёрский гипервизор</li>
Это не просто прораб на стройке, а сильно влиятельное лицо. Если подумать, вряд ли он является шахтёром и сам машет киркой. Поэтому правильнее будет так:
```suggestion
    <li>place_foeLeader->главный управляющий шахтой</li>
```

2021-07-19 13:08 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_adjective->Ксанидец</li>
Понял-принял. Но заглавную всё равно уберу
```suggestion
    <li>place_name->Ксанид</li>
    <li>place_adjective->ксанидец</li>
```

2021-07-19 17:18 UTC, kamadz commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_foeLeader->шахтёрский гипервизор</li>
Либо главный, либо управляющий - масло масляное.

2021-07-19 17:50 UTC, Elevator89 requested changes

2021-07-19 17:50 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_job->водитель транспорта</li>
Ладно, допустим

2021-07-19 17:50 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_massWeapon->древняя «грязная» ядерная бомба</li>
![изображение](https://user-images.githubusercontent.com/21694533/126203897-30ca3b11-445a-43e3-8fa7-d1d987dd48ab.png)
Подходит "токсичная бомба"

2021-07-19 18:01 UTC, kamadz commented on Core/DefInjected/PlaceDef/Places.xml
> +  <!-- EN:
Это скриншот со страницы в стиме

2021-07-19 18:50 UTC, Elevator89 commented on Core/DefInjected/PlaceDef/Places.xml
> +    <li>place_massWeapon->древняя «грязная» ядерная бомба</li>
```suggestion
    <li>place_massWeapon->древняя токсичная бомба</li>
```

2021-07-19 18:51 UTC, Elevator89 approved these changes

2021-07-19 18:52 UTC, merged