3056 Core/DefInjected-7
Ludeon/RimWorld-ru pull request #1236
Opened 2021-07-18 21:10 UTC by kamadz

Close #1208 Translate Core/DefInjected-7

2021-07-19 21:36 UTC, Elevator89 requested changes

2021-07-19 21:36 UTC, Elevator89 commented on Core/DefInjected/QuestScriptDef/Script_PeaceTalks.xml
>      <li>questDescription->[faction_leader_nameFull], [faction_leaderTitle] фракции [faction_name], сообщает, что хочет встретиться с вами на нейтральной территории для переговоров.\n\nЭто хорошая воз
```suggestion
    <li>questDescription->[faction_leader_nameFull], [faction_leaderTitle] фракции [faction_name], сообщает, что хочет встретиться с вами на нейтральной территории для переговоров.\n\nЭто хорошая возможность улучшить отношения с этой фракцией и получить ценные дипломатические подарки, но знайте: неумелый переговорщик может принести больше вреда, чем пользы.[extraLeaderPart][favorRewardDetails]</li>
```

2021-07-19 21:36 UTC, Elevator89 commented on Core/DefInjected/QuestScriptDef/Script_WandererJoins.xml
> +  <WandererJoins.questNameRules.rulesStrings>Пополнение</WandererJoins.questNameRules.rulesStrings>
Надо быть внимательнее со списками. Здесь и везде по реквесту такая же ошибка.
```suggestion
  <!-- EN:
    <li>questDescription-></li>
  -->
  <WandererJoins.questDescriptionRules.rulesStrings>
    <li>questDescription-></li>
  </WandererJoins.questDescriptionRules.rulesStrings>
  <!-- EN:
    <li>questName->Wanderer joins</li>
  -->
  <WandererJoins.questNameRules.rulesStrings>
    <li>questName->Пополнение</li>
  </WandererJoins.questNameRules.rulesStrings>
```

2021-07-19 21:36 UTC, Elevator89 commented on Core/DefInjected/QuestScriptDef/Script_TransportPodCrash.xml
> +  <RefugeePodCrash.questDescriptionRules.rulesStrings>Капсула с беженцем потерпела крушение</RefugeePodCrash.questDescriptionRules.rulesStrings>
Это списковое значение

2021-07-19 21:36 UTC, Elevator89 commented on Core/DefInjected/QuestScriptDef/Scripts_Utility_ThreatsCore.xml
>        <li>root(priority=1,sitePart==ClimateAdjuster)->в регионе находится (*Threat)регулятор климата,(/Threat) изменяющий температуру на [temperatureOffset]</li>
В оригинале есть изменения, а в переводе нет

2021-07-19 21:36 UTC, Elevator89 commented on Core/DefInjected/RecipeDef/Recipes_Meals.xml
>    <CookMealFineBulk.description>Приготовить 4 вкусных сбалансированных блюда из ингредиентов растительного и животного происхождения.</CookMealFineBulk.description>
Оригинал изменён, а перевод - нет

2021-07-19 21:36 UTC, Elevator89 commented on Core/DefInjected/RecipeDef/Recipes_Meals.xml
> +  <CookMealFineBulk_Meat.description>Приготовить 4 вкусных блюда из ингредиентов животного происхождения.</CookMealFineBulk_Meat.description>
Оригинал изменён, а перевод - нет

2021-07-19 21:36 UTC, Elevator89 commented on Core/DefInjected/RecipeDef/Recipes_Meals.xml
> +  <CookMealFineBulk_Veg.description>Приготовить 4 вкусных блюда из ингредиентов растительного происхождения.</CookMealFineBulk_Veg.description>
Оригинал изменён, а перевод - нет

2021-07-19 21:36 UTC, Elevator89 commented on Core/DefInjected/RecipeDef/Recipes_Meals.xml
>    <CookMealLavish.description>Приготовить сложное изысканное блюдо из ингредиентов растительного и животного происхождения. Часть ингредиентов уйдёт впустую.</CookMealLavish.description>
Оригинал изменён, а перевод - нет

2021-07-19 21:36 UTC, Elevator89 commented on Core/DefInjected/RecipeDef/Recipes_Meals.xml
> +  <CookMealLavish_Meat.description>Приготовить сложное изысканное блюдо из ингредиентов животного происхождения. Часть ингредиентов уйдёт впустую.</CookMealLavish_Meat.description>
Оригинал изменён, а перевод - нет

2021-07-19 21:36 UTC, Elevator89 commented on Core/DefInjected/RecipeDef/Recipes_Meals.xml
> +  <CookMealLavish_Veg.description>Приготовить сложное изысканное блюдо из ингредиентов растительного происхождения. Часть ингредиентов уйдёт впустую.</CookMealLavish_Veg.description>
Оригинал изменён, а перевод - нет

2021-07-19 21:36 UTC, Elevator89 commented on Core/DefInjected/RecipeDef/Recipes_Meals.xml
>    <CookMealLavishBulk.description>Приготовить 4 сложных изысканных блюда из ингредиентов растительного и животного происхождения. Часть ингредиентов уйдёт впустую.</CookMealLavishBulk.description>
Оригинал изменён, а перевод - нет

2021-07-19 21:36 UTC, Elevator89 commented on Core/DefInjected/RecipeDef/Recipes_Meals.xml
> +  <CookMealLavishBulk_Meat.description>Приготовить 4 сложных изысканных блюда из ингредиентов животного происхождения. Часть ингредиентов уйдёт впустую.</CookMealLavishBulk_Meat.description>
Оригинал изменён, а перевод - нет

2021-07-19 21:36 UTC, Elevator89 commented on Core/DefInjected/RecipeDef/Recipes_Meals.xml
> +  <CookMealLavishBulk_Veg.description>Приготовить 4 сложных изысканных блюда из ингредиентов растительного происхождения. Часть ингредиентов уйдёт впустую.</CookMealLavishBulk_Veg.description>
Оригинал изменён, а перевод - нет

2021-07-19 21:36 UTC, Elevator89 commented on Core/DefInjected/QuestScriptDef/Scripts_Permits.xml
> +</LanguageData>
Сгенерился пустой файл?

2021-07-25 11:30 UTC, Elevator89 requested changes

2021-07-25 11:30 UTC, Elevator89 commented on Core/DefInjected/QuestScriptDef/Script_WandererJoins.xml
> +  <WandererJoins.questNameRules.rulesStrings>Пополнение</WandererJoins.questNameRules.rulesStrings>
Под XML-элементом "WandererJoins.questDescriptionRules.rulesStrings" должен идти список вложенных XML-элементов "li" (list item). Название родительского элемента "rulesStrings" своим множественным числом буквально кричит об этом.
Посмотри внимательно на мою правку, и всё поймёшь

2021-07-25 11:30 UTC, Elevator89 commented on Core/DefInjected/PreceptDef/Precepts_InsectMeat.xml
> +  <InsectMeatEating_Despised_Classic.description>На мясо насекомых даже просто смотреть без отвращения невозможно, не то что есть. Склизенькое!</InsectMeatEating_Despised_Classic.description>
Я не буду вставлять "склизенькое" в перевод, потому что это слово не имеет негативного оттенка, и по-русски так никто не говорит об отвратительных вещах.
```suggestion
  <InsectMeatEating_Despised_Classic.description>На мясо насекомых даже просто смотреть без отвращения невозможно, не то что есть. Оно ещё и склизкое!</InsectMeatEating_Despised_Classic.description>
```

2021-07-25 11:30 UTC, Elevator89 commented on Core/DefInjected/QuestScriptDef/Scripts_Utility_ThreatsCore.xml
>        <li>root(priority=1,sitePart==ClimateAdjuster)->в регионе находится (*Threat)регулятор климата,(/Threat) изменяющий температуру на [temperatureOffset]</li>
Гитхаб всё равномерно-красно-зелёным красит, найти отличия нереально. Главное, что они есть, и ты о них знаешь.

2021-07-25 11:43 UTC, kamadz commented on Core/DefInjected/PreceptDef/Precepts_InsectMeat.xml
> +  <InsectMeatEating_Despised_Classic.description>На мясо насекомых даже просто смотреть без отвращения невозможно, не то что есть. Склизенькое!</InsectMeatEating_Despised_Classic.description>
Если ты так не говоришь — не значит, что никто так не говорит. Но последний вариант мне нравится.

2021-07-25 11:43 UTC, kamadz commented on Core/DefInjected/QuestScriptDef/Script_WandererJoins.xml
> +  <WandererJoins.questNameRules.rulesStrings>Пополнение</WandererJoins.questNameRules.rulesStrings>
как файл отформатировался, так я и переводил

2021-07-25 11:48 UTC, Elevator89 commented on Core/DefInjected/QuestScriptDef/Script_WandererJoins.xml
> +  <WandererJoins.questNameRules.rulesStrings>Пополнение</WandererJoins.questNameRules.rulesStrings>
В оригинале были теги <li>, но ты их не перенёс в перевод

2021-07-25 11:55 UTC, Elevator89 requested changes

2021-07-25 11:55 UTC, Elevator89 commented on Core/DefInjected/QuestScriptDef/Script_TransportPodCrash.xml
> +  <RefugeePodCrash.questDescriptionRules.rulesStrings>Капсула с беженцем потерпела крушение</RefugeePodCrash.questDescriptionRules.rulesStrings>
Смотри оригинал. Это список правил генератора. А у тебя нет нет ни списка, ни правил.
```suggestion
  <RefugeePodCrash.questDescriptionRules.rulesStrings>
    <li>questDescription->Капсула с беженцем потерпела крушение</li>
  </RefugeePodCrash.questDescriptionRules.rulesStrings>
```

2021-07-25 11:55 UTC, Elevator89 commented on Core/DefInjected/QuestScriptDef/Script_TransportPodCrash.xml
> +  <RefugeePodCrash.questNameRules.rulesStrings>Крушение капсулы</RefugeePodCrash.questNameRules.rulesStrings>
```suggestion
  <RefugeePodCrash.questNameRules.rulesStrings>
    <li>questName->Крушение капсулы</li>
  </RefugeePodCrash.questNameRules.rulesStrings>
```

2021-07-25 11:55 UTC, Elevator89 commented on Core/DefInjected/QuestScriptDef/Script_DelayedRewardDropPods.xml
> +  <DelayedRewardDropPods.questDescriptionRules.rulesStrings>отсроченная награда</DelayedRewardDropPods.questDescriptionRules.rulesStrings>
```suggestion
  <DelayedRewardDropPods.questDescriptionRules.rulesStrings>
    <li>questDescription->отсроченная награда</li>
  </DelayedRewardDropPods.questDescriptionRules.rulesStrings>
```

2021-07-25 11:55 UTC, Elevator89 commented on Core/DefInjected/QuestScriptDef/Script_DelayedRewardDropPods.xml
> +  <DelayedRewardDropPods.questNameRules.rulesStrings>отсроченная награда</DelayedRewardDropPods.questNameRules.rulesStrings>
```suggestion
  <DelayedRewardDropPods.questNameRules.rulesStrings>
    <li>questDescription->отсроченная награда</li>
  </DelayedRewardDropPods.questNameRules.rulesStrings>
```

2021-07-25 12:16 UTC, merged