3056 Core/DefInjected-8
Ludeon/RimWorld-ru pull request #1237
Opened 2021-07-19 12:38 UTC by kamadz

Close #1209  Translate Core/DefInjected-8

2021-07-19 16:23 UTC, kamadz commented on Core/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <AttendedSpeech.comps.0.label>общественное влияние {PAWN_labelShort}</AttendedSpeech.comps.0.label>
```suggestion
  <AttendedSpeech.comps.0.label>социальное влияние {PAWN_labelShort}</AttendedSpeech.comps.0.label>
```

2021-07-19 16:23 UTC, kamadz commented on Core/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <AttendedSpeech.comps.0.labelAbstract>общественное влияние говорящего</AttendedSpeech.comps.0.labelAbstract>
```suggestion
  <AttendedSpeech.comps.0.labelAbstract>социальное влияние говорящего</AttendedSpeech.comps.0.labelAbstract>
```

2021-07-22 14:44 UTC, Elevator89 requested changes

2021-07-22 14:44 UTC, Elevator89 commented on Core/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <AttendedSpeech.description>В зависимости от успешности ритуала, его участники получат бонус к настроению от {MINMOOD} до {MAXMOOD} на {MOODDAYS} дней</AttendedSpeech.description>
```suggestion
  <AttendedSpeech.description>В зависимости от успешности ритуала, его участники получат бонус к настроению от {MINMOOD} до {MAXMOOD} на {MOODDAYS_numCase ? день : дня : дней}</AttendedSpeech.description>
```

2021-07-22 14:44 UTC, Elevator89 commented on Core/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
> +  <AllowFemaleGender.description>разрешить для женщин</AllowFemaleGender.description>
Перевод подозрительно отличается от оригинала. В каком контексте это будет отображаться?

2021-07-23 09:03 UTC, kamadz commented on Core/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
> +  <AllowFemaleGender.description>разрешить для женщин</AllowFemaleGender.description>
Скорее всего речь про присутствующие разрешения на взаимодействия (с предметами, зонами) у мужчин и женщин.

2021-07-23 14:16 UTC, Elevator89 commented on Core/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
> +  <AllowFemaleGender.description>разрешить для женщин</AllowFemaleGender.description>
А в игре это получилось проверить?

2021-07-23 14:18 UTC, kamadz commented on Core/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
> +  <AllowFemaleGender.description>разрешить для женщин</AllowFemaleGender.description>
Не успел пока. Сейчас как раз появилась возможность.

2021-07-23 15:35 UTC, kamadz commented on Core/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
> +  <AllowFemaleGender.description>разрешить для женщин</AllowFemaleGender.description>
Не смог пока найти в игре эту штуку, не могу подтвердить.

2021-07-25 11:44 UTC, Elevator89 commented on Core/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
> +  <AllowFemaleGender.description>разрешить для женщин</AllowFemaleGender.description>
Ладно, оставим пока как есть, в игре увидим несоответствие

2021-07-25 11:45 UTC, kamadz commented on Core/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
> +  <AllowFemaleGender.description>разрешить для женщин</AllowFemaleGender.description>
Судя по тегу видно, что это фильтр разрешения, в данном случае на использование какой-то категории вещей.

2021-07-25 11:45 UTC, merged