3056 Core/DefInjected-9
Ludeon/RimWorld-ru pull request #1238
Opened 2021-07-19 17:10 UTC by kamadz

Close #1210 Translate Core/DefInjected-9

2021-07-19 17:12 UTC, kamadz commented on Core/DefInjected/StyleItemCategoryDef/StyleItemCategoryDefs.xml
> +  <Cannibal.label>каннибальский</Cannibal.label>
уточнить что это

2021-07-22 15:04 UTC, Elevator89 requested changes

2021-07-22 15:04 UTC, Elevator89 commented on Core/DefInjected/StyleItemCategoryDef/StyleItemCategoryDefs.xml
> +  <Moustache.label>усы</Moustache.label>
Вот тут затрудняюсь. Разве что:
```suggestion
  <Moustache.label>«усатый»</Moustache.label>
```

2021-07-23 09:05 UTC, kamadz commented on Core/DefInjected/StyleItemCategoryDef/StyleItemCategoryDefs.xml
> +  <Punk.label>панк</Punk.label>
Стиль "панк" существует.

2021-07-23 09:10 UTC, kamadz commented on Core/DefInjected/StyleItemCategoryDef/StyleItemCategoryDefs.xml
> +  <Moustache.label>усы</Moustache.label>
Мб тогда что-нибудь формата "солидный", "респектабельный", "фешенебельный"?
Тут можно ознакомиться, кстати
https://www.reddit.com/r/RimWorld/comments/ooajhu/all_the_differnt_style_types_from_ideology/

2021-07-23 14:34 UTC, Elevator89 commented on Core/DefInjected/StyleItemCategoryDef/StyleItemCategoryDefs.xml
> +  <Moustache.label>усы</Moustache.label>
По ссылке я не увидел упоминаний "cannibal", "moustache" и других. Я вообще без понятия, что это такое

2021-07-23 14:39 UTC, Elevator89 commented on Core/DefInjected/StyleItemCategoryDef/StyleItemCategoryDefs.xml
> +  <Cannibal.label>каннибальский</Cannibal.label>
Непохоже, что это оно. Создал таск про эти "Категории стильных предметов" #1252

2021-07-23 14:40 UTC, merged