1215 core keyed 3
Ludeon/RimWorld-ru pull request #1240
Opened 2021-07-21 16:50 UTC by memedozer

2021-07-21 21:11 UTC, Elevator89 requested changes
Не буду досматривать реквест: слишком много ошибок. Сначала исправьте указанные ошибки в просмотренной и непросмотренной частях, потом - продолжу ревью.

2021-07-21 21:11 UTC, Elevator89 commented on Core/Keyed/Menus_Main.xml
> +  <FactionsDisabledWarning>Без других фракций рейды, торговля и задания не будут появляться.</FactionsDisabledWarning>
У нас не "рейды", а "налёты"
Глагол "появляться" неприменим налётам и торговле

2021-07-21 21:11 UTC, Elevator89 commented on Core/Keyed/Messages.xml
>    <MessageCaravanDetectedRaidArrived>{0} из фракции {1} нападают на ваш караван. Через {2} прибудут их новые подкрепления.</MessageCaravanDetectedRaidArrived>
Здесь текст не потерял актуальности, но восклицательный знак лишним не будет
```suggestion
  <MessageCaravanDetectedRaidArrived>{0} из фракции {1} нападают на ваш караван! Через {2} прибудут их новые подкрепления.</MessageCaravanDetectedRaidArrived>
```

2021-07-21 21:11 UTC, Elevator89 commented on Core/Keyed/Messages.xml
> +  <MessageInsectTameDesignated>Только колонисты с чертой характера "Любовь к насекомым" могут приручить {INSECT_indefinite}.</MessageInsectTameDesignated>
Поселенцы

2021-07-23 20:51 UTC, kazenosaga commented on Core/Keyed/MainTabs.xml
> +
Зачем? Они же никому не мешают. А вдруг они потом опять станут used?

2021-07-26 22:17 UTC, kamadz requested changes

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <MessageTameNoSuitablePens>Нет подходящего загона для {ANIMAL_labelShort}. В конце концов он уйдет.</MessageTameNoSuitablePens>
```suggestion
  <MessageTameNoSuitablePens>Нет подходящего загона для {ANIMAL_labelShort}. Рано или поздно {ANIMAL_pronoun} убредёт от поселения.</MessageTameNoSuitablePens>
```

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <MessageReceivedBrainDamageFromHediff>{PAWN_labelShort} {PAWN_gender ? получил : получила} повреждение мозга на ^Number( {1} | '# единицу' | '# единицы' | '# единиц')^ из-за: {2}.</MessageReceivedB
Нужно вернуть обратно

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <MessageRoamerLeaving>{PAWN_labelShort} начал убегать! {PAWN_pronoun} покинет карту, если дрессировщик не вернет {PAWN_objective} обратно в загон.</MessageRoamerLeaving>
```suggestion
  <MessageRoamerLeaving>{PAWN_labelShort} {PAWN_gender ? начал : начала : начало} убредать. {PAWN_pronoun} покинет карту, если животновод не вернет {PAWN_possessive} обратно в загон.</MessageRoamerLeaving>
```

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <MessageAutoCutInUnenclosedPen>Невозможно автоматически обрезать растения, если загон не закрыт.</MessageAutoCutInUnenclosedPen>
```suggestion
  <MessageAutoCutInUnenclosedPen>Невозможно автоматически срезать растения, если загон не закрыт.</MessageAutoCutInUnenclosedPen>
```

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <MessageReleaseBondedAnimal>Поскольку они связаны, освобождение {DESIGNATED_labelShort} сделает {BONDED_labelShort} несчастным.</MessageReleaseBondedAnimal>
```suggestion
  <MessageReleaseBondedAnimal>Если отпустить на волю {DESIGNATED_labelShort}, {BONDED_labelShort} расстроится, так как они связаны.</MessageReleaseBondedAnimal>
```

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <MessageCanReformCaravanNowNoMoreEnemies>Зона теперь безопасна. Вы можете снарядить караван.</MessageCanReformCaravanNowNoMoreEnemies>
```suggestion
  <MessageCanReformCaravanNowNoMoreEnemies>Область теперь безопасна. Вы можете снарядить караван.</MessageCanReformCaravanNowNoMoreEnemies>
```

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <MessageCanReformCaravanNowNoMoreEnemiesButUnexploredAreas>Зона теперь безопасна. Но остались неисследованные комнаты. Вы можете доисследовать из или снарядить караван.</MessageCanReformCaravanNowN
```suggestion
  <MessageCanReformCaravanNowNoMoreEnemiesButUnexploredAreas>Область теперь безопасна, но остались неисследованные комнаты. Вы можете исследовать их или снарядить караван.</MessageCanReformCaravanNowNoMoreEnemiesButUnexploredAreas>
```

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <MessageAnimalReturnedWildReleased>{1_labelShort} был выпущен в дикую природу.</MessageAnimalReturnedWildReleased>
```suggestion
  <MessageAnimalReturnedWildReleased>{1_labelShort} {1_gender ? был выпущен : была выпущена : было выпущено} в дикую природу.</MessageAnimalReturnedWildReleased>
```

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <MessageEnterCooldownBlocksEntering>Это место посещать слишком слишком опасно ещё ^Number( {0} | '# день' | '# дня' | '# дней')^.</MessageEnterCooldownBlocksEntering>
Нужно вернуть обратно

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <MessageIdeoOpposedWorkTypeSelected>Внимание: Мировоззрение {0_nameDef} противоречит работе {1}. {0_pronoun} может стать несчастным из-за этого.</MessageIdeoOpposedWorkTypeSelected>
```suggestion
  <MessageIdeoOpposedWorkTypeSelected>Внимание: убеждения {0_nameDef} не разрешают {0_objective} заниматься {1}. {0_pronoun} может из-за этого расстроиться.</MessageIdeoOpposedWorkTypeSelected>
```

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <MessageBedLostAssignment>{0} больше не привязан {1_nameDef}.</MessageBedLostAssignment>
```suggestion
  <MessageBedLostAssignment>{0} больше не назначена {1_nameDef}.</MessageBedLostAssignment>
```

кровать

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <MessageBedDestroyed>{0} привязанный к {1_nameDef} был разрущен.</MessageBedDestroyed>
```suggestion
  <MessageBedDestroyed>{0} назначенная {1_nameDef} был разрушена.</MessageBedDestroyed>
```

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <AssignToRole>Привязать к {0}</AssignToRole>
```suggestion
  <AssignToRole>Назначить {0}</AssignToRole>
```

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <RitualBegun>{0} началось.</RitualBegun>
```suggestion
  <RitualBegun>{0} начинается.</RitualBegun>
```

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <MessageRitualRoleMustBePrisoner>{0} должен являться заключенным.</MessageRitualRoleMustBePrisoner>
```suggestion
  <MessageRitualRoleMustBePrisoner>{0} должен быть заключенным.</MessageRitualRoleMustBePrisoner>
```

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <MessageRitualRoleMustBeAnimal>{0} должен являться животным.</MessageRitualRoleMustBeAnimal>
```suggestion
  <MessageRitualRoleMustBeAnimal>{0} должен быть животным.</MessageRitualRoleMustBeAnimal>
```

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <MessageRitualRoleMustBeHumanlike>{0} должен являться человеком.</MessageRitualRoleMustBeHumanlike>
```suggestion
  <MessageRitualRoleMustBeHumanlike>{0} должен быть человеком.</MessageRitualRoleMustBeHumanlike>
```

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <MessageRitualRoleMustBeColonist>должен быть колонистом роли {0}.</MessageRitualRoleMustBeColonist>
```suggestion
  <MessageRitualRoleMustBeColonist>должен быть поселенцем для роли {0}.</MessageRitualRoleMustBeColonist>
```

2021-07-26 22:17 UTC, kamadz commented on Core/Keyed/Messages.xml
> +  <MessageRitualCannotAssignAnyRoleFromSpectating>{0_labelShort} не может занять роль иную чем наблюдатель.</MessageRitualCannotAssignAnyRoleFromSpectating>
```suggestion
  <MessageRitualCannotAssignAnyRoleFromSpectating>{0_labelShort} не может занять роль, кроме наблюдателя.</MessageRitualCannotAssignAnyRoleFromSpectating>
```

2021-08-30 23:47 UTC, Elevator89 commented
Закрываю реквест по причине неактивности

2021-08-30 23:47 UTC, closed without merging