3056 Royalty/DefInjected-1
Ludeon/RimWorld-ru pull request #1254
Opened 2021-07-23 17:47 UTC by kamadz

Close #1218  Translate Royalty/DefInjected-1

2021-07-23 17:48 UTC, kamadz commented on Royalty/DefInjected/AbilityDef/Abilities.xml
> +  <Neuroquake.description>Позволяет найти разрыв в пси-поле и расширить его, высвобождая из него огромное количество пси-энергии. Каждое живое существо, находящееся в радиусе действия и вне безопасно
```suggestion
  <Neuroquake.description>Позволяет найти разрыв в пси-поле и расширить его, высвобождая из него огромное количество пси-энергии. Каждое живое существо, находящееся в радиусе действия и вне безопасной зоны вокруг псионика, войдёт в состояние неконтролируемой ярости. Создание нейрошторма требует 12 секунд подготовительной медитации, после чего псионик впадёт в пси-кому на 5 дней. Отголоски нейрошторма пронесутся по планете на много километров вокруг, причиняя боль всем попавшим под их воздействие. После этого ухудшатся отношения со всеми фракциями.</Neuroquake.description>

```

2021-07-23 17:50 UTC, kamadz commented on Royalty/DefInjected/IncidentDef/Incidents_Map_Misc.xml
> -  <!-- EN: Transport pod crash: {PAWN_nameDef} -->
![Uploading image.png…]()

2021-07-23 18:48 UTC, kamadz commented on Royalty/DefInjected/IncidentDef/Incidents_Map_Misc.xml
> -  <!-- EN: Transport pod crash: {PAWN_nameDef} -->
Под удаление, перенесено в Script_WandererJoins

2021-07-25 12:14 UTC, Elevator89 requested changes

2021-07-25 12:14 UTC, Elevator89 commented on Royalty/DefInjected/FactionDef/Faction_Empire.xml
> +  <Empire.description>Технологически продвинутое сообщество с планеты Софиамунда. Их культура основана на принципах чести, жёстком классовом разделении и полном отсутствии социальной мобильности.\n\n
Rimworld - окраинный мир, а не приграничный
```suggestion
  <Empire.description>Технологически продвинутое сообщество с планеты Софиамунда. Их культура основана на принципах чести, жёстком классовом разделении и полном отсутствии социальной мобильности.\n\nОни — выжившие катастрофы, разорвавшей софийское общество. Им пришлось бежать на окраинные миры на остатках своего космического флота. Несмотря на огромные потери, флот и технологии всё ещё делают имперцев сильными.\n\nОни отказываются торговать с теми, у кого нет соответствующего знатного титула.</Empire.description>
```

2021-07-25 12:14 UTC, Elevator89 commented on Royalty/DefInjected/IncidentDef/Incidents_Map_Misc.xml
> -  <!-- EN: Transport pod crash: {PAWN_nameDef} -->
В случае отсутствия оригинала перевод тоже надо выпиливать

2021-07-25 12:14 UTC, Elevator89 commented on Royalty/DefInjected/AbilityDef/Abilities.xml
> +  <AnimaTreeLinking.description>TODO</AnimaTreeLinking.description>
Пусто

2021-07-25 13:15 UTC, kamadz commented on Royalty/DefInjected/AbilityDef/Abilities.xml
> +  <AnimaTreeLinking.description>TODO</AnimaTreeLinking.description>
Твою мать, ну я помню, что переводил эти две строчки.
```suggestion
  <!-- EN: anima tree linking -->
  <AnimaTreeLinking.label>ритуал связывания</AnimaTreeLinking.label>
  <!-- EN: Start the anima tree linking ceremony. The linking person will meditate near the tree to gain a psylink level. Other psychically-sensitive colonists can also  help enhance the psychic link. More participants will accelerate the ceremony and cause some of the anima grass to re-grow as the ritual completes. -->
  <AnimaTreeLinking.description>Начать ритуал связывания с древом души. Связывающийся начнёт медитировать рядом с древом, чтобы получить уровень пси-связи. Другие пси-чувствительные поселенцы тоже могут участвовать в ритуале. Большое количество участников значительно ускорит ритуал, а также вызовет моментальный рост некоторого количества травы души вокруг древа по его завершении.</AnimaTreeLinking.description>

```

2021-07-25 13:28 UTC, merged