3056 Royalty/DefInjected-2
Ludeon/RimWorld-ru pull request #1255
Opened 2021-07-23 19:24 UTC by kamadz

Close #1219  Translate Royalty/DefInjected-2

2021-07-23 20:10 UTC, kamadz commented on Royalty/DefInjected/PlaceDef/Places.xml
> +    <li>place_massWeapon->военизированный штамм чумы</li>
в core/definjected/places.xml строчку 381 привести к этому надо

2021-07-24 11:53 UTC, kazenosaga commented on Royalty/DefInjected/PawnKindDef/PawnKinds_Empire.xml
> +  <Empire_Fighter_Grenadier.label>импреский гренадёр</Empire_Fighter_Grenadier.label>
импреский -> имперский

2021-07-24 11:57 UTC, kazenosaga commented on Royalty/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <ThroneSpeech.description>Начинает тронную речь. {ORGANIZER_labelShort} отправится к своему трону и позовёт всех поселенцев, чтобы прослушать речь. Если всё пройдёт гладко, речь вдохновит слушателе
**social** damage
Дословно перевести непросто, можно описательно: "огорчит участников", "разочарует слушателей" и т.п.
То же, что и в Royalty/DefInjected/RitualBehaviorDef/Ritual_Behaviors.xml в #1257

2021-07-24 12:04 UTC, kazenosaga commented on Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml
> +  <ThreatReward_Infestation_Joiner.root.nodes.Util_JoinerThreat_Joiner.parms.customLetterText.value.slateRef>{BASETEXT}\n\n[joiner_nameDef] с ног до головы в феромонах насекомых. Преследующие [joiner
is fleeing from an infestation не переведено, но по контексту понятно.

2021-07-24 12:07 UTC, kazenosaga requested changes
Поменять структуры типа ^Number ... ^ на NumCase

2021-07-24 12:13 UTC, kazenosaga commented on Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml
> -  <ThreatReward_MysteryThreat_Joiner.LetterTextChasingRaid.slateRef>[joiner_nameDef] признаётся, от чего [joiner_was_fleeing].\n\n[joiner_pronoun] [joiner_supposed_to] вступить в брак с [joiner_spous
Здесь и в строках ниже в переводе есть тег [joiner_was_fleeing], а в оригинале нет. Точно всё норм?

2021-07-24 12:16 UTC, kazenosaga commented on Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml
> +  <ThreatReward_RaidMultiFaction_Joiner.root.nodes.Delay.node.nodes.Util_Raid.parms.customLetterLabel.value.slateRef>{BASELABEL} в погоне за [joiner_nameDef]</ThreatReward_RaidMultiFaction_Joiner.roo
Здесь и ниже в переводе [../joiner_nameDef] превращается в [joiner_nameDef], это норм?

2021-07-24 12:17 UTC, kazenosaga commented on Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml
> +  <ThreatReward_SiteThreat_Joiner.root.nodes.Delay.node.nodes.Util_SpawnSiteThreat.parms.customLetterText.value.slateRef>Так как вы приняли к себе [joiner_nameDef], [joinersEnemies] теперь организуют
[../threat] превратилось в [joinersEnemies], это норм?

2021-07-25 11:46 UTC, kamadz commented on Royalty/DefInjected/PawnKindDef/PawnKinds_Empire.xml
> +  <Empire_Fighter_Grenadier.label>импреский гренадёр</Empire_Fighter_Grenadier.label>
```suggestion
  <Empire_Fighter_Grenadier.label>имперский гренадёр</Empire_Fighter_Grenadier.label>
```

2021-07-25 11:47 UTC, kamadz commented on Royalty/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <ThroneSpeech.description>Начинает тронную речь. {ORGANIZER_labelShort} отправится к своему трону и позовёт всех поселенцев, чтобы прослушать речь. Если всё пройдёт гладко, речь вдохновит слушателе
Перевод по аналогии с уже существующей строкой по тронной речи

2021-07-25 11:48 UTC, kamadz commented on Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml
> -  <ThreatReward_MysteryThreat_Joiner.LetterTextChasingRaid.slateRef>[joiner_nameDef] признаётся, от чего [joiner_was_fleeing].\n\n[joiner_pronoun] [joiner_supposed_to] вступить в брак с [joiner_spous
Да

2021-07-25 11:48 UTC, kamadz commented on Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml
> +  <ThreatReward_RaidMultiFaction_Joiner.root.nodes.Delay.node.nodes.Util_Raid.parms.customLetterLabel.value.slateRef>{BASELABEL} в погоне за [joiner_nameDef]</ThreatReward_RaidMultiFaction_Joiner.roo
Да

2021-07-25 11:49 UTC, kamadz commented on Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml
> +  <ThreatReward_SiteThreat_Joiner.root.nodes.Delay.node.nodes.Util_SpawnSiteThreat.parms.customLetterText.value.slateRef>Так как вы приняли к себе [joiner_nameDef], [joinersEnemies] теперь организуют
Нет

2021-07-25 11:49 UTC, kamadz commented on Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml
> +  <ThreatReward_SiteThreat_Joiner.root.nodes.Delay.node.nodes.Util_SpawnSiteThreat.parms.customLetterText.value.slateRef>Так как вы приняли к себе [joiner_nameDef], [joinersEnemies] теперь организуют
```suggestion
  <ThreatReward_SiteThreat_Joiner.root.nodes.Delay.node.nodes.Util_SpawnSiteThreat.parms.customLetterText.value.slateRef>Так как вы приняли к себе [joiner_nameDef], [threat] теперь организуют неподалёку лагерь, чтобы досаждать вам.\n\n[allSitePartsDescriptions]</ThreatReward_SiteThreat_Joiner.root.nodes.Delay.node.nodes.Util_SpawnSiteThreat.parms.customLetterText.value.slateRef>

```

2021-07-25 13:20 UTC, Elevator89 requested changes

2021-07-25 13:20 UTC, Elevator89 commented on Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml
> +  <ThreatReward_SiteThreat_Joiner.root.nodes.Delay.node.nodes.Util_SpawnSiteThreat.parms.customLetterText.value.slateRef>Так как вы приняли к себе [joiner_nameDef], [joinersEnemies] теперь организуют
Это - норм. Чуть выше, в списке <ThreatReward_SiteThreat_Joiner.questDescriptionRules.rulesStrings> если правила и для [threat], и для [joinersEnemies]. Разница в падеже. joinersEnemies - в именительном падеже, который здесь и нужен

2021-07-25 13:20 UTC, Elevator89 commented on Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml
> -  <ThreatReward_MysteryThreat_Joiner.LetterTextChasingRaid.slateRef>[joiner_nameDef] признаётся, от чего [joiner_was_fleeing].\n\n[joiner_pronoun] [joiner_supposed_to] вступить в брак с [joiner_spous
Это правила для генерации текста квестов. Из-за наличия падежей, родов, и прочего веселья в русском языке правила для него будут часто отличаться от правил для английского.

2021-07-25 13:20 UTC, Elevator89 commented on Royalty/DefInjected/QuestScriptDef/Script_WandererJoins.xml
> +  <WandererJoinAbasia.questNameRules.rulesStrings>Пополнение (абазия)</WandererJoinAbasia.questNameRules.rulesStrings>
```suggestion
  <WandererJoinAbasia.questNameRules.rulesStrings>
    <li>questName->Пополнение (абазия)</li>
  </WandererJoinAbasia.questNameRules.rulesStrings>
```

2021-07-25 13:20 UTC, Elevator89 commented on Royalty/DefInjected/PlaceDef/Places.xml
> +    <li>place_massWeapon->военизированный штамм чумы</li>
9b84a39a65445a3e8e51b63793878358e8f844d7

2021-07-26 14:08 UTC, kamadz commented on Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml
> +  <ThreatReward_RaidMultiFaction_Joiner.root.nodes.Delay.node.nodes.Util_Raid.parms.customLetterLabel.value.slateRef>{BASELABEL} в погоне за [joiner_nameDef]</ThreatReward_RaidMultiFaction_Joiner.roo
Всё работает. 
Есть ощущение, что это была ошибка форматтера. Есть проблема с этим зато. 
![image](https://user-images.githubusercontent.com/57110948/127002613-2dbabe8f-39ef-420e-8a0a-6954fe0a46b9.png)

2021-07-26 22:11 UTC, merged