1216 core keyed 4
Ludeon/RimWorld-ru pull request #1256
Opened 2021-07-23 19:54 UTC by kazenosaga

Changes translated
num_Cases updated

2021-07-24 11:06 UTC, KorDum commented on Core/Keyed/Misc.xml
> +  <ToCommaListOr>или</ToCommaListOr>
```xml
<ToCommaListOr>{0} или {1}</ToCommaListOr>
```
Кажется, пропущено

2021-07-24 11:51 UTC, kazenosaga commented on Core/Keyed/Misc.xml
> +  <ToCommaListOr>или</ToCommaListOr>
Точно, спасибо.
Исправлено.

2021-07-25 19:37 UTC, Elevator89 requested changes

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
>    <CannotOrderNonControlled>Нельзя отдавать приказы неконтролируемым юнитам.</CannotOrderNonControlled>
```suggestion
  <CannotOrderNonControlled>Нельзя отдавать приказы неконтролируемым персонажам.</CannotOrderNonControlled>
```

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
> +  <ReportHaulingTo>несёт {THING_label} на {DESTINATION}</ReportHaulingTo><!-- Тут везде точки в конце, это ничего, что в переводе их нет?-->
Специально точки убраны, ибо эти строки не являются предложениями в составе текста. Это скорее статусные сроки.
```suggestion
  <ReportHaulingTo>несёт {THING_label} на {DESTINATION}</ReportHaulingTo>
```

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
>    <ReportHaulingToGrave>хоронит {THING_label} в {DESTINATION}.</ReportHaulingToGrave>
И вот тут ещё надо убрать
```suggestion
  <ReportHaulingToGrave>хоронит {THING_label} в {DESTINATION}</ReportHaulingToGrave>
```

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
> +  <CutGerund>Рубить</CutGerund>
Регистр
```suggestion
  <!-- EN: harvesting -->
  <HarvestGerund>собирать</HarvestGerund>
  <!-- EN: cutting -->
  <CutGerund>рубить</CutGerund>
```

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
> +  <MustPlaceUnderThickRoof>Следует размещать под плотной крышей.</MustPlaceUnderThickRoof>
Кроме толщи горной породы у нас нет толстых крыш.
```suggestion
  <MustPlaceUnderThickRoof>Следует размещать под толщей горной породой.</MustPlaceUnderThickRoof>
```

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
> +  <WarningBuildingCausesHostility>Внимание! Фракция {FACTION_name} будет рассержена, если вы здесь что-то построите! </WarningBuildingCausesHostility>
Лишний пробел
```suggestion
  <WarningBuildingCausesHostility>Внимание! Фракция {FACTION_name} будет рассержена, если вы здесь что-то построите!</WarningBuildingCausesHostility>
```

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
> +  <QualityFactorTooltipUncertain>Это условие может быть выполнено, если всё пройдет хорошо.\n\nЕсли условие будет выполнено, будет применено вознаграждение за успешный ритуал.</QualityFactorTooltipUn
```suggestion
  <QualityFactorTooltipUncertain>Это условие может быть выполнено, если всё пройдет хорошо.\n\nЕсли условие будет выполнено, качество ритуала возрастёт.</QualityFactorTooltipUncertain>
```

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
> +  <QualityFactorTooltipNotFulfilled>Условие не выполнено.\n\nВознаграждение за успешный ритуал не будет применено.</QualityFactorTooltipNotFulfilled>
```suggestion
  <QualityFactorTooltipNotFulfilled>Условие не выполнено.\n\nКачество ритуала не возрастёт.</QualityFactorTooltipNotFulfilled>
```

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
> +  <RitualQualityLowWarning>Совокупное качество ритуала {0} составляет {1}. Если вы продолжите, то, скорее всего, это приведет к негативным последствиям для поселения. Вы уверены?</RitualQualityLowWar
```suggestion
  <RitualQualityLowWarning>Совокупное качество ритуала {0} составляет {1}. Если вы продолжите, то, скорее всего, это приведет к негативным последствиям для поселения.\n\nВы уверены?</RitualQualityLowWarning>
```

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
> +  <BeginRitualFor>Начать {0} для {1} --> </BeginRitualFor>
```suggestion
  <BeginRitualFor>Начать {0} для {1}</BeginRitualFor>
```

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
> +  <RitualOutcomeLabelAnyOfThese>Любое из перечисленного:</RitualOutcomeLabelAnyOfThese>
Двоеточие подставляет игра
```suggestion
  <RitualOutcomeLabelAnyOfThese>Любое из перечисленного</RitualOutcomeLabelAnyOfThese>
```

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
> +
Надо удалять UNUSED-строки

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/ScenParts.xml
> +  <ScenPart_SetNeed>{0_numCase ? : имеет : имеют : имеют) {1} шанс получить параметр «{2}» в диапазоне от {3} до {4}.</ScenPart_SetNeed>
Вместо {0} подставится значение по ключу PawnGenerationContext_All, PawnGenerationContext_PlayerStarter или PawnGenerationContext_NonPlayer. Это не число, чтобы использовать подсимвол numCase
```suggestion
  <ScenPart_SetNeed>{0} имеют {1} шанс получить параметр «{2}» в диапазоне от {3} до {4}.</ScenPart_SetNeed>
```

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/ScenParts.xml
> +  <ScenPart_PawnsHaveTrait>{0_numCase ? : имеет : имеют : имеют) имеют {1} шанс начать с чертой: «{2}»</ScenPart_PawnsHaveTrait>
```suggestion
  <ScenPart_PawnsHaveTrait>{0} имеют {1} шанс начать с чертой: «{2}»</ScenPart_PawnsHaveTrait>
```

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/ScenParts.xml
> +  <ScenPart_PawnsAreNaked>{0_numCase ? : начинает : начинают : начинают) без одежды с вероятностью {1}</ScenPart_PawnsAreNaked>
```suggestion
  <ScenPart_PawnsAreNaked>{0} начинают без одежды с вероятностью {1}</ScenPart_PawnsAreNaked>
```

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/ScenParts.xml
> +  <ScenPart_StartingPawnAgeMin>Вашим людям будет как минимум {0_numCase ? : год : года : лет).</ScenPart_StartingPawnAgeMin>
Зачем было это менять?
```suggestion
  <ScenPart_StartingPawnAgeMin>Вашим людям будет как минимум {0_numCase ? год : года : лет}.</ScenPart_StartingPawnAgeMin>
```

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/ScenParts.xml
> +  <ScenPart_StartingPawnAgeMax>Вашим людям будет не более {0_numCase ? : год : года : лет).</ScenPart_StartingPawnAgeMax>
Зачем было это менять, да ещё и с ошибками?
```suggestion
  <ScenPart_StartingPawnAgeMax>Вашим людям будет не более {0_numCase ? года : лет : лет}.</ScenPart_StartingPawnAgeMax>
```

2021-07-25 19:37 UTC, Elevator89 commented on Core/Keyed/ScenParts.xml
> +  <ScenPart_StartingPawnAgeRange>Вашим людям будет от {0} до {1q_numCase ? : год : года : лет).</ScenPart_StartingPawnAgeRange>
```suggestion
  <ScenPart_StartingPawnAgeRange>Вашим людям будет от {0} до {1_numCase ? года : лет : лет}.</ScenPart_StartingPawnAgeRange>
```

2021-07-26 09:49 UTC, kazenosaga commented on Core/Keyed/Misc_Gameplay.xml
> +  <RopedToSpot>Отводится к точке.</RopedToSpot>
Видел только Roped by, когда колонист тащит животное в загон.
Надо искать в коде, на самом деле.

2021-07-26 09:52 UTC, kazenosaga commented on Core/Keyed/Misc_Gameplay.xml
>    <CannotOrderNonControlled>Нельзя отдавать приказы неконтролируемым юнитам.</CannotOrderNonControlled>
Нельзя отдавать приказы персонажам, которые не находятся под вашим управлением

Потому что неконтролируемый звучит как буйный.

2021-07-26 10:29 UTC, kazenosaga commented on Core/Keyed/ScenParts.xml
> +  <ScenPart_StartingPawnAgeMin>Вашим людям будет как минимум {0_numCase ? : год : года : лет).</ScenPart_StartingPawnAgeMin>
Заигрался с автозаменой, косяк

2021-07-26 21:36 UTC, kamadz commented on Core/Keyed/Misc_Gameplay.xml
> +  <ExecuteColonist>Казнить виновного поселенца\n\nЕсли включено, этот человек будет казнён надзирателем.</ExecuteColonist> <!-- text_doto -->
```suggestion
  <ExecuteColonist>Казнить виновного поселенца\n\nЕсли выбрано, этот персонаж будет казнён надзирателем.</ExecuteColonist> <!-- text_doto -->
```

2021-07-26 21:43 UTC, kamadz commented on Core/Keyed/Misc_Gameplay.xml
> +  <RideableAnimalTip>Это ездовое животное. Таких животных можно оседлать в караване, увеличивая скорость его передвижения. Караванщики будут выбирать для этого самых быстрых животных.</RideableAnimal
```suggestion
  <RideableAnimalTip>Это ездовое животное.  Караванщики будут выбирать для верховой езды самых быстрых животных, чтобы максимально ускорить движение каравана.</RideableAnimalTip>
```

2021-07-26 21:45 UTC, kamadz commented on Core/Keyed/Misc_Gameplay.xml
> +  <NaturalGoodwillDescription>Базовая репутация фракции зависит от её самосознания и верований. Если текущая репутация значительно отличается от базовой репутации, то она будет постепенно уменьшаться
```suggestion
  <NaturalGoodwillDescription>Базовая репутация фракции зависит от принятых в ней убеждений и принципов. Если текущая репутация значительно отличается от базовой репутации, то она будет постепенно уменьшаться или увеличиваться в её сторону.\n\nПока текущая репутация значительно отличается от базовой, эффективность любых действий, влияющих на репутацию, составляет {0}.</NaturalGoodwillDescription>
```

2021-07-26 21:47 UTC, kamadz commented on Core/Keyed/Misc_Gameplay.xml
> +  <UnpennedTooltip>Чтобы создать загон для животных, установите метку загона внутри огороженной области. Животноводы отведут животных в подходящие загоны. Загон может быть огорожен оградой и баррикад
Повторение корней "огорожен" и "оградой"
```suggestion
  <UnpennedTooltip>Чтобы создать загон для животных, установите метку загона внутри огороженной области. Животноводы отведут животных в подходящие загоны. Загон может быть обнесён оградой и баррикадой, а также стенами и дверьми.</UnpennedTooltip>
```

2021-07-26 21:47 UTC, kamadz commented on Core/Keyed/Misc_Gameplay.xml
> +  <RopedToThing>Привязяно к</RopedToThing>
```suggestion
  <RopedToThing>На привязи к</RopedToThing>
```

2021-07-26 21:47 UTC, kamadz commented on Core/Keyed/Misc_Gameplay.xml
> +  <RopedToSpot>Привязано к точке.</RopedToSpot>
```suggestion
  <RopedToSpot>На привязи к точке.</RopedToSpot>
```

2021-07-26 21:48 UTC, kamadz commented on Core/Keyed/Misc_Gameplay.xml
> +  <ReportHaulingToGrave>хоронит {THING_label} в {DESTINATION}</ReportHaulingToGrave>
в оригинале стоит точка

2021-07-26 21:50 UTC, kamadz commented on Core/Keyed/Misc_Gameplay.xml
> +  <PlantResting>Спит</PlantResting> <!-- Меня беспокоит, что деревья и кукуруза "спят", но пока варианта лучше не придумаю. -->
Растения тоже "спят". 
https://www.booksite.ru/fulltext/1/001/008/104/504.htm#:~:text=«Сон»%20растений%2C,обусловленным%20сменой%20дня%20и%20ночи.

2021-07-26 21:51 UTC, kamadz commented on Core/Keyed/Misc_Gameplay.xml
> +  <CannotPlaceAdjacentSameDef>Нельяз разместить рядом с другой постройкой того же типа.</CannotPlaceAdjacentSameDef>
```suggestion
  <CannotPlaceAdjacentSameDef>Нельзя разместить рядом с другой постройкой того же типа.</CannotPlaceAdjacentSameDef>
```

2021-07-26 21:52 UTC, kamadz commented on Core/Keyed/Misc_Gameplay.xml
> +  <RitualRoleRequiresSocialRole>С этим лучше всего справится поселенец с ролью {0}.\n\nЕсли выбрать поселенца без этой роли, то вы не сможете получить следующие бонусы</RitualRoleRequiresSocialRole>
```suggestion
  <RitualRoleRequiresSocialRole>С этим лучше всего справится поселенец с ролью {0}.\n\nЕсли выбрать поселенца без этой роли, то вы не сможете получить следующие бонусы:</RitualRoleRequiresSocialRole>
```

2021-07-26 21:53 UTC, kamadz commented on Core/Keyed/Misc_Gameplay.xml
> +  <RitualQualityLowWarning>Совокупное качество ритуала {0} составляет {1}. Если вы продолжите, то, скорее всего, это приведет к негативным последствиям для поселения.\n\nВы уверены?</RitualQualityLow
```suggestion
  <RitualQualityLowWarning>Совокупное качество ритуала {0} составляет {1}. Если вы продолжите, то это, скорее всего, приведет к негативным последствиям для поселения.\n\nВы уверены?</RitualQualityLowWarning>
```

2021-07-26 21:54 UTC, kamadz requested changes
.

2021-07-26 22:25 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
> +  <ReportHaulingToGrave>хоронит {THING_label} в {DESTINATION}</ReportHaulingToGrave>
Да. Но мы сознательно отказались от точек в таких репортах. Ибо выглядит криво: это статус, а не предложение в тексте

2021-07-26 22:25 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
> +  <PlantResting>Спит</PlantResting> <!-- Меня беспокоит, что деревья и кукуруза "спят", но пока варианта лучше не придумаю. -->
```suggestion
  <PlantResting>Спит</PlantResting>
```

2021-07-26 22:25 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
> +  <RitualRoleRequiresSocialRole>С этим лучше всего справится поселенец с ролью {0}.\n\nЕсли выбрать поселенца без этой роли, то вы не сможете получить следующие бонусы</RitualRoleRequiresSocialRole>
Игра сама подставляет двоеточие

2021-07-26 22:25 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
> +  <ExecuteColonist>Казнить виновного поселенца\n\nЕсли включено, этот человек будет казнён надзирателем.</ExecuteColonist> <!-- text_doto -->
Чем стало лучше?

2021-07-26 22:26 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
> +  <RopedByPawn>На верёвке у</RopedByPawn>
```suggestion
  <RopedByPawn>На привязи у</RopedByPawn>
```

2021-07-26 22:27 UTC, Elevator89 commented on Core/Keyed/ScenParts.xml
> +  <ScenPart_SetNeed>{0} имеют шанс получить параметр «{2}» в диапазоне от {3} до {4}.</ScenPart_SetNeed>
```suggestion
  <ScenPart_SetNeed>{0} имеют {1} шанс получить параметр «{2}» в диапазоне от {3} до {4}.</ScenPart_SetNeed>
```

2021-07-26 22:31 UTC, Elevator89 commented on Core/Keyed/ScenParts.xml
> +  <ScenPart_PawnsAreNaked>{0} без одежды с вероятностью {1}</ScenPart_PawnsAreNaked>
```suggestion
  <ScenPart_PawnsAreNaked>{0} начинают без одежды с вероятностью {1}</ScenPart_PawnsAreNaked>
```

2021-07-26 22:53 UTC, kamadz commented on Core/Keyed/Misc_Gameplay.xml
> +  <ExecuteColonist>Казнить виновного поселенца\n\nЕсли включено, этот человек будет казнён надзирателем.</ExecuteColonist> <!-- text_doto -->
Приведение к другим строчкам из соседнего реквеста

2021-07-27 21:51 UTC, Elevator89 commented on Core/Keyed/Misc_Gameplay.xml
> +  <ExecuteColonist>Казнить виновного поселенца\n\nЕсли включено, этот человек будет казнён надзирателем.</ExecuteColonist> <!-- text_doto -->
Тогда стоит переделать соседний реквест. "Toggle on" - это не совсем "выбрать", это именно "включить". Да и между "казнить человека" и "казнить персонажа" первое звучит лучше, ибо лучше погружает в игру.

2021-07-29 22:11 UTC, merged