3056 Royalty/DefInjected-3
Ludeon/RimWorld-ru pull request #1257
Opened 2021-07-23 20:18 UTC by kamadz

Close #1220  Translate Royalty/DefInjected-3

2021-07-23 20:19 UTC, kamadz commented on Royalty/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <BestowingCeremony.outcomeChances.2.label>почётно</BestowingCeremony.outcomeChances.2.label>
нужно на что-то поменять, потому что по смыслу не подходит, как и "торжественно"
у меня на этом моменте сломался моск, предложите что-нибудь

2021-07-24 11:23 UTC, kazenosaga commented on Royalty/DefInjected/RitualAttachableOutcomeEffectDef/Ritual_AttachableOutcomes_Universal.xml
> +  <RechargePsyfocus.label>перезарядить пси-концентрацию</RechargePsyfocus.label>
восстановить пси-концентрацию

2021-07-24 11:23 UTC, kazenosaga commented on Royalty/DefInjected/RitualAttachableOutcomeEffectDef/Ritual_AttachableOutcomes_Universal.xml
> +  <RechargePsyfocus.effectDesc>поднять пси-концентрацию всех участников на максимум.</RechargePsyfocus.effectDesc>
полностью восстановить пси-концентрацию всех участников

2021-07-24 11:24 UTC, kazenosaga commented on Royalty/DefInjected/RitualAttachableOutcomeEffectDef/Ritual_AttachableOutcomes_Universal.xml
> +  <RechargePsyfocus.letterInfoText>Пси-концентрация всех участников была поднята на максимум.</RechargePsyfocus.letterInfoText>
Пси-концентрация всех участников была полностью восстановлена.

2021-07-24 11:34 UTC, kazenosaga commented on Royalty/DefInjected/RitualBehaviorDef/Ritual_Behaviors.xml
> +  <ThroneSpeech.letterText>{ORGANIZER_labelShort} произносит тронную речь.\n\nЕсли всё пройдёт гладко, речь вдохновит слушателей, а оратор укрепит свой авторитет. Если нет — она принесёт только вред.
**social** damage
Дословно перевести непросто, можно описательно: "огорчит участников", "разочарует слушателей" и т.п.

2021-07-24 11:40 UTC, kazenosaga commented on Royalty/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <BestowingCeremony.outcomeChances.2.label>почётно</BestowingCeremony.outcomeChances.2.label>
Может, "Величественно"? Хотя "Торжественно" тоже ничего, как по мне.
Есть еще смешное слово "Пышно", но оно очень смешное.

2021-07-24 11:45 UTC, kazenosaga commented on Royalty/DefInjected/RoyalTitleDef/RoyalTitles_Empire.xml
> +  <Acolyte.description>Аколит — это самая первая ступень имперской знати. Обладатели данного титула занимают широкий спектр должностей. Некоторые аколиты — всего лишь студенты, обучающиеся государств
"отправка аколита ... может восприниматься, как оскорбление"
Обстоятельство образа действия, запятая не нужна

2021-07-25 13:25 UTC, kamadz commented on Royalty/DefInjected/RitualAttachableOutcomeEffectDef/Ritual_AttachableOutcomes_Universal.xml
> +  <RechargePsyfocus.label>перезарядить пси-концентрацию</RechargePsyfocus.label>
```suggestion
  <RechargePsyfocus.label>восстановить пси-концентрацию</RechargePsyfocus.label>
```

2021-07-25 13:25 UTC, kamadz commented on Royalty/DefInjected/RitualAttachableOutcomeEffectDef/Ritual_AttachableOutcomes_Universal.xml
> +  <RechargePsyfocus.effectDesc>поднять пси-концентрацию всех участников на максимум.</RechargePsyfocus.effectDesc>
```suggestion
  <RechargePsyfocus.effectDesc>полностью восстановить пси-концентрацию всех участников.</RechargePsyfocus.effectDesc>
```

2021-07-25 13:26 UTC, kamadz commented on Royalty/DefInjected/RitualAttachableOutcomeEffectDef/Ritual_AttachableOutcomes_Universal.xml
> +  <RechargePsyfocus.letterInfoText>Пси-концентрация всех участников была поднята на максимум.</RechargePsyfocus.letterInfoText>
```suggestion
  <RechargePsyfocus.letterInfoText>Пси-концентрация всех участников была полностью восстановлена.</RechargePsyfocus.letterInfoText>
```

2021-07-25 13:28 UTC, kamadz commented on Royalty/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <BestowingCeremony.outcomeChances.2.label>почётно</BestowingCeremony.outcomeChances.2.label>
Торжественно и почётно не являются категориями качества

2021-07-25 13:29 UTC, kamadz commented on Royalty/DefInjected/RoyalTitleDef/RoyalTitles_Empire.xml
> +  <Acolyte.description>Аколит — это самая первая ступень имперской знати. Обладатели данного титула занимают широкий спектр должностей. Некоторые аколиты — всего лишь студенты, обучающиеся государств
```suggestion
  <Acolyte.description>Аколит — это самая первая ступень имперской знати. Обладатели данного титула занимают широкий спектр должностей. Некоторые аколиты — всего лишь студенты, обучающиеся государственному управлению, командованию военными подразделениями или использованию пси-воздействий в специализированных учебных заведениях. Другие — выходцы из богатых семей, которые могут располагать городским имением или поместьем.\n\nВ военное время аколит может руководить взводом бойцов, небольшим фрегатом или служить своему господину как специалист или советник.\n\nНизкое знатное положение делает аколита парадоксально куда менее полезным с дипломатической точки зрения, чем йомена. В то время, как йомен воспринимается сугубо как представитель своего господина, отправка аколита на переговоры сама по себе может восприниматься как оскорбление.</Acolyte.description>

```

2021-07-25 13:51 UTC, Elevator89 requested changes

2021-07-25 13:51 UTC, Elevator89 commented on Royalty/DefInjected/RulePackDef/Faction_Empire.xml
> +    <li>r_name(p=3)->[ImperialNameFirstMale] [ImperialNameLast]</li>
Не порти правило. ImperialNameLastMale - у нас вполне себе есть. А вот ImperialNameLast - нет
```suggestion
    <li>r_name(p=3)->[ImperialNameFirstMale] [ImperialNameLastMale]</li>

```

2021-07-25 13:51 UTC, Elevator89 commented on Royalty/DefInjected/RulePackDef/Faction_Empire.xml
> +    <li>r_name(p=3)->[ImperialNameFirstFemale] [ImperialNameLast]</li>
Аналогично. Надо вернуть правило, как было
```suggestion
    <li>r_name(p=3)->[ImperialNameFirstFemale] [ImperialNameLastFemale]</li>

```

2021-07-25 13:51 UTC, Elevator89 commented on Royalty/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <BestowingCeremony.outcomeChances.2.label>почётно</BestowingCeremony.outcomeChances.2.label>
"Превосходно"? 
Пусть и не совсем, как в оригинале, но по смыслу и контексту подходит лучше.
Честно говоря, я не понимаю, что в оригинале делает "Honorable" среди остальных категорий

2021-07-25 13:51 UTC, Elevator89 commented on Royalty/DefInjected/RitualBehaviorDef/Ritual_Behaviors.xml
> +  <ThroneSpeech.letterText>{ORGANIZER_labelShort} произносит тронную речь.\n\nЕсли всё пройдёт гладко, речь вдохновит слушателей, а оратор укрепит свой авторитет. Если нет — она принесёт только вред.
Надо в нескольких местах сразу менять. Лениво )

2021-07-25 13:54 UTC, kamadz commented on Royalty/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <BestowingCeremony.outcomeChances.2.label>почётно</BestowingCeremony.outcomeChances.2.label>
Подходит

2021-07-25 19:42 UTC, Elevator89 commented on Royalty/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <BestowingCeremony.outcomeChances.2.label>почётно</BestowingCeremony.outcomeChances.2.label>
```suggestion
  <BestowingCeremony.outcomeChances.2.label>превосходно</BestowingCeremony.outcomeChances.2.label>
```

2021-07-25 19:43 UTC, Elevator89 commented on Royalty/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <BestowingCeremony.outcomeChances.2.label>превосходно</BestowingCeremony.outcomeChances.2.label>
```suggestion
  <BestowingCeremony.outcomeChances.2.label>достойно</BestowingCeremony.outcomeChances.2.label>
```

2021-07-26 22:34 UTC, merged