1245 ideology keyed 1
Ludeon/RimWorld-ru pull request #1262
Opened 2021-07-25 09:45 UTC by Kansaiweeb

Translation update

2021-07-25 10:26 UTC, KorDum commented on Ideology/Keyed/Alerts.xml
> +  <SlavesUnsuppressedDesc>Уровень усмирения {0_nameDef} низок. Велик шанс, что {0_pronoun} начнет бунтовать. Убедитесь что колонист назначен надзирателем. Надзиратели будут периодически повышать уров
> Убедитесь что колонист

Пропущена запятая

2021-07-25 10:26 UTC, KorDum commented on Ideology/Keyed/Alerts.xml
> +  <SlavesUnsuppressedLabel>Раб не усмирён</SlavesUnsuppressedLabel>
Такое ощущение, что слово "усмирение" хоть и подходит по семантике, но не очень благозвучно выглядит в текстах. Может быть "подавление"? Оно ведь также относится к слову "will"

2021-07-25 10:26 UTC, KorDum commented on Ideology/Keyed/Alerts.xml
> +  <SlavesUnattendedDesc>Рабы оставлены без надзора. Рабы оставленные без надзора скорее всего взбунтуются в ближайшие дни.</SlavesUnattendedDesc>
Проверьте весь текст на запятые, очень много пропущенных.

2021-07-25 10:26 UTC, KorDum commented on Ideology/Keyed/Alerts.xml
> +  <RitualExpected>{0} expected</RitualExpected>
Не переведено

2021-07-25 10:26 UTC, KorDum commented on Ideology/Keyed/Alerts.xml
> +  <RitualUnfilledRoles>{0}</RitualUnfilledRoles>
Тут куда-то делся весь перевод

2021-07-25 10:26 UTC, KorDum commented on Ideology/Keyed/Alerts.xml
> +  <IdeoBuildingRoomRequirementsDesc>dignify {0}</IdeoBuildingRoomRequirementsDesc>
И тут перевода нет. Проверьте весь текст, пожалуйста.

2021-07-25 10:29 UTC, KorDum commented on Ideology/Keyed/Alerts.xml
> +  <AlertRoyalTitleNoVeneratedAnimalMeat>Вера {PAWN_nameDef} в {IDEO_name} запрещает ему есть мясо {ANIMALS}.</AlertRoyalTitleNoVeneratedAnimalMeat>
> запрещает ему

Полагаю, здесь в переводе пол поселенца прибился гвоздями

2021-07-25 10:33 UTC, KorDum commented on Ideology/Keyed/Alerts.xml
> +  <SlavesUnsuppressedLabel>Раб не усмирён</SlavesUnsuppressedLabel>
Может быть тут было бы лучше "Воля раба не подавлена" или нечто подобное.

2021-07-25 10:35 UTC, KorDum commented on Ideology/Keyed/Alerts.xml
> +  <SlavesUnsuppressedLabel>Раб не усмирён</SlavesUnsuppressedLabel>
Насколько могу помнить, этот текст появляется в ситуации, когда полоска подавления воли раба < 30%. При этом сам раб не буйствует, его не нужно усмирять.

2021-07-25 17:49 UTC, kamadz commented on Ideology/Keyed/Alerts.xml
> +  <AlertNoRecentSlaughterDescPost>TODO</AlertNoRecentSlaughterDescPost>
не переведено

2021-07-25 17:49 UTC, kamadz commented on Ideology/Keyed/Alerts.xml
> +  <AlertConnectedPawnNotAssignedToPlantCuttingDesc>TODO</AlertConnectedPawnNotAssignedToPlantCuttingDesc>
не переведено

2021-07-26 06:13 UTC, Kansaiweeb commented on Ideology/Keyed/Alerts.xml
> +  <SlavesUnsuppressedLabel>Раб не усмирён</SlavesUnsuppressedLabel>
Сменил на подавление, но я бы еще подумал на вариантами.

2021-07-26 06:14 UTC, Kansaiweeb commented on Ideology/Keyed/Alerts.xml
> +  <SlavesUnattendedDesc>Рабы оставлены без надзора. Рабы оставленные без надзора скорее всего взбунтуются в ближайшие дни.</SlavesUnattendedDesc>
Да, заметил, почти все причастные/деепричастные без пунктуации. Скоро исправлю

2021-07-26 06:16 UTC, Kansaiweeb commented on Ideology/Keyed/Alerts.xml
> +  <AlertRoyalTitleNoVeneratedAnimalMeat>Вера {PAWN_nameDef} в {IDEO_name} запрещает ему есть мясо {ANIMALS}.</AlertRoyalTitleNoVeneratedAnimalMeat>
Не переводил раньше римворлд, забыл про наличие специальных команд. Исправил

2021-07-26 06:25 UTC, KorDum commented on Ideology/Keyed/Alerts.xml
> +  <AlertNoRecentSlaughterDescPost>Игнорирование требования приведет к недовольству:</AlertNoRecentSlaughterDescPost>
В оригинале отсутствует двоеточие, оно точно здесь нужно для более красивого формирования фразы в игре?

2021-07-26 06:25 UTC, KorDum commented on Ideology/Keyed/Alerts.xml
> +  <AlertNoRecentSlaughterDesc>Следующие идеолигии требуют регулярного убоя животных</AlertNoRecentSlaughterDesc>
Тут умышленно опущено первое предложение? В ней ведь содержится причина события.

2021-07-26 06:25 UTC, KorDum commented on Ideology/Keyed/Alerts.xml
> +  <AlertNoRecentSlaughter>Убой животных</AlertNoRecentSlaughter>
Совсем потерялся смысл оригинала

2021-07-26 07:08 UTC, Kansaiweeb commented on Ideology/Keyed/Alerts.xml
> +  <AlertNoRecentSlaughterDescPost>Игнорирование требования приведет к недовольству:</AlertNoRecentSlaughterDescPost>
После таких слов следует, обычно, список колонистов и я подумал с двоеточием будет лучше смотреться

2021-07-26 07:35 UTC, KorDum commented on Ideology/Keyed/Alerts.xml
> +  <AlertNoRecentSlaughterDescPost>Игнорирование требования приведет к недовольству:</AlertNoRecentSlaughterDescPost>
Думаю, лучше всегда проверять в игре, так как сама игра может вставлять двоеточение

2021-07-26 21:34 UTC, kamadz requested changes

2021-07-26 21:34 UTC, kamadz commented on Ideology/Keyed/Alerts.xml
> +  <AlertConnectedPawnNotAssignedToPlantCuttingDesc>Древа Гауранлен ожидают остригания, но их соединители не назначены садоводами.\n\n Вам следует назначить садоводами следующих поселенцев</AlertConne
```suggestion
  <AlertConnectedPawnNotAssignedToPlantCuttingDesc>Древа Гауранлен ожидают остригания, но их соединители не назначены садоводами.\n\n Вам следует назначить садоводами следующих поселенцев:</AlertConnectedPawnNotAssignedToPlantCuttingDesc>
```

2021-07-26 21:34 UTC, kamadz commented on Ideology/Keyed/Alerts.xml
> +  <AlertInfestationArrivingDesc>Гигантские насекомые почувствовали ваше присутствие и выкапываются из земли для атаки. </AlertInfestationArrivingDesc>
```suggestion
  <AlertInfestationArrivingDesc>Гигантские насекомые почувствовали ваше присутствие и выкапываются из под земли для атаки. </AlertInfestationArrivingDesc>
```

2021-07-26 21:34 UTC, kamadz commented on Ideology/Keyed/Alerts.xml
> +  <AlertHostilesWakingUpDesc>Один или более {0_pawnsPlural} пробуждаются.\n\n В случае обнаружения готовьтесь к битве.</AlertHostilesWakingUpDesc>
```suggestion
  <AlertHostilesWakingUpDesc>Один или более {0_pawnsPlural} пробуждаются.\n\nОни нападут, если найдут вас.</AlertHostilesWakingUpDesc>
```

2021-07-26 21:34 UTC, kamadz commented on Ideology/Keyed/Alerts.xml
> +  <AlertCasketOpeningDesc>Неизвестная угроза дремлющая в саркофагах криптосна скоро пробудится.</AlertCasketOpeningDesc>
```suggestion
  <AlertCasketOpeningDesc>Неизвестная угроза, дремлющая в саркофагах криптосна, скоро пробудится.</AlertCasketOpeningDesc>
```

2021-07-27 00:17 UTC, Elevator89 requested changes
Очень слабый реквест. Быстрее было самому сделать, чем находить все ошибки, совершённые по невнимательности!

2021-07-27 00:17 UTC, Elevator89 commented on Ideology/Keyed/Alerts.xml
> +  <NeedSlaveBedsDesc>Недостаточно кроватей для рабов. Постройте больше кроватей или смените назначение кровати колониста или пленника. В случае недостатка ресурсов постройте спальное место, его постр
У нас нет колонистов!
А про спальные места - копия уже существующего и переведённого текста
```suggestion
  <NeedSlaveBedsDesc>Недостаточно кроватей для рабов.\n\nПостройте больше кроватей или смените режим кроватей, назначенных поселенцам или пленникам.\n\nЕсли у вас не хватает ресурсов, вы можете просто обозначить для них спальные места.</NeedSlaveBedsDesc>
```

2021-07-27 00:17 UTC, Elevator89 commented on Ideology/Keyed/Alerts.xml
> +  <SlavesUnsuppressedLabel>Воля раба не подавлена</SlavesUnsuppressedLabel>
Раб подавлен - это у него депрессия, что ли?
Рабу или **подавляют волю** или **усмиряют** его.
```suggestion
  <SlavesUnsuppressedLabel>Раб не усмирён</SlavesUnsuppressedLabel>
```

2021-07-27 00:17 UTC, Elevator89 commented on Ideology/Keyed/Alerts.xml
> +  <SlavesUnsuppressedDesc>Воля раба {0_nameDef} недостаточно подавлена. Велик шанс, что {0_pronoun} начнет бунтовать. Убедитесь, что колонист назначен надзирателем. Надзиратели будут периодически пов
```suggestion
  <SlavesUnsuppressedDesc>{0_gender ? Раб : Рабыня} {0_nameDef} недостаточно хорошо {0_gender ? усмирён : усмирена}. Велик шанс, что {0_pronoun} начнет бунтовать. Убедитесь, что среди поселенцев есть надзиратель. Надзиратели будут периодически усмирять рабов для предотвращения восстаний.</SlavesUnsuppressedDesc>
```

2021-07-27 00:17 UTC, Elevator89 commented on Ideology/Keyed/Alerts.xml
> +  <SlavesUnattendedDesc>Рабы оставлены без надзора. Рабы, оставленные без надзора, скорее всего взбунтуются в ближайшие дни.</SlavesUnattendedDesc>
Повторение
```suggestion
  <SlavesUnattendedDesc>За некоторыми рабами не следит ни один трудоспособный поселенец. Рабы, оставленные без надзора, скорее всего взбунтуются в ближайшие дни или часы.</SlavesUnattendedDesc>
```

2021-07-27 00:17 UTC, Elevator89 commented on Ideology/Keyed/Alerts.xml
> +  <RitualObligationDelayEffectDesc>{0} дней:{1} настроения всем {2}</RitualObligationDelayEffectDesc>
```suggestion
  <RitualObligationDelayEffectDesc>{0} дней: {1} настроения всем {2}</RitualObligationDelayEffectDesc>
```

2021-07-27 08:34 UTC, kamadz commented on Ideology/Keyed/Alerts.xml
> +  <SlavesUnsuppressedLabel>Воля раба не подавлена</SlavesUnsuppressedLabel>
Воля - показатель для заключённого. 
Подавленность - показатель для раба. 
Два разных игромеханических термина.

2021-07-27 08:35 UTC, kamadz commented on Ideology/Keyed/Alerts.xml
> +  <SlavesUnsuppressedLabel>Воля раба не подавлена</SlavesUnsuppressedLabel>
Рабов запугивают, чтобы они чувствовали себя подавленно и не бунтовали. Волю заключённых подавляют, чтобы вербовать или обращать в рабство.

2021-07-27 15:41 UTC, kamadz commented on Ideology/Keyed/Alerts.xml
> +  <SlavesUnsuppressedLabel>Воля раба не подавлена</SlavesUnsuppressedLabel>
Можно использовать "Раб не запуган", так как запуганность и подавленность в рамках игры напрямую связаны. Но велосипед придумывать не надо.

2021-07-27 15:43 UTC, kamadz commented on Ideology/Keyed/Alerts.xml
> +  <SlavesUnsuppressedLabel>Воля раба не подавлена</SlavesUnsuppressedLabel>
Не говоря уже о том, что подавленность по семантике связана изначально не с депрессией
https://dic.academic.ru/dic.nsf/ushakov/942202

2021-07-27 21:59 UTC, Elevator89 commented on Ideology/Keyed/Alerts.xml
> +  <SlavesUnsuppressedLabel>Воля раба не подавлена</SlavesUnsuppressedLabel>
По твоей же ссылке
![изображение](https://user-images.githubusercontent.com/21694533/127232429-2e1fda27-9fd7-43c6-98d7-08c60ad5ff6d.png)
Явно не наш случай

2021-07-27 21:59 UTC, Elevator89 commented on Ideology/Keyed/Alerts.xml
> +  <SlavesUnsuppressedLabel>Воля раба не подавлена</SlavesUnsuppressedLabel>
А для заключённого (пленника) у нас есть "психологическое сопротивление"
"Подавленность" как характеристика мне ещё в переводе не попадалась. Можем перевести как посчитаем нужным

2021-07-27 22:09 UTC, kamadz commented on Ideology/Keyed/Alerts.xml
> +  <SlavesUnsuppressedLabel>Воля раба не подавлена</SlavesUnsuppressedLabel>
![image](https://user-images.githubusercontent.com/57110948/127233900-05063313-0b3b-4d8c-9d5a-dba24bd7d7b3.png)

Чуть-чуть ниже.

Подавленность - supression есть в 3-ем реквесте. Более того, я кидал перевод по ней в телегу.

2021-07-28 00:21 UTC, merged