3067 Ideology/Keyed-2
Ludeon/RimWorld-ru pull request #1263
Opened 2021-07-25 14:09 UTC by kamadz

Close #1246 Translate Ideology/Keyed-2

2021-07-25 14:34 UTC, kamadz commented on Ideology/Keyed/Dialogs_Various.xml
> +  <AbilityIdeoConvertBreakdownConversionPower>Влияние обращения {PAWN_labelShort}</AbilityIdeoConvertBreakdownConversionPower>
```suggestion
  <AbilityIdeoConvertBreakdownConversionPower>Эффективность обращения {PAWN_labelShort}</AbilityIdeoConvertBreakdownConversionPower>
```

2021-07-25 14:35 UTC, kamadz commented on Ideology/Keyed/Dialogs_Various.xml
> +  <AbilityIdeoConvertBreakdownConversionPower>Влияние обращения {PAWN_labelShort}</AbilityIdeoConvertBreakdownConversionPower>
Ритуал обращения работает только если уверенность обращаемого достаточно низкая. При этом он может быть успешным и все могут получить бонус к настроению. Хз, баг это или нет, я лично проверял.

2021-07-26 07:59 UTC, KorDum commented on Ideology/Keyed/Dialogs_Various.xml
> +  <AbilityIdeoConvertBreakdownConversionPower>Влияние обращения {PAWN_labelShort}</AbilityIdeoConvertBreakdownConversionPower>
Играю уже несколько дней с этим ритуалом. Насколько я понял, ритуал обращения скидывает то ли 30, то ли 60 процентов от текущего показателя верования. Соответственно, цель может как обратиться в новую, так и остаться с ослабленной своей верой. Поэтому успешно проведенным ритуалом является тот, который смог воздействовать на цель каким-либо образом.

2021-07-26 17:10 UTC, KorDum commented on Ideology/Keyed/Dialogs_Various.xml
> +  <AbilityIdeoConvertBreakdownConversionPower>Влияние обращения {PAWN_labelShort}</AbilityIdeoConvertBreakdownConversionPower>
Проверил. Взял выборочно жителя с 69% его религии и провел ритуал, который снизил ровно на 30 до 39%. Ритуал был успешен, все довольны. При этом житель не получил никакого дебафа к настроению - прикольно.

2021-07-27 22:33 UTC, Elevator89 requested changes

2021-07-27 22:33 UTC, Elevator89 commented on Ideology/Keyed/Dialogs_Various.xml
> +  <ChooseStructureMeme>Выберите структуру</ChooseStructureMeme>
```suggestion
  <!-- EN: Choose at least {0} meme. -->
  <NotEnoughMemes>Выберите как минимум {0} черту.</NotEnoughMemes>
  <!-- EN: Choose at most {0} memes. -->
  <TooManyMemes>Выберите максимум {0} черты.</TooManyMemes>
  <!-- EN: Choose structure. -->
  <ChooseStructureMeme>Выберите структуру.</ChooseStructureMeme>
```

2021-07-27 22:33 UTC, Elevator89 commented on Ideology/Keyed/Dialogs_Various.xml
> +  <ChooseNormalMemesInfo>Выберите {0}-{1} черты, которые сформируют фундамент вашей идеолигии. Некоторые из них влияют на геймплей сильнее, чем другие.</ChooseNormalMemesInfo>
```suggestion
  <ChooseNormalMemesInfo>Выберите {0}-{1_numCase ? черту : черты : черты}, которые сформируют фундамент вашей идеолигии. Некоторые из них влияют на геймплей сильнее, чем другие.</ChooseNormalMemesInfo>
```

2021-07-27 22:33 UTC, Elevator89 commented on Ideology/Keyed/Dialogs_Various.xml
> +  <RoomRequirements>Требования к комнате</RoomRequirements>
Для консистентности с соседним реквестом
```suggestion
  <RoomRequirements>Требования к помещению</RoomRequirements>
```

2021-07-27 22:33 UTC, Elevator89 commented on Ideology/Keyed/Dialogs_Various.xml
> +  <ChooseRoleListWorkTypeRestrictions>{PAWN_labelShort} не будет выполнять следующие виды работ:</ChooseRoleListWorkTypeRestrictions>
```suggestion
  <!-- EN: {PAWN_labelShort} will gain the following abilities -->
  <ChooseRoleListAbilities>{PAWN_labelShort} получит следующие способности</ChooseRoleListAbilities>
  <!-- EN: The {ROLE_label} role requires the following apparel -->
  <ChooseRoleListApparelDemands>Поселенцу с ролью {ROLE_label} необходима следующая одежда</ChooseRoleListApparelDemands>
  <!-- EN: {PAWN_labelShort} will refuse to do these work types -->
  <ChooseRoleListWorkTypeRestrictions>{PAWN_labelShort} не будет выполнять следующие виды работ</ChooseRoleListWorkTypeRestrictions>
```

2021-07-27 22:33 UTC, Elevator89 commented on Ideology/Keyed/Dialogs_Various.xml
> +  <ChooseRoleRequiredWorkTagsDisabled>{PAWN_nameDef} не может заниматься работой, подразумеваемой ролью {ROLE_label}. Если вы назначите {PAWN_objective} эту роль, {PAWN_pronoun}, вероятно, не сможет
```suggestion
  <MemeUnlocksRoles>Разблокированы роли</MemeUnlocksRoles>
  <!-- EN: Unlocked rituals -->
  <MemeUnlocksRituals>Разблокированы ритуалы</MemeUnlocksRituals>
  <!-- EN: WARNING: {PAWN_nameDef} is unable to do work that is required for the role of {ROLE_label}. If you choose to give {PAWN_objective} this role, {PAWN_pronoun} may be unable to use the abilities associated with {ROLE_label}. The missing work types are -->
  <ChooseRoleRequiredWorkTagsDisabled>Внимание: {PAWN_nameDef} не может заниматься работой, подразумеваемой ролью {ROLE_label}. Если вы назначите {PAWN_objective} эту роль, {PAWN_pronoun}, вероятно, не сможет использовать некоторые связанные с ней способности. Недоступные виды работ</ChooseRoleRequiredWorkTagsDisabled>
```

2021-07-27 22:33 UTC, Elevator89 commented on Ideology/Keyed/Dialogs_Various.xml
> +  <AbilityIdeoConvertBreakdownRelic>{RELICCOUNT} реликвий находится на карте</AbilityIdeoConvertBreakdownRelic>
```suggestion
  <AbilityIdeoConvertBreakdownRelic>{RELICCOUNT_numCase ? реликвия находится : реликвии находятся : реликвий находится} на карте</AbilityIdeoConvertBreakdownRelic>
```

2021-07-27 22:33 UTC, Elevator89 commented on Ideology/Keyed/Dialogs_Various.xml
> +  <AbilityCantApplyAlreadyCounselled>{PAWN_labelShort} уже {PAWN_gender ? получал : получала} наставление недавно.</AbilityCantApplyAlreadyCounselled>
Калька с английской грамматики
```suggestion
  <AbilityCantApplyAlreadyCounselled>{PAWN_labelShort} недавно уже {PAWN_gender ? получал : получала} наставление.</AbilityCantApplyAlreadyCounselled>
```

2021-07-27 22:33 UTC, Elevator89 commented on Ideology/Keyed/Dialogs_Various.xml
> +  <NegotiatorWillNotTradeSlaves>Переговорщик не будет продавать людей в рабство</NegotiatorWillNotTradeSlaves>
```suggestion
  <NegotiatorWillNotTradeSlaves>Переговорщик не будет продавать людей в рабство.</NegotiatorWillNotTradeSlaves>
```

2021-07-27 22:33 UTC, Elevator89 commented on Ideology/Keyed/Dialogs_Various.xml
> +  <LastHumanMeat>Последний раз съедена человечина:</LastHumanMeat>
Какая-то беда просто с точками и с двоеточиями
```suggestion
  <LastHumanMeat>Последний раз съедена человечина</LastHumanMeat>
```

2021-07-27 22:33 UTC, Elevator89 commented on Ideology/Keyed/Dialogs_Various.xml
> +  <IdeoMakesBuildingBuildable>Новые строения </IdeoMakesBuildingBuildable>
```suggestion
  <IdeoMakesBuildingBuildable>Новые строения</IdeoMakesBuildingBuildable>
```

2021-07-27 22:33 UTC, Elevator89 commented on Ideology/Keyed/Dialogs_Various.xml
> +  <NoneUsableForPawn>ничто не может быть использовано {PAWN_nameDef}</NoneUsableForPawn>
Судя по коду, это должно быть в окне выбора стиля предмета для конкретного персонажа.
```suggestion
  <NoneUsableForPawn>нет ничего для {PAWN_nameDef}</NoneUsableForPawn> 
```

2021-07-27 22:33 UTC, Elevator89 commented on Ideology/Keyed/Dialogs_Various.xml
> +  <HairAndBeardsDesc>Эти настройки определяют как часто каждый стиль проявляется на последователях этой идеолигии.</HairAndBeardsDesc>
```suggestion
  <HairAndBeardsDesc>Эти настройки определяют, как часто каждый стиль проявляется на последователях этой идеолигии.</HairAndBeardsDesc>
```

2021-07-27 22:33 UTC, Elevator89 commented on Ideology/Keyed/Dialogs_Various.xml
> +  <TattoosDesc>Эти настройки определяют как часто каждая татуировка появляется на последователях этой идеолигии</TattoosDesc>
```suggestion
  <TattoosDesc>Эти настройки определяют, как часто каждая татуировка появляется на последователях этой идеолигии</TattoosDesc>
```

2021-07-27 22:33 UTC, Elevator89 commented on Ideology/Keyed/Dialogs_Various.xml
> +  <ChooseProductionModeInitialDesc>Здесь можно выбрать, какую касту дриад создаст {TREE_label}.\n\nДриады появятся из капсул, растущих у основания дерева. Максимальное число дриад зависит от уровня с
Не надо называть людей персонажами.
```suggestion
  <ChooseProductionModeInitialDesc>Здесь можно выбрать, какую касту дриад создаст {TREE_label}.\n\nДриады появятся из капсул, растущих у основания дерева. Максимальное число дриад зависит от уровня связи между {TREE_definite} и связанным человеком.</ChooseProductionModeInitialDesc>
```

2021-07-31 21:35 UTC, kamadz commented on Ideology/Keyed/Dialogs_Various.xml
> +  <AbilityCantApplyAlreadyCounselled>{PAWN_labelShort} уже {PAWN_gender ? получал : получала} наставление недавно.</AbilityCantApplyAlreadyCounselled>
В русском языке нет жёстки рамок постпозитивности и припозитивности обстоятельств. Не надо вот этих инсинуаций.

2021-07-31 21:36 UTC, kamadz commented on Ideology/Keyed/Dialogs_Various.xml
> +  <ChooseProductionModeInitialDesc>Здесь можно выбрать, какую касту дриад создаст {TREE_label}.\n\nДриады появятся из капсул, растущих у основания дерева. Максимальное число дриад зависит от уровня с
![image](https://user-images.githubusercontent.com/57110948/127752962-7195520a-aaea-4e15-b15f-ee7cb34b1bee.png)

que?

2021-07-31 21:37 UTC, kamadz commented on Ideology/Keyed/Dialogs_Various.xml
> +  <ChooseProductionModeInitialDesc>Здесь можно выбрать, какую касту дриад создаст {TREE_label}.\n\nДриады появятся из капсул, растущих у основания дерева. Максимальное число дриад зависит от уровня с
Я в очередной раз напомню, что было бы неплохо оставлять хоть какое-то окно совместимости с модификациями.

2021-08-01 14:00 UTC, merged