1266-little-missings
Ludeon/RimWorld-ru pull request #1267
Opened 2021-07-25 22:15 UTC by maxqwerty

Close #1266

2021-07-26 07:42 UTC, KorDum commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} специализируется на раскопаках и строительстве спещерных комплексов.</desc>
> спещерных
очепятка

2021-07-26 07:42 UTC, KorDum commented on Core/Backstories/Backstories.xml
> +		<title>строитель пещер</title>
А разве пещеру можно построить? Это ведь полость естественного происхождения. Полагаю, тут имеется в виду застройка пещеры

2021-07-26 07:42 UTC, KorDum commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? зарабатывал : зарабатывала} на жизнь созданием карт тёмных тунелей и практически недоступных расщелин в поисках ценных минералов. {PAWN_gender ? Его : Её} работа
> тунелей

Не совсем уверен, но, кажется, в русском языке есть 2 равнозначных варианта написания этого французского заимствования - "тунНель" и "тонНель"

2021-07-26 07:42 UTC, KorDum commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? имел : имела} неутолимые амбиции, которые продвинули {PAWN_possessive} на высшие уровни венного командования.\n\n{PAWN_pronoun} получает удовольствие от обладани
> венного
опечатка

2021-07-26 07:42 UTC, KorDum commented on Core/Backstories/Backstories.xml
> +		<desc>В своём охотничем отряде {PAWN_nameDef} в основном {PAWN_gender ? занимался : занималась} разделкой животных. {PAWN_pronoun} {PAWN_gender ? стал : стала} мастером ножа, и {PAWN_gender ? спосо
> своём

по регламентам можно использовать букву "ё"?

2021-07-26 07:42 UTC, KorDum commented on Core/Keyed/Misc_Gameplay.xml
> +  <AutoCutNow>Срезать Сейчас</AutoCutNow>
> Сейчас

слово капитализировано

2021-07-26 07:42 UTC, KorDum commented on Core/Keyed/Misc_Gameplay.xml
> +  <HarvestGerund>Собрать</HarvestGerund>
В оригинале с маленькой буквы

2021-07-26 07:42 UTC, KorDum commented on Core/Keyed/Misc_Gameplay.xml
> +  <CutGerund>Срезать</CutGerund>
В оригинале с маленькой буквы

2021-07-26 15:44 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<title>строитель пещер</title>
```suggestion
		<title>строитель пещер</title>
```
```suggestion
		<title>копатель пещер</title>
```

Имеется в виду создание систем пещер и тоннелей.

2021-07-26 17:18 UTC, kamadz requested changes

2021-07-26 17:18 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<titleShort>командующий</titleShort>
```suggestion
		<titleShort>командующий</titleShort>
		<titleShortFemale>командующая</titleShortFemale>
```

2021-07-26 17:18 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? имел : имела} неутолимые амбиции, которые продвинули {PAWN_possessive} на высшие уровни венного командования.\n\n{PAWN_pronoun} получает удовольствие от обладани
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? имел : имела} неутолимые амбиции, которые продвинули {PAWN_possessive} на высшие уровни венного командования.\n\n{PAWN_pronoun}  {PAWN_gender ? получал : получала} удовольствие от возможности причинять смерть и боль как своим врагам, так и собственным солдатам.</desc>
```

2021-07-26 17:18 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>В своём охотничем отряде {PAWN_nameDef} в основном {PAWN_gender ? занимался : занималась} разделкой животных. {PAWN_pronoun} {PAWN_gender ? стал : стала} мастером ножа, и {PAWN_gender ? спосо
нужно
```suggestion
		<desc>В своём охотничьем отряде {PAWN_nameDef} в основном {PAWN_gender ? занимался : занималась} разделкой животных. {PAWN_pronoun} {PAWN_gender ? стал : стала} мастером ножа, и {PAWN_gender ? способен : способна} за короткое время извлечь из туши каждый ценный кусочек.</desc>
```

2021-07-26 17:18 UTC, kamadz commented on Core/Keyed/Misc_Gameplay.xml
> +  <ExecuteColonist>Казнить виновного колониста\n\nЕсли включить, надзиратель приступит к казни этого человека.</ExecuteColonist>
```suggestion
  <ExecuteColonist>Казнить виновного поселенца\n\nЕсли выбрать, надзиратель приступит к казни этого персонажа.</ExecuteColonist>
```

2021-07-26 17:18 UTC, kamadz commented on Core/Keyed/Misc_Gameplay.xml
> +  <MessageColonistMarkedForExecution>{0_labelShort} отмечен для казни. Доступный надзиратель начнёт казнь {0_objective}.</MessageColonistMarkedForExecution>
```suggestion
  <MessageColonistMarkedForExecution>{0_labelShort} приговорён к казни. Свободный надзиратель приступит к казни {0_objective}.</MessageColonistMarkedForExecution>
```

2021-07-26 17:18 UTC, kamadz commented on Core/Keyed/Misc_Gameplay.xml
> +  <AutoCutNow>Срезать Сейчас</AutoCutNow>
```suggestion
  <AutoCutNow>Срезать сейчас</AutoCutNow>
```

2021-07-26 17:18 UTC, kamadz commented on Core/Keyed/Misc_Gameplay.xml
> +  <HarvestGerund>Собрать</HarvestGerund>
```suggestion
  <HarvestGerund>собирает</HarvestGerund>
```

2021-07-26 17:18 UTC, kamadz commented on Core/Keyed/Misc_Gameplay.xml
> +  <CutGerund>Срезать</CutGerund>
```suggestion
  <CutGerund>срезает</CutGerund>
```

2021-07-26 17:45 UTC, maxqwerty commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? имел : имела} неутолимые амбиции, которые продвинули {PAWN_possessive} на высшие уровни венного командования.\n\n{PAWN_pronoun} получает удовольствие от обладани
Может вместо "причинять" всё таки "нести"?

2021-07-26 18:16 UTC, KorDum commented on Core/Backstories/Backstories.xml
> +</BackstoryTranslations>
По регламентам в конце не должно быть пустой строки, см. вики

2021-07-26 18:16 UTC, kazenosaga commented on Core/Backstories/Backstories.xml
> +		<title>строитель пещер</title>
Пещерник.
Подземелец.
Копатель.
Горняк.
Шахтёр, наконец.

2021-07-26 18:19 UTC, kazenosaga commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? зарабатывал : зарабатывала} на жизнь созданием карт тёмных тунелей и практически недоступных расщелин в поисках ценных минералов. {PAWN_gender ? Его : Её} работа
Современные словари дают "Тоннель"

2021-07-28 15:00 UTC, KorDum commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} Неутолимые амбиции помогли {PAWN_nameDef} добиться высокго звания в армии.\n\nСтрадания и смерть восхищяют {PAWN_pronoun}, и неважно, кто умирает: противник или его собственные
> высокго

опечатка

> восхищяют

орфографическая ошибка

2021-07-28 15:02 UTC, KorDum commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} Неутолимые амбиции помогли {PAWN_nameDef} добиться высокго звания в армии.\n\nСтрадания и смерть восхищяют {PAWN_pronoun}, и неважно, кто умирает: противник или его собственные
> солдаты .

пробел лишний

2021-07-28 15:03 UTC, KorDum commented on Core/Backstories/Backstories.xml
> +		<desc>В своём охотничьем отряде {PAWN_nameDef} в основном {PAWN_gender ? занимался : занималась} разделкой животных. {PAWN_pronoun} {PAWN_gender ? стал : стала} мастером ножа, и {PAWN_gender ? спос
>  мастером ножа, и 

Как много ошибок в тексте... Проверьте все внимательно.

2021-07-29 06:26 UTC, maxqwerty commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} Неутолимые амбиции помогли {PAWN_nameDef} добиться высокго звания в армии.\n\nСтрадания и смерть восхищяют {PAWN_pronoun}, и неважно, кто умирает: противник или его собственные
```suggestion
		<desc>{PAWN_nameDef} Неутолимые амбиции помогли {PAWN_nameDef} добиться высокого звания в армии.\n\nСтрадания и смерть восхищают {PAWN_pronoun}, и неважно, кто умирает: противник или его собственные солдаты.</desc>
```

2021-07-29 07:20 UTC, maxqwerty commented on Core/Backstories/Backstories.xml
> +		<desc>В своём охотничьем отряде {PAWN_nameDef} в основном {PAWN_gender ? занимался : занималась} разделкой животных. {PAWN_pronoun} {PAWN_gender ? стал : стала} мастером ножа, и {PAWN_gender ? спос
```suggestion
		<desc>В своём охотничьем отряде {PAWN_nameDef} в основном {PAWN_gender ? занимался : занималась} разделкой животных. {PAWN_pronoun} {PAWN_gender ? стал : стала} мастером в обращении с ножом и {PAWN_gender ? способен : способна} за короткое время извлечь из туши каждый ценный кусочек.</desc>
```

2021-09-13 19:42 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} специализируется на раскопках и создании пещерных комплексов.</desc>
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? специализировался : специализировалась} на раскопках и создании пещерных комплексов.</desc>
```

2021-09-13 19:43 UTC, kamadz commented on Core/Backstories/Backstories.xml
> +		<desc>{PAWN_nameDef} {PAWN_gender ? зарабатывал : зарабатывала} на жизнь созданием карт тёмных тунелей и практически недоступных расщелин в поисках ценных минералов. {PAWN_gender ? Его : Её} работа
```suggestion
		<desc>{PAWN_nameDef} {PAWN_gender ? зарабатывал : зарабатывала} на жизнь созданием карт тёмных тунелей и практически недоступных расщелин в поисках ценных минералов. {PAWN_possessive} работа была опасной, но хорошо оплачивалась.</desc>
```

2021-09-13 19:44 UTC, kamadz requested changes
.

2021-09-14 10:41 UTC, kamadz approved these changes

2021-10-30 19:42 UTC, Elevator89 commented
Реквест устарел. Вместо него вмержен новый, #1340

2021-10-30 19:42 UTC, closed without merging