3067 Ideology/Keyed-3
Ludeon/RimWorld-ru pull request #1268
Opened 2021-07-26 13:50 UTC by kamadz

Close #1247  Translate Ideology/Keyed-3

2021-07-27 08:31 UTC, kamadz commented on Ideology/Keyed/Dialog_StatsReports.xml
> +  <StatsReports_HasRelic>Обладает реликвию</StatsReports_HasRelic>
Ну видно же, что опечатка
```suggestion
  <StatsReports_HasRelic>Обладает реликвией</StatsReports_HasRelic>
```

2021-07-28 13:06 UTC, Kansaiweeb commented on Ideology/Keyed/Dialog_StatsReports.xml
> +  <StatsReport_BlindPsychicSensitivityOffset>Бонус ослепления</StatsReport_BlindPsychicSensitivityOffset>
Бонус ослепления как-то в заблуждение вводит, бонус слепоты не лучше будет?

2021-07-31 23:10 UTC, Elevator89 requested changes

2021-07-31 23:10 UTC, Elevator89 commented on Ideology/Keyed/ITabs.xml
> +  <Suppression>Подавленность</Suppression>
Ладно, пусть будет "подавленность", а не "подавленность воли". Как минимум потому, что так короче.

Где там в соседнем реквесте был мой комментарий про волю?

2021-07-31 23:10 UTC, Elevator89 commented on Ideology/Keyed/ITabs.xml
> +  <SuppressionFallRateDesc>Подавленность уменьшается со временем в зависимости от её текущего уровня:\n\n- {1}+ подавленность: {0} в день\n- {4}-{3} подавленность: {2} в день\n- {6}- подавленность: {
Сделай что-нибудь с этим двеоточиями в конце! Здесь и во всех реквестах.
```suggestion
  <SuppressionFallRateDesc>Подавленность уменьшается со временем в зависимости от её текущего уровня:\n\n- {1}+ подавленность: {0} в день\n- {4}-{3} подавленность: {2} в день\n- {6}- подавленность: {5} в день\n\nОдежда и запугивание также влияют на темп уменьшения подавленности. Подавленность этого раба уменьшается так</SuppressionFallRateDesc>
```

2021-07-31 23:10 UTC, Elevator89 commented on Ideology/Keyed/ITabs.xml
> +  <TerrorCurrentThoughts>Последнее увиденное устрашающее:</TerrorCurrentThoughts>
```suggestion
  <TerrorCurrentThoughts>Последнее увиденное устрашающее</TerrorCurrentThoughts>
```

2021-07-31 23:10 UTC, Elevator89 commented on Ideology/Keyed/ITabs.xml
> +  <ConversionWeakerDueToTraitAgreements>Попытки обращения будут слабее из-за совместимости идеолигии с чертам характера</ConversionWeakerDueToTraitAgreements>
```suggestion
  <ConversionWeakerDueToTraitAgreements>Попытки обращения будут менее успешными из-за совместимости идеолигии с чертами характера</ConversionWeakerDueToTraitAgreements>
```

2021-07-31 23:10 UTC, Elevator89 commented on Ideology/Keyed/ITabs.xml
> +  <ConversionStrongerDueToTraitAgreements>Попытки обращения будут сильнее из-за несовместимости идеолигии с чертами характера</ConversionStrongerDueToTraitAgreements>
"Сильная попытка" - не самое удачное сочетание
```suggestion
  <ConversionStrongerDueToTraitAgreements>Попытки обращения будут успешнее из-за несовместимости идеолигии с чертами характера</ConversionStrongerDueToTraitAgreements>
```

2021-07-31 23:13 UTC, Elevator89 commented on Ideology/Keyed/ITabs.xml
> +  <Suppression>Подавленность</Suppression>
Внеси, пожалуйста, правки в Ideology\Keyed\Alerts.xml

2021-08-01 14:58 UTC, kamadz commented on Ideology/Keyed/Dialog_StatsReports.xml
> +  <Stat_Thing_RelicOf_Desc>Идеолигия, к которой принадлежит реликвия</Stat_Thing_RelicOf_Desc>
Я вообще не вкуриваю. По смыслу разницы нет никакой в контексте. Никаких идеологий отдельно от идеолигий в игре 100% нет. Мне кажется, ошибка райтера.

2021-08-01 14:58 UTC, kamadz commented on Ideology/Keyed/Dialog_StatsReports.xml
> +  <Stat_Thing_RelatedToIdeos_Desc>Идеолигии</Stat_Thing_RelatedToIdeos_Desc>
```suggestion
  <Stat_Thing_RelatedToIdeos_Desc>Идеолигии, с которыми связан предмет.</Stat_Thing_RelatedToIdeos_Desc>
```

2021-08-01 15:00 UTC, kamadz commented on Ideology/Keyed/Dialog_StatsReports.xml
> +  <Stat_Pawn_DarknessCombatShooting_Desc>Модификатор шанса поражения цели в зависимости от её освещённости.</Stat_Pawn_DarknessCombatShooting_Desc>
тогда надо исправить и здесь 
![image](https://user-images.githubusercontent.com/57110948/127775574-4bf5f72a-3af4-4fc9-8d79-b346985a2ddc.png)

2021-08-01 15:00 UTC, kamadz commented on Ideology/Keyed/Dialog_StatsReports.xml
> +  <Stat_Pawn_DarknessMeleeHitChance_Name>Шанс удара в рукопашную в темноте</Stat_Pawn_DarknessMeleeHitChance_Name>
упс

2021-08-01 15:01 UTC, kamadz commented on Ideology/Keyed/FloatMenu.xml
> +  <CantStartFuneralForSlave>{0_labelShort} — {0_gender ? раб : рабыня}. {0_gender ? рабам : рабыням} не полагаются похороны.</CantStartFuneralForSlave>
Сомнительно, но ладно

2021-08-01 15:02 UTC, kamadz commented on Ideology/Keyed/FloatMenu.xml
> +  <ToDropSupplies>бросить припасы</ToDropSupplies>
Да, на тот момент не понимал вообще о чём речь.

2021-08-01 15:06 UTC, kamadz commented on Ideology/Keyed/GameplayCommands.xml
> +  <CommandNeuralSuperchargerNoAutoUseDescription>Никто из ваших поселенцев не будет автоматически использовать этот нейронный стимулятор.</CommandNeuralSuperchargerNoAutoUseDescription>
Смеялись всей маршруткой

2021-08-01 15:06 UTC, kamadz commented on Ideology/Keyed/GameplayCommands.xml
> +  <CommandNeuralSuperchargerAutoForEveryone>Автоматическое использование для всех</CommandNeuralSuperchargerAutoForEveryone>
```suggestion
  <CommandNeuralSuperchargerAutoForEveryone>Разрешить самостоятельное использование всем</CommandNeuralSuperchargerAutoForEveryone>
```

2021-08-01 15:07 UTC, kamadz commented on Ideology/Keyed/ITabs.xml
> +  <AgreeableMemes>Соответствует чертам:</AgreeableMemes>
Нужно исправить
```suggestion
  <AgreeableMemes>Дополняется чертами</AgreeableMemes>
```

2021-08-01 15:09 UTC, kamadz commented on Ideology/Keyed/ITabs.xml
> +  <Suppression>Подавленность</Suppression>
Так я же тебе говорил про это!

2021-08-01 15:12 UTC, kamadz commented on Ideology/Keyed/ITabs.xml
> +  <Suppression>Подавленность</Suppression>
Исправь, пожалуйста, сам.

2021-08-05 23:00 UTC, merged