3067 Ideology/Keyed4
Ludeon/RimWorld-ru pull request #1270
Opened 2021-07-28 14:56 UTC by kamadz

Close #1248  Translate Ideology/Keyed4

2021-07-29 06:23 UTC, KorDum commented on Ideology/Keyed/Letters.xml
> +  <LetterSingleSlaveRebellion>{0_nameDef} восстал против вас! {0_nameDef} будет искать оружие и будет пытаться убить ваших поселенцев.</LetterSingleSlaveRebellion>
будет-будет, думаю, можно второе убрать без потери смысла? Как в примере на строке 14

2021-07-29 06:23 UTC, KorDum commented on Ideology/Keyed/Letters.xml
> +  <LetterGrandSlaveEscape>Начался массовый побег рабов! Все ваши рабы изо всех сил постараются сбежать.\n\nБегут эти рабы:\n\n{0}</LetterGrandSlaveEscape>
Может быть слово "эти" убрать? В других местах, связанных с перечислениями, такого нет

2021-07-29 07:52 UTC, PyHToR4eG commented on Ideology/Keyed/Letters.xml
> +  <LetterGrandSlaveEscape>Начался массовый побег рабов! Все ваши рабы изо всех сил постараются сбежать.\n\nБегут эти рабы:\n\n{0}</LetterGrandSlaveEscape>
Возможно можно заменить "Бегут эти рабы" на "Беглецы" или что-то в этом духе

2021-08-01 14:55 UTC, Elevator89 requested changes

2021-08-01 14:55 UTC, Elevator89 commented on Ideology/Keyed/Letters.xml
> +  <LetterGrandSlaveRebellion>Началось массовое восстание рабов! Все ваши рабы поднимаются на борьбу с вами. Они будут искать оружие и постараются убить ваших поселенцев\n\nБунтуют эти рабы:\n\n{0}</L
```suggestion
  <LetterGrandSlaveRebellion>Началось массовое восстание рабов! Все ваши рабы поднимаются на борьбу с вами. Они будут искать оружие и постараются убить ваших поселенцев.\n\nБунтуют эти рабы:\n\n{0}</LetterGrandSlaveRebellion>
```

2021-08-01 14:55 UTC, Elevator89 commented on Ideology/Keyed/Letters.xml
> +  <LetterLocalSlaveRebellion>Началось восстание рабов! {0_nameDef} и несколько других рабов поднимаются на борьбу с вами. Они будут искать оружие и постараются убить ваших поселенцев\n\nБунтуют эти р
```suggestion
  <LetterLocalSlaveRebellion>Началось восстание рабов! {0_nameDef} и несколько других рабов поднимаются на борьбу с вами. Они будут искать оружие и постараются убить ваших поселенцев.\n\nБунтуют эти рабы:\n\n{1}</LetterLocalSlaveRebellion> 
```

2021-08-01 14:55 UTC, Elevator89 commented on Ideology/Keyed/Letters.xml
> +  <LetterLocalSlaveEscape>Начался побег рабов! {0_nameDef} и несколько других рабов изо всех сил постараются сбежать.\n\nБегут эти рабы:\n\n{0}</LetterLocalSlaveEscape>
```suggestion
  <LetterLocalSlaveEscape>Начался побег рабов! {0_nameDef} и несколько других рабов изо всех сил постараются сбежать.\n\nБегут эти рабы:\n\n{1}</LetterLocalSlaveEscape>
```

2021-08-01 14:55 UTC, Elevator89 commented on Ideology/Keyed/Letters.xml
> +  <LetterLabelRoleInactiveDesc>Количество {0} снизилось до {1}. Роль {ROLE_labelDef} больше не доступна. Она снова станет доступной, когда число {0} достигнет {2}</LetterLabelRoleInactiveDesc>
```suggestion
  <LetterLabelRoleInactiveDesc>Количество {0} снизилось до {1}. Роль {ROLE_labelDef} больше не доступна. Она снова станет доступной, когда число {0} достигнет {2}.</LetterLabelRoleInactiveDesc>
```

2021-08-01 14:55 UTC, Elevator89 commented on Ideology/Keyed/Letters.xml
> +  <LetterRoleLostReasonUnassignedDesc>{PAWN_objective} сняли с роли.</LetterRoleLostReasonUnassignedDesc>
```suggestion
  <LetterRoleLostReasonUnassignedDesc>{PAWN_possessive} сняли с роли.</LetterRoleLostReasonUnassignedDesc>
```

2021-08-01 14:55 UTC, Elevator89 commented on Ideology/Keyed/Letters.xml
> +  <LetterSpeechConvertedListeners>После {PAWN_possessive} речи, следующие персонажи приняли {IDEO}</LetterSpeechConvertedListeners>
```suggestion
  <LetterSpeechConvertedListeners>После {PAWN_possessive} речи следующие персонажи приняли {IDEO}</LetterSpeechConvertedListeners>
```

2021-08-01 14:55 UTC, Elevator89 commented on Ideology/Keyed/Letters.xml
> +  <JoinerCharityInfo>Это акт милосердия. Если вы не примите {0}, последователи с милосердными убеждениями будут недовольны.</JoinerCharityInfo>
```suggestion
  <JoinerCharityInfo>Это акт милосердия. Если вы не примете {0}, последователи с милосердными убеждениями будут недовольны.</JoinerCharityInfo>
```

2021-08-01 14:55 UTC, Elevator89 commented on Ideology/Keyed/Letters.xml
> +  <LetterIdeoChangedWanderOwnRoom>Чтобы разобраться в {PAWN_possessive} убеждениях, {PAWN_nameDef} прячется в своей комнате.</LetterIdeoChangedWanderOwnRoom>
```suggestion
  <LetterIdeoChangedWanderOwnRoom>Чтобы разобраться в своих убеждениях, {PAWN_nameDef} прячется в своей комнате.</LetterIdeoChangedWanderOwnRoom>
```

2021-08-01 14:55 UTC, Elevator89 commented on Ideology/Keyed/Letters.xml
> +  <LetterWantLookChangeDesc>{PAWN_nameDef} хочет сменить {PAWN_possessive} внешний вид, так как он больше не соответствует {PAWN_possessive} убеждениям.\n\n{PAWN_pronoun} самостоятельно воспользуется
Слишком много "выбрать" рядом
```suggestion
  <LetterWantLookChangeDesc>{PAWN_nameDef} хочет сменить свой внешний вид, так как он больше не соответствует {PAWN_possessive} убеждениям.\n\n{PAWN_pronoun} самостоятельно воспользуется доступным туалетным столиком и выберет себе новую внешность. Если вы хотите сделать это за н{PAWN_possessive}, выберите {PAWN_possessive} и нажмите правой кнопкой мыши по туалетному столику.</LetterWantLookChangeDesc>
```

2021-08-01 14:55 UTC, Elevator89 commented on Ideology/Keyed/Letters.xml
> +  <LetterTextSpacedroneIncoming>Космический дрон приземляется поблизости</LetterTextSpacedroneIncoming>
```suggestion
  <LetterTextSpacedroneIncoming>Космический дрон приземляется поблизости.</LetterTextSpacedroneIncoming>
```

2021-08-01 14:55 UTC, Elevator89 commented on Ideology/Keyed/Letters.xml
> +  <LetterOnlySlaveCaravanColonistsLeft>Все непорабощённые члены {0} погибли. Оставшиеся рабы ушли своей дорогой. Караван был расформирован.</LetterOnlySlaveCaravanColonistsLeft>
Караван не был ни кем расформирован, он просто перестал существовать как караван
```suggestion
  <LetterOnlySlaveCaravanColonistsLeft>Все непорабощённые члены {0} погибли. Оставшиеся рабы ушли своей дорогой. Караван был прекратил свой существование.</LetterOnlySlaveCaravanColonistsLeft>
```

2021-08-01 14:55 UTC, Elevator89 commented on Ideology/Keyed/Letters.xml
> +  <LetterTextRelicFoundSecurityThreats>Реликвия находится в древнем сооружении. Она находится под защитой охранной системы, состоящей из нескольких независимых элементов. Вы можете последовательно ра
```suggestion
  <LetterTextRelicFoundSecurityThreats>Реликвия находится в древнем сооружении. Она находится под защитой охранной системы, состоящей из нескольких независимых элементов. Вы можете последовательно разобраться со всей охранной системой, перед тем как забрать реликвию, или попытаться убежать с ней прежде, чем вам смогут навредить.\n\nЧерез {0} вся охранная система активируется.</LetterTextRelicFoundSecurityThreats>
```

2021-08-01 14:55 UTC, Elevator89 commented on Ideology/Keyed/Letters.xml
> +  <LetterTextRelicsCollected>Все реликвии идеолигии {0} были собраны. Следующие персонажи в восторге </LetterTextRelicsCollected>
```suggestion
  <LetterTextRelicsCollected>Все реликвии идеолигии {0} были собраны. Эти люди — в восторге</LetterTextRelicsCollected>
```

2021-08-01 14:55 UTC, Elevator89 commented on Ideology/Keyed/Letters.xml
> +  <LetterLabelConnectedTreeDestroyed>Связанное древо {TREE_label} destroyed</LetterLabelConnectedTreeDestroyed>
```suggestion
  <LetterLabelConnectedTreeDestroyed>Связанное древо {TREE_label} уничтожено</LetterLabelConnectedTreeDestroyed>
```

2021-08-01 14:55 UTC, Elevator89 commented on Ideology/Keyed/Letters.xml
> +  <LetterTextConnectedTreeDestroyed>{TREE_label}, связанное с {CONNECTEDPAWN_nameDef}, было уничтожено. Королева дриад, находившаяся внутри, погибла.\n\nСо смертью королевы, погиб коллективный разум
```suggestion
  <LetterTextConnectedTreeDestroyed>{TREE_label}, связанное с {CONNECTEDPAWN_nameDef}, было уничтожено. Королева дриад, находившаяся внутри, погибла.\n\nСо смертью королевы погиб коллективный разум дриад, а с ним и все дриады.</LetterTextConnectedTreeDestroyed>
```

2021-08-01 15:14 UTC, kamadz commented on Ideology/Keyed/Letters.xml
> +  <LetterSingleSlaveRebellion>{0_nameDef} восстал против вас! {0_nameDef} будет искать оружие и будет пытаться убить ваших поселенцев.</LetterSingleSlaveRebellion>
```suggestion
  <LetterSingleSlaveRebellion>{0_nameDef} восстал против вас! {0_nameDef} будет искать оружие и постарается убить ваших поселенцев.</LetterSingleSlaveRebellion>
```

2021-08-05 23:04 UTC, Elevator89 commented on Ideology/Keyed/Letters.xml
> +  <LetterSingleSlaveRebellion>{0_nameDef} восстал против вас! {0_nameDef} будет искать оружие и будет пытаться убить ваших поселенцев.</LetterSingleSlaveRebellion>
Местоимение нужно
```suggestion
  <LetterSingleSlaveRebellion>{0_nameDef} восстал против вас! {0_pronoun} будет искать оружие и постарается убить ваших поселенцев.</LetterSingleSlaveRebellion>
```

2021-08-05 23:06 UTC, merged