Ideology/DefInjected-2
Ludeon/RimWorld-ru pull request #1300
Opened 2021-08-02 11:50 UTC by kamadz

Close #1272 Translate Ideology/DefInjected-2

2021-08-02 11:50 UTC, kamadz commented on Ideology/DefInjected/GauranlenTreeModeDef/GauranlenTreeModeDefs.xml
> +  <Clawer.label>коготь</Clawer.label>
```suggestion
  <Clawer.label>царапка</Clawer.label>
```

😄

2021-08-02 11:51 UTC, kamadz commented on Ideology/DefInjected/GauranlenTreeModeDef/GauranlenTreeModeDefs.xml
> +﻿<?xml version="1.0" encoding="UTF-8"?>
```suggestion
﻿<?xml version="1.0" encoding="UTF-8"?>
```

Райтерам за такие скупые на фантазию названия для каст надо что-то оторвать

2021-08-08 14:33 UTC, Elevator89 requested changes

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <Collectivist_Individualist.label>коллективим vs индивидуалистов</Collectivist_Individualist.label>
```suggestion
  <Collectivist_Individualist.label>коллективизм vs индивидуализм</Collectivist_Individualist.label>
```

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <FemaleSupremacy_FemaleSupremacy.label>верховенство женщин</FemaleSupremacy_FemaleSupremacy.label>
```suggestion
  <FemaleSupremacy_FemaleSupremacy.label>матриархат</FemaleSupremacy_FemaleSupremacy.label>
```

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <HumanPrimacy_HumanPrimacy.label>верховенство человека</HumanPrimacy_HumanPrimacy.label>
```suggestion
  <HumanPrimacy_HumanPrimacy.label>гуманизм</HumanPrimacy_HumanPrimacy.label>
```

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <MaleSupremacy_MaleSupremacy.label>верховенство мужчин</MaleSupremacy_MaleSupremacy.label>
```suggestion
  <MaleSupremacy_MaleSupremacy.label>патриархат</MaleSupremacy_MaleSupremacy.label>
```

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <Transhumanist_Transhumanist.label>трансгуманизм</Transhumanist_Transhumanist.label>
Весь этот файл выглядит мутным. Надо его использование проверить в игре и убедиться, что мы правильно понимаем его смысл и контекст.

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <Nudism_Nudism.label>нудизм</Nudism_Nudism.label>
Написано же, что не просто "нудизм", а "нудизм agreement". Это "agreement" должно что-то значить. Вряд ли его можно просто так выкинуть.

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/HediffDef/Hediffs_Casts.xml
> +  <CombatCommandBuff.description>Боевые навыки улучшены благодаря принявшему на себя командование другому человеку.</CombatCommandBuff.description>
```suggestion
  <CombatCommandBuff.description>Боевые навыки улучшены благодаря другому человеку, принявшему на себя командование.</CombatCommandBuff.description>
```

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/HediffDef/Hediffs_Casts.xml
> +  <ImmunityDrive.description>Этот человек получил моральную поддержку. Это придало ему уверенности и укорило выработку иммунитета.</ImmunityDrive.description>
```suggestion
  <ImmunityDrive.description>Этот человек получил моральную поддержку, что придало ему уверенности и укорило выработку иммунитета.</ImmunityDrive.description>
```

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/HediffDef/Hediffs_Casts.xml
> +  <PreachHealth.description>Воля к жизни этого человека усилилась после прослушанной проповеди. Это ускорила заживление его ран и формирование иммунитета.</PreachHealth.description>
```suggestion
  <PreachHealth.description>Воля к жизни этого человека усилилась после прослушанной проповеди. Она ускорила заживление его ран и формирование иммунитета.</PreachHealth.description>
```

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/HediffDef/Hediffs_Casts.xml
> +  <FarmingCommand.description>Этот человек предлагает советы и наставления по фермерству, улучшая способности всех вокруг.</FarmingCommand.description>
Не предлагает, а уже вовсю даёт
```suggestion
  <FarmingCommand.description>Этот человек даёт советы и наставления по фермерству, улучшая способности всех вокруг.</FarmingCommand.description>
```

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/HediffDef/Hediffs_Casts.xml
> +  <FarmingCommandBuff.description>Навыки фермерства этого человека улучшены кем-то поблизости, предлагающим советы и наставления.</FarmingCommandBuff.description>
```suggestion
  <FarmingCommandBuff.description>Навыки фермерства этого человека улучшены кем-то поблизости, дающим советы и наставления.</FarmingCommandBuff.description>
```

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/HediffDef/Hediffs_Casts.xml
> +  <MiningCommand.description>Этот человек предлагает советы и наставления по фермерству, улучшая способности всех вокруг.</MiningCommand.description>
```suggestion
  <MiningCommand.description>Этот человек даёт советы и наставления по добыче, улучшая способности всех вокруг.</MiningCommand.description>
```

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/HediffDef/Hediffs_Casts.xml
> +  <MiningCommandBuff.description>Навыки добычи этого человека улучшены кем-то поблизости, предлагающим советы и наставления.</MiningCommandBuff.description>
```suggestion
  <MiningCommandBuff.description>Навыки добычи этого человека улучшены кем-то поблизости, дающим советы и наставления.</MiningCommandBuff.description>
```

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/HediffDef/Hediffs_Casts.xml
> +  <ProductionCommand.description>Этот человек предлагает советы и наставления по производству и строительству, улучшая способности всех вокруг.</ProductionCommand.description>
```suggestion
  <ProductionCommand.description>Этот человек даёт советы и наставления по производству и строительству, улучшая способности всех вокруг.</ProductionCommand.description>
```

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/HediffDef/Hediffs_Casts.xml
> +  <ProductionCommandBuff.description>Навыки производства и строительства этого человека улучшены кем-то поблизости, предлагающим советы и наставления.</ProductionCommandBuff.description>
```suggestion
  <ProductionCommandBuff.description>Навыки производства и строительства этого человека улучшены кем-то поблизости, дающим советы и наставления.</ProductionCommandBuff.description>
```

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/HediffDef/Precepts_Scarification.xml
> +  <Scarification.labelNounPretty>TODO</Scarification.labelNounPretty>
Недоделки

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/HistoryEventDef/Precepts_Charity.xml
> +  <CharityRefused_Beggars_Betrayed.label>попрошайки были преданы</CharityRefused_Beggars_Betrayed.label>
Я в соседнем реквесте попрошаек "обманывал". Что ближе к теме по факту?
Что конкретно с ними делают?

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/HistoryEventDef/Precepts_SpouseCount.xml
> +  <GotMarried_SpouseCount_FiveOrMore.label>брак с 5-ю или более партнёрами</GotMarried_SpouseCount_FiveOrMore.label>
Ну нафиг эти "-ю" и "-мя"! Выглядят они нелепо.
```suggestion
  <GotMarried_SpouseCount_FiveOrMore.label>брак с 5 или более партнёрами</GotMarried_SpouseCount_FiveOrMore.label>
```

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/HistoryEventDef/Precepts_SpouseCount.xml
> +  <GotMarried_SpouseCount_Four.label>брак с 4-мя или более партнёрами</GotMarried_SpouseCount_Four.label>
```suggestion
  <GotMarried_SpouseCount_Four.label>брак с 4 или более партнёрами</GotMarried_SpouseCount_Four.label>
```

2021-08-08 14:33 UTC, Elevator89 commented on Ideology/DefInjected/HistoryEventDef/Precepts_SpouseCount.xml
> +  <GotMarried_SpouseCount_Three.label>брак с 3-мя или более партнёрами</GotMarried_SpouseCount_Three.label>
```suggestion
  <GotMarried_SpouseCount_Three.label>брак с 3 или более партнёрами</GotMarried_SpouseCount_Three.label>
```

2021-08-08 14:34 UTC, Elevator89 commented on Ideology/DefInjected/GauranlenTreeModeDef/GauranlenTreeModeDefs.xml
> +  <Barkskin.label>дубокож</Barkskin.label>
Хорошо, что не "кожедуб" )

2021-08-08 16:52 UTC, kamadz commented on Ideology/DefInjected/GauranlenTreeModeDef/GauranlenTreeModeDefs.xml
> +  <Barkskin.label>дубокож</Barkskin.label>
Да, было бы странно

2021-08-08 16:53 UTC, kamadz commented on Ideology/DefInjected/GauranlenTreeModeDef/GauranlenTreeModeDefs.xml
> +  <Berrymaker.description>Каста дриад, занимающихся производством пищи. Эти дриады регулярно производят ягоды, но процесс медлительный и на него нельзя полагаться в работе или бою.</Berrymaker.descri
О. как. А я об этом не подумал почему-то. Бывает :)

2021-08-08 16:54 UTC, kamadz commented on Ideology/DefInjected/GauranlenTreeModeDef/GauranlenTreeModeDefs.xml
> +  <Clawer.description>Дриады, основное предназначение которых — мощные атаки в бою. Своему названию они обязаны своим массивным когтям на лапах. Хоть они и могут наносить огромный урон, когти уязвимы
под когтями здесь имелись в виду дриады, но да, твой вариант понятнее

2021-08-08 16:56 UTC, kamadz commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <Nudism_Nudism.label>нудизм</Nudism_Nudism.label>
это значит, что фракции, у которых совпадает трейт "нудизм" получают бонус к отношениям
лаконичнее этого я придумать не смог

2021-08-08 16:56 UTC, kamadz commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <Transhumanist_Transhumanist.label>трансгуманизм</Transhumanist_Transhumanist.label>
уже проверено

2021-08-08 16:58 UTC, kamadz commented on Ideology/DefInjected/HistoryEventDef/Precepts_Charity.xml
> +  <CharityRefused_Beggars_Betrayed.label>попрошайки были преданы</CharityRefused_Beggars_Betrayed.label>
их можно сдать убить по поручению босса другой фракции, как и в случае с бродягами

2021-08-08 17:00 UTC, kamadz commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <HumanPrimacy_HumanPrimacy.label>верховенство человека</HumanPrimacy_HumanPrimacy.label>
Гуманизм это:
![image](https://user-images.githubusercontent.com/57110948/128639490-e0f66aa1-ae50-4d04-ae49-f03e3eedf9dd.png)

а в игре гомо (гомо сапиенс) фашизм
![image](https://user-images.githubusercontent.com/57110948/128639597-99085b21-4235-4a0a-82be-d5f02b34ad83.png)

2021-08-08 17:00 UTC, kamadz commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <HumanPrimacy_HumanPrimacy.label>верховенство человека</HumanPrimacy_HumanPrimacy.label>
Это дуализм отношений "животные такие же как и мы" и "животные - это животные"

2021-08-08 17:01 UTC, kamadz commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <FemaleSupremacy_FemaleSupremacy.label>верховенство женщин</FemaleSupremacy_FemaleSupremacy.label>
вместе с патриархатом надо во всех пересекающихся исправить, возможно нужен ишью

2021-08-08 17:12 UTC, kamadz commented on Ideology/DefInjected/HediffDef/Precepts_Scarification.xml
> +  <Scarification.labelNounPretty>TODO</Scarification.labelNounPretty>
```suggestion
  <!-- EN: scarification -->
  <Scarification.label>шрамирование</Scarification.label>
  <!-- EN: An artistic scar carefully carved into the flesh for ritual or artistic purposes. -->
  <Scarification.description>Вычурный шрам, аккуратно нанесённый на кожу в ритуальных целях.</Scarification.description>
  <!-- EN: a scarification -->
  <Scarification.labelNoun>шрамирование</Scarification.labelNoun>
  <!-- EN: {0} in the {1} -->
  <Scarification.labelNounPretty>{0} в {1}</Scarification.labelNounPretty>
```

2021-08-08 20:25 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <Nudism_Nudism.label>нудизм</Nudism_Nudism.label>
Как насчёт "солидарности"? Здесь тогда будет "солидарность в нудизме" )

2021-08-08 20:31 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <Individualist_Proselytizer.label>прозелетизм</Individualist_Proselytizer.label>
```suggestion
  <Individualist_Proselytizer.label>индивидуализм vs прозелетизм</Individualist_Proselytizer.label>
```

2021-08-08 20:39 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <HumanPrimacy_HumanPrimacy.label>верховенство человека</HumanPrimacy_HumanPrimacy.label>
Прочитал статью про гуманизм. Не очень я увидел, в чём противоречие? Причём тут животные?

2021-08-08 20:40 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <FemaleSupremacy_FemaleSupremacy.label>верховенство женщин</FemaleSupremacy_FemaleSupremacy.label>
Пока что я не мержил ничего похожего. Ты будешь первым. Исправлять имеет смысл прямо сейчас

2021-08-08 20:43 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <FemaleSupremacy_MaleSupremacy.label>верховенство женщин vs верховенство мужчин</FemaleSupremacy_MaleSupremacy.label>
```suggestion
  <FemaleSupremacy_MaleSupremacy.label>матриархат vs патриархат</FemaleSupremacy_MaleSupremacy.label>
```

2021-08-08 20:43 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <FemaleSupremacy_Individualist.label>верховенство женщин vs индивидуализм</FemaleSupremacy_Individualist.label>
```suggestion
  <FemaleSupremacy_Individualist.label>матриархат vs индивидуализм</FemaleSupremacy_Individualist.label>
```

2021-08-08 20:43 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <MaleSupremacy_Individualist.label>верховенство мужчин vs индивидуализм</MaleSupremacy_Individualist.label>
```suggestion
  <MaleSupremacy_Individualist.label>патриархат vs индивидуализм</MaleSupremacy_Individualist.label>
```

2021-08-09 18:38 UTC, kamadz commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <HumanPrimacy_HumanPrimacy.label>верховенство человека</HumanPrimacy_HumanPrimacy.label>
На скрине видно, что в данной идеолигии с данным мемом не приветствуется привязанность к животным. Это раз. 
Во-вторых, этот мем блокирует 18 прецептов, среди которых много связанных с взаимодействием с животными. 
Ещё раз, мемы выстраиваются преимущественно парами: матриархат-патриархат, технократия-биоконсерватизм.
Этот мем входит в пару с "очеловечиванием животных" и получается "очеловечивание животных" - "верховенство человека"

2021-08-09 18:38 UTC, kamadz commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <Nudism_Nudism.label>нудизм</Nudism_Nudism.label>
Звучит неплохо!

2021-08-17 22:15 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <HumanPrimacy_HumanPrimacy.label>верховенство человека</HumanPrimacy_HumanPrimacy.label>
Гуманизм ставит высшей ценностью именно человека, а не животных. Упомянутое тобой противопоставление вписывается в гуманизм вполне органично.

2021-08-17 22:32 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <HumanPrimacy_HumanPrimacy.label>верховенство человека</HumanPrimacy_HumanPrimacy.label>
Ладно, оставим пока, как есть, потом поправим, если надо

2021-08-17 22:32 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <Nudism_Nudism.label>нудизм</Nudism_Nudism.label>
Заменил везде

2021-08-17 22:34 UTC, merged