Ideology/DefInjected-3
Ludeon/RimWorld-ru pull request #1301
Opened 2021-08-03 11:08 UTC by kamadz

Close #1273 Translate Ideology/DefInjected-3

2021-08-03 11:09 UTC, kamadz commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +	</TheistFounder.rules.rulesStrings>
Требует доработки

2021-08-03 11:09 UTC, kamadz commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +	</IdeologicalLesson.rules.rulesStrings>
Требует доработки

2021-08-03 17:00 UTC, PyHToR4eG commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +	</TheistFounder.rules.rulesStrings>
Ни deity0_gender, ни founder_gender не работает. По крайней мере, у меня не работало

2021-08-03 17:37 UTC, PyHToR4eG commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +	</TheistFounder.rules.rulesStrings>
К тому же, правда пока не могу найти этот дескрипшен, foeLeader пока только мужского пола

2021-08-03 21:11 UTC, kamadz commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +	</TheistFounder.rules.rulesStrings>
Надо написать им, чтобы сделали сделали рабочим.

2021-08-08 15:17 UTC, Elevator89 requested changes
Если переведённые правила ломают генерацию, этот реквест заливать нельзя.

2021-08-08 15:17 UTC, Elevator89 commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +    <li>story(uses=1,priority=-10)->[founderName] везде [founder_gender ? носил : носила] с собой [relic0_thingDef_label] [relic0_name], чтобы напоминать людям о важности [memeAdjective].</li>
`о важности [memeAdjective]` В оригинале прилагательное, а у нас - существительное?

2021-08-08 15:17 UTC, Elevator89 commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +	</IdeologicalLesson.rules.rulesStrings>
А оно вообще работает в игре?

2021-08-08 15:17 UTC, Elevator89 commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +    <li>lessonAttribution->[founder_nameFull] [speech] в [Community]</li>
```suggestion
    <li>lessonAttribution->[founder_nameFull], из материалов [memeConference_titleCase]</li>
    <li>lessonAttribution->[founder_nameFull] на своём смертном одре</li>
    <li>lessonAttribution->[founder_nameFull] прямо перед своей казнью</li>
    <li>lessonAttribution->[speech] [founder_nameFull] на [TerrainFeature]</li>
    <li>lessonAttribution->[speech] [founder_nameFull] в [Community]</li>
```

2021-08-08 15:17 UTC, Elevator89 commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +    <li>lessonIntro->Даже будучи ребёнком на [place_summary] [place_name], у меня было понимание, что</li>
Понимание не можно быть ребёнком
```suggestion
    <li>lessonIntro->Даже в детстве, на [place_summary] [place_name], у меня было понимание, что</li>
```

2021-08-08 15:17 UTC, Elevator89 commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +    <li>lessonIntro->Я говорю это, не для того, чтобы вы прожили мою жизнь, а чтобы вы узнали то, что было постигнуто мной. Что</li>
```suggestion
    <li>lessonIntro->Я говорю это не для того, чтобы вы прожили мою жизнь, а чтобы вы узнали то, что было постигнуто мной. Что</li>
```

2021-08-08 15:17 UTC, Elevator89 commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +    <li>intro->Население на [place_summary] [place_name] жило в [memeAdjective] порядке, организованном  [deity0_name].</li>
```suggestion
    <li>intro->Население на [place_summary] [place_name] жило в [memeAdjective] порядке, организованном [deity0_name].</li>
```

2021-08-08 15:17 UTC, Elevator89 commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +    <li>intro->На [place_summary] [place_name] и [memberNamePlural], и все другие, многие года жили в мире и гармонии под пристальным взором [deity0_name].</li>
```suggestion
    <li>intro->На [place_summary] [place_name] и [memberNamePlural], и все другие многие года жили в мире и гармонии под пристальным взором [deity0_name].</li>
```

2021-08-08 15:17 UTC, Elevator89 commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +    <li>intro->На [place_summary] [place_name] во время [ritualName] люди подходили к [altarName] в [altarRoomLabel] [deity0_name] и молились, а в их сердцах бы [memeConcept].</li>
```suggestion
    <li>intro->На [place_summary] [place_name] во время [ritualName] люди подходили к [altarName] в [altarRoomLabel] [deity0_name] и молились, а в их сердцах был [memeConcept].</li>
```

2021-08-08 15:17 UTC, Elevator89 commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +    <li>conflict->Пришла [foeSoldiers] по руководством [foeLeader]. Они поймали всех [memberNamePlural] в [place_community].</li>
```suggestion
    <li>conflict->Пришли [foeSoldiers] по руководством [foeLeader]. Они поймали всех [memberNamePlural] в [place_community].</li>
```

2021-08-08 15:17 UTC, Elevator89 commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +    <li>founderJoin->[founder_gender ? Герой : Героиня], [founderName] [founder_gender ? попытался : попыталась] убить [foeLeader]. Покушение провалилось, но [deity0_name] [deity0_gender ? заметил :
```suggestion
    <li>founderJoin->[founder_gender ? Герой : Героиня], [founderName], [founder_gender ? попытался : попыталась] убить [foeLeader]. Покушение провалилось, но [deity0_name] [deity0_gender ? заметил : заметила] усилия [founderName] и [deity0_gender ? сделал : сделала] [founder_possessive] своим пророком.</li>
```

2021-08-08 15:17 UTC, Elevator89 commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +    <li>founderJoin->place_job] [founderName] [founder_gender ? восстал : восстала] против [foeLeader], и [deity0_name] [deity0_gender ? благословил : благословила] [founder_possessive].</li>
```suggestion
    <li>founderJoin->[place_job] [founderName] [founder_gender ? восстал : восстала] против [foeLeader], и [deity0_name] [deity0_gender ? благословил : благословила] [founder_possessive].</li>
```

2021-08-08 15:17 UTC, Elevator89 commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +    <li>creation->В раздоре старого мира, [deity0_name] [deity0_gender ? создал : создала] великий пожар, из пепла последних веков которого вышел новый.</li>
```suggestion
    <li>creation->В раздоре старого мира, [deity0_name] [deity0_gender ? создал : создала] великий пожар, из пепла последних эпох которого родилась эпоха новая.</li>
```

2021-08-08 17:03 UTC, kamadz commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +    <li>setup->Среди прогнившего мира, [founderName] [founder_gender ? видел : видела] что всё не так и [founder_gender ? создал : создала] собственное движение.</li>
Проверялись, не работают. Надо заставить разрабов сделать так, чтобы работали.

2021-08-08 17:04 UTC, kamadz commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +    <li>story(uses=1,priority=-10)->[founderName] везде [founder_gender ? носил : носила] с собой [relic0_thingDef_label] [relic0_name], чтобы напоминать людям о важности [memeAdjective].</li>
да, не знаю, что лучше: пытаться играть от прилагательного "x жизнь" или просто поставить существительное

2021-08-08 17:05 UTC, kamadz commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +	</IdeologicalLesson.rules.rulesStrings>
Не тестировал, сегодня прогоню

2021-08-08 17:07 UTC, kamadz commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +    <li>creation->В раздоре старого мира, [deity0_name] [deity0_gender ? создал : создала] великий пожар, из пепла последних веков которого вышел новый.</li>
```suggestion
    <li>creation->В раздоре старого мира, [deity0_name] [deity0_gender ? создал : создала] великий пожар, из пепла последних эпох которого родился новый мир.</li>
```

2021-08-08 20:47 UTC, Elevator89 commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +    <li>setup->Среди прогнившего мира, [founderName] [founder_gender ? видел : видела] что всё не так и [founder_gender ? создал : создала] собственное движение.</li>
Значит пока мержить не будем, чтобы потом не переделывать.

2021-08-08 20:52 UTC, Elevator89 commented on Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
> +    <li>story(uses=1,priority=-10)->[founderName] везде [founder_gender ? носил : носила] с собой [relic0_thingDef_label] [relic0_name], чтобы напоминать людям о важности [memeAdjective].</li>
Прилагательные потом просклоняем словарём
```suggestion
    <li>story(uses=1,priority=-10)->[founderName] везде [founder_gender ? носил : носила] с собой [relic0_thingDef_label] [relic0_name], чтобы напоминать людям о важности [memeAdjective] жизни.</li>
```

2021-08-18 21:15 UTC, merged