Ideology/DefInjected/ThingDef-1
Ludeon/RimWorld-ru pull request #1312
Opened 2021-08-07 14:13 UTC by EtoZheJih

2021-08-07 20:05 UTC, shikulja commented on Ideology/DefInjected/ThingDef/Buildings_Art.xml
> +  <SculptureTerror.label>скульптура ужаса</SculptureTerror.label>
Скульптура террора
с описанием, что она - наводит ужас.
Будет более правильным. Террор это общественное явление, а ужас последствие.

2021-08-07 20:06 UTC, shikulja commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <CannibalPlatter.description>Участок пола, покрытый предваретельно нарезанным и разложенным человеческим мясом, готовым к пиршеству каннибалов.</CannibalPlatter.description>
опечатка

2021-08-07 20:07 UTC, shikulja commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <CannibalPlatter.description>Участок пола, покрытый предваретельно нарезанным и разложенным человеческим мясом, готовым к пиршеству каннибалов.</CannibalPlatter.description>
опечатка

2021-08-08 10:07 UTC, KorDum commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_AuthorityCap.description>Шляпа с жёсткими полями и остроконечным верхом. Не особо защищает, но создаёт ощущение авторитета носителя и делает его более эффективным в подавлении рабов.</Appa
> создаёт ощущение авторитета носителя и делает его более эффективным в подавлении рабов

"его" - авторитета или носителя?

2021-09-12 10:30 UTC, PyHToR4eG commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_Slicecap.description>Шапочка, немного закрывающая голову носителя.</Apparel_Slicecap.description>
Это не совсем "чепчик". Насколько могу судить, разработчики вдохновлялись футуристическим головным убором Эмануэля Зорга из Пятого элемента, покрывающего половину головы. И в описании неспроста указано, что она именно "hard", т.к. делается из дерева, стали и прочих твердых материалов

2021-09-13 12:26 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_AuthorityCap.label>шляпа надзирателя</Apparel_AuthorityCap.label>
Шляпа, рили?
```suggestion
  <Apparel_AuthorityCap.label>фуражка надзирателя</Apparel_AuthorityCap.label>
```

2021-09-13 12:34 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <ChristmasTree.label>рождественская ёлка</ChristmasTree.label>
```suggestion
  <ChristmasTree.label>рождественское дерево</ChristmasTree.label>
```

оба варианта допустимы, но уже используется этот

2021-09-13 12:38 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_AuthorityCap.description>Шляпа с жёсткими полями и остроконечным верхом. Не особо защищает, но повышает авторитет носителя, благодаря чему становится легче подавлять рабов.</Apparel_Author
```suggestion
  <Apparel_AuthorityCap.description>Фуражка с жёсткими полями и острым верхом. Повышает авторитет носящего, благодаря чему становится легче подавлять рабов, но не предоставляет никакой защиты.</Apparel_AuthorityCap.description>
```

2021-09-13 12:39 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_Broadwrap.description>Обёрнутые тканевые простыни, которые закрывают голову и пллечи владельца.</Apparel_Broadwrap.description>
```suggestion
  <Apparel_Broadwrap.description>Накидка, покрывающая голову и плечи.</Apparel_Broadwrap.description>
```

2021-09-13 12:41 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_Collar.description>Неудобный ошейник, сделанный для рабов. Он напоминает носителю о статусе раба и оказывает психологическое воздействие. Уменьшает вероятность восстания.</Apparel_Collar.d
```suggestion
  <Apparel_Collar.description>Неудобный ошейник для рабов. Он напоминает своему владельцу о его рабском положении, тем самым подавляя его. Уменьшает вероятность бунта.</Apparel_Collar.description>
```
О вич-статусе, ага

2021-09-13 12:47 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_Flophat.label>панама</Apparel_Flophat.label>
```suggestion
  <Apparel_Flophat.label>шапка-носок</Apparel_Flophat.label>
```

2021-09-13 12:47 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_Flophat.description>Большая, толстая кепка. Ткань с неё свисает до затылка.</Apparel_Flophat.description>
```suggestion
  <Apparel_Flophat.description>Большая и толстая шапка. Свисает до затылка.</Apparel_Flophat.description>
```

Так кепка или панама???

2021-09-13 12:50 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_Headwrap.description>Завёрнутый кусок ткани, обвязывается вокруг головы.</Apparel_Headwrap.description>
Да в кого заворачивается эта ваша ткань?
![image](https://user-images.githubusercontent.com/57110948/133086279-db84cf71-4a03-48ec-a098-173762e170ed.png)
```suggestion
  <Apparel_Headwrap.description>Полоска ткани, которая повязывается на голову.</Apparel_Headwrap.description>
```

2021-09-13 12:50 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_Headwrap.label>повязка на голову</Apparel_Headwrap.label>
```suggestion
  <Apparel_Headwrap.label>платок</Apparel_Headwrap.label>
```

2021-09-13 12:52 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_Shadecone.label>плетёная шляпа</Apparel_Shadecone.label>
```suggestion
  <Apparel_Shadecone.label>коническая шляпа</Apparel_Shadecone.label>
```
из кожи тоже плетёнка будет?

2021-09-13 12:53 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_Shadecone.description>Коническая плетёная шляпа. Хорошо защищает от солнца.</Apparel_Shadecone.description>
```suggestion
  <Apparel_Shadecone.description>Коническая шляпа. Хорошо защищает от солнца.</Apparel_Shadecone.description>
```

2021-09-13 12:58 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_Slicecap.label>чепчик</Apparel_Slicecap.label>
Защитных свойств эта штука не имеет.
Можно перевести так:
```suggestion
  <Apparel_Slicecap.label>накладка на голову</Apparel_Slicecap.label>
```
```suggestion
  <Apparel_Slicecap.label>накладка на скальп</Apparel_Slicecap.label>
```
```suggestion
  <Apparel_Slicecap.label>жёсткая накладка</Apparel_Slicecap.label>
```

2021-09-13 12:59 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_Slicecap.description>Шапочка, немного закрывающая голову носителя.</Apparel_Slicecap.description>
```suggestion
  <Apparel_Slicecap.description>Жёсткая накладка, закрывающая скальп владельца.</Apparel_Slicecap.description>
```

2021-09-13 13:01 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_VisageMask.label>маска для лица</Apparel_VisageMask.label>
```suggestion
  <Apparel_VisageMask.label>маска</Apparel_VisageMask.label>
```
Ну не для жопы же маски делают

2021-09-13 13:06 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Various.xml
> +  <Apparel_Burka.label>паранджа</Apparel_Burka.label>
```suggestion
  <Apparel_Burka.label>бурка</Apparel_Burka.label>
```
В игре именно афганска бурка

2021-09-13 13:07 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Various.xml
> +  <Apparel_Burka.description>Наряд, закрывающий всю голову и тело носителя.</Apparel_Burka.description>
```suggestion
  <Apparel_Burka.description>Наряд, закрывающий всю голову и тело владельца.</Apparel_Burka.description>
```
Носители обычно у заболеваний. У одежды "носящие" и "владельцы"

2021-09-13 13:08 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Various.xml
> +  <Apparel_BodyStrap.label>рабский ремень</Apparel_BodyStrap.label>
```suggestion
  <Apparel_BodyStrap.label>рабская шлейка</Apparel_BodyStrap.label>
```

2021-09-13 13:09 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Various.xml
> +  <Apparel_BodyStrap.description>Ремень, который наматывают на тело раба. Он напоминает носителю о его рабском статусе, что давит на психику и уменьшает вероятность восстания.</Apparel_BodyStrap.desc
```suggestion
  <Apparel_BodyStrap.description>Система ремней, повязывающаяся на верхнюю часть тела раба. Она напоминает носящему о его рабском положении, тем самым подавляя его. Уменьшает вероятность бунта.</Apparel_BodyStrap.description>
```

2021-09-13 19:45 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Various.xml
> +  <Apparel_TortureCrown.description>Головной убор в виде короны с короткими шипами, обращёнными внутрь. Из-за того, что шипы впиваются в голову, причиняет носителю боль.</Apparel_TortureCrown.descrip
```suggestion
  <Apparel_TortureCrown.description>Головной убор в виде короны с короткими шипами, обращёнными внутрь. Iипы впиваются в голову и причиняют носящему боль.</Apparel_TortureCrown.description>
```

2021-09-13 19:45 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Various.xml
> +  <Apparel_TortureCrown.label>корона страданий</Apparel_TortureCrown.label>
```suggestion
  <Apparel_TortureCrown.label>терновая корона</Apparel_TortureCrown.label>
```
более прозаично, но debatable.

2021-09-13 19:46 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Active.xml
> +  <AncientFuelNode.description>Древний, нестабильный топливный узел, который когда-то использовался для заправки машин. С годами он стал нестабилен из-за отсутствия технического обслуживания.</Ancien
```suggestion
  <AncientFuelNode.description>Древний нестабильный топливный узел, который когда-то использовался для заправки машин. С годами он стал нестабилен из-за отсутствия технического обслуживания.</AncientFuelNode.description>
```

2021-09-13 19:48 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Active.xml
> +  <AncientSecurityCrate.label>защитный контейнер</AncientSecurityCrate.label>
```suggestion
  <AncientSecurityCrate.label>защищённый контейнер</AncientSecurityCrate.label>
```

2021-09-13 19:52 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Active.xml
> +  <AncientTerminal.description>Древний компьютерный терминал. Может быть взломан для получения давно забытой информации.</AncientTerminal.description>
```suggestion
  <AncientTerminal.description>Древний компьютерный терминал. Может быть взломан для получения давно забытых данных.</AncientTerminal.description>
```

2021-09-13 19:52 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Indoors.xml
> +  <AncientBed.description>Старый, прогнивший матрас на ржавой раме. Хоть эта кровать и не очень удобна, ей всё ещё можно пользоваться. Не подлежит ремонту.</AncientBed.description>
```suggestion
  <AncientBed.description>Старый прогнивший матрас на ржавой раме. Хоть эта кровать и не очень удобна, ей всё ещё можно пользоваться. Не подлежит ремонту.</AncientBed.description>
```

2021-09-13 19:53 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Indoors.xml
> +  <AncientBarrel.description>Древняя, разбитая бочка. Выглядит так, будто раньше в ней хранили какие-то отходы. Единственное, что в ней осталось - это кусок высохшего ила.</AncientBarrel.description>
```suggestion
  <AncientBarrel.description>Древняя разбитая бочка. Выглядит так, будто раньше в ней хранили какие-то отходы. Единственное, что в ней осталось - это кусок высохшего ила.</AncientBarrel.description>
```

2021-09-13 20:01 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Indoors.xml
> +  <AncientCrate.description>Древний, сломанный ящик. Непригоден для хранения чего угодно..</AncientCrate.description>
```suggestion
  <AncientCrate.description>Древний сломанный ящик. Непригоден для использования по назначению.</AncientCrate.description>
```

2021-09-13 20:03 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Indoors.xml
> +  <AncientDisplayBank.description>Древний компьютерный интерфейс. Ценные части отсутсвуют, остальное деградировало до бесполезного состояния.</AncientDisplayBank.description>
```suggestion
  <AncientDisplayBank.description>Древний компьютерный интерфейс. Ценные части отсутствуют, остальное деградировало до бесполезного состояния.</AncientDisplayBank.description>
```

2021-09-13 20:05 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Indoors.xml
> +  <AncientEquipmentBlocks.description>Блок древнего оборудования неизвестного назначения. Ценные части отсутствуют, всё остальное деградировало до бесполезного состояния.</AncientEquipmentBlocks.desc
```suggestion
  <AncientEquipmentBlocks.description>Блок древнего оборудования неизвестного назначения. Ценные части отсутствуют, всё остальное прогнило до бесполезного состояния.</AncientEquipmentBlocks.description>
```

2021-09-13 20:06 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Indoors.xml
> +  <AncientGenerator.description>Древний электрический генератор. Его части разрушены и разграблены годы назад, а всё, что осталось, проржавело насквозь.</AncientGenerator.description>
```suggestion
  <AncientGenerator.description>Древний электрический генератор. Всё, что не успели растащить на части, давным-давно пришло в негодность, а всё, что осталось, проржавело насквозь.</AncientGenerator.description>
```

2021-09-13 20:07 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Indoors.xml
> +  <AncientLockerBank.description>Древние ржавые шкафчики. Все они давно взломаны, в них не осталось ничего ценного.</AncientLockerBank.description>
```suggestion
  <AncientLockerBank.description>Древние ржавые шкафчики. Они давно взломаны, в них не осталось ничего ценного.</AncientLockerBank.description>
```

2021-09-13 20:07 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Indoors.xml
> +  <AncientMachine.description>Большой древний корпус механизма неизвестного предназначения. Ценные части отсутствуют, а всё остальное деградировало до бесполезного состояния.</AncientMachine.descript
```suggestion
  <AncientMachine.description>Большой древний корпус механизма неизвестного предназначения. Ценные части отсутствуют, а всё остальное прогнило до бесполезного состояния.</AncientMachine.description>
```

2021-09-13 20:08 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Indoors.xml
> +  <AncientOperatingTable.description>Стол, который в давние времена использовали для операций. Разрушился с течением времени.</AncientOperatingTable.description>
```suggestion
  <AncientOperatingTable.description>Стол, который в давние времена использовали для операций. Разрушился под гнётом времени.</AncientOperatingTable.description>
```

2021-09-13 20:08 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Indoors.xml
> +  <AncientStorageCylinder.description>Старая цистерна, видимо раньше использовалась для хранения какой-то жидкости. В ней не осталось ничего ценного.</AncientStorageCylinder.description>
```suggestion
  <AncientStorageCylinder.description>Старая цистерна, которая, судя по виду, использовалась для хранения какой-то жидкости. В ней не осталось ничего ценного.</AncientStorageCylinder.description>
```

2021-09-13 20:09 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Indoors.xml
> +  <AncientSystemRack.description>Древний стеллаж, заполненный неизвестными устройствами. Ценные части отсутствуют, остальное давным-давно разрушено.</AncientSystemRack.description>
```suggestion
  <AncientSystemRack.description>Древний стеллаж, заполненный неизвестными устройствами. Ценные части отсутствуют, а всё остальное прогнило до бесполезного состояния.</AncientSystemRack.description>
```

2021-09-13 20:10 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Art.xml
> +  <SculptureTerror.label>скульптура террора</SculptureTerror.label>
```suggestion
  <SculptureTerror.label>ужасающая скульптура</SculptureTerror.label>
```

2021-09-13 20:11 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Art.xml
> +  <SculptureTerror.description>Скульптура внушающая ужас. Рабы испытывают страх, находясь рядом с ней. Скульптура заставляет их дольше оставаться подавленными, и, таким образом, приводит к уменьшению
```suggestion
  <SculptureTerror.description>Внушающая ужас скульптура. Рабы испытывают страх, находясь рядом с ней. Это делает их более подавленными, и, таким образом, приводит к уменьшению шанса восстания.</SculptureTerror.description>
```

2021-09-13 20:12 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <Altar_Small.description>Небольшой алтарь, используется в религиозных ритуалах</Altar_Small.description>
```suggestion
  <!-- EN: grand altar -->
  <Altar_Grand.label>великий алтарь</Altar_Grand.label>
  <!-- EN: A grand platform that plays a role in ideoligious rituals. -->
  <Altar_Grand.description>Великий алтарь, используется в идеолигиозных ритуалах.</Altar_Grand.description>
  
  <!-- EN: large altar -->
  <Altar_Large.label>большой алтарь</Altar_Large.label>
  <!-- EN: A large platform that plays a role in ideoligious rituals. -->
  <Altar_Large.description>Большой алтарь, используется в идеолигиозных ритуалах.</Altar_Large.description>
  
  <!-- EN: medium altar -->
  <Altar_Medium.label>средний алтарь</Altar_Medium.label>
  <!-- EN: A medium platform that plays a role in ideoligious rituals. -->
  <Altar_Medium.description>Средний алтарь, используется в идеолигиозных ритуалах.</Altar_Medium.description>
  
  <!-- EN: small altar -->
  <Altar_Small.label>небольшой алтарь</Altar_Small.label>
  <!-- EN: A small platform that plays a role in ideoligious rituals. -->
  <Altar_Small.description>Небольшой алтарь, используется в идеолигиозных ритуалах.</Altar_Small.description>
```

2021-09-13 20:14 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientAirConditioner.description>Древний прибор для кондиционирования воздуха. Его внутренности сломались давным-давно, а то, что не разграбили, проржавело насквозь.</AncientAirConditioner.descri
```suggestion
  <AncientAirConditioner.description>Древний прибор для кондиционирования помещений. Его внутренности сломались давным-давно, а то, что не растащили, проржавело насквозь.</AncientAirConditioner.description>
```

2021-09-13 20:15 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientJetEngine.description>Древний реактивный двигатель, вероятно, отсоединённый от большого средства передвижения по воздуху. Его хрупкие внутренности проржавели до основания. Если в нём и оста
```suggestion
  <AncientJetEngine.description>Древний реактивный двигатель, вероятно, отсоединённый от большого самолёта. Его хрупкие внутренности проржавели до основания. Если в нём и оставались целые компоненты, то их давным-давно утащили.</AncientJetEngine.description>
```

2021-09-13 20:16 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientKitchenSink.description>Древняя кухонная раковина, сделанная из какого-то неметаллического листового материала. Он сильно испорчен, и нет никакой возможности от него что-либо спасти.\n\n Ка
```suggestion
  <AncientKitchenSink.description>Древняя кухонная раковина, сделанная из некого неметаллического листового материала. Он сильно испорчен, и нет никакой возможности что-либо спасти.\n\n Как он сюда попал? Наверное, это долгая история..</AncientKitchenSink.description>
```

2021-09-13 20:17 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientLargeCrate.description>Этот большой ящык был оставлен здесь годы назад. Он слишком проржавел, чтобы что-либо хранить.</AncientLargeCrate.description>
```suggestion
  <AncientLargeCrate.description>Этот большой ящик был оставлен здесь годы назад. Он слишком ржавый, чтобы использовать его по назначению.</AncientLargeCrate.description>
```

чык чырык

2021-09-13 20:17 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientLargeRustedEngineBlock.description>Большой, древний блок двигателя от какого-то гигантского транспортного средства или механизма. Он полностью проржавел, а все полезные компоненты кто-то уж
```suggestion
  <AncientLargeRustedEngineBlock.description>Большой древний блок двигателя от какого-то гигантского транспортного средства или механизма. Он полностью проржавел, а все полезные компоненты кто-то уже забрал.</AncientLargeRustedEngineBlock.description>
```

2021-09-13 20:18 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientLongCrate.description>Длинный, пустой и проржавевший ящик, оставленный здесь годы назад.</AncientLongCrate.description>
```suggestion
  <AncientLongCrate.description>Длинный пустой и проржавевший ящик, оставленный здесь годы назад.</AncientLongCrate.description>
```

2021-09-13 20:18 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientMechanoidShell.description>Корпус уничтоженного механоида. Он разрушался под воздействием внешней среды в течение многих лет, а все полезные компоненты распались уже давным-давно.</AncientM
```suggestion
  <AncientMechanoidShell.description>Корпус уничтоженного механоида. Он разрушался под воздействием внешней среды в течение многих лет, а все полезные компоненты рассыпались уже давным-давно.</AncientMechanoidShell.description>
```

2021-09-13 20:21 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientMegaCannonBarrel.description>Ствол дальнобойного артиллерийского или противовоздушного орудия. Когда он был новым, должно быть, был пугающе мощным. Сейчас же неремонтопригоден, а уцелевшие
```suggestion
  <AncientMegaCannonBarrel.description>Дальнобойное артиллерийское или зенитное орудие. Когда-то оно было новым и, должно быть, пугающе мощным. Сейчас же орудие неремонтопригодно, а уцелевшие полезные компоненты отсутствуют.</AncientMegaCannonBarrel.description>
```

2021-09-13 20:21 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientMegaCannonBarrel.label>древний ствол мега-орудия</AncientMegaCannonBarrel.label>
```suggestion
  <AncientMegaCannonBarrel.label>мега-орудия</AncientMegaCannonBarrel.label>
```

2021-09-13 20:21 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientMegaCannonTripod.label>древняя платформа мега-орудия</AncientMegaCannonTripod.label>
```suggestion
  <AncientMegaCannonTripod.label>лафет древнего мега-орудия</AncientMegaCannonTripod.label>
```

2021-09-13 20:22 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientMegaCannonTripod.description>Платформа, на которой когда-то стояло огромное орудие. Полезные компоненты украдены, а то, что от него осталось, не представляет интереса.</AncientMegaCannonTri
```suggestion
  <AncientMegaCannonTripod.description>Платформа, на которой когда-то стояло огромное орудие. Полезные компоненты украдены, а то, что от неё осталось, не представляет интереса.</AncientMegaCannonTripod.description>
```

2021-09-13 20:22 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientMiniWarwalkerRemains.description>Разбитые останки древного боевого бегуна, все его части, которые не были уничтожены, уже давно украдены.</AncientMiniWarwalkerRemains.description>
```suggestion
  <AncientMiniWarwalkerRemains.description>Разбитые останки древнего боевого бегуна. Всё, что не было уничтожено, уже давно украдено.</AncientMiniWarwalkerRemains.description>
```

2021-09-13 20:23 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientPipelineSection.description>Секция древнего трубопровода. Видимо раньше он доставлял какие-то жидкости на огромные расстояния, теперь же он разрушен и бесполезен. </AncientPipelineSection.d
```suggestion
  <AncientPipelineSection.description>Секция древнего трубопровода. Видимо, раньше он служил для доставки каких-то жидкостей на огромные расстояния, теперь же он разрушен и бесполезен. </AncientPipelineSection.description>
```

2021-09-13 20:24 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientPodCar.description>Древний автомобиль-капсула, когда-то способный к автоматическому полёту. Его ценные части давно разграблены, а всё, что осталось, сильно обветшало.</AncientPodCar.descrip
```suggestion
  <AncientPodCar.description>Древний автомобиль-капсула, когда-то способный к автоматическому полёту. Ценные компоненты давно растащены, а всё, что осталось, сильно обветшало.</AncientPodCar.description>
```

2021-09-13 20:25 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientRefrigerator.description>Древний холодильник. Интересные запчасти разграблены давным-давно.</AncientRefrigerator.description>
```suggestion
  <AncientRefrigerator.description>Древний холодильник. Интересные запчасти извлечены давным-давно.</AncientRefrigerator.description>
```

2021-09-13 20:25 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientRustedCar.description>Древний, разрушенный автомобиль. Всё, что не проржавело насквозь, было разграблено давным-давно.</AncientRustedCar.description>
```suggestion
  <AncientRustedCar.description>Древний разрушенный автомобиль. Всё, что не проржавело насквозь, было давным-давно растащено.</AncientRustedCar.description>
```

2021-09-13 20:26 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientRustedJeep.description>Древний, сломанный бронетранспортёр. Всё, что не проржавело, давно разграблено.</AncientRustedJeep.description>
```suggestion
  <AncientRustedJeep.description>Древний сломанный бронетранспортёр. Всё, что не проржавело, давно разграблено.</AncientRustedJeep.description>
```

2021-09-13 20:26 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientSecurityTurret.description>Древняя, сломанная защитная турель. Её запчасти давно разграблены или разрушены.</AncientSecurityTurret.description>
```suggestion
  <AncientSecurityTurret.description>Древняя сломанная защитная турель. Её запчасти давно растащены или поломаны.</AncientSecurityTurret.description>
```

2021-09-13 20:27 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientShipBeacon.description>Древний, сломанный маяк. Раньше его использовали для посадки транспорта, теперь же представляет из себя ржавые останки.</AncientShipBeacon.description>
```suggestion
  <AncientShipBeacon.description>Древний сломанный маяк. Раньше его использовали для посадки транспорта, теперь же это просто ржавые останки.</AncientShipBeacon.description>
```

2021-09-13 20:28 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientShoppingCart.description>Древняя, проржавевшая тележка для покупок. Как она здесь оказалась - большая загадка, однако это история, наверное, длинная и очень грустная.</AncientShoppingCart.d
```suggestion
  <AncientShoppingCart.description>Древняя проржавевшая тележка для покупок. Как она здесь оказалась - большая загадка, однако эта история, наверное, длинная и очень грустная.</AncientShoppingCart.description>
```

2021-09-13 20:28 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientSmallCrate.description>Маленький, пустой ящик, оставленный здесь годы назад. Он слишком ржавый, чтобы в нём что-либо хранить.</AncientSmallCrate.description>
```suggestion
  <AncientSmallCrate.description>Маленький пустой ящик, оставленный здесь годы назад. Он слишком ржавый, чтобы использовать его по назначению.</AncientSmallCrate.description>
```

2021-09-13 20:28 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientStove.description>Древняя печь. Разрушена, и полностью проржавела, её никак не восстановить.\n\nТяжело сказать, как она здесь очутилась..</AncientStove.description>
```suggestion
  <AncientStove.description>Древняя печь. Разрушена, и полностью проржавела, её никак не восстановить.\n\nТяжело сказать, как она здесь очутилась.</AncientStove.description>
```

2021-09-14 07:17 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <BiosculpterPod.label>Терминал биоскульптора</BiosculpterPod.label>
```suggestion
  <BiosculpterPod.label>Капсула биоскульптора</BiosculpterPod.label>
```

2021-09-14 07:23 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <BiosculpterPod.description>Терминал с имплантационной установкой, оснащённый инжектором биоскульптурной жидкости и собственной системой управления. С его помощью можно спровоцировать биологические
```suggestion
  <BiosculpterPod.description>Капсула, оснащённая инжектором биоскульптурной жидкости и собственной системой управления. Она используется для различных манипуляций с организмом на биологическом уровне — с её помощью можно пройти процедуру омоложения или вызвать чувство эйфории. После использования биоскульптор закрепляется за носителем и не может быть использован другим человеком. Настройки сбрасываются через 60 дней. Сторонники трансгуманизма считают, что биоскульпторы имеют решающее значение в их стремлении преодолеть границы слабой человеческой плоти.</BiosculpterPod.description>
```

2021-09-14 07:23 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <BiosculpterPod.comps.CompBiosculpterPod_AgeReversalCycle.description>Произведён откат возраста на 1 год.</BiosculpterPod.comps.CompBiosculpterPod_AgeReversalCycle.description>
```suggestion
  <BiosculpterPod.comps.CompBiosculpterPod_AgeReversalCycle.description>Произведёно омоложение на 1 год.</BiosculpterPod.comps.CompBiosculpterPod_AgeReversalCycle.description>
```

2021-09-14 07:25 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <Burnbong.label>дымотрубка</Burnbong.label>
```suggestion
  <Burnbong.label>одноразовый бонг</Burnbong.label>
```

2021-09-14 07:26 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <IncenseShrine.label>храм благовоний</IncenseShrine.label>
```suggestion
  <IncenseShrine.label>дымолистовая рака</IncenseShrine.label>
```

2021-09-14 07:29 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <Burnbong.description>Деревянная конструкция, набитая дымолистом. Её можно поджечь во время ритуала, что приведёт к выделению большого количество дыма в течении нескольких часов. Уничтожается после
```suggestion
  <Burnbong.description>Деревянная конструкция, набитая дымолистом. Её можно поджечь во время ритуала, что приведёт к выделению большого количество дыма в течение нескольких часов. Уничтожается после использования.</Burnbong.description>
```

У нас было вроде другое описание уже где-то, не помню

2021-09-14 07:30 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <ChristmasTree.description>Праздничная ёлка, украшенная гирляндой и игрушками, традиционно изготовленными в рамках торжественных праздников.</ChristmasTree.description>
```suggestion
  <ChristmasTree.description>Праздничное дерево, украшенная гирляндой и игрушками, традиционно изготовленными в рамках торжественных праздников.</ChristmasTree.description>
```

2021-09-14 07:36 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <BiosculpterPod.comps.CompBiosculpterPod_PleasureCycle.description>Временная перестройка нервной системы на какое-то время повысила уровень счастья.</BiosculpterPod.comps.CompBiosculpterPod_Pleasur
```suggestion
  <BiosculpterPod.comps.CompBiosculpterPod_PleasureCycle.label>блаженственная нервная перестройка</BiosculpterPod.comps.CompBiosculpterPod_PleasureCycle.label>
  <!-- EN: Temporarily reshape the nervous system to deliver elevated levels of happiness for a time. -->
  <BiosculpterPod.comps.CompBiosculpterPod_PleasureCycle.description>Временная перестройка нервной системы на какое-то время повысила настроение.</BiosculpterPod.comps.CompBiosculpterPod_PleasureCycle.description>
```

2021-09-14 08:53 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <IncenseShrine.description>Алтарь из благовоний. После зажжения производит мощный эффект благовоний, который помогает сосредоточиться на ритуале. Сгорает дотла.</IncenseShrine.description>
```suggestion
  <IncenseShrine.description>Деревянный алтарь, заполеннный благовониями. После зажжения производит облако дыма, которое помогает сосредоточиться на ритуале. Сгорает дотла.</IncenseShrine.description>
```

2021-09-14 10:33 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <Effigy.label>чучело</Effigy.label>
```suggestion
  <Effigy.label>пугало</Effigy.label>
```
лучше пугало, потому что у чучела 2 основных значения, одно из которых: набитый и законсервированный труп или фрагмент трупа животного

2021-09-14 10:33 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <Effigy.description>Грубо сколоченное из дерева чучело, готовое к ритуальному сожжению.</Effigy.description>
```suggestion
  <Effigy.description>Грубо сколоченное из дерева пугало, готовое к ритуальному сожжению.</Effigy.description>
```

2021-09-14 10:35 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <Ideogram.description>Большое изображение, нарисованное на полу и укреплённое металлическим обрамлением. Помогает сосредоточиться на ритуале.</Ideogram.description>
```suggestion
  <Ideogram.description>Большое изображение, нарисованное на полу и украшенное металлическим обрамлением. Важная часть многих ритуалов.</Ideogram.description>
```
Зачем укреплять рисунок мелом на полу?

2021-09-14 10:37 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <RitualSpot.description>Место для проведения определённых видов ритуалов.</RitualSpot.description>
```suggestion
  <RitualSpot.description>Место для проведения определённых ритуалов.</RitualSpot.description>
```

2021-09-14 10:38 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <SacrificialFlag.description>Флаг с изображением врагов, используется для сожжения в ритуалах.</SacrificialFlag.description>
```suggestion
  <SacrificialFlag.description>Флаг, ассоциирующийся с врагами. Используется для сожжения в ритуалах.</SacrificialFlag.description>
```

2021-09-14 10:40 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <SleepAccelerator.description>Прикроватное устройство, влияющее на циркадный ритм спящего. Оно повышает качество сна, снижая его продолжительность. Использует много электроэнергии, а так же вызывае
```suggestion
  <SleepAccelerator.description>Прикроватное устройство, влияющее на циркадный ритм спящего. Оно повышает качество сна, уменьшая его продолжительность. Использует много электроэнергии, а так же повышает аппетит. Стимулятор сна должен располагаться рядом с изголовьем кровати, фронтальной частью к нему. Размещение более чем одного экземпляра рядом с кроватью не окажет никакого эффекта.</SleepAccelerator.description>
```

2021-09-14 10:42 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <NeuralSupercharger.comps.CompNeuralSupercharger.jobString>Процесс стимуляции нейронов</NeuralSupercharger.comps.CompNeuralSupercharger.jobString>
```suggestion
  <NeuralSupercharger.comps.CompNeuralSupercharger.jobString>Получить нейростимуляцию</NeuralSupercharger.comps.CompNeuralSupercharger.jobString>
```

2021-09-14 10:46 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <NeuralSupercharger.description>Устройство, используемое для возбуждения нейронных клеток, может использоваться раз в день. Человек, применивший стимулятор, будет думать и учиться быстрее, однако д
```suggestion
  <NeuralSupercharger.description>Устройство, используемое для повышения чувствительности нейронов, может использоваться раз в день. Ускоряет работу мозга и усиливает эффективность обучения за счёт повышения аппетита. Эффект длится один день. Нейронные стимуляторы требуют большое количество энергии.</NeuralSupercharger.description>
```

2021-09-14 10:47 UTC, kamadz requested changes
.

2021-09-14 12:14 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Various.xml
> +  <Apparel_BodyStrap.description>Ремень, который наматывают на тело раба. Он напоминает носителю о его рабском статусе, что давит на психику и уменьшает вероятность восстания.</Apparel_BodyStrap.desc
![image](https://user-images.githubusercontent.com/57110948/133255664-19092a4e-7a60-4361-8ee4-1c4dc9c98c98.png)

2021-09-14 12:16 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Various.xml
> +  <Apparel_TortureCrown.label>корона страданий</Apparel_TortureCrown.label>
![chrome_zqvJUyoW0g](https://user-images.githubusercontent.com/57110948/133255818-dda9f087-0b3a-44a0-ad29-6bd1014cc990.png)
Ну не, тут прямо корона

2022-02-23 00:43 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_Collar.description>Неудобный ошейник для рабов. Он напоминает своему владельцу о его рабском положении, тем самым подавляя его. Уменьшает вероятность восстания.</Apparel_Collar.description
```suggestion
  <Apparel_Collar.description>Неудобный ошейник для рабов. Он напоминает носителю о его рабском положении, тем самым подавляя его. Уменьшает вероятность восстания.</Apparel_Collar.description>
```

2022-02-23 00:47 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_Tailcap.description>Шапка, сделанная из шкуры животного, с выделяющимся хвостом сзади. Зимой в ней достаточно тепло.</Apparel_Tailcap.description>
```suggestion
  <Apparel_Tailcap.description>Шапка из шкуры животного, с шикарным густым хвостом сзади. Зимой в ней достаточно тепло.</Apparel_Tailcap.description>
```

2022-02-23 00:49 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Apparel_Various.xml
> +  <Apparel_BodyStrap.description>Система ремней, повязывающаяся на верхнюю часть тела раба. Она напоминает носящему о его рабском положении, тем самым подавляя его. Уменьшает вероятность восстания.</
```suggestion
  <Apparel_BodyStrap.description>Система ремней, повязывающаяся на верхнюю часть тела раба. Напоминает носителю о его рабском положении, тем самым подавляя его. Уменьшает вероятность восстания.</Apparel_BodyStrap.description>
```

2022-02-23 00:50 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Apparel_Various.xml
> +  <Apparel_Robe.description>Длинная, свисающая мантия без капюшона.</Apparel_Robe.description>
```suggestion
  <Apparel_Robe.description>Длинная ниспадающая мантия без капюшона.</Apparel_Robe.description>
```

2022-02-23 00:53 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Active.xml
> +  <AncientEnemyTerminal.description>Древний компьютерный терминал. Был взломан давным-давно.</AncientEnemyTerminal.description>
```suggestion
  <AncientEnemyTerminal.description>Древний компьютерный терминал. Может быть взломан, чтобы призвать врагов неподалёку.</AncientEnemyTerminal.description>
```

2022-02-23 00:55 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Active.xml
> +  <AncientHermeticCrate.description>Герметичный контейнер с автономным источником питания, использовался для хранения ценных вещей. Он может хранить их долгое время.</AncientHermeticCrate.description
```suggestion
  <AncientHermeticCrate.description>Герметичный контейнер с автономным источником питания для хранения ценных вещей. Вещи в таких контейнерах могут не ветшать долгое время.</AncientHermeticCrate.description>
```

2022-02-23 00:58 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Active.xml
> +  <AncientSecurityCrate.description>Большой контейнер с автономным источником питания и встроенной системой сигнализации. Может хранить вещи в течение долгого времени. Если попытаться открыть его без
```suggestion
  <AncientSecurityCrate.description>Большой герметичный контейнер с автономным источником питания и встроенной системой сигнализации. Предметы в таких контейнерах могут не ветшать долгое время. Если попытаться открыть его без кода доступа, могут активироваться защитные механизмы.</AncientSecurityCrate.description>
```

2022-02-23 01:03 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Art.xml
> +  <SculptureTerror.description>Внушающая ужас скульптура. Рабы испытывают страх, находясь рядом с ней. Это делает их более подавленными, и, таким образом, приводит к уменьшению шанса восстания.</Scul
```suggestion
  <SculptureTerror.description>Внушающая ужас скульптура высотой в человеческий рост. Рабы испытывают страх, находясь рядом с ней. Это продлевает их подавленное состояние, а значит уменьшает вероятность восстания.</SculptureTerror.description>
```

2022-02-23 01:07 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Indoors.xml
> +  <AncientGenerator.description>Древний электрический генератор. Всё, что не успели растащить на части, давным-давно пришло в негодность, а всё, что осталось, проржавело насквозь.</AncientGenerator.d
```suggestion
  <AncientGenerator.description>Древний электрический генератор. Всё, что не успели растащить на части, давным-давно пришло в негодность, а остальное проржавело насквозь.</AncientGenerator.description>
```

2022-02-23 01:11 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <BiosculpterPod.comps.CompBiosculpterPod_HealingCycle.description>Излечены все раны и одна случайная постоянная травма.</BiosculpterPod.comps.CompBiosculpterPod_HealingCycle.description>
```suggestion
  <BiosculpterPod.comps.CompBiosculpterPod_HealingCycle.description>Излечить все свежие раны и одну случайную постоянную травму.</BiosculpterPod.comps.CompBiosculpterPod_HealingCycle.description>
```

2022-02-23 01:12 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <BiosculpterPod.comps.CompBiosculpterPod_AgeReversalCycle.description>Произведёно омоложение на 1 год.</BiosculpterPod.comps.CompBiosculpterPod_AgeReversalCycle.description>
```suggestion
  <BiosculpterPod.comps.CompBiosculpterPod_AgeReversalCycle.description>Обратить 1 год старения.</BiosculpterPod.comps.CompBiosculpterPod_AgeReversalCycle.description>
```

2022-02-23 01:12 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <BiosculpterPod.comps.CompBiosculpterPod_AgeReversalCycle.label>процесс изменения возраста</BiosculpterPod.comps.CompBiosculpterPod_AgeReversalCycle.label>
```suggestion
  <BiosculpterPod.comps.CompBiosculpterPod_AgeReversalCycle.label>обращение старения</BiosculpterPod.comps.CompBiosculpterPod_AgeReversalCycle.label>
```

2022-02-23 01:13 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <BiosculpterPod.comps.CompBiosculpterPod_HealingCycle.label>процесс исцеления</BiosculpterPod.comps.CompBiosculpterPod_HealingCycle.label>
```suggestion
  <BiosculpterPod.comps.CompBiosculpterPod_HealingCycle.label>исцеление</BiosculpterPod.comps.CompBiosculpterPod_HealingCycle.label>
```

2022-02-23 01:16 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <ChristmasTree.description>Праздничное дерево, украшенная гирляндой и игрушками, традиционно изготовленными в рамках торжественных праздников.</ChristmasTree.description>
```suggestion
  <ChristmasTree.description>Праздничное дерево, украшенное гирляндой и игрушками, традиционно изготовленными в рамках рождественских праздников.</ChristmasTree.description>
```

2022-02-23 01:18 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <Darklamp.description>Маломощная электрическая напольная лампа, которая излучает тусклый свет на большой территории. Люди, которые предпочитают работать в тусклом освещении, будут довольны этим ист
```suggestion
  <Darklamp.description>Маломощная напольная электрическая лампа, которая излучает тусклый свет на большой территории. Люди, которые предпочитают работать в тусклом освещении, будут довольны этим источником света.</Darklamp.description>
```

2022-02-23 01:24 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <SleepAccelerator.description>Прикроватное устройство, влияющее на циркадный ритм спящего. Оно повышает качество сна, уменьшая его продолжительность. Использует много энергии, а так же повышает апп
```suggestion
  <SleepAccelerator.description>Прикроватное устройство, влияющее на циркадный ритм спящего. Согращает необходимую продолжительность сна, но повышает аппетит. Использует много энергии. Стимулятор сна должен располагаться рядом с изголовьем кровати, фронтальной частью к нему. Размещение более одного экземпляра рядом с кроватью не окажет никакого эффекта.</SleepAccelerator.description>
```

2022-02-23 01:26 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientKitchenSink.description>Древняя кухонная раковина, сделанная из некого неметаллического листового материала. Он сильно испорчен, и нет никакой возможности что-либо спасти.\n\nКак он сюда по
```suggestion
  <AncientKitchenSink.description>Древняя кухонная раковина, сделанная из некоего неметаллического листового материала. Он сильно испорчен, и нет никакой возможности что-либо спасти.\n\nКак он сюда попал? Наверное, это долгая история.</AncientKitchenSink.description>
```

2022-02-23 01:28 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientLargeCrate.description>Этот большой ящик был оставлен здесь годы назад. Он слишком ржавый, чтобы использовать его по назначению.</AncientLargeCrate.description>
```suggestion
  <AncientLargeCrate.description>Этот большой ящик был оставлен здесь давным-давно. Он слишком ржавый, чтобы использовать его по назначению.</AncientLargeCrate.description>
```

2022-02-23 01:28 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientLongCrate.description>Длинный пустой и проржавевший ящик, оставленный здесь годы назад.</AncientLongCrate.description>
```suggestion
  <AncientLongCrate.description>Длинный пустой и проржавевший ящик, оставленный здесь давным-давно.</AncientLongCrate.description>
```

2022-02-23 01:31 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
>    <AncientRustedDropship.description>Остатки древнего челнока. Ценные части были давно растащили, а остальное пришло в негодность.</AncientRustedDropship.description>
```suggestion
  <AncientRustedDropship.description>Останки древнего челнока. Ценные части давно растащили, а остальное пришло в негодность.</AncientRustedDropship.description>
```

2022-02-23 01:35 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientShoppingCart.description>Древняя проржавевшая тележка для покупок. Как она здесь оказалась - большая загадка, однако эта история, наверное, длинная и очень грустная.</AncientShoppingCart.de
```suggestion
  <AncientShoppingCart.description>Древняя проржавевшая тележка для покупок. Как она здесь оказалась — большая загадка, однако история эта длинна и наверняка грустна.</AncientShoppingCart.description>
```

2022-02-23 01:37 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientSmallCrate.description>Маленький пустой ящик, оставленный здесь годы назад. Он слишком ржавый, чтобы использовать его по назначению.</AncientSmallCrate.description>
```suggestion
  <AncientSmallCrate.description>Маленький пустой ящик, оставленный здесь давным-давно. Он слишком ржавый, чтобы использовать его по назначению.</AncientSmallCrate.description>
```

2022-02-23 01:37 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientTankTrap.label>древняя противотанковый ёж</AncientTankTrap.label>
```suggestion
  <AncientTankTrap.label>древний противотанковый ёж</AncientTankTrap.label>
```

2022-02-23 01:42 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
>    <!-- EN: ancient vending machine -->
Не могу оставить комментарий к строке 207.
Вместо `\n\nак` должно быть `\n\nКак`.

2022-02-23 01:45 UTC, Dimonasdf commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientWarwalkerLeg.description>Раздробленная нога боевого шагохода среднего размера, оставлена здесь давным давно. Полезные компоненты или разграблены, или разрушены.</AncientWarwalkerLeg.descrip
```suggestion
  <AncientWarwalkerLeg.description>Раздробленная нога боевого шагохода среднего размера, оставлена здесь давным-давно. Полезные компоненты или разграблены, или разрушены.</AncientWarwalkerLeg.description>
```

2022-02-23 01:47 UTC, Dimonasdf requested changes
Посмотрел.

2022-02-26 12:57 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
>    <!-- EN: ancient vending machine -->
Исправлено в мастер-ветке

2022-02-28 21:30 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Headgear.xml
> +  <Apparel_Tailcap.description>Шапка из шкуры животного, с шикарным густым хвостом сзади. Зимой в ней достаточно тепло.</Apparel_Tailcap.description>
```suggestion
  <Apparel_Tailcap.description>Шапка из шкуры животного, с шикарным густым хвостом сзади. Хорошо сохраняет тепло зимой.</Apparel_Tailcap.description>
```

2022-02-28 21:30 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Apparel_Various.xml
> +  <Apparel_Blindfold.description>Длинная полоска ткани, которая полностью закрывает глаза.</Apparel_Blindfold.description>
```suggestion
  <Apparel_Blindfold.description>Длинная полоса ткани, которая полностью закрывает глаза.</Apparel_Blindfold.description>
```

2022-02-28 21:39 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
> +  <NeuralSupercharger.description>Синтезатор нейронов, используемый для получения нейронного заряда. Нейронный заряд ускоряет работу мозга и усиливает эффективность обучения, ценой повышения аппетита
neuron-sensitizing /= neuron-synthesizing

2022-02-28 22:56 UTC, merged