Ideology/DefInjected/ThingDef, part 2
Ludeon/RimWorld-ru pull request #1314
Opened 2021-08-08 09:13 UTC by EtoZheJih

2021-09-14 12:05 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <Autobong.description>Устройство, используемое для автоматического сжигания дымолиста и выделения большого количество дыма. Чтобы поселенец получил кайф от курения, он должен оставаться в дыму како
```suggestion
  <Autobong.description>Устройство, используемое для автоматического сжигания дымолиста и выделения большого количество дыма. Чтобы поселенец получил кайф от курения, он должен какое-то время находиться в дыму.</Autobong.description>
```

2021-09-14 12:06 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <DryadCocoon.description>Сфера из волокнистой растительной материи. Дриада внутри неё медленно трансформируется в новую форму. Деревья Гауранлен выращивают эти коконы, чтобы помощь защитить дриад в
```suggestion
  <DryadCocoon.description>Сфера из волокнистой растительной материи. Дриада внутри неё медленно трансформируется в новую форму. Деревья Гауранлен выращивают эти коконы, чтобы защищать дриад во время их трансформации.</DryadCocoon.description>
```

2021-09-14 12:07 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <GaumakerCocoon.description>Этот симбионт растения и животного появляется в результате слияния нескольких дриад-гау. Через некоторое время он превратится в семя Гуаранлена, который можно будет испо
```suggestion
  <GaumakerCocoon.description>Этот симбионт растения и животного появляется в результате слияния нескольких дриад-гау. Через некоторое время он превратится в семя Гауранлена, которое можно будет использовать для посадки.</GaumakerCocoon.description>
```

2021-09-14 12:08 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <GibbetCage.description>Стальная клетка для хранения и демонстрации трупов. Это ужасающее зрелище внушает ужас и отвращение наблюдателям. Является особенно жестоким, но эффективным способом террори
```suggestion
  <GibbetCage.description>Стальная клетка для хранения и демонстрации трупов. Это ужасающее зрелище внушает страх и отвращение смотрящим. Является особенно жестоким, но эффективным способом запугивать рабов.</GibbetCage.description>
```

2021-09-15 07:38 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <KneelPillow.description>Подушка, на которую встают коленями во время ритуалов, молитв или рассуждений.</KneelPillow.description>
```suggestion
  <KneelPillow.description>Подушка, на которую встают коленями во время ритуалов, молитв или общественных обсуждений.</KneelPillow.description>
```

2021-09-15 07:40 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <KneelSheet.description>Покрывало, на котором верующие, стоя на коленях, исполняют ритуалы, молятся или занимаются рассуждениями.</KneelSheet.description>
```suggestion
  <KneelSheet.description>Коврик, на который встают коленями во время ритуалов, молитв или общественных обсуждений.</KneelSheet.description>
```

2021-09-15 07:40 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <KneelSheet.label>молитвенное покрывало</KneelSheet.label>
```suggestion
  <KneelSheet.label>молитвенный коврик</KneelSheet.label>
```

2021-09-15 07:41 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <Loudspeaker.label>бумбокс</Loudspeaker.label>
```suggestion
  <Loudspeaker.label>динамик</Loudspeaker.label>
```
каво

2021-09-15 08:00 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <Lectern.label>трибуна</Lectern.label>
```suggestion
  <Lectern.label>кафедра</Lectern.label>
```

2021-09-15 08:02 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <PlantPot_Bonsai.label>горшок для бонсай</PlantPot_Bonsai.label>
```suggestion
  <PlantPot_Bonsai.label>горшок для бонсая</PlantPot_Bonsai.label>
```
Бонсай склоняется

2021-09-15 10:39 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Filth_Various.xml
> +  <Filth_MoldyUniform.label>разорванная униформа</Filth_MoldyUniform.label>
```suggestion
  <Filth_MoldyUniform.label>рваная униформа</Filth_MoldyUniform.label>
```

2021-09-15 10:39 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Filth_Various.xml
> +  <Filth_OilSmear.label>след из масла</Filth_OilSmear.label>
```suggestion
  <Filth_OilSmear.label>масляное пятно</Filth_OilSmear.label>
```

2021-09-15 10:39 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Filth_Various.xml
> +  <Filth_ScatteredDocuments.label>разрозненные документы</Filth_ScatteredDocuments.label>
```suggestion
  <Filth_ScatteredDocuments.label>разбросанные документы</Filth_ScatteredDocuments.label>
```

2021-09-15 10:40 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Ethereal_Skyfallers.xml
> +  <SkyLantern.label>небесный фонарик</SkyLantern.label>
```suggestion
  <SkyLantern.label>небесный фонарь</SkyLantern.label>
```

2021-09-15 10:57 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <LightBall.description>Декоративная круглая лампа, которая вращается и меняет цвет.  Используется для проведения танцевальных вечеринок.</LightBall.description>
```suggestion
  <LightBall.description>Декоративная круглая лампа, которая вращается и переливается разными цветами.  Используется для проведения танцевальных вечеринок.</LightBall.description>
```

2021-09-15 10:57 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <Loudspeaker.description>Большой бумбокс, используемый для воспроизведения музыки. Как минимум один бумбокс необходим для проведения танцевальной вечеринки. Чем их больше - тем круче вечеринка!</Lo
```suggestion
  <Loudspeaker.description>Большой динамик, используемый для проигрывания музыки. Как минимум один динамик необходим для проведения танцевальной вечеринки. Чем их больше - тем круче вечеринка!</Loudspeaker.description>
```

2021-09-15 11:00 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <Pew.description>Длинная скамейка, на которой участники ритуала могут сидеть, слушая оратора. Поместите его перед местом ритуала или выступлением оратора, чтобы продлить продолжительность положител
```suggestion
  <Pew.description>Длинная скамейка, на которой участники ритуала могут сидеть и слушть оратора. Поместите её перед местом проведения ритуала или речи, чтобы продлить их положительные эффекты.</Pew.description>
```

2021-09-15 11:01 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <PlantPot_Bonsai.description>Этот специальный горшок подходит для посадки и выращивания деревьев бонсай, которые могут улучшить настроение окружающих и удовлетворить идеологические требования посел
```suggestion
  <PlantPot_Bonsai.description>Этот специальный горшок подходит для посадки и выращивания бонсая, дерева, которое могут улучшить настроение окружающих и удовлетворить идеолигиозные требования поселенцев.</PlantPot_Bonsai.description>
```

2021-09-15 11:05 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Races_Animal_Special.xml
> +﻿<?xml version="1.0" encoding="UTF-8"?>
У нас уже есть исправленные описания для каст.
Нужно привести содержимое документа к этим описаниям, внимательно прочитать текст и прогнать его спеллчекером. 
Убедиться, что на месте тире стоят именно тире (—), а не дефисы (-). Разницу можно нагуглить, если непонятно.

2021-09-15 11:06 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Relics.xml
> +﻿<?xml version="1.0" encoding="UTF-8"?>
Необходимо идеологическое исправить везде на идеолигиозное.

2021-09-15 11:07 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Relics.xml
> +  <RelicInertBox.label>коробок</RelicInertBox.label>
```suggestion
  <RelicInertBox.label>короб</RelicInertBox.label>
```
Спичек?

2021-09-15 11:25 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Special.xml
> +  <ArchonexusCore.description>Центральное ядро архонексуса. Его поверхность идеально чистая, и она почему-то кажется одновременно и плоской, и изогнутой.\n\n Большинство людей не поймут его предназна
```suggestion
  <ArchonexusCore.description>Центральное ядро архонексуса. Его поверхность идеально чистая и почему-то кажется одновременно и плоской, и изогнутой.\n\nБольшинству непостижимо его предназначение, однако бытует мнение, что это часть самого архотеха, и что тот, кто найдет его, сможет призвать силу бога-машины.\n\nОн излучает ужасающе мощное пси-излучение, которое невозможно услышать, но от которого люди буквально глохнут. Его можно услышать глухим, увидеть слепым и даже помнить, потеряв свою память. Ядро излучает мысли существа, находящегося на другом уровне существования. Немногие могут сохранить рассудок, подойдя к нему слишком близко и ощутив весь груз колоссального ментального давления. Только психически-невосприимчивые люди имеют иммунитет к его воздействию.</ArchonexusCore.description>
```

2021-09-15 11:26 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Special.xml
> +  <GrandArchotechStructure.label>великая структура архотеха</GrandArchotechStructure.label>
```suggestion
  <GrandArchotechStructure.label>огромная структура архотеха</GrandArchotechStructure.label>
```

2021-09-15 11:26 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Special.xml
> +  <ArchotechTower.label>башня архотеха</ArchotechTower.label>
```suggestion
  <ArchotechTower.label>башня архотека</ArchotechTower.label>
```

2021-09-15 11:27 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Special.xml
> +  <ArchotechTower.description>Башня архотеха, возвыщающаяся над землёй. Рисунки на её поверхности постоянно светятся странными светом. Люди могут только догадываться о её предназначении.</ArchotechTo
```suggestion
  <ArchotechTower.description>Башня архотека, возвыщающаяся над землёй. Рисунки на её поверхности постоянно светятся странными светом. Люди могут только догадываться о её предназначении.</ArchotechTower.description>
```

2021-09-15 11:32 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <StylingStation.label>столик стилиста</StylingStation.label>
```suggestion
  <StylingStation.label>туалетный столик
  </StylingStation.label>
```
Серьёзно?

2021-09-15 11:36 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <Autobong.label>Автоматический бонг</Autobong.label>
```suggestion
  <Autobong.label>Автобонг</Autobong.label>
```

2021-09-15 11:37 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Special.xml
> +  <MajorArchotechStructure.label>главная структура архотеха</MajorArchotechStructure.label>
```suggestion
  <MajorArchotechStructure.label>главная структура архотеков</MajorArchotechStructure.label>
```

2021-09-15 12:53 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Plants_Special.xml
> +  <GauranlenSeed.label>семена Гуаранлен</GauranlenSeed.label>
```suggestion
  <GauranlenSeed.label>семена Гауранлен</GauranlenSeed.label>
```

2021-09-15 12:53 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Plants_Special.xml
> +  <Plant_Fibercorn.description>Несъедобное, волокнистое растение, которое выделяет небольшое количество древовидной субстанции.</Plant_Fibercorn.description>
```suggestion
  <Plant_Fibercorn.description>Несъедобное волокнистое растение, которое выделяет небольшое количество древовидной субстанции.</Plant_Fibercorn.description>
```

2021-09-15 12:53 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Plants_Special.xml
> +  <Plant_MossGauranlen.description>Симбиотический мох, который растёт на деревьях Гуаранлен.</Plant_MossGauranlen.description>
```suggestion
  <Plant_MossGauranlen.description>Симбиотический мох, который растёт на деревьях Гауранлен.</Plant_MossGauranlen.description>
```

2021-09-15 12:54 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Plants_Special.xml
> +  <Plant_Nutrifungus.description>Мясистый гриб, выращенный благодаря биоинженерному искусству. Молжет расти на грибковом гравии, но только в темноте - воздействие любого вида света убьёт его.</Plant_
```suggestion
  <Plant_Nutrifungus.description>Мясистый гриб искусственного происхождения. Молжет расти на грибковом гравии, но только в темноте - воздействие любого вида света убьёт его.</Plant_Nutrifungus.description>
```

2021-09-15 12:55 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Plants_Special.xml
> +  <Plant_MossGauranlen.description>Симбиотический мох, который растёт на деревьях Гуаранлен.</Plant_MossGauranlen.description>
```suggestion
  <Plant_MossGauranlen.description>Симбиотический мох, который растёт рядом с деревьями Гауранлен.</Plant_MossGauranlen.description>
```

2021-09-15 12:55 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Plants_Special.xml
> +  <Plant_PodGauranlen.label>семенная капсула Гуаранлен</Plant_PodGauranlen.label>
```suggestion
  <Plant_PodGauranlen.label>семенная капсула Гауранлен</Plant_PodGauranlen.label>
```

2021-09-15 12:56 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Plants_Special.xml
> +  <Plant_PodGauranlen.description>Капсула, защищающая одно семечко Гуаранлен. Это семя можно посадить, чтобы вырастить своё дерево Гуаранлен.</Plant_PodGauranlen.description>
```suggestion
  <Plant_PodGauranlen.description>Капсула, покрывающая одно семечко Гауранлен. Это семя можно посадить, чтобы вырастить древо Гауранлен.</Plant_PodGauranlen.description>
```

2021-09-15 12:56 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Plants_Special.xml
> +  <Plant_Timbershroom.description>Высокий коричневый гриб с длинным стеблем. При сборе из него можно получить вещество, похожее на древесину.</Plant_Timbershroom.description>
```suggestion
  <Plant_Timbershroom.description>Высокий коричневый гриб с длинным стеблем. Из него можно получить вещество, похожее на древесину.</Plant_Timbershroom.description>
```

2021-09-15 12:59 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Plants_Special.xml
> +  <Plant_Tinctoria.description>Генетически-модифицированное растение, которое выделяет самоизменяющийся краситель. Краситель индигоферы можно окрашивать в разные цвета и использовать для окрашивания
```suggestion
  <Plant_Tinctoria.description>Генетически-модифицированное растение, которое выделяет универсальный краситель. Его для окрашивания одежды в самые разные цвета.</Plant_Tinctoria.description>
```

2021-09-15 13:03 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Plants_Special.xml
> +  <Plant_Tinctoria.label>индигофера</Plant_Tinctoria.label>
```suggestion
  <Plant_Tinctoria.label>нео-индигофера</Plant_Tinctoria.label>
```
Предлагаю так, будет лучше передавать смысл. Если да, то сверху тоже надо поменять.

2021-09-15 13:04 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Plants_Special.xml
> +  <Plant_TreeGauranlen.label>дерево Гуаранлен</Plant_TreeGauranlen.label>
```suggestion
  <Plant_TreeGauranlen.label>древо Гауранлен</Plant_TreeGauranlen.label>
```

2021-09-15 13:05 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Plants_Special.xml
> +  <Plant_TreeBonsai.description>Искуственно сформированное карликовое дерево, ухожено и аккуратно подстрижено.</Plant_TreeBonsai.description>
```suggestion
  <Plant_TreeBonsai.description>Карликовое дерево, ухожено и аккуратно подстрижено, чтобы радовать глаз.</Plant_TreeBonsai.description>
```

2021-09-15 13:12 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Plants_Special.xml
> +  <Plant_TreeGauranlen.description>Большое, необычно-выглядящее дерево с уникальным жизненным циклом. Каждое дерево Гуаранлен содержит маленькую королеву дриад, находящуюся в безсознательном состояни
```suggestion
  <Plant_TreeGauranlen.description>Большое, необычное дерево с уникальным жизненным циклом. Каждое древо Гауранлен содержит в себе маленькое создание, находящееся в безсознательном состоянии и называющееся королевой дриад. Она порождает существ, которых называют дриадами. Они ухаживают за деревом и охраняют его. В обмен на это, дерево заботится о своих защитниках, питая их напрямую. Со стороны кажется, что дриады являются частью древа и созданы непосредственно им.\n\nНекоторые говорят, что древо Гауранлен - это дом духа природы, который следует за человеком, куда бы он не направился.</Plant_TreeGauranlen.description>
```

2021-09-15 13:23 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Special.xml
> +  <GrandArchotechStructure.description>Грандиозная структура архотеха, имеет огромную высоту и впечатляющую массу. Её форму трудно идентифицировать, при долгом наблюдении можно заметить, словно её по
```suggestion
  <GrandArchotechStructure.description>Огромное строение архотеков огромных высоты и размеров. Форму строения трудно распознать, при долгом наблюдении начинает казаться, что его поверхность медленно движется. Это строение могло появиться здесь пару минут назад, а может находиться здесь уже на протяжении тысячелетий.\n\nОно излучает интенсивное пси-излучение, проникающее в разум любого, кто рискнёт подойти слишком близко. Это пси-излучение похоже на невероятно мощный поток сознания, не агрессивного, но чужеродного. Ощущения, не связанные ни временем, ни пространством, бесконечные размышления постороннего разума, больше и сложнее человеческого в миллиарды раз. Неподготовленные люди быстро теряют рассудок, и только психически-невосприимчивые люди обладают к нему иммунитетом.</GrandArchotechStructure.description>
```

2021-09-15 13:33 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Special.xml
> +  <MajorArchotechStructure.description>Главная структура архотеха. Её тускло-зелёная поверхность находится в идеальном состоянии и кажется настолько гладкой, будто можно на ней подскользнуться. Невоз
```suggestion
  <MajorArchotechStructure.description>Главное строение архотеков. Его тускло-зелёная поверхность выглядит идеально и кажется настолько гладкой, будто на ней можно поскользнуться. Невозможно определить, как долго и для какой цели это строение здесь находится\n\nПси-излучение, которое оно создаёт, не агрессивно, однако оно чужеродно и обладает невероятно огромной силой. Воздействие излучения можно описать как нахождение внутри монструозного механизма, полного вращающихся лезвий, внутри сердца спящего титана, внутри тесного тоннеля, внутри которого ты не можешь двигаться, говорить и даже дышать. Любой, кто попадёт под него, пожалеет о своём решении. Только психически-невосприимчивые люди обладают иммунитетом к излучению.</MajorArchotechStructure.description>
```

2021-09-15 13:34 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <StylingStation.description>Столик с зеркалом и инструментами для укладки. Поселенцы могут использовать его для изменения внешнего вида.</StylingStation.description>
```suggestion
  <StylingStation.description>Столик с зеркалом и инструментами для ухода за собой. Поселенцы могут использовать его для изменения внешнего вида.</StylingStation.description>
```

2021-09-15 13:39 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <Lectern.description>Высокий склон с немного наклонённой поверхностью, на которой перед выступающим находится текст. Распологается рядом с местом проведения ритуалов и речей, чтобы продлить продолж
```suggestion
  <Lectern.description>Высокий склон с немного наклонённой поверхностью, на которой перед выступающим находится текст. Расположите рядом с местом проведения ритуалов или речи, чтобы продлить их положительные эффекты.</Lectern.description>
```

2021-09-15 13:44 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <SlabBed.description>Кровать, выполненная из плит твёрдого материала. На ней неудобно спать, но некоторые рассматривают её как способ демонстрации благонравия.</SlabBed.description>
```suggestion
  <SlabBed.description>Плита, высеченная из твёрдого материала. На ней неудобно спать, но некоторые рассматривают это как способ демонстрации благонравия.</SlabBed.description>
```
Вообще из камня, но мб потом планируются другие твёрдые материалы.

2021-09-15 13:44 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <SlabDoubleBed.description>Кровать, выполненная из плит твёрдого материала. На ней неудобно спать, но некоторые рассматривают её как способ демонстрации благонравия. На ней хватит места для двух че
```suggestion
  <SlabDoubleBed.description>Плита, высеченная из твёрдого материала. На ней неудобно спать, но некоторые рассматривают это как способ демонстрации благонравия.. На ней хватит места для двух человек.</SlabDoubleBed.description>
```

2021-09-15 15:08 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <Reliquary.description>Церемониальная шкатулка, которая демонстрирует и защищает реликвию. Реликвии - это древние предметы, почитаемые верующими определенной идеологии.</Reliquary.description>
```suggestion
  <Reliquary.description>Вместилище для хранения реликвий. Реликвии - это древние предметы, почитаемые последователями различных идеолигий.</Reliquary.description>
```

2021-09-15 15:11 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <Skullspike.description>Вертикально установленная пика, на которую насаживают человеческие черепа. Для некоторых выставленные черепа являются символов власти, для других же, они являются олицетворе
```suggestion
  <Skullspike.description>Пика, на которую насаживают человеческие черепа. Для некоторых это является символом власти, для других же — олицетворением варварства и зла. Пики с черепами - жестокий, но эффективный способ запугивать рабов.</Skullspike.description>
```

2021-09-15 15:13 UTC, kamadz commented on Ideology/DefInjected/ThingDef/FloorCoverings.xml
> +  <AnimalistSlab_Broad.label>барельеф анимализма (большой)</AnimalistSlab_Broad.label>
```suggestion
  <AnimalistSlab_Broad.label>анималистский барельеф (большой)</AnimalistSlab_Broad.label>
```

2021-09-15 15:14 UTC, kamadz commented on Ideology/DefInjected/ThingDef/FloorCoverings.xml
> +  <AnimalistSlab_Broad.description>Деревянный барельеф, олицетворяющий суть анимализма. Подходит для украшения комнаты.</AnimalistSlab_Broad.description>
```suggestion
  <AnimalistSlab_Broad.description>Деревянный барельеф с анималистскими мотивами. Подходит для украшения полов.</AnimalistSlab_Broad.description>
```

2021-09-15 15:16 UTC, kamadz commented on Ideology/DefInjected/ThingDef/FloorCoverings.xml
> +  <AnimalistSlab_Medium.label>барельеф анимализма (средний)</AnimalistSlab_Medium.label>
```suggestion
  <AnimalistSlab_Medium.label>анималистский барельеф (средний)</AnimalistSlab_Medium.label>
```

2021-09-15 15:18 UTC, kamadz commented on Ideology/DefInjected/ThingDef/FloorCoverings.xml
> +  <MorbidSlab_Medium.description>Мрачный барельеф выполненный на камне, используется для украшения комнат.</MorbidSlab_Medium.description>
```suggestion
  <MorbidSlab_Broad.description>Барельеф с мрачными мотивами. Подходит для украшения полов.</MorbidSlab_Broad.description>
  
  <!-- EN: morbid slab (medium) -->
  <MorbidSlab_Medium.label>мрачный барельеф (средний)</MorbidSlab_Medium.label>
  <!-- EN: A stone bas relief of morbid imagery for decorating a floor. -->
  <MorbidSlab_Medium.description>Барельеф с мрачными мотивами. Подходит для украшения полов.</MorbidSlab_Medium.description>
```

2021-09-15 15:21 UTC, kamadz commented on Ideology/DefInjected/ThingDef/FloorCoverings.xml
> +  <RusticRug_Medium.description>Ковёр, выполненный в старинном стиле глубоких деревень. Используется для украшения комнат.</RusticRug_Medium.description>
```suggestion
  <RusticRug_Broad.label>ковёр (большой)</RusticRug_Broad.label>
  <!-- EN: A homey rug with a rustic-style pattern, for decorating a floor. -->
  <RusticRug_Broad.description>Уютный ковёр с узорами в рустиканском стиле. Подходит для украшения полов.</RusticRug_Broad.description>
  
  <!-- EN: rustic rug (medium) -->
  <RusticRug_Medium.label>ковёр (средний)</RusticRug_Medium.label>
  <!-- EN: A homey rug with a rustic-style pattern, for decorating a floor. -->
  <RusticRug_Medium.description>Уютный ковёр с узорами в рустиканском стиле. Подходит для украшения полов.</RusticRug_Medium.description>
```

2021-09-15 15:22 UTC, kamadz commented on Ideology/DefInjected/ThingDef/FloorCoverings.xml
> +  <SpikecoreFloorStar_Broad.description>Металлические шипы, расположенные в форме звезды. Используется для украшения пола.</SpikecoreFloorStar_Broad.description>
```suggestion
  <SpikecoreFloorStar_Broad.description>Металлические шипы в форме звезды. Подходит для украшения полов.</SpikecoreFloorStar_Broad.description>
```

2021-09-15 15:22 UTC, kamadz commented on Ideology/DefInjected/ThingDef/FloorCoverings.xml
> +  <SpikecoreFloorStar_Medium.description>Металлические шипы, расположенные в форме звезды. Используется для украшения пола.</SpikecoreFloorStar_Medium.description>
```suggestion
  <SpikecoreFloorStar_Medium.description>Металлические шипы в форме звезды. Подходит для украшения полов.</SpikecoreFloorStar_Medium.description>
```

2021-09-15 15:24 UTC, kamadz commented on Ideology/DefInjected/ThingDef/FloorCoverings.xml
> +  <TotemicSlab_Medium.description>Барельеф, олицетворяющий суть тотемизма. Используется для украшения комнат.</TotemicSlab_Medium.description>
```suggestion
  <TotemicSlab_Broad.label>тотемический барельеф (большой)</TotemicSlab_Broad.label>
  <!-- EN: A wooden bas relief of totemic imagery for decorating a floor. -->
  <TotemicSlab_Broad.description>Барельеф с тотемическими мотивами. Подходит для украшения полов.</TotemicSlab_Broad.description>
  
  <!-- EN: totemic slab (medium) -->
  <TotemicSlab_Medium.label>тотемический барельеф (средний)</TotemicSlab_Medium.label>
  <!-- EN: A wooden bas relief of totemic imagery for decorating a floor. -->
  <TotemicSlab_Medium.description>Барельеф, олицетворяющий суть тотемизма. Подходит для украшения полов.</TotemicSlab_Medium.description>
```

2021-09-15 15:25 UTC, kamadz requested changes
:(

2021-12-09 22:03 UTC, Elevator89 requested changes

2021-12-09 22:13 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <KneelPillow.description>Подушка, на которую встают коленями во время ритуалов, молитв или общественных обсуждений.</KneelPillow.description>
@kamadz, это была твоя правка )

2021-12-11 17:06 UTC, Elevator89 requested changes

2021-12-11 17:06 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Plants_Special.xml
> +  <Plant_TreeGauranlen.description>Большое и необычное дерево с уникальным жизненным циклом. Каждое древо Гауранлен содержит в себе маленькое создание, находящееся в безсознательном состоянии и назыв
Пропущено целое предложение
```suggestion
  <Plant_TreeGauranlen.description>Большое и необычное дерево с уникальным жизненным циклом. В каждом древе Гауранлен в бессознательном состоянии находится королева дриад. Она порождает существ, называемых дриадами, которые ухаживают за древом и охраняют его. В обмен на это, древо заботится о своих защитниках, питая их напрямую. Со стороны кажется, что дриады являются частью древа и созданы непосредственно им.\n\nЧеловек может наладить с древом связь, и влиять на тип дриад, который оно порождает.\n\nНекоторые говорят, что древо Гауранлен - это дом духа природы, который следует за человеком, куда бы он не направился.</Plant_TreeGauranlen.description>
```

2021-12-18 11:15 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <KneelPillow.description>Подушка, на которую встают коленями во время ритуалов, молитв или общественных обсуждений.</KneelPillow.description>
Как термина этого "discussing" нет. Имеются в виду **иделогические** ритуалы, которые обыгрываются как общественный сбор. Если в теистических идеолигиях люди собираются на проповеди, то в атеистических, соответственно, на светские общественные обсуждения.

2021-12-18 11:23 UTC, kamadz commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <Reliquary.description>Вместилище для хранения реликвий. Реликвии - это древние предметы, почитаемые последователями различных идеолигий.</Reliquary.description>
Предмет мебели не может быть сооружением 
![image](https://user-images.githubusercontent.com/57110948/146639012-f25cf04e-dfcb-4001-bea3-538b572649b8.png)

Перевод корректен.

2021-12-18 13:03 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/FloorCoverings.xml
> +  <SpikecoreFloorStar_Medium.description>Металлические шипы в форме звезды. Подходит для украшения полов.</SpikecoreFloorStar_Medium.description>
https://github.com/Ludeon/RimWorld-ru/pull/1353 - исправление остальных spikecore'ов

2021-12-18 13:27 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Races_Animal_Special.xml
> +  <Dryad_Barkskin.description>Каста дриад, основное назначение которых — принимать на себя удар во время боя. Дубокожи покрыты толстой, похожей на кору шкурой, частично сформированной самим древом Гу
```suggestion
  <Dryad_Barkskin.description>Каста дриад, основное назначение которых — принимать на себя удар во время боя. Дубокожи покрыты толстой, похожей на кору шкурой, частично сформированной самим древом Гуаранлен. Под руководством людей они могут сражаться, поглощая наносимый противником урон.\n\nДриады — это зверообразные существа, имеющие симбиотические отношения с древом Гуаранлен. С его помощью они размножаются, и в нём же находится их королева. У дриад существует несколько каст, и они могут видоизменять себя для перехода из одной касты в другую.</Dryad_Barkskin.description>
```

2021-12-18 13:27 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Races_Animal_Special.xml
> +  <Dryad_Basic.description>Дриады - это небольшие млекопитающие существа, которые имеют симбиотические отношения с деревом Гуаранлен. Эта незрелая дриада может поддерживать и защищать свое дерево, но
```suggestion
  <Dryad_Basic.description>Дриады — это небольшие зверообразные существа, имеющие симбиотические отношения с древом Гуаранлен. Эта незрелая дриада может поддерживать и защищать свое древо, но её главная цель — развиться до зрелой формы одной из специализированных каст.</Dryad_Basic.description>
```

2021-12-18 13:27 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Races_Animal_Special.xml
> +  <Dryad_Berrymaker.description>Каста дриад, занимающихся выработкой пищи. Эти дриады могут непрерывно производить питательные ягоды, но при этом медлительны и неэффективны в работе и в бою.\n\nДриад
```suggestion
  <Dryad_Berrymaker.description>Каста дриад, занимающихся выработкой пищи. Эти дриады могут непрерывно производить питательные ягоды, но при этом медлительны и неэффективны в работе и в бою.\n\nДриады — это зверообразные существа, имеющие симбиотические отношения с древом Гуаранлен. С его помощью они размножаются, и в нём же находится их королева. У дриад существует несколько каст, и они могут видоизменять себя для перехода из одной касты в другую.</Dryad_Berrymaker.description>
```

2021-12-18 13:27 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Races_Animal_Special.xml
> +  <Dryad_Carrier.description>Каста дриад, занимающихся переносом вещей. Под руководством людей они могут перемещать предметы туда, куда надо.\n\nДриады - это млекопитающие, имеющие симбиотические отн
```suggestion
  <Dryad_Carrier.description>Каста дриад, занимающихся переносом вещей. Под руководством людей они могут перемещать предметы туда, куда надо.\n\nДриады — это зверообразные существа, имеющие симбиотические отношения с древом Гуаранлен. С его помощью они размножаются, и в нём же находится их королева. У дриад существует несколько каст, и они могут видоизменять себя для перехода из одной касты в другую.</Dryad_Carrier.description>
```

2021-12-18 13:27 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Races_Animal_Special.xml
> +  <Dryad_Clawer.description>Дриады, основное предназначение которых — мощные атаки в бою. Своему названию они обязаны своим массивным когтям на лапах. Хоть эти дриады и могут наносить огромный урон,
```suggestion
  <Dryad_Clawer.description>Дриады, основное предназначение которых — мощные атаки в бою. Своему названию они обязаны своим массивным когтям на лапах. Хоть эти дриады и могут наносить огромный урон, сами они уязвимы к атакам.\n\nДриады — это зверообразные существа, имеющие симбиотические отношения с древом Гуаранлен. С его помощью они размножаются, и в нём же находится их королева. У дриад существует несколько каст, и они могут видоизменять себя для перехода из одной касты в другую.</Dryad_Clawer.description>
```

2021-12-18 13:27 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Races_Animal_Special.xml
> +  <Dryad_Gaumaker.description>Каста дриад, занимающихся производством новых семенных капсул древ Гуаранлен, а также созданий-симбиотов, королев дриад. Для этого требуется дождаться завершения длитель
```suggestion
  <Dryad_Gaumaker.description>Каста дриад, занимающихся производством новых семенных капсул древ Гуаранлен, а также созданий-симбиотов, королев дриад. Для этого требуется дождаться завершения длительного процесса слияния трёх гау.\n\nДриады — это зверообразные существа, имеющие симбиотические отношения с древом Гуаранлен. С его помощью они размножаются, и в нём же находится их королева. У дриад существует несколько каст, и они могут видоизменять себя для перехода из одной касты в другую.</Dryad_Gaumaker.description>
```

2021-12-18 13:27 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Races_Animal_Special.xml
> +  <Dryad_Medicinemaker.description>Каста дриад, занимающихся производством медикаментов. Эти дриады могут непрерывно выращивать лекарственные травы, но при этом медлительны и неэффективны в работе и
```suggestion
  <Dryad_Medicinemaker.description>Каста дриад, занимающихся производством медикаментов. Эти дриады могут непрерывно выращивать лекарственные травы, но при этом медлительны и неэффективны в работе и в бою.\n\nДриады — это зверообразные существа, имеющие симбиотические отношения с древом Гуаранлен. С его помощью они размножаются, и в нём же находится их королева. У дриад существует несколько каст, и они могут видоизменять себя для перехода из одной касты в другую.</Dryad_Medicinemaker.description>
```

2021-12-18 13:27 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Races_Animal_Special.xml
> +  <Dryad_Woodmaker.description>Каста медленных и неуклюжих дриад, занимающихся производством древесины. Эти дриады непрерывно производят похожий на древесину материал, но при этом медлительны и неэфф
```suggestion
  <Dryad_Woodmaker.description>Каста медленных и неуклюжих дриад, занимающихся производством древесины. Эти дриады непрерывно производят похожий на древесину материал, но при этом медлительны и неэффективны в работе и в бою.\n\nДриады — это зверообразные существа, имеющие симбиотические отношения с древом Гуаранлен. С его помощью они размножаются, и в нём же находится их королева. У дриад существует несколько каст, и они могут видоизменять себя для перехода из одной касты в другую.</Dryad_Woodmaker.description>
```

2021-12-19 12:53 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Misc.xml
> +  <KneelPillow.description>Подушка, на которую встают коленями во время ритуалов, молитв или общественных обсуждений.</KneelPillow.description>
Давай заменим так:
```suggestion
  <KneelPillow.description>Подушка, на которую встают коленями во время ритуалов, молитв и публичных собраний.</KneelPillow.description>
```

2021-12-20 21:34 UTC, merged