Ideology/DefInjected/MemeDef-2
Ludeon/RimWorld-ru pull request #1315
Opened 2021-08-08 16:51 UTC by kamadz

Close #1277  Translate Ideology/DefInjected/MemeDef-2

2021-08-09 10:13 UTC, shikulja commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +    <li>episode(uses=1,tag=meme_Loyalist)  ->Началась война с неверующими. [believer_gender ? один : одна] из верующих, [believer_nameFull], ища собственную выгоду, привёл дикарей на землю [deity0_na
н[believer_possessive]

2021-08-09 18:40 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +    <li>episode(uses=1,tag=meme_Loyalist)  ->Началась война с неверующими. [believer_gender ? один : одна] из верующих, [believer_nameFull], ища собственную выгоду, привёл дикарей на землю [deity0_na
???

2021-08-09 18:58 UTC, shikulja commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +    <li>episode(uses=1,tag=meme_Loyalist)  ->Началась война с неверующими. [believer_gender ? один : одна] из верующих, [believer_nameFull], ища собственную выгоду, привёл дикарей на землю [deity0_na
[believer_possessive] betrayal, and struck [believer_objective] down ten thousand times.</li>
скорее всего *н* лишняя

2021-08-09 22:33 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +    <li>episode(uses=1,tag=meme_Loyalist)  ->Началась война с неверующими. [believer_gender ? один : одна] из верующих, [believer_nameFull], ища собственную выгоду, привёл дикарей на землю [deity0_na
ниспослал на н[её]/н[его]

2021-08-10 05:18 UTC, shikulja commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +    <li>episode(uses=1,tag=meme_Loyalist)  ->Началась война с неверующими. [believer_gender ? один : одна] из верующих, [believer_nameFull], ища собственную выгоду, привёл дикарей на землю [deity0_na
Ясно, еще не все нюансы знаю. Думал что [believer_possessive] имя в м\ж падеже.
Тогда все ок

2021-08-20 21:43 UTC, Elevator89 requested changes

2021-08-20 21:43 UTC, Elevator89 commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +    <li>animistBasis(tag=meme_Loyalist)    ->Существует три племени духов: племя воинственных убийц, племя нытиков и пораженцев и благородно племя тех, кто остаётся сильными и преданными.</li>
```suggestion
    <li>animistBasis(tag=meme_Loyalist)    ->Существует три племени духов: племя воинственных убийц, племя нытиков и пораженцев и благородное племя тех, кто остаётся сильными и преданными.</li>
```

2021-08-20 21:43 UTC, Elevator89 commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +    <li>animistProphecy(tag=meme_Loyalist) ->[itIsSaid], что однажды будет рождён тот, кто проживёт свою жизнь в верности своему народу. После смерти его душа взорвётся поглощая в свете всех поджигат
В оригинале не просто взорвётся (как на мине, что ли?), а взорвётся светом.
```suggestion
    <li>animistProphecy(tag=meme_Loyalist) ->[itIsSaid], что однажды будет рождён тот, кто проживёт свою жизнь в верности своему народу. После смерти его душа взорвётся светом, поглощающим всех поджигателей войны и трусов.</li>
```

2021-08-20 21:43 UTC, Elevator89 commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +  <Loyalist.symbolPacks.0.adjective>лоялтистский</Loyalist.symbolPacks.0.adjective>
Обычно говорят "лоялизм", а не "лоялтизм"

2021-08-20 21:43 UTC, Elevator89 commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +    <li>intro(tag=meme_Supremacist)           ->Народ [place_summary] [place_name] почитал [deity0_name]. [deity0_pronoun]  [deity0_gender ? увидел : увидела], что они были верными приверженцами [mem
"верными приверженцами" - звучит как повторение и смысловая тавтология
```suggestion
    <li>intro(tag=meme_Supremacist)           ->Народ [place_summary] [place_name] почитал [deity0_name]. [deity0_pronoun]  [deity0_gender ? увидел : увидела], что они были приверженцами [memeConcept], и [deity0_gender ? повелел : повелела] им править всеми остальными.</li>
```

2021-08-20 21:43 UTC, Elevator89 commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +    <li>founderJoin(tag=meme_Supremacist)     ->[founder_gender ? Воин : Воительница] по имени [founderName] [founder_gender ? использовал : использовала] [place_massWeapon], чтобы уничтожить [place_
```suggestion
    <li>founderJoin(tag=meme_Supremacist)     ->[founder_gender ? Воин : Воительница] по имени [founderName] [founder_gender ? использовал : использовала] [place_massWeapon], чтобы уничтожить [place_community]. [deity0_name] [deity0_gender ? увидел : увидела] безжалостность [founderName] и [deity0_gender ? сделал : сделала] [founder_possessive] [deity0_gender ? законным правителем : законной правительницей] всего человечества.</li>
```

2021-08-20 21:43 UTC, Elevator89 commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +    <li>lessonIntro(tag=meme_Supremacist)         ->Я [founder_gender ? видел : видела] [foeLeader] со своими [foeLeader_possessive] жалкими [foeSoldiers] и со своей смешной властью. Я [founder_gende
```suggestion
    <li>lessonIntro(tag=meme_Supremacist)         ->Я [founder_gender ? видел : видела] [foeLeader] со своими жалкими [foeSoldiers] и со своей смешной властью. Я [founder_gender ? попытался : попыталась] убедить [foeLeader_possessive], что</li>
```

2021-08-20 21:43 UTC, Elevator89 commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +    <li>lesson(tag=meme_Supremacist)              ->мы давно доказали, что заслуживаем править вселенной за счёт нашей силы</li>
Иначе не вяжется с предыдущим предложением
```suggestion
    <li>lesson(tag=meme_Supremacist)              ->мы заслуживаем править вселенной за счёт нашей силы</li>
```

2021-08-20 21:43 UTC, Elevator89 commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +    <li>animistFact(tag=meme_Supremacist)     ->Могущественные духи решают, кому править Они же дают силы тем, кто подчиняет своей воле других.</li>
```suggestion
    <li>animistFact(tag=meme_Supremacist)     ->Могущественные духи решают, кому править. Они же дают силы тем, кто подчиняет своей воле других.</li>
```

2021-08-21 10:10 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +    <li>animistProphecy(tag=meme_Loyalist) ->[itIsSaid], что однажды будет рождён тот, кто проживёт свою жизнь в верности своему народу. После смерти его душа взорвётся поглощая в свете всех поджигат
Впервые слышу оборот "взорваться чем-то". Я понимаю, конечно, что картаслов наше всё, но я бы не стал ориентироваться на примеры отечественных пейсателей, очень часто экономящих на редакторах, как на литературные. Обычно со словом "взорваться" используются предлоги, указывающие на место и причину.
```suggestion
    <li>animistProphecy(tag=meme_Loyalist) ->[itIsSaid], что однажды будет рождён тот, кто проживёт свою жизнь в верности своему народу. После смерти его душа испустит свет, который поглотит всех поджигателей войны и трусов.</li>
```

2021-08-21 10:14 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +  <Loyalist.symbolPacks.0.adjective>лоялтистский</Loyalist.symbolPacks.0.adjective>
Здесь не это:
![image](https://user-images.githubusercontent.com/57110948/130318587-43652bd7-4b3a-4b48-9099-c16768d485d6.png)

А выдуманная идеология.

2021-08-21 10:15 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +    <li>intro(tag=meme_Supremacist)           ->Народ [place_summary] [place_name] почитал [deity0_name]. [deity0_pronoun]  [deity0_gender ? увидел : увидела], что они были верными приверженцами [mem
```suggestion
    <li>intro(tag=meme_Supremacist)           ->Народ [place_summary] [place_name] почитал [deity0_name]. [deity0_pronoun]  [deity0_gender ? увидел : увидела], что они были верными последователями [memeConcept], и [deity0_gender ? повелел : повелела] им править всеми остальными.</li>
```

2021-08-24 20:09 UTC, Elevator89 commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +    <li>animistProphecy(tag=meme_Loyalist) ->[itIsSaid], что однажды будет рождён тот, кто проживёт свою жизнь в верности своему народу. После смерти его душа взорвётся поглощая в свете всех поджигат
"Испустит свет" и "взорвётся светом" - сильно разные вещи.
Чем тебе не нравится "взорваться светом"? Не достаточно книжно, что ли? Напомню. Наш контекст - пророчество в анимистической религии. Там *должно* быть всё выразительно, метафорично и полно эпитетов. Ты сам нашёл примеры "взорваться светом", обрати внимание, в художественной литературе. 100% попадание же.

2021-08-24 20:23 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +    <li>animistProphecy(tag=meme_Loyalist) ->[itIsSaid], что однажды будет рождён тот, кто проживёт свою жизнь в верности своему народу. После смерти его душа взорвётся поглощая в свете всех поджигат
Суть даже не в "недостаточно книжно", а, скорее, в недостаточно литературно. Ну, камон, это не устойчивое выражение, это не что-то, что можно проследить в _литературе_ или, хотя бы, СМИ. Я понимаю, что пример употребления есть и я тебе хочу сказать, что не все фанфики и беллетристика - литература. На Дарью Донцову ты не стал бы опираться, как на образчик выражения мысли, я надеюсь? Вот тут то же самое.

2021-08-28 21:57 UTC, Elevator89 commented on Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
> +    <li>animistProphecy(tag=meme_Loyalist) ->[itIsSaid], что однажды будет рождён тот, кто проживёт свою жизнь в верности своему народу. После смерти его душа взорвётся поглощая в свете всех поджигат
Ну держи
```suggestion
    <li>animistProphecy(tag=meme_Loyalist) ->[itIsSaid], что однажды будет рождён тот, кто проживёт свою жизнь в верности своему народу. После смерти его душа вспыхнет светом, поглощающим всех поджигателей войны и трусов.</li>
```

2021-08-30 23:04 UTC, merged