#1250 Translate Keyed/Misc_Gameplay.xml
Ludeon/RimWorld-ru pull request #1322
Opened 2021-08-22 15:02 UTC by Elevator89

2021-09-05 00:00 UTC, kamadz commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <RitualTargetUnconnectedGaruanlenTreeInfo>Не связанное древо Гауранлен.</RitualTargetUnconnectedGaruanlenTreeInfo>
```suggestion
  <RitualTargetUnconnectedGaruanlenTreeInfo>Несвязанное древо Гауранлен.</RitualTargetUnconnectedGaruanlenTreeInfo>
```

2021-09-05 00:01 UTC, kamadz commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <RitualTargetConnectionTornGauranlenTree>Связь с {TREE_definite} оборвалось. Связывание можно повторить через {1}.</RitualTargetConnectionTornGauranlenTree>
```suggestion
  <RitualTargetConnectionTornGauranlenTree>Связь с {TREE_definite} оборвалась. Связывание можно повторить через {1}.</RitualTargetConnectionTornGauranlenTree>
```

2021-09-05 00:02 UTC, kamadz commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <RitualScarificationWarnNonScarificationIdeo>{PAWN_labelShort} не верит в одеолигиозное шрамирование и не хочет быть {PAWN_gender ? шрамированным : шрамированной}.</RitualScarificationWarnNonScarif
```suggestion
  <RitualScarificationWarnNonScarificationIdeo>{PAWN_labelShort} не верит в идеолигиозное шрамирование и не хочет быть {PAWN_gender ? шрамированным : шрамированной}.</RitualScarificationWarnNonScarificationIdeo>
```

2021-09-05 00:04 UTC, kamadz commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <RitualOutcomeExtraDesc_SkylanternWanderers>Ваши фонарики привлекли дружественных торговцев. Они скоро прибудут с дарами.</RitualOutcomeExtraDesc_SkylanternWanderers>
Насколько оправданна здесь замена на другую смысловую единицу?
Приходит не торговый караван же, а группа, с которой можно торговать.

Тем более, это уже вроде как перевели как "путешественников" и "странников" в других реквестах?

2021-09-05 00:06 UTC, kamadz commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <RitualOutcomeExtraDesc_Execution>Все присутствующие рабы были потрясены сценой смерти. Их подавленность достигла максимального уровня.</RitualOutcomeExtraDesc_Execution>
Можно заменить на слово с более яркой эмоциональной окраской, но, как по мне, это не супер важно. На твоё усмотрение здесь.
```suggestion
  <RitualOutcomeExtraDesc_Execution>Все присутствующие рабы были ошеломлены сценой смерти. Их подавленность достигла максимального уровня.</RitualOutcomeExtraDesc_Execution>
```

2021-09-05 00:08 UTC, kamadz commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <RitualRepeatPenaltyTip>Повторное проведение ритуала в течение {0_numCase ? дня : дней : дней} уменьшит его качество. С прошлого ритуала прошло {1_numCase ? день : дня : дней}, при повторном провед
```suggestion
  <RitualRepeatPenaltyTip>Повторное проведение ритуала в течение {0_numCase ? дня : дней : дней} уменьшит его качество. С прошлого ритуала прошло {1_numCase ? день : дня : дней}, при повторном проведении его качество понизится на {2}. Этот штраф исчезнет через {3_numCase ? день : дня : дней}.</RitualRepeatPenaltyTip>
```

2021-09-05 00:10 UTC, kamadz commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <RoleBelieverCountDesc>Эта роль приобретает смысл, когда ваша фракция имеет {1} {0}. Она теряет свой смысл, когда у вас всего {3} {2}.</RoleBelieverCountDesc>
```suggestion
  <RoleBelieverCountDesc>Эта роль становится доступна, когда ваша фракция имеет {1} {0}. Она перестаёт быть доступной, когда у вас всего {3} {2}.</RoleBelieverCountDesc>
```
Смысл в формате доступности игровой механики звучит не очень.

2021-09-05 00:11 UTC, kamadz commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <ConfirmationCharityJoiner>Принятие этого человека считается актом милосердия. Если вы откажете ему, следующие поселенцы будут недовольны:\n{0}\n\nВы действительно хотите отказать этому человеку?</
Лучше уточнить для связности.
```suggestion
  <ConfirmationCharityJoiner>Принятие этого человека в ряды поселения считается актом милосердия. Если вы откажете ему, следующие поселенцы будут недовольны:\n{0}\n\nВы действительно хотите отказать этому человеку?</ConfirmationCharityJoiner>
```

2021-09-05 00:14 UTC, kamadz commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <GauranlenModeChangeDescFull>Смена касты дриад у {TREE_definite} требует времени и энергии.\n\nПосле того, как связанный человек инициирует этот процесс, все дриады на {DURATION_numCase ? день : дн
Так получше звучит. Сначала лучше обозначать само действие, а потом сопутствующие обстоятельства.
```suggestion
  <GauranlenModeChangeDescFull>Смена касты дриад у {TREE_definite} требует времени и энергии.\n\nПосле того, как связанный человек инициирует этот процесс, все дриады спрячутся в коконы для трансформации на {DURATION_numCase ? день : дня : дней} .\n\nДриады, уже находящиеся в коконах, прервут текущую трансформацию, чтобы преобразоваться в выбранную касту.</GauranlenModeChangeDescFull>
```

2021-09-05 00:15 UTC, kamadz commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <HoursEveryOtherDay>{0} ч каждый второй день</HoursEveryOtherDay>
```suggestion
  <HoursEveryDay>{0} ч каждый день</HoursEveryDay>
  <!-- EN: {0} hours every other day-->
  <HoursEveryOtherDay>{0} ч каждый второй день</HoursEveryOtherDay>
```
Точки?

2021-09-05 00:33 UTC, kamadz commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <GameOverColonistsTranscended>Эти поселенцы превознеслись:\n\n{0}</GameOverColonistsTranscended>
Превозноситься от слова превозносить.

```suggestion
  <GameOverColonistsTranscended>Эти поселенцы вознеслись:\n\n{0}</GameOverColonistsTranscended>
```

2021-09-05 00:35 UTC, kamadz commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <BiosculpterInteruptCycleDesc>Прервать текущий цикл. Человек, находящийся внутри, будет выброшен из капсулы, не получив никаких положительных эффектов цикла, и кратковременно будет страдать от биос
```suggestion
  <BiosculpterInteruptCycleDesc>Прервать текущий цикл. Человек, находящийся внутри, будет выброшен из капсулы, не получив никаких положительных эффектов цикла, и будет непродолжительно страдать от биоскульпторной болезни.</BiosculpterInteruptCycleDesc>
```

2021-09-05 00:36 UTC, kamadz requested changes
.

2021-09-07 20:26 UTC, Elevator89 commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <HoursEveryOtherDay>{0} ч каждый второй день</HoursEveryOtherDay>
В предложенных строках нет изменений
Если ты про точки после "ч", то в общепринятых сокращениях точки не ставятся

2021-09-07 20:26 UTC, Elevator89 commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <RitualRepeatPenaltyTip>Повторное проведение ритуала в течение {0_numCase ? дня : дней : дней} уменьшит его качество. С прошлого ритуала прошло {1_numCase ? день : дня : дней}, при повторном провед
В начальном варианте более понятно, что понижение идёт **постепенно,** а не сразу

2021-09-07 22:38 UTC, Elevator89 commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <RitualOutcomeExtraDesc_SkylanternWanderers>Ваши фонарики привлекли дружественных торговцев. Они скоро прибудут с дарами.</RitualOutcomeExtraDesc_SkylanternWanderers>
Исправил

2021-09-09 21:15 UTC, kamadz commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <RitualRepeatPenaltyTip>Повторное проведение ритуала в течение {0_numCase ? дня : дней : дней} уменьшит его качество. С прошлого ритуала прошло {1_numCase ? день : дня : дней}, при повторном провед
Окей, звучит разумно

2021-09-09 21:16 UTC, kamadz commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <HoursEveryOtherDay>{0} ч каждый второй день</HoursEveryOtherDay>
Оки

2021-09-10 15:52 UTC, merged