Ideology/DefInjected/MemeDef-5
Ludeon/RimWorld-ru pull request #1325
Opened 2021-08-29 14:06 UTC by kamadz

Close #1280 Ideology/DefInjected/MemeDef-5

2021-09-01 21:38 UTC, Elevator89 requested changes
Почти не к чему придраться )

2021-09-01 21:38 UTC, Elevator89 commented on Ideology/DefInjected/MemeDef/Memes_Structures_OriginsReligious.xml
> +  <Structure_OriginHindu.symbolPacks.10.member>вайшишика-индуист</Structure_OriginHindu.symbolPacks.10.member>
Ваишешика или вайшишика?

2021-09-01 21:38 UTC, Elevator89 commented on Ideology/DefInjected/MemeDef/Memes_Structures_OriginsReligious.xml
> +  <Structure_OriginHindu.symbolPacks.12.member>минаманса-индуист</Structure_OriginHindu.symbolPacks.12.member>
Миманса
https://ru.wikipedia.org/wiki/%D0%9C%D0%B8%D0%BC%D0%B0%D0%BD%D1%81%D0%B0

2021-09-02 20:04 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Structures_OriginsReligious.xml
> +  <Structure_OriginHindu.symbolPacks.10.member>вайшишика-индуист</Structure_OriginHindu.symbolPacks.10.member>
второе

2021-09-02 20:04 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Structures_OriginsReligious.xml
> +  <Structure_OriginHindu.symbolPacks.12.member>минаманса-индуист</Structure_OriginHindu.symbolPacks.12.member>
ага, проглядел

2021-09-02 20:05 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Structures_OriginsReligious.xml
> +  <Structure_OriginHindu.symbolPacks.12.member>минаманса-индуист</Structure_OriginHindu.symbolPacks.12.member>
```suggestion
  <Structure_OriginHindu.symbolPacks.12.adjective>миманса-индуистский</Structure_OriginHindu.symbolPacks.12.adjective>
  <!-- EN: Mimamsa -->
  <Structure_OriginHindu.symbolPacks.12.ideoName>миманса</Structure_OriginHindu.symbolPacks.12.ideoName>
  <!-- EN: Mimamsan -->
  <Structure_OriginHindu.symbolPacks.12.member>миманса-индуист</Structure_OriginHindu.symbolPacks.12.member>
```

2021-09-02 20:06 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Structures_OriginsReligious.xml
> +  <Structure_OriginHindu.symbolPacks.10.adjective>ваишешика-индуистский</Structure_OriginHindu.symbolPacks.10.adjective>
```suggestion
  <Structure_OriginHindu.symbolPacks.10.adjective>вайшешика-индуистский</Structure_OriginHindu.symbolPacks.10.adjective>
```

2021-09-04 11:50 UTC, merged

2021-09-13 14:30 UTC, PyHToR4eG commented
https://github.com/Ludeon/RimWorld-ru/blob/4ceeb10dcefde2c876d6b9974bde88eda407ca18/Ideology/DefInjected/MemeDef/Memes_Structures_OriginsReligious.xml#L5
https://github.com/Ludeon/RimWorld-ru/blob/4ceeb10dcefde2c876d6b9974bde88eda407ca18/Ideology/DefInjected/MemeDef/Memes_Structures_OriginsReligious.xml#L108
https://github.com/Ludeon/RimWorld-ru/blob/4ceeb10dcefde2c876d6b9974bde88eda407ca18/Ideology/DefInjected/MemeDef/Memes_Structures_OriginsReligious.xml#L246
Не знаю как у всех, но у меня на FHD при 1x размере UI названия нормально не влезают