#1215 Translate Core-Keyed-3
Ludeon/RimWorld-ru pull request #1326
Opened 2021-08-30 23:45 UTC by Elevator89

Close #1215

2021-09-05 00:37 UTC, kamadz commented on Core/DefInjected/ThingDef/Buildings_Structure.xml
> +  <Fence.description>Ограда из столбов и перекладин между ними, основное предназначение которой — содержание животных внутри загонов. Некоторых виды существ могут проходить через неё. Хищники не буду
```suggestion
  <Fence.description>Ограда из столбов и перекладин между ними, основное предназначение которой — содержание животных внутри загонов. Некоторые виды существ могут проходить через неё. Хищники не будут охотиться на животных по другую сторону ограды, но могут забрести внутрь.</Fence.description>
```

2021-09-05 00:39 UTC, kamadz commented on Core/DefInjected/ThingDef/Hediffs_BodyParts_Bionic.xml
> +  <BionicTongue.description>Искусственная замена для языка. Бионический язык изготовлен из синтетических гладких волокон и соединяется с нервной системой через нейрогелевый интерфейс. Этот имплант не
```suggestion
  <BionicTongue.description>Искусственная замена для языка. Бионический язык изготовлен из синтетических гладких волокон и соединяется с нервной системой через нейрогелевый интерфейс. Этот имплант позволяет говорить, есть и чувствовать вкус без каких-либо ограничений.</BionicTongue.description>
```
В еде не уступают обычно друг другу различные заведения

2021-09-05 00:41 UTC, kamadz commented on Core/Keyed/Dialogs_Various.xml
> +  <DaysWorthOfFoodDietWarningDialog>Диета некоторых людей исключает большую часть еды в вашем караване. Если им придётся есть другую еду, чтобы не умереть с голоду, это испортит им настроение.</DaysW
```suggestion
  <DaysWorthOfFoodDietWarningDialog>Диета некоторых людей исключает употребление большей части еды в вашем караване. Если им придётся есть её, чтобы не умереть с голоду, это испортит им настроение.</DaysWorthOfFoodDietWarningDialog>
```

2021-09-05 00:45 UTC, kamadz commented on Core/Keyed/Menus_Main.xml
> +  <RecommendedFactionCount>В случае более {0_numCase ? фракции : фракций : фракций} с игровом процессом могут возникнуть проблемы.</RecommendedFactionCount>
```suggestion
  <RecommendedFactionCount>При присутствии {0_numCase ? фракции : фракций : фракций} с игровом процессом могут возникнуть проблемы.</RecommendedFactionCount>
```

2021-09-05 00:47 UTC, kamadz commented on Core/Keyed/Menus_Main.xml
> +  <Difficulty_LowPopConversionBoost_Info>В случае одного поселенца с начальной идеолигией игрока, шанс обращения других людей в эту идеолигию умножается на это значение. Результативность попыток обра
```suggestion
  <Difficulty_LowPopConversionBoost_Info>При наличии одного поселенца с начальной идеолигией игрока, шанс обращения других людей в эту идеолигию умножается на это значение. Результативность попыток обращения этого поселенца в другую идеолигию делится на это значение.\n\nПри наличии двух поселенцев с начальной идеолигией игрока влияние этой величины уменьшается вдвое.\n\При наличии трёх и более поселенцев с начальной идеолигией игрока это значение не учитывается.</Difficulty_LowPopConversionBoost_Info>
```

2021-09-05 00:48 UTC, kamadz commented on Core/Keyed/Menus_Main.xml
> +  <TotalFactionsAllowed>Допускается не более {0_numCase ? видимой фракции : видимых фракций : видимых фракций} .</TotalFactionsAllowed>
```suggestion
  <TotalFactionsAllowed>Допускается не более {0} {0_numCase ? видимой фракции : видимых фракций : видимых фракций} .</TotalFactionsAllowed>
```

2021-09-05 00:49 UTC, kamadz commented on Core/Keyed/Menus_Main.xml
> +  <FactionSelectionDesc>Выберите фракции для этого мира. Можно выбрать до {0_numCase ? фракции : фракций : фракций}.</FactionSelectionDesc>
```suggestion
  <FactionSelectionDesc>Выберите фракции для этого мира. Можно выбрать до {0} {0_numCase ? фракции : фракций : фракций}.</FactionSelectionDesc>
```

2021-09-05 00:52 UTC, kamadz requested changes
.

2021-09-07 20:38 UTC, Elevator89 commented on Core/Keyed/Menus_Main.xml
> +  <RecommendedFactionCount>В случае более {0_numCase ? фракции : фракций : фракций} с игровом процессом могут возникнуть проблемы.</RecommendedFactionCount>
При-при
```suggestion
  <RecommendedFactionCount>В случае присутствия более {0_numCase ? фракции : фракций : фракций} с игровом процессом могут возникнуть проблемы.</RecommendedFactionCount>
```

2021-09-07 20:38 UTC, Elevator89 commented on Core/Keyed/Menus_Main.xml
> +  <TotalFactionsAllowed>Допускается не более {0_numCase ? видимой фракции : видимых фракций : видимых фракций} .</TotalFactionsAllowed>
А вот нет. Начальный вариант вернёт и число, и одну из фраз.

Я понимаю, что это контр-интуитивно. Я с самого начала попросил разраба сделать по-другому. Но пока исправления нет.

2021-09-07 20:38 UTC, Elevator89 commented on Core/Keyed/Menus_Main.xml
> +  <FactionSelectionDesc>Выберите фракции для этого мира. Можно выбрать до {0_numCase ? фракции : фракций : фракций}.</FactionSelectionDesc>
К сожалению, нет. Будет дублирование числа

2021-09-09 21:17 UTC, kamadz commented on Core/Keyed/Menus_Main.xml
> +  <TotalFactionsAllowed>Допускается не более {0_numCase ? видимой фракции : видимых фракций : видимых фракций} .</TotalFactionsAllowed>
Окей, буду знать.
Очень странное решение

2021-09-10 15:49 UTC, merged