Update Core and Royalty to latest version
Ludeon/RimWorld-ru pull request #1333
Opened 2021-10-03 19:52 UTC by Elevator89

2021-10-10 21:33 UTC, kamadz commented on Core/DefInjected/JobDef/Jobs_Work.xml
> +  <RopeRoamerToHitchingPost.reportString>ведёт TargetA к коновязи</RopeRoamerToHitchingPost.reportString>
Коновязь, всё-таки, обозначает довольно конкретную вещь для лошадок. Стоит поискать замену.

2021-10-10 21:35 UTC, kamadz commented on Core/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
> +  <TravelAnticipation.stages.eager_to_travel.label>ожидание путешествию</TravelAnticipation.stages.eager_to_travel.label>
С форматированием всё ок? Странно как-то выглядит перенос

2021-10-10 21:38 UTC, kamadz commented on Core/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
> +  <TravelAnticipation.stages.eager_to_travel.description>Я уже довольно какое-то время {PAWN_gender ? готовил : готовила} этот караван к отправке, и жду предстоящего путешествия.</TravelAnticipation.
```suggestion
  <TravelAnticipation.stages.eager_to_travel.description>Я уже довольно давно готовлю этот караван к отправке, и жду предстоящего путешествия.</TravelAnticipation.stages.eager_to_travel.description>
```
Презен пёрфект континиус обычно обозначает действие, которое началось в прошлом, всё время до разговора продолжалось и до сих пор продолжается.
I've been running this shop for a while - я уже довольно давно владею (занимаюсь) этим магазином.

2021-10-10 21:40 UTC, kamadz commented on Core/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
> +  <TravelAnticipation.stages.excited_to_travel.description>Это путешествие я так долго {PAWN_gender ? обдумывал : обдумывала} и {PAWN_gender ? готовил : готовила}. Мне уже не терпится отправится в пу
```suggestion
  <TravelAnticipation.stages.excited_to_travel.description>Я так долго {PAWN_gender ? обдумывал : обдумывала} и {PAWN_gender ? планировал : планировала} это путешествие. Мне уже не терпится отправится в путь!</TravelAnticipation.stages.excited_to_travel.description>
```
Так получше

2021-10-10 21:42 UTC, kamadz commented on Core/DefInjected/TipSetDef/Tips.xml
> +  <GameplayTips.CaravanHitchingPostRoamers>Если хотите во время остановок каравана держать бродячих животных в определённом месте, поставьте там коновязь.</GameplayTips.CaravanHitchingPostRoamers>
```suggestion
  <GameplayTips.CaravanHitchingPostRoamers>Если хотите во время остановок каравана держать животных в определённом месте, поставьте там коновязь.</GameplayTips.CaravanHitchingPostRoamers>
```
Бродячий скорее всего будет читаться как антоним слову "домашний" в данном случае. Поскольку эта механика применима всё равно только для домашнего скота, можно оставить так.

2021-10-10 21:43 UTC, kamadz commented on Core/Keyed/Alerts.xml
> +  <AlertAnimalPenNeededDesc>Некоторые из ваших животных — бродячие. Если не держать их в загоне или привязанными к коновязи, они разбредутся от вас.</AlertAnimalPenNeededDesc>
```suggestion
  <AlertAnimalPenNeededDesc>Некоторые из ваших животных могут разбрестись. Если не держать их в загоне или привязанными к коновязи, они убредут от вас.</AlertAnimalPenNeededDesc>
```

2021-10-10 21:45 UTC, kamadz commented on Ideology/DefInjected/InstructionDef/Tutor.xml
> +  <ChooseIdeo.text>На этой странице можно выбрать идеолигию ваших поселенцев. В понятие «идеолигия» входят религии, идеологии и любые другие системы убеждений, определяющие представления о нравственн
Или
```suggestion
  <ChooseIdeo.text>На этой странице можно выбрать идеолигию ваших поселенцев. В понятие «идеолигия» входят религии, идеологии и любые другие системы убеждений, определяющие представления о нравственном мироустройстве.\n\nДля обучения лучше всего подходит «Играть в классический RimWorld». Нажмите соответствующую кнопку.</ChooseIdeo.text>
```

2021-10-10 21:50 UTC, kamadz requested changes
.

2021-10-12 20:31 UTC, Elevator89 commented on Core/DefInjected/TipSetDef/Tips.xml
> +  <GameplayTips.CaravanHitchingPostRoamers>Если хотите во время остановок каравана держать бродячих животных в определённом месте, поставьте там коновязь.</GameplayTips.CaravanHitchingPostRoamers>
Бывают приручённые, но при этом не "бродячие" животные. Если ты дашь альтернативный перевод слову "roaming", я буду только рад.

2021-10-12 20:51 UTC, Elevator89 commented on Core/Keyed/Alerts.xml
> +  <AlertAnimalPenNeededDesc>Некоторые из ваших животных — бродячие. Если не держать их в загоне или привязанными к коновязи, они разбредутся от вас.</AlertAnimalPenNeededDesc>
Ты здесь предлагаешь избегать игромеханического термина "roamers". А мне кажется, что вместо этого стоит поискать ему более удачный перевод. Мой вариант -- "бродячие".

2021-10-17 21:45 UTC, kamadz commented on Core/Keyed/Alerts.xml
> +  <AlertAnimalPenNeededDesc>Некоторые из ваших животных — бродячие. Если не держать их в загоне или привязанными к коновязи, они разбредутся от вас.</AlertAnimalPenNeededDesc>
Ответил выше

2021-10-17 21:46 UTC, kamadz commented on Core/DefInjected/TipSetDef/Tips.xml
> +  <GameplayTips.CaravanHitchingPostRoamers>Если хотите во время остановок каравана держать бродячих животных в определённом месте, поставьте там коновязь.</GameplayTips.CaravanHitchingPostRoamers>
Я понимаю, что это увеличивает термин аж на одно слово, но любые пересечения с "бродячим - диким" животным пропадают моментально.

2021-10-20 20:02 UTC, merged