Translate PainIsVirtue, Proselytizer, Raider
Ludeon/RimWorld-ru pull request #1337
Opened 2021-10-21 22:52 UTC by Elevator89

Refactor some existing memes' rules

2021-10-29 22:08 UTC, kamadz requested changes

2021-10-29 22:08 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +    <li>episode(uses=1,tag=meme_PainIsVirtue)  ->И [deity0_burned] [deity0_name] десять тысяч лет на погребальном костре, ибо боль очищала дух [deity0_possessive] spirit.</li>
```suggestion
    <li>episode(uses=1,tag=meme_PainIsVirtue)  ->И [deity0_burned] [deity0_name] десять тысяч лет на погребальном костре, ибо боль очищала дух [deity0_possessive].</li>
```

2021-10-29 22:08 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +  <PainIsVirtue.symbolPacks.4.theme>нищета</PainIsVirtue.symbolPacks.4.theme>
```suggestion
  <PainIsVirtue.symbolPacks.4.theme>мытарство</PainIsVirtue.symbolPacks.4.theme>
```
```suggestion
  <PainIsVirtue.symbolPacks.4.theme>горе</PainIsVirtue.symbolPacks.4.theme>
```
```suggestion
  <PainIsVirtue.symbolPacks.4.theme>мучение</PainIsVirtue.symbolPacks.4.theme>
```

Выбирай

2021-10-29 22:08 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +  <Raider.label>пиратство</Raider.label>
```suggestion
  <Raider.label>аналогично</Raider.label>
```

2021-10-29 22:13 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <Raider_All.label>пиратство</Raider_All.label>
Я старался единообразно называть черты. А слово "налётчики" звучит мягко говоря неподходяще для черты.

2021-10-29 22:19 UTC, Elevator89 commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +  <Raider.label>пиратство</Raider.label>
В игре как минимум есть пиратство как явление. Почему бы так не назвать черту?

2021-10-30 09:27 UTC, kamadz commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <Raider_All.label>пиратство</Raider_All.label>
Разбой имхо получше будет.

2021-10-30 09:28 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +  <Raider.label>пиратство</Raider.label>
Потому что пиратство относится к бандитизму и разбою на море/воздухе/космосе. Тут земля. Я предложил выше вариант

2021-10-30 13:57 UTC, Elevator89 commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +  <Raider.label>пиратство</Raider.label>
Тут земля, но пиратство уже прочно вошло в игру в более общем смысле:
![изображение](https://user-images.githubusercontent.com/21694533/139535888-8dd3677c-8fa9-4707-8153-c5993dd01ffa.png)

2021-10-30 19:45 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <Raider_All.label>пиратство</Raider_All.label>
"Разбой" - это сам акт нападения с целью отъёма. Тоже не особо тянет на название черты.

2021-11-02 18:08 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +  <Raider.label>пиратство</Raider.label>
Пираты - лишь одно из проявлений целой идеолигии. Нам нужен термин для собирательного названия. Что пираты, что бандиты, что налётчики - это всё так или иначе входит в определение разбойников. 
![image](https://user-images.githubusercontent.com/57110948/139921327-88bf434d-edd8-455f-8768-fc5a18f7286b.png)

2021-11-02 18:09 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +  <Raider.label>пиратство</Raider.label>
Называть пиратством практику (даже целую культуру) грабежей на земле - некорректно

2021-11-03 21:27 UTC, Elevator89 commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +  <Raider.label>пиратство</Raider.label>
Но в игре так **уже** назван целый тип фракций. Причём в оригинале. Не вижу проблем по аналогии назвать и черту. Чтобы не было у игрока когнитивного диссонанса

2021-11-05 13:08 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +  <Raider.label>пиратство</Raider.label>
А лично у меня огромный когнитивный диссонанс вызовет фракция аборигенов рейдеров-каннибалов, у которых 1 из двух характеризующих черт будет "пиратство"

2021-11-05 13:08 UTC, kamadz commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <Raider_All.label>пиратство</Raider_All.label>
Окей, предложи что-то, что не пиратство

2021-11-05 13:14 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +  <Raider.label>пиратство</Raider.label>
"Но в игре так уже назван целый тип фракций." - и что? Аборигены с палками и едва знающие, что такое огнестрельное оружие автоматически должны стать пиратами после этого?

2021-11-08 14:49 UTC, Elevator89 commented on Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
> +  <Raider_All.label>пиратство</Raider_All.label>
Сейчас я вмержу как есть, чтобы не тратить время.
Потом решим, что делать, в ишью https://github.com/Ludeon/RimWorld-ru/issues/1342

2021-11-08 14:49 UTC, merged