Translate Ideology/DefInjected/ThoughtDef, part 1
Ludeon/RimWorld-ru pull request #1341
Opened 2021-10-29 15:13 UTC by kamadz

Close #1290

2021-10-30 19:38 UTC, Elevator89 requested changes

2021-10-30 19:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Animal.xml
> +  <VeneratedAnimalsOnMapOrCaravan.stages.venerated-0.description>Меня окружают священные животные.</VeneratedAnimalsOnMapOrCaravan.stages.venerated-0.description>
Животных может быть не настолько много, чтобы его прямо окружать. Да и ситуация, когда тебя животные прям _окружают,_ не самая приятная.
```suggestion
  <VeneratedAnimalsOnMapOrCaravan.stages.venerated-0.description>Рядом со мной есть священные животные.</VeneratedAnimalsOnMapOrCaravan.stages.venerated-0.description>
```
Кстати, из кода можно понять, о каких количествах размера животных на человека идёт речь: 1, 2, 4 и 6.  ![изображение](https://user-images.githubusercontent.com/21694533/139555592-2c14dac2-2b16-456b-a09e-8fc53d1939ae.png)

2021-10-30 19:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Animal.xml
> +  <VeneratedAnimalsOnMapOrCaravan.stages.venerated-1.description>Меня окружают священные животные.</VeneratedAnimalsOnMapOrCaravan.stages.venerated-1.description>
```suggestion
  <VeneratedAnimalsOnMapOrCaravan.stages.venerated-1.description>Рядом со мной есть священные животные.</VeneratedAnimalsOnMapOrCaravan.stages.venerated-1.description>
```

2021-10-30 19:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Animal.xml
> +  <VeneratedAnimalsOnMapOrCaravan.stages.venerated-2.description>Меня окружает много священных животных.</VeneratedAnimalsOnMapOrCaravan.stages.venerated-2.description>
```suggestion
  <VeneratedAnimalsOnMapOrCaravan.stages.venerated-2.description>Рядом со мной много священных животных.</VeneratedAnimalsOnMapOrCaravan.stages.venerated-2.description>
```

2021-10-30 19:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Animal.xml
> +  <VeneratedAnimalsOnMapOrCaravan.stages.venerated-3.description>Меня окружает очень много священных животных!</VeneratedAnimalsOnMapOrCaravan.stages.venerated-3.description>
```suggestion
  <VeneratedAnimalsOnMapOrCaravan.stages.venerated-3.description>Рядом со мной очень много священных животных!</VeneratedAnimalsOnMapOrCaravan.stages.venerated-3.description>
```

2021-10-30 19:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Animal.xml
> +  <VeneratedAnimalsOnMapOrCaravan.stages.venerated-4.description>Здесь невероятно много священных животных!</VeneratedAnimalsOnMapOrCaravan.stages.venerated-4.description>
```suggestion
  <VeneratedAnimalsOnMapOrCaravan.stages.venerated-4.description>Рядом со мной невероятно много священных животных!</VeneratedAnimalsOnMapOrCaravan.stages.venerated-4.description>
```

2021-10-30 19:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_AutonomousWeapons.xml
> +  <HasAutomatedTurrets_Horrible.stages.automated_turrets.description>Мы пользуемся автоматическими турелями. Мы пользуемся автоматическими турелями. Давать машинам принимать решения, от которых завис
```suggestion
  <HasAutomatedTurrets_Horrible.stages.automated_turrets.description>Мы пользуемся автоматическими турелями. Давать машинам принимать решения, от которых зависят жизнь и смерть — ужасно.</HasAutomatedTurrets_Horrible.stages.automated_turrets.description>
```

2021-10-30 19:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Blindness.xml
> +  <BlindingCeremony_Know_Horrible.stages.blinding_ceremony.description>Мы кого-то ослепили из идеолигических соображений! Это ужасно!</BlindingCeremony_Know_Horrible.stages.blinding_ceremony.descript
```suggestion
  <BlindingCeremony_Know_Horrible.stages.blinding_ceremony.description>Мы кого-то ослепили из идеолигиозных соображений! Это ужасно!</BlindingCeremony_Know_Horrible.stages.blinding_ceremony.description>
```

2021-10-30 19:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Blindness.xml
> +  <Blindness_ArtificialBlind.stages.vision_blocked.description>Временно закрывая себе обзор я помогаю могу воспринимать мир вокруг себя истинно. Этого хватает, но настоящее ослепление в разы лучше.</
```suggestion
  <Blindness_ArtificialBlind.stages.vision_blocked.description>Временно закрывая свой обзор, я помогаю себе воспринимать мир истинным образом. Этого хватает, но настоящее ослепление в разы лучше.</Blindness_ArtificialBlind.stages.vision_blocked.description>
```

2021-10-30 19:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Blindness.xml
> +  <Blindness_Elevated_HalfBlind.stages.halfblind.description>Я на пути к просвещению через слепоту.</Blindness_Elevated_HalfBlind.stages.halfblind.description>
```suggestion
  <Blindness_Elevated_HalfBlind.stages.halfblind.description>Я на пути к просветлению через слепоту.</Blindness_Elevated_HalfBlind.stages.halfblind.description>
```

2021-10-30 19:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Blindness.xml
> +  <Blindness_Sublime_HalfBlind.stages.halfblind.description>Я на пороге просвещения через слепоту.</Blindness_Sublime_HalfBlind.stages.halfblind.description>
```suggestion
  <Blindness_Sublime_HalfBlind.stages.halfblind.description>Я на пороге просветления через слепоту.</Blindness_Sublime_HalfBlind.stages.halfblind.description>
```

2021-10-30 19:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_BodyMod.xml
> +  <HasProsthetic_Approved.stages.transhumanist_connected.description>Чем больше искусственных частей тела во мне находится, тем лучше я могу выражать свои убеждения.</HasProsthetic_Approved.stages.tr
```suggestion
  <HasProsthetic_Approved.stages.transhumanist_connected.description>Чем больше искусственных частей тела у меня есть, тем лучше я могу выражать свои убеждения.</HasProsthetic_Approved.stages.transhumanist_connected.description>
```

2021-10-30 19:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_BodyMod.xml
> +  <HasProsthetic_Abhorrent.stages.artificial_part.description>Во мне искусственная часть тела. Это омерзительно и противоречит всему, во что я верю!</HasProsthetic_Abhorrent.stages.artificial_part.de
```suggestion
  <HasProsthetic_Abhorrent.stages.artificial_part.description>У меня искусственная часть тела. Это омерзительно и противоречит всему, во что я верю!</HasProsthetic_Abhorrent.stages.artificial_part.description>
```

2021-10-30 19:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_BodyMod.xml
> +  <HasProsthetic_Approved.stages.transhumanist_integrated.description>Пять искусственных частей тела! Я чувствую, что до настоящего перерождения мне осталось совсем немного.</HasProsthetic_Approved.s
Первые полторы минуты: https://youtu.be/Qc7mpGSnrBk

2021-10-30 19:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_BodyMod.xml
> +  <HasProsthetic_Approved.stages.transhumanist_transformed.description>Плоть слаба и она теперь словно в прошлом.</HasProsthetic_Approved.stages.transhumanist_transformed.description>
```suggestion
  <HasProsthetic_Approved.stages.transhumanist_transformed.description>Плоть слаба, и она теперь словно в прошлом.</HasProsthetic_Approved.stages.transhumanist_transformed.description>
```

2021-11-02 18:34 UTC, kamadz commented on Ideology/DefInjected/ThoughtDef/Precepts_Animal.xml
> +  <VeneratedAnimalsOnMapOrCaravan.stages.venerated-0.description>Меня окружают священные животные.</VeneratedAnimalsOnMapOrCaravan.stages.venerated-0.description>
Не вижу противоречий.

2021-11-02 18:34 UTC, kamadz commented on Ideology/DefInjected/ThoughtDef/Precepts_Animal.xml
> +  <VeneratedAnimalsOnMapOrCaravan.stages.venerated-0.description>Меня окружают священные животные.</VeneratedAnimalsOnMapOrCaravan.stages.venerated-0.description>
Меня окружают приятные мне люди - мне хорошо и я рад. 
Меня окружают священные животные - мне хорошо и я рад.

2021-11-02 18:34 UTC, kamadz commented on Ideology/DefInjected/ThoughtDef/Precepts_BodyMod.xml
> +  <HasProsthetic_Abhorrent.stages.artificial_part.description>Во мне искусственная часть тела. Это омерзительно и противоречит всему, во что я верю!</HasProsthetic_Abhorrent.stages.artificial_part.de
Не согласен вообще. Предложенный вариант не отражает эмоционально-экспрессивного компонента, а выигрыш с точки зрения грамматики очень сомнительный - 4 конечности против больше чем 10 имплантов и аугментаций, которые могут находиться внутри. Да и это не звучит прямо как-то плохо: 
В моём теле есть искусственные части - руки, лёгкие, ребро -> Во мне есть искусственные части - руки, лёгкие, ребро.

2021-11-03 21:20 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Animal.xml
> +  <VeneratedAnimalsOnMapOrCaravan.stages.venerated-0.description>Меня окружают священные животные.</VeneratedAnimalsOnMapOrCaravan.stages.venerated-0.description>
"Меня окружают" намекает на некое большое количество, явно больше 1 и даже 2 особей. А по игре эта мысль будет возникать даже если рядом одно животное, пусть и большое.

В этом плане "Рядом со мной" выигрывает, ибо покрывает все возможные кейсы.

2021-11-03 21:22 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_BodyMod.xml
> +  <HasProsthetic_Abhorrent.stages.artificial_part.description>Во мне искусственная часть тела. Это омерзительно и противоречит всему, во что я верю!</HasProsthetic_Abhorrent.stages.artificial_part.de
Если вариант не подходит для 4 из 14 вариантов - это плохой вариант.

Мой вариант подходит для всех случаев. А эмоциональный компонент можно выразить и другим способом.

2021-11-05 13:11 UTC, kamadz commented on Ideology/DefInjected/ThoughtDef/Precepts_BodyMod.xml
> +  <HasProsthetic_Abhorrent.stages.artificial_part.description>Во мне искусственная часть тела. Это омерзительно и противоречит всему, во что я верю!</HasProsthetic_Abhorrent.stages.artificial_part.de
Я не согласен, что он **не подходит**. Если тебе человек скажет "во мне проклятый металл" вместо "у меня проклятая металлическая рука" - это будут неравноценные с точки зрения семантики и грамматики конструкции?

2021-11-05 13:13 UTC, kamadz commented on Ideology/DefInjected/ThoughtDef/Precepts_Animal.xml
> +  <VeneratedAnimalsOnMapOrCaravan.stages.venerated-0.description>Меня окружают священные животные.</VeneratedAnimalsOnMapOrCaravan.stages.venerated-0.description>
Хорошо, мы можем использовать "рядом со мной" для первых двух стадий, в остальных случаях "меня окружают" будут отлично передавать дополнительный эмоциональный компонент и не будут противоречить реальной ситуации в игре

2021-11-08 15:00 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_BodyMod.xml
> +  <HasProsthetic_Abhorrent.stages.artificial_part.description>Во мне искусственная часть тела. Это омерзительно и противоречит всему, во что я верю!</HasProsthetic_Abhorrent.stages.artificial_part.de
Мержим как есть, потом решаем проблему в ишью https://github.com/Ludeon/RimWorld-ru/issues/1343

2021-11-08 15:01 UTC, merged