#1278 Translate Rancher, Transhumanst, TreeConnection
Ludeon/RimWorld-ru pull request #1344
Opened 2021-11-10 22:53 UTC by Elevator89

2021-11-11 21:24 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +    <li>victory(tag=meme_Rancher)         ->Наконец, [founder_rode] [founderName] к [place_community] на лихом коне, и [founder_challenged] [place_personalWeapon], и [founder_challenged] [foeLeader]
```suggestion
    <li>victory(tag=meme_Rancher)         ->Наконец, [founder_rode] [founderName] к [place_community] на лихом коне, и [founder_challenged] [place_personalWeapon], и [founder_challenged] [foeLeader] на поединок честный в полдень жаркий. Не отказал [foeLeader], ибо потерял бы тогда он доверие [foeSoldiers] своих. И был в тот полдень убит [foeLeader].</li>
```

Для выдержки стилистики

2021-11-11 21:46 UTC, kamadz requested changes
.

2021-11-11 21:46 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +    <li>lesson(tag=meme_Rancher)              ->мир и пристанище найдёшь ты на пастбище</li>
![image](https://user-images.githubusercontent.com/57110948/141371315-ebbfdf6f-68f4-4eaf-a6f7-0bb1335ec598.png)

2021-11-11 21:46 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +    <li>archistProphecy(tag=meme_Rancher) ->[inTheEnd] архотеки уйдут, ведя перед собой тех, кто хорошо обращался со своими стадами. Остальные же будут брошены среди пустыни.</li>
```suggestion
    <li>archistProphecy(tag=meme_Rancher) ->[inTheEnd] архотеки уйдут, ведя перед собой тех, кто хорошо обращался со своими стадами. Остальные же будут брошены посреди пустыни.</li>
```

2021-11-11 21:46 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +    <li>animistProphecy(tag=meme_Transhumanist) ->[itIsSaid], что тот, у кого есть [relic0_name], призовёт его дух, что научит человечество абсолютной технологии биослияния.</li>
Здесь всё верно, но я бы немного перефразировал. Абсолютная технология может странно прозвучать для русскоговорящего.  
```suggestion
    <li>animistProphecy(tag=meme_Transhumanist) ->[itIsSaid], что тот, у кого есть [relic0_name], призовёт его дух, что даст человечеству технологию биослияния — апогей научного прогресса.</li>
```

2021-11-11 21:46 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +    <li>memeConcept->биомодификациb</li>
```suggestion
    <li>memeConcept->биомодификации</li>
```

2021-11-11 21:46 UTC, kamadz commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +    <li>memeConcept->artifice</li>
-приблуда-
```suggestion
    <li>memeConcept->техникалии</li>
```

Изобретение бы здесь странно звучало, а вот этот малоупотребимый синоним зайдёт имхо

2021-11-12 20:55 UTC, Elevator89 commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +    <li>memeConcept->биомодификациb</li>
Ай, опять накосячил

2021-11-12 20:55 UTC, Elevator89 commented on Ideology/DefInjected/MemeDef/Memes_Misc.xml
> +    <li>memeConcept->artifice</li>
Ай, накосячил

2021-11-12 21:21 UTC, merged