Древний хлам
Ludeon/RimWorld-ru pull request #1350
Opened 2021-11-25 08:07 UTC by Macropod777

Два файла с описаниями старого хлама, были сделаны для перевода на русский мода Vanilla Ideology Expanded - Memes and Structures. Текстовые строки идентичны таким же из DLC Ideology

2021-11-28 13:22 UTC, kamadz commented
Уже есть в ветках дутлиста

2021-11-28 14:49 UTC, Elevator89 requested changes

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientMiniWarwalkerRemains.description>Разбитые останки древнего малого боевого паука. Все детали, которые не сломались при разрушении, были разграблены давным-давно.</AncientMiniWarwalkerRemains
```suggestion
  <AncientMiniWarwalkerRemains.description>Разбитые останки древнего малого боевого паука. Все уцелевшие детали давным-давно растащили.</AncientMiniWarwalkerRemains.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientWarspiderRemains.description>Разрушенные останки древнего боевого паука среднего размена. Его обыскивали много раз и не оставили никакой ценной добычи.</AncientWarspiderRemains.description>
```suggestion
  <AncientWarspiderRemains.description>Разрушенные останки древнего боевого паука среднего размера. Его обыскивали много раз и не оставили ничего ценного.</AncientWarspiderRemains.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientWarwalkerShell.description>Корпус древнего боевого шагохода. Похоже, его оторвало какое-то колоссальное оружие. Все ценные части были разграблены, а остальное сильно испорчено.</AncientWarw
```suggestion
  <AncientWarwalkerShell.description>Корпус древнего боевого шагохода. Похоже, его оторвало какое-то колоссальное оружие. Все ценные части изъяты, а остальное сильно испорчено.</AncientWarwalkerShell.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientAirConditioner.description>Древняя машина для охлаждения воздуха. Её внутренности были разбиты давным-давно, а то, что не было разграблено, с тех пор проржавело.</AncientAirConditioner.desc
```suggestion
  <AncientAirConditioner.description>Древняя машина для охлаждения воздуха. Её внутренности были разбиты давным-давно, а то, что не растащили, с тех пор проржавело.</AncientAirConditioner.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientRustedCar.description>Древний разбитый автомобиль. Всё, что не заржавело, было разграблено давным-давно.</AncientRustedCar.description>
```suggestion
  <AncientRustedCar.description>Древний разбитый автомобиль. Всё, что не заржавело, давным-давно растащили.</AncientRustedCar.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientRustedTruck.description>Древний разбитый грузовик. Всё полезное либо заржавело, либо было давно разграблено.</AncientRustedTruck.description>
Не стоит злоупотреблять конструкциями с "было". Звучит как неуместный канцеляризм.
```suggestion
  <AncientRustedTruck.description>Древний разбитый грузовик. Всё полезное либо заржавело, либо давно изъято.</AncientRustedTruck.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientRustedJeep.description>Древний разбитый бронетранспортёр. Всё, что не заржавело, было разграблено давным-давно.</AncientRustedJeep.description>
```suggestion
  <AncientRustedJeep.description>Древний разбитый бронетранспортёр. Всё, что не заржавело, давным-давно растащили.</AncientRustedJeep.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientWarwalkerTorso.description>Остов боевого шагохода среднего размера, который упал здесь в древние времена. Ценные части давно разграблены.</AncientWarwalkerTorso.description>
```suggestion
  <AncientWarwalkerTorso.description>Остов боевого шагохода среднего размера, который упал здесь в древние времена. Ценные части давно растащили.</AncientWarwalkerTorso.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientWarwalkerFoot.description>Массивная ступня древнего боевого шагохода. Похоже, её оторвало каким-то тяжёлым оружием. Все полезные компоненты давно разграблены или испорчены.</AncientWarwalke
"Компоненты" - это название игрового предмета. Не стоит его применять для чего-то ещё.
```suggestion
  <AncientWarwalkerFoot.description>Массивная ступня древнего боевого шагохода. Похоже, её оторвало каким-то тяжёлым оружием. Все полезные части давно изъяты или испорчены.</AncientWarwalkerFoot.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientTank.description>Остатки древнего танка, который был уничтожен каким-то тяжёлым оружием. Все полезные компоненты давно разграблены или испорчены.</AncientTank.description>
```suggestion
  <AncientTank.description>Остатки древнего танка, который был уничтожен каким-то тяжёлым оружием. Все полезные части давно изъяты или испорчены.</AncientTank.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientAPC.description>Остатки древней БМП, которая была уничтожена каким-то тяжёлым оружием. Все полезные компоненты давно разграблены или испорчены.</AncientAPC.description>
```suggestion
  <AncientAPC.description>Остатки древней БМП, которая была уничтожена каким-то тяжёлым оружием. Все полезные части давно изъяты или испорчены.</AncientAPC.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientJetEngine.description>Древний реактивный двигатель, вероятно, оторванный от большого самолета. Его хрупкие внутренности заржавели до бесполезности, а ценные части давно разграблены.</Ancien
"заржавели до бесполезности" выглядит, как машинный перевод. Не годится.
```suggestion
  <AncientJetEngine.description>Древний реактивный двигатель, вероятно, оторванный от большого самолета. Его хрупкие внутренности заржавели, а ценные части давно изъяты.</AncientJetEngine.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientDropshipEngine.description>Древний двигатель шаттла. Вероятно, он отвалился от военного десантного корабля. Его хрупкие внутренности заржавели до бесполезности, а ценные части давно разграб
```suggestion
  <AncientDropshipEngine.description>Древний двигатель челнока. Вероятно, он отвалился от военного десантного корабля. Его хрупкие внутренности заржавели, а ценные части давно изъяты.</AncientDropshipEngine.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientDropshipEngine.label>древний двигатель шаттла</AncientDropshipEngine.label>
```suggestion
  <AncientDropshipEngine.label>древний двигатель челнока</AncientDropshipEngine.label>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientPodCar.description>Древний автомобиль-капсула, когда-то способный к автоматическому полёту. Его ценные части были давно разграблены, а остальное сильно испорчено.</AncientPodCar.description
```suggestion
  <AncientPodCar.description>Древний автомобиль-капсула, когда-то способный к автоматическому полёту. Его ценные части давно изъяты, а остальное сильно испорчено.</AncientPodCar.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientTankTrap.description>Оборонительная фортификация для остановки транспортных средств. Она ветшала в течение многих лет.</AncientTankTrap.description>
```suggestion
  <AncientTankTrap.description>Оборонительное сооружение для остановки транспортных средств. Оно ветшало в течение многих лет.</AncientTankTrap.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientMegaCannonTripod.description>Платформа, на которой когда-то стояла большая пушка. Она была сломана много лет назад, а все полезные части давно разграблены.</AncientMegaCannonTripod.descript
```suggestion
  <AncientMegaCannonTripod.description>Платформа, на которой когда-то стояла большая пушка. Она была сломана много лет назад, а все полезные части давно изъяты.</AncientMegaCannonTripod.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientMegaCannonBarrel.description>Ствол от дальнобойной пушки артиллерийского или противокорабельного назначения. Когда он был новым, то, должно быть, устрашал своей мощью. Теперь же абсолютно н
Сложно "разграбить" ствол орудия
```suggestion
  <AncientMegaCannonBarrel.description>Ствол от дальнобойной пушки артиллерийского или противокорабельного назначения. Когда он был новым, то, должно быть, устрашал своей мощью. Теперь же он абсолютно не подлежит ремонту, ценных частей в нём тоже не осталось.</AncientMegaCannonBarrel.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientContainer.description>Большой контейнер для какого-то древнего грузового транспортного средства. Он уже давно разграблен и пришел в негодность.</AncientContainer.description>
А здесь слово "разграблен" использовано верно, ибо речь про контейнер, а не про ценности.
```suggestion
  <AncientContainer.description>Большой контейнер для какого-то древнего грузового транспортного средства. Он уже давно разграблен и пришёл в негодность.</AncientContainer.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientSecurityTurret.description>Сломанная древняя охранная турель. Все ценные части были разграблены или разбиты.</AncientSecurityTurret.description>
```suggestion
  <AncientSecurityTurret.description>Сломанная древняя охранная турель. Все ценные части изъяты или разбиты.</AncientSecurityTurret.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientShipBeacon.description>Сломанный древний корабельный навигационный маяк. Все полезные компоненты давно разграблены.</AncientShipBeacon.description>
```suggestion
  <AncientShipBeacon.description>Сломанный древний корабельный навигационный маяк. Все полезные части давно изъяты.</AncientShipBeacon.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientMechanoidShell.description>Корпус разбитого механоида. Он ветшал в течение многих лет, полезные компоненты рассыпались.</AncientMechanoidShell.description>
```suggestion
  <AncientMechanoidShell.description>Корпус разбитого механоида. Он ветшал в течение многих лет, все ценные части рассыпались.</AncientMechanoidShell.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientMechDropBeacon.description>Разбитый корпус десантного маяка механоидов. Полезные комплектующие в нём отсутствуют, а сам корпус испортился после долгих лет.</AncientMechDropBeacon.descriptio
```suggestion
  <AncientMechDropBeacon.description>Разбитый корпус десантного маяка механоидов. Ценные части в нём отсутствуют, а сам корпус испортился после долгих лет.</AncientMechDropBeacon.description>
```

2021-11-28 14:49 UTC, Elevator89 commented on Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
> +  <AncientCentipedeShell.description>Корпус давно разбитой сентипеды. Он ветшал в течение многих лет, полезные части уже рассыпались.</AncientCentipedeShell.description>
```suggestion
  <AncientCentipedeShell.description>Корпус давно разбитой сентипеды. Он ветшал в течение многих лет, ценные части уже рассыпались.</AncientCentipedeShell.description>
```

2021-11-28 21:23 UTC, Macropod777 commented
так убирать это, или пусть повисит?
Собственно, перевод Vanilla Ideology Expanded - Memes and Structures уже подходит к завершению.
Всё равно потом, когда переведёте хлам, мне придётся сверять и подгонять под официальный перевод, т.к. тексты должнф полностью совпадать.

2021-12-09 22:20 UTC, Elevator89 commented
Не убирай. В обозначенных выше реквестах я такого не нашёл (возможно, плохо искал).

2021-12-11 16:48 UTC, Elevator89 commented
А, нет. Нашёл пересечение: https://github.com/Ludeon/RimWorld-ru/pull/1312/files#diff-d2e3eb2f46aa231432f7e0ae5237f3237cbba24f927a39d6f70c225caebc90af
Думаю, рациональнее всего будет сначала вмержить один вариант, а из другого взять всё, что выглядит лучше первого.

2022-02-20 12:54 UTC, merged