DefInjected/PreceptDef pt.1 (edited)
Ludeon/RimWorld-ru pull request #1351
Opened 2021-12-05 21:40 UTC by kamadz

Close #1281

2021-12-05 21:43 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Nudity.xml
> +  <Nudity_Male_UncoveredGroinDisapproved.description>>У мужчин должна быть покрыта область паха. Остальные части тела покрывать необязательно.</Nudity_Male_UncoveredGroinDisapproved.description>
```suggestion
  <Nudity_Male_UncoveredGroinDisapproved.description>У мужчин должна быть покрыта область паха. Остальные части тела покрывать необязательно.</Nudity_Male_UncoveredGroinDisapproved.description>
```

2021-12-11 20:02 UTC, Elevator89 requested changes

2021-12-11 20:02 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Nudity.xml
> +  <Nudity_Male_CoveringAnythingButGroinDisapproved.description>Мужчины могут прикрывать только область паха и ничего больше. Допускаются элементы снаряжения, такие как защитные ремни или прыжковые ра
```suggestion
  <Nudity_Male_CoveringAnythingButGroinDisapproved.description>Мужчины могут прикрывать только область паха и ничего больше. Допускаются предметы снаряжения, такие как защитные ремни или прыжковые ранцы.</Nudity_Male_CoveringAnythingButGroinDisapproved.description>
```

2021-12-11 20:02 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Nudity.xml
> +  <Nudity_Male_Mandatory.description>Мужчины должны быть всегда полностью обнажены. Допускаются элементы снаряжения, такие как защитные ремни или прыжковые ранцы.</Nudity_Male_Mandatory.description>
```suggestion
  <Nudity_Male_Mandatory.description>Мужчины должны быть всегда полностью обнажены. Допускаются предметы снаряжения, такие как защитные ремни или прыжковые ранцы.</Nudity_Male_Mandatory.description>
```

2021-12-18 11:24 UTC, kamadz commented on Ideology/DefInjected/IssueDef/Precepts_Apparel.xml
> +  <ApparelDesire.label>специф. одежда</ApparelDesire.label>
неа, смотрел в игре

2021-12-18 11:25 UTC, kamadz commented on Ideology/DefInjected/IssueDef/Precepts_Apparel.xml
> +  <ApparelDesire.label>специф. одежда</ApparelDesire.label>
Плюс по смыслу плохо подходит. Потребность в одежде в целом оч плохо сочетается по смыслу с тем, что поселенцы хотят носить шляпы.

2021-12-18 11:26 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Animal.xml
> +  <AnimalVenerated.comps.4.thoughtStageDescriptions.0>Мало животных {STAGE1}</AnimalVenerated.comps.4.thoughtStageDescriptions.0>
Нам с этим нужно что-то сделать?

2021-12-18 11:51 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_AutonomousWeapons.xml
> +  <AutonomousWeapons_Horrible.comps.0.description>Автоматическая турель в колонии</AutonomousWeapons_Horrible.comps.0.description>
Пропустил

2021-12-18 11:51 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_BlindPsysense.xml
> +  <Blind_Psysense.description>Наши слепые обладают особыми способностями связываться с пси-сферой.</Blind_Psysense.description>
```suggestion
  <Blind_Psysense.description>Наши слепые обладают особой способностью связываться с пси-сферой.</Blind_Psysense.description>
```
Так проще

2021-12-18 12:09 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Blindness.xml
> +  <Blinding_Horrible.description>Слепые люди ужасны по идеологическим причинам.</Blinding_Horrible.description>
Проглядел, бывает. Можешь ради интереса зайти в оригинальную ветку и посмотреть, чё там было

2021-12-18 12:13 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Blindness.xml
> +  <Blindness_Elevated.description>Слепой наголову лучше зрячего.</Blindness_Elevated.description>
Вот тут нет. "Stand pure" - использовано в смысле "более приближённых" к познанию смысла мироздания, менее осквернённых осязаемым миром, от того более "чистых". И от того, что они stand pure, они ещё и stand above. Так-то понятно, что в таких общинах у слепых статус поболее, чем у остальных, но в оригинале этого не сказано.

2021-12-18 12:14 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_BodyMod.xml
> +  <BodyMod_Disapproved.description>Изменение естественного облика человеческого тела — грязно и плохо.</BodyMod_Disapproved.description>
Омерзительно имеет более негативную окраску, чем плохо. Нужно помнить, что это описание к статусу "не одобряется", а не "порицается". Плохо может звучать немного пресновато, но омерзительно здесь будет излишним.

2021-12-18 12:22 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Apparel.xml
> +  <ApparelDesired_Soft_Subordinate.description>{GENDER ? мужчинам : женщинам} будет приятно носить {APPAREL_indefinite}. Они будут носить {APPAREL_indefinite}, если это не будет мешать другим элемент
Работает

2021-12-18 12:24 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_DrugUse.xml
> +  <DrugUse_MedicalOnly.comps.5.description>Назначать лёгкие наркотики</DrugUse_MedicalOnly.comps.5.description>
![image](https://user-images.githubusercontent.com/57110948/146640918-09e95144-e74e-4c23-8ca6-d8e9f9760fc3.png)

2021-12-18 12:29 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Mining.xml
> +  <Mining_Horrible.comps.2.description>Кто-то выкопал блок</Mining_Horrible.comps.2.description>
```suggestion
  <Mining_Horrible.comps.0.description>Кто-то выкопал породу</Mining_Horrible.comps.0.description>
  <!-- EN: Someone mined a block -->
  <Mining_Horrible.comps.2.description>Кто-то выкопал породу</Mining_Horrible.comps.2.description>
```

2021-12-18 12:30 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Mining.xml
> +  <MiningYield_High.description>Горное дело — очень важное занятие. Настолько важное, что мы делаем это со всем вниманием уважением к процессу, благодаря чему добываем больше полезных ресурсов.</Mini
Не понял, в чём проблема с настолько важное? Упор именно на то, что "А настолько важное, что мы делаем В, чтобы С".

2021-12-18 12:33 UTC, Elevator89 commented on Ideology/DefInjected/IssueDef/Precepts_Apparel.xml
> +  <ApparelDesire.label>специф. одежда</ApparelDesire.label>
Может, тогда так?
```suggestion
  <ApparelDesire.label>особая одежда</ApparelDesire.label>
```

2021-12-19 17:05 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Mining.xml
> +  <MiningYield_High.description>Горное дело — очень важное занятие. Настолько важное, что мы делаем это со всем вниманием уважением к процессу, благодаря чему добываем больше полезных ресурсов.</Mini
Проблема в том, что нужный смысл читается и без "Настолько важное, что". Я предлагаю удалить лишнее

2021-12-19 17:05 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Blindness.xml
> +  <Blinding_Horrible.description>Слепые люди ужасны по идеологическим причинам.</Blinding_Horrible.description>
То же самое: "Слепые люди ужасны по идеологическим причинам."

2021-12-20 11:05 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Blindness.xml
> +  <Blinding_Horrible.description>Слепые люди ужасны по идеологическим причинам.</Blinding_Horrible.description>
Я к тому, что такого треша там было просто дохера, и некоторые вещи просто ускользали

2021-12-20 11:05 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Blindness.xml
> +  <Blindness_Elevated.description>Слепой наголову лучше зрячего.</Blindness_Elevated.description>
Во, второй прям в тему

2021-12-20 11:06 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_BodyMod.xml
> +  <BodyMod_Disapproved.description>Изменение естественного облика человеческого тела — грязно и плохо.</BodyMod_Disapproved.description>
А как тебе такой вариант? 
```suggestion
  <BodyMod_Disapproved.description>Изменение естественного облика человеческого тела — грязно и порочно.</BodyMod_Disapproved.description>
```

2021-12-20 11:06 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Mining.xml
> +  <MiningYield_High.description>Горное дело — очень важное занятие. Настолько важное, что мы делаем это со всем вниманием уважением к процессу, благодаря чему добываем больше полезных ресурсов.</Mini
Ну ок

2021-12-20 21:24 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Blindness.xml
> +  <Blinding_Horrible.description>Слепые люди ужасны по идеологическим причинам.</Blinding_Horrible.description>
Я тоже с таким сталкивался. С тех пор предпочитаю начинать задачу с нуля, а не брать чужой сырой вариант.

2021-12-20 21:25 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_BodyMod.xml
> +  <BodyMod_Disapproved.description>Изменение естественного облика человеческого тела — грязно и плохо.</BodyMod_Disapproved.description>
Норм

2021-12-20 21:31 UTC, Elevator89 approved these changes

2021-12-20 21:31 UTC, merged