Ideology/DefInjected/PreceptDef pt. 2 (edited)
Ludeon/RimWorld-ru pull request #1355
Opened 2021-12-20 15:41 UTC by kamadz

Close #1282 + minor adjustments

2021-12-25 21:12 UTC, Elevator89 requested changes

2021-12-27 22:05 UTC, Elevator89 requested changes

2021-12-27 22:05 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <Execution.description>Палач публично казнит заключённого. Он произнесёт короткую речь, а затем убьёт пленника, обезглавив его, и завершит все несколькими словами. Видящие рабы потеряют дар речи и
Судя по обилию "колонистов", эта часть ревью не подвергалась
```suggestion
  <Execution.description>Палач публично казнит пленника. Он произнесёт короткую речь, перережет жертве горло, после чего скажет пару заключительных слов. После увиденного рабы потеряют дар речи от страха, а поселенцы либо придут в восторг, либо почувствуют отвращение, в зависимости от их убеждений.</Execution.description>
```

2021-12-27 22:05 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <Festival.description>Праздничное собрание для ваших колонистов, чтобы хорошо провести время. Лидер произнесёт воодушевляющую речь, а затем все пообщаются некоторое время.</Festival.description>
> Праздничное собрание для ваших колонистов, чтобы хорошо провести время

Чувствую, такого впереди много. Можешь, пожалуйста, всё отсюда и ниже исправить и перефразировать _**по-нормальному?**_

2022-01-09 17:25 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <Festival.description>Праздничное собрание для ваших колонистов, чтобы хорошо провести время. Лидер произнесёт воодушевляющую речь, а затем все пообщаются некоторое время.</Festival.description>
Вижу, что пропустил ряд файлов, буду смотреть

2022-01-14 15:31 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Ranching.xml
> +  <Ranching_Central.comps.0.thoughtStageDescriptions.5>Тонны животных</Ranching_Central.comps.0.thoughtStageDescriptions.5>
Правильно "немерено"

2022-01-14 15:33 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Research.xml
> +  <Research_VerySlow.description>Исследования не заслуживают серьёзного уважения. Лучше не замечать, как он старается в этой области.</Research_VerySlow.description>
Это дутлист так переводил, не я :D

2022-01-14 15:34 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Research.xml
> +  <Research_Normal.description>Исследования - это стоящая форма работы, в которой нуждается сообщество.</Research_Normal.description>
```suggestion
  <Research_Normal.description>Исследования — значимая и важная деятельность, в которой нуждается наша община.</Research_Normal.description>
```

2022-01-14 15:35 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Research.xml
> +  <Research_Slow.description>Исследования не имеют особого смысла. Зачем так стараться?</Research_Slow.description>
```suggestion
  <Research_Slow.description>Исследования не имеют какого-либо смысла. Так зачем стараться?</Research_Slow.description>
```

2022-01-14 15:37 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Research.xml
> +  <Research_VeryFast.description>Исследования - одно из самых значимых действий, которые может совершить человек.</Research_VeryFast.description>
```suggestion
  <Research_VeryFast.description>Проведение исследований —  один из самых значимых видов деятельности, доступных человеку.</Research_VeryFast.description>
```

2022-01-14 15:39 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Research.xml
> +  <Research_VerySlow.description>Исследования не заслуживают серьёзного уважения. Лучше не замечать, как он старается в этой области.</Research_VerySlow.description>
```suggestion
  <Research_VerySlow.description>В исследовании нет ничего, заслуживающего уважения. Лучше, чтобы никто не видел, как я этим всерьёз занимаюсь.</Research_VerySlow.description>
```

2022-01-14 15:43 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Ranching.xml
> +</LanguageData>
Все правки здесь будут залиты через отдельный коммит

2022-01-15 14:30 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Ranching.xml
> +  <Ranching_Central.comps.0.thoughtStageDescriptions.5>Тонны животных</Ranching_Central.comps.0.thoughtStageDescriptions.5>
Согласен, исправил коммент

2022-01-28 10:59 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Raiders.xml
> +  <Raiding_Respected.comps.0.thoughtStageDescriptions.0>Менее {DAYSSINCELASTRAIDTHRESHOLD} дней с последнего нашего налёта</Raiding_Respected.comps.0.thoughtStageDescriptions.0>
До этого было "нашего последнего". Предлагаю сделать единообразно

2022-01-28 10:59 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Raiders.xml
> +  <Raiding_Respected.comps.0.thoughtStageDescriptions.1>Более {DAYSSINCELASTRAIDTHRESHOLD} дней с последнего нашего налёта</Raiding_Respected.comps.0.thoughtStageDescriptions.1>
И здесь "нашего последнего"

2022-01-28 10:59 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Relics.xml
> +  <IdeoRelic.description>Идеолигическая реликвия.</IdeoRelic.description>
Идеолигиозная

2022-01-28 11:27 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_SmallSpaces.xml
> +  <SmallSpaces_Acceptable.description>В тесноте да не в обиде.</SmallSpaces_Acceptable.description>
Хорошо )

2022-01-28 11:27 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_SpouseCount.xml
> +  <SpouseCount_Female_MaxFour.description>У женщины может быть до четырёх супругов.</SpouseCount_Female_MaxFour.description>
В игре разве возможны однополые браки?

Если нет, то нет смысла писать "супругов", когда есть "мужья" и "жёны"

2022-01-28 11:27 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_TreeCutting.xml
> +  <TreeCutting_Prohibited.description>Осквернять лес срубая деревья — крайне отвратительно. Так делать нельзя ни в коем случае.</TreeCutting_Prohibited.description>
```suggestion
  <TreeCutting_Prohibited.description>Осквернять лес, срубая деревья, — крайне отвратительно. Так делать нельзя ни в коем случае.</TreeCutting_Prohibited.description>
```

2022-01-29 23:45 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <BlindingCeremony.description>Ритуал, в ходе которого цель будет лишена зрения. Присутствующие будут наблюдать, как цели будут вырезаны оба глаза, после чего будет произнесена короткая речь. По око
Слишком много страдательного залога не идёт на пользу тексту. И бездушная "цель" вместо сочной "жертвы" звучит слишком сухо.
Я бы всё же советовал хотя бы частично воспользоваться мои вариантом:
```suggestion
  <BlindingCeremony.description>Резчик ослепит жертву ритуальным ножом. Зрители будут наблюдать, как резчик произносит речь, вырезает оба глаза жертвы и произносит несколько заключительных слов. У жертвы начнётся кровотечение, и ей потребуется немедленная медицинская помощь.</BlindingCeremony.description>
```

2022-01-29 23:45 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <DateRitualConsumable.description>Праздничное собрание для ваших поселенцев, чтобы они могли весело и хорошо провести время вместе. Сначала лидер произнесёт воодушевляющую речь, а затем все смогут
Восстановлю свой комментарий:
Нас со второго класса школы учили не злоупотреблять прилагательными "большой", "добрый" и "хороший"
```suggestion
  <DateRitualConsumable.description>Праздничное собрание для ваших поселенцев, чтобы они могли весело и приятно провести время вместе. Сначала лидер произнесёт воодушевляющую речь, а затем все смогут пообщаться друг с другом.</DateRitualConsumable.description>
```

2022-01-29 23:45 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <Festival.description>Праздничное собрание для ваших поселенцев, чтобы они могли весело и хорошо провести время вместе. Лидер произнесёт воодушевляющую речь, после чего участники пообщаются друг с
```suggestion
  <Festival.description>Праздничное собрание для ваших поселенцев, чтобы они могли весело и приятно провести время вместе. Лидер произнесёт воодушевляющую речь, после чего участники смогут пообщаться друг с другом.</Festival.description>
```

2022-01-29 23:45 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <Funeral.description>Собрание у могилы погибшего последователя во время его погребения. Если тело было уничтожено, можно использовать пустую могилу. Рабы похорон не получают.</Funeral.description>
"Получать похороны" - не очень естественное словосочетание.
```suggestion
  <Funeral.description>Собрание у могилы погибшего последователя во время его погребения. Если тело было уничтожено, можно использовать пустую могилу. Похороны рабов не проводятся.</Funeral.description>
```

2022-01-29 23:45 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <Funeral.extraTextPawnDeathLetter>Необходимо устроить похороны для {PAWN_nameDef}, чтобы {PAWN_possessive} друзья и семья смогли с н{PAWN_objective} попрощаться.</Funeral.extraTextPawnDeathLetter>
Вместо "н{PAWN_objective}" будет "нему".
```suggestion
  <Funeral.extraTextPawnDeathLetter>Необходимо устроить похороны для {PAWN_nameDef}, чтобы {PAWN_possessive} друзья и семья смогли с {PAWN_gender ? ним : ней} попрощаться.</Funeral.extraTextPawnDeathLetter>
```

2022-01-29 23:45 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <LeaderSpeech.description>Воодушевляющая речь, призванная поднять дух всех слушателей. Поселенцы соберутся, после чего лидер несколько часов будет произносить длинную речь. Если все пойдёт хорошо,
Из имеющегося перевода:
```suggestion
  <LeaderSpeech.description>Воодушевляющая речь, призванная поднять дух всех слушателей. Поселенцы соберутся, после чего лидер несколько часов будет произносить длинную речь. Если всё пройдёт гладко, речь вдохновит слушателей, а оратор укрепит свой авторитет. Если нет — она принесёт только вред.</LeaderSpeech.description>
```

2022-01-29 23:45 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <ScarificationCeremony.description>Ритуальное шрамирование, в ходе которой на коже цели будут вырезаны идеолигиозные символы. В начале присутствующие прослушают речь, после чего будет проведено шра
Опять страдательный залог. Предлагаю ввести резчика и сюда тоже
```suggestion
  <ScarificationCeremony.description>Ритуальное шрамирование, в ходе которой на коже жертвы будут вырезаны идеолигиозные символы. В начале резчик произнесёт речь, потом проведёт шрамирование и в конце скажет несколько заключительных слов.</ScarificationCeremony.description>
```

2022-01-29 23:45 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <Trial.description>Судебный процесс по какому-то ужасному обвинению. Обвинитель инкриминирует кому-то некое чудовищное злодеяние. Присутствующие будут слушать, как обвинитель и обвиняемый защищают
```suggestion
  <Trial.description>Судебный процесс по сложному делу. Обвинитель инкриминирует обвиняемому некое чудовищное злодеяние. Затем присутствующие будут слушать, как обвинитель и обвиняемый защищают свои позиции, и наконец решат, виновен ли обвиняемый. Если обвиняемый будет признан виновным, вы сможете изгнать его, арестовать или казнить, и никто не будет возражать. Вероятность обвинительного приговора зависит от социальных навыков обвиняемого и обвинителя, а также от количества собравшихся зрителей.</Trial.description>
```
Ниже - аналогично

2022-02-13 18:10 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <Funeral.description>Собрание у могилы погибшего последователя во время его погребения. Если тело было уничтожено, можно использовать пустую могилу. Рабы похорон не получают.</Funeral.description>
```suggestion
  <Funeral.description>Собрание у могилы погибшего последователя во время его погребения. Если тело было уничтожено, можно использовать пустую могилу. Рабов не хоронят.</Funeral.description>
```

Тогда уж так.
Такую кальку просто пару раз слышал, мне ненормальным не показалось.

2022-02-13 18:11 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <Funeral.extraTextPawnDeathLetter>Необходимо устроить похороны для {PAWN_nameDef}, чтобы {PAWN_possessive} друзья и семья смогли с н{PAWN_objective} попрощаться.</Funeral.extraTextPawnDeathLetter>
Точно

2022-02-13 18:11 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <ScarificationCeremony.description>Ритуальное шрамирование, в ходе которой на коже цели будут вырезаны идеолигиозные символы. В начале присутствующие прослушают речь, после чего будет проведено шра
Никаких резчиков.

2022-02-13 18:12 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_SpouseCount.xml
> +  <SpouseCount_Female_MaxFour.description>У женщины может быть до четырёх супругов.</SpouseCount_Female_MaxFour.description>
0_0
Очень давно как.

2022-02-13 18:12 UTC, kamadz commented on Ideology/DefInjected/PreceptDef/Precepts_SpouseCount.xml
> +  <SpouseCount_Female_MaxFour.description>У женщины может быть до четырёх супругов.</SpouseCount_Female_MaxFour.description>
Именно поэтому используется нейтральное spouse, а не то, что ты предложил

2022-02-19 11:50 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <TrialMentalState.description>Судебный процесс по какому-то ужасному обвинению. Обвинитель инкриминирует кому-то некое чудовищное злодеяние. Присутствующие будут слушать, как обвинитель и обвиняемы
```suggestion
  <TrialMentalState.description>Судебный процесс по сложному делу. Обвинитель инкриминирует обвиняемому некое чудовищное злодеяние. Затем присутствующие будут слушать, как обвинитель и обвиняемый защищают свои позиции, и наконец решат, виновен ли обвиняемый. Если обвиняемый будет признан виновным, вы сможете изгнать его, арестовать или казнить, и никто не будет возражать. Вероятность обвинительного приговора зависит от социальных навыков обвиняемого и обвинителя, а также от количества собравшихся зрителей.</TrialMentalState.description>
```

2022-02-19 11:51 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <TrialPrisoner.description>Судебный процесс по какому-то ужасному обвинению. Обвинитель инкриминирует кому-то некое чудовищное злодеяние. Присутствующие будут слушать, как обвинитель и обвиняемый з
```suggestion
  <TrialPrisoner.description>Судебный процесс по сложному делу. Обвинитель инкриминирует обвиняемому некое чудовищное злодеяние. Затем присутствующие будут слушать, как обвинитель и обвиняемый защищают свои позиции, и наконец решат, виновен ли обвиняемый. Если обвиняемый будет признан виновным, вы сможете изгнать его, арестовать или казнить, и никто не будет возражать. Вероятность обвинительного приговора зависит от социальных навыков обвиняемого и обвинителя, а также от количества собравшихся зрителей.</TrialPrisoner.description>
```

2022-02-19 11:58 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Raiders.xml
> +  <Raiding_Respected.comps.0.thoughtStageDescriptions.0>Менее {DAYSSINCELASTRAIDTHRESHOLD} дней с последнего нашего налёта</Raiding_Respected.comps.0.thoughtStageDescriptions.0>
```suggestion
  <Raiding_Respected.comps.0.thoughtStageDescriptions.0>Менее {DAYSSINCELASTRAIDTHRESHOLD} дней с нашего последнего налёта</Raiding_Respected.comps.0.thoughtStageDescriptions.0>
```

2022-02-19 11:59 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Raiders.xml
> +  <Raiding_Respected.comps.0.thoughtStageDescriptions.1>Более {DAYSSINCELASTRAIDTHRESHOLD} дней с последнего нашего налёта</Raiding_Respected.comps.0.thoughtStageDescriptions.1>
```suggestion
  <Raiding_Respected.comps.0.thoughtStageDescriptions.1>Более {DAYSSINCELASTRAIDTHRESHOLD} дней с нашего последнего налёта</Raiding_Respected.comps.0.thoughtStageDescriptions.1>
```

2022-02-19 12:00 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Relics.xml
> +  <IdeoRelic.description>Идеолигическая реликвия.</IdeoRelic.description>
```suggestion
  <IdeoRelic.description>Идеолигиозная реликвия.</IdeoRelic.description>
```

2022-02-19 12:00 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_RitualSeats.xml
> +  <IdeoRitualSeat.description>Мебель идеолигического назначения. Последователи здесь сидят или стоят на коленях, наблюдая за ритуалами.</IdeoRitualSeat.description>
```suggestion
  <IdeoRitualSeat.description>Мебель идеолигиозного назначения. Последователи здесь сидят или стоят на коленях, наблюдая за ритуалами.</IdeoRitualSeat.description>
```

2022-02-19 12:53 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <BlindingCeremony.description>Ритуал, в ходе которого цель будет лишена зрения. Присутствующие будут наблюдать, как цели будут вырезаны оба глаза, после чего будет произнесена короткая речь. По око
```suggestion
  <BlindingCeremony.description>Исполнитель ослепит жертву ритуальным ножом. Зрители будут наблюдать, как исполнитель произносит речь, вырезает оба глаза жертвы и произносит несколько заключительных слов. У жертвы начнётся кровотечение, и ей потребуется немедленная медицинская помощь.</BlindingCeremony.description>
```

2022-02-19 12:54 UTC, Elevator89 commented on Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
> +  <ScarificationCeremony.description>Ритуальное шрамирование, в ходе которой на коже цели будут вырезаны идеолигиозные символы. В начале присутствующие прослушают речь, после чего будет проведено шра
```suggestion
  <ScarificationCeremony.description>Ритуальное шрамирование, в ходе которой на коже жертвы будут вырезаны идеолигиозные символы. В начале исполнитель произнесёт речь, потом проведёт шрамирование и в конце скажет несколько заключительных слов.</ScarificationCeremony.description>
```

2022-02-19 13:11 UTC, Elevator89 approved these changes

2022-02-19 13:11 UTC, merged