#1295 Translate Ieology ThoughtDef 6, part 2
Ludeon/RimWorld-ru pull request #1373
Opened 2022-03-08 15:52 UTC by Elevator89

Close #1295

2022-03-12 15:45 UTC, BlitGaming requested changes

2022-03-12 15:45 UTC, BlitGaming commented on Ideology/DefInjected/ThoughtDef/Precepts_Scarification.xml
> +  <Scarification_Extreme_Opinion.stages.not_scarified.label>не шрамирован(а)</Scarification_Extreme_Opinion.stages.not_scarified.label>
Здесь нельзя использовать переменную PAWN_gender?

2022-03-12 15:45 UTC, BlitGaming commented on Ideology/DefInjected/ThoughtDef/Precepts_Scarification.xml
> +  <ScarificationCeremony_Know_Horrible.stages.Scarification_ceremony.description>Мы изуродовали нашего же поселенца против его идеолигиозных взглядов! Так делать нельзя!</ScarificationCeremony_Know_H
```suggestion
  <ScarificationCeremony_Know_Horrible.stages.Scarification_ceremony.description>Мы изуродовали нашего же поселенца против его идеологических взглядов! Так делать нельзя!</ScarificationCeremony_Know_Horrible.stages.Scarification_ceremony.description>
```
Так читается естественнее + в русском языке нет такого слова.

2022-03-12 15:45 UTC, BlitGaming commented on Ideology/DefInjected/ThoughtDef/Precepts_Skullspike.xml
> +  <Skullspike_Desired.stages.skullspikes-0.description>Рядом с нами несколько колов с черепами. Они говорят о том, что мы сильны.</Skullspike_Desired.stages.skullspikes-0.description>
```suggestion
  <Skullspike_Desired.stages.skullspikes-0.description>Мы сделали несколько черепов на кольях. Они послужат напоминанием того, что мы сильны.</Skullspike_Desired.stages.skullspikes-0.description>
```
**I have been around ... recently.**.
Время Present Perfect, действие полностью законченное в прошлом, но имеющее связь с настоящим через результат. Этот перевод более *достоверный*.

2022-03-12 15:45 UTC, BlitGaming commented on Ideology/DefInjected/ThoughtDef/Precepts_Skullspike.xml
> +  <Skullspike_Desired.stages.skullspikes-1.description>Рядом с нами много колов с черепами. Пусть все нас боятся.</Skullspike_Desired.stages.skullspikes-1.description>
```suggestion
  <Skullspike_Desired.stages.skullspikes-1.description>Мы сделали несколько черепов на кольях. Пусть все нас боятся.</Skullspike_Desired.stages.skullspikes-1.description>
```

2022-03-12 15:45 UTC, BlitGaming commented on Ideology/DefInjected/ThoughtDef/Precepts_Skullspike.xml
> +  <Skullspike_Disapproved.stages.skullspikes-0.description>Рядом с нами несколько колов с черепами. Их не то чтобы много, но всё равно неприятно.</Skullspike_Disapproved.stages.skullspikes-0.descript
```suggestion
  <Skullspike_Disapproved.stages.skullspikes-0.description>Рядом с нами несколько черепов на кольях. Их не то чтобы много, но это всё равно неприятно.</Skullspike_Disapproved.stages.skullspikes-0.description>
```

2022-03-12 15:45 UTC, BlitGaming commented on Ideology/DefInjected/ThoughtDef/Precepts_Skullspike.xml
> +  <Skullspike_Disapproved.stages.skullspikes-1.description>Рядом с нами много колов с черепами. Жутковато.</Skullspike_Disapproved.stages.skullspikes-1.description>
```suggestion
  <Skullspike_Disapproved.stages.skullspikes-1.description>Рядом с нами много черепов на кольях. Жутковато.</Skullspike_Disapproved.stages.skullspikes-1.description>
```

2022-03-12 15:45 UTC, BlitGaming commented on Ideology/DefInjected/ThoughtDef/Precepts_Skullspike.xml
> +  <Skullspike_Disapproved.stages.skullspikes-2.description>Почему вокруг меня целый лес из колов с черепами? Это же просто жутко!</Skullspike_Disapproved.stages.skullspikes-2.description>
```suggestion
  <Skullspike_Disapproved.stages.skullspikes-2.description>Почему вокруг меня целый лес из колов с черепами? Это же просто чудовищно!</Skullspike_Disapproved.stages.skullspikes-2.description>
```

2022-03-13 13:55 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Ranching.xml
> +  <Ranching_Central_AnimalMassPerCapita.stages.few_animals.label>мало животных</Ranching_Central_AnimalMassPerCapita.stages.few_animals.label>
"Few" - значит не немного, а именно что "мало", в значении - "не хватает". Более того, мысль даёт дебаф к настроению. Поэтому "мало" здесь абсолютно уместно и правильно.
"У нас мало животных" - вполне нормальная фраза, и звучит естественно.

2022-03-13 13:57 UTC, BlitGaming commented on Ideology/DefInjected/ThoughtDef/Precepts_Ranching.xml
> +  <Ranching_Central_AnimalMassPerCapita.stages.few_animals.label>мало животных</Ranching_Central_AnimalMassPerCapita.stages.few_animals.label>
> "Few" - значит не "немного", а именно что "мало", в значении "не хватает". Более того, мысль даёт дебаф к настроению. Поэтому "мало" здесь абсолютно уместно и правильно. "У нас мало животных" - вполне нормальная фраза, и звучит естественно.

Я просто предположил, что могут существовать фразы, где это будет звучать неестественно, тогда в будущем может возникнуть необходимость исправления этой проблемы.

2022-03-13 14:00 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Scarification.xml
> +  <Scarification_Extreme_Opinion.stages.not_scarified.label>не шрамирован(а)</Scarification_Extreme_Opinion.stages.not_scarified.label>
Нельзя, к сожалению. Более того, label и не будет нигде использоваться, ибо в списке мыслей её не будет. Это "социальная" мысль, её можно найти во вкладке "Социум", и там будет применяться labelSocial, а не просто label

2022-03-13 14:02 UTC, BlitGaming commented on Ideology/DefInjected/ThoughtDef/Precepts_Scarification.xml
> +  <Scarification_Extreme_Opinion.stages.not_scarified.label>не шрамирован(а)</Scarification_Extreme_Opinion.stages.not_scarified.label>
> Нельзя, к сожалению. Более того, label и не будет нигде использоваться, ибо в списке мыслей её не будет. Это "социальная" мысль, её можно найти во вкладке "Социум", и там будет применяться labelSocial, а не просто label

Буду учитывать это при переводе, спасибо

2022-03-13 14:04 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Scarification.xml
> +  <ScarificationCeremony_Know_Horrible.stages.Scarification_ceremony.description>Мы изуродовали нашего же поселенца против его идеолигиозных взглядов! Так делать нельзя!</ScarificationCeremony_Know_H
Ideoligion - игровой неологизм, и мы переводим его соответственно: как смешение слов "идеология" и "религия". Все производные слова мы формируем из последней части, поэтому - **_"идеолигиозный"_**, а не "идеолигический"

2022-03-13 14:21 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Skullspike.xml
> +  <Skullspike_Desired.stages.skullspikes-0.description>Рядом с нами несколько колов с черепами. Они говорят о том, что мы сильны.</Skullspike_Desired.stages.skullspikes-0.description>
Почему "I **_have been_** around a few skullspikes recently" ты переводишь как "Мы **_сделали_** несколько черепов на кольях"? Где здесь достоверность? Мысль связана не с тем, что черепа изготовлены, а с тем, что несколько кольев с ними торчат рядом, и персонажу это нравится.

"I have been around a few skullspikes recently" дословно означает "Я недавно был рядом с несколькими черепами на кольях". Но по-русски так не скажешь. Да и переводим мы не дословно, а по смыслу и по механике игры.

А по смыслу и механике мысль относится к классу "ситуативных", то есть меняется в зависимости от ситуации, а не от того, что персонаж когда-то увидел и запомнил. Уберёшь колья - мысль исчезнет. Поэтому я бы не стал здесь вообще к Present Perfect привязываться: он и в оригинале не уместен. Для персонажа главное, что колья стоят **_сейчас._**

2022-03-13 14:22 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Skullspike.xml
> +  <Skullspike_Desired.stages.skullspikes-1.description>Рядом с нами много колов с черепами. Пусть все нас боятся.</Skullspike_Desired.stages.skullspikes-1.description>
Аналогично, см. предыдущий коммент

2022-03-13 14:26 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Skullspike.xml
> +  <Skullspike_Desired.stages.skullspikes-0.description>Рядом с нами несколько колов с черепами. Они говорят о том, что мы сильны.</Skullspike_Desired.stages.skullspikes-0.description>
Ну вот, я такую простыню накатал, а ты взял и исправил )

2022-03-13 14:27 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Skullspike.xml
> +  <Skullspike_Desired.stages.skullspikes-1.description>Рядом с нами много колов с черепами. Пусть все нас боятся.</Skullspike_Desired.stages.skullspikes-1.description>
```suggestion
  <Skullspike_Desired.stages.skullspikes-1.description>Рядом с нами много черепов на кольях. Пусть все нас боятся.</Skullspike_Desired.stages.skullspikes-1.description>
```

2022-03-13 14:29 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Ranching.xml
> +  <Ranching_Central_AnimalMassPerCapita.stages.few_animals.label>мало животных</Ranching_Central_AnimalMassPerCapita.stages.few_animals.label>
Такие фразы, конечно, могут существовать. И мы стараемся неестественных фраз не допускать. Но фраза "мало животных" - не одна из них

2022-03-13 14:52 UTC, BlitGaming commented on Ideology/DefInjected/ThoughtDef/Precepts_Skullspike.xml
> +  <Skullspike_Desired.stages.skullspikes-0.description>Рядом с нами несколько колов с черепами. Они говорят о том, что мы сильны.</Skullspike_Desired.stages.skullspikes-0.description>
> Ну вот, я такую простыню накатал, а ты взял и исправил )

Блин, я старался исправить по быстрее, но не успел(

2022-03-24 11:42 UTC, merged