#1294 Translate thoughts about pain and organ use
Ludeon/RimWorld-ru pull request #1375
Opened 2022-03-11 16:57 UTC by BlitGaming

2022-03-13 21:38 UTC, Elevator89 requested changes

2022-03-13 21:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_OrganUse.xml
> +  <!-- Thought_Memory, null. Label: {PAWN}. Description: {PAWN} -->
Я добавил комментарии для того, чтобы ориентироваться в контексте и механике.

Thought_Memory - это класс мысли. Мысли класса `Thought_Memory` возникают после определённого события и держатся какое-то фиксированное время, вне зависимости от обстоятельств.

Следующим идёт класс ThoughtWorker'а, здесь он null.

Зная эти классы, можно при должном имении посмотреть в код и определить доступные символы.

Дальше идут сами доступные символы, найденные при анализе кода. Для полей `label` и `description` можно использовать символ `{PAWN}`. 

А символа может быть множество **под**символов. Один из самых ценных подсимволов символа `PAWN` - это `_gender`

2022-03-13 21:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_OrganUse.xml
> +  <HarvestedOrgan_Horrible.stages.harvested_organ.label>вырезанный орган</HarvestedOrgan_Horrible.stages.harvested_organ.label>
Аналогично. Кривой заголовок

2022-03-13 21:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_OrganUse.xml
> +  <HarvestedOrgan_Know_Abhorrent.stages.harvested_organ.label>вырезанный орган</HarvestedOrgan_Know_Abhorrent.stages.harvested_organ.label>
Социальные мысли (у которых в имени класса есть "Social") попадают во вкладку "Социум", а не "Потребности". Такие мысли возникают у персонажу по отношению к **_другому_** персонажу. У этих мыслей нет `description`, но можно определить поле `labelSocial`. И тогда именно оно будет использоваться в "Социуме". 

Обрати внимание, что для разных полей здесь доступен разный набор символов. 

Для `label` в случае `Thought_MemorySocial` в логике определены слишком сложные правила. Они не всегда нормально работают. Лучше определить именно `labelSocial`. А из `label` убрать все символы.
```suggestion
  <HarvestedOrgan_Know_Abhorrent.stages.harvested_organ.label>вырезал(а) орган</HarvestedOrgan_Know_Abhorrent.stages.harvested_organ.label>
  <HarvestedOrgan_Know_Abhorrent.stages.harvested_organ.labelSocial>{OTHERPAWN_gender ? вырезал : вырезала} орган</HarvestedOrgan_Know_Abhorrent.stages.harvested_organ.labelSocial>
```
Во всех социальных мыслях ниже надо сделать так же

2022-03-13 21:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_OrganUse.xml
> +  <HarvestedOrgan_Know_Abhorrent_Mood.stages.organ_harvested.description>Кто-то забрал части тела у нашего товарища. Это ужасно.</HarvestedOrgan_Know_Abhorrent_Mood.stages.organ_harvested.description
> Кто-то забрал части тела у нашего товарища

Такой дословный перевод звучит не по-русски и не канает. Надо переделать.

И здесь, и ниже.

2022-03-13 21:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_OrganUse.xml
> +  <InstalledOrgan_Abhorrent.stages.installed_organ.description>Мне пришлось вживить кому-то орган. Это отвратительное нарушение моей веры.</InstalledOrgan_Abhorrent.stages.installed_organ.description
"Кому-то" здесь не очень уместно. Потому что вжививший может очень хорошо знать, кому он вживил орган. Лучше написать так:
```suggestion
  <InstalledOrgan_Abhorrent.stages.installed_organ.description>Мне пришлось вживить человеку орган. Это отвратительное нарушение моей веры.</InstalledOrgan_Abhorrent.stages.installed_organ.description>

```
Ниже аналогичные случаи тоже надо исправить.

2022-03-13 21:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_OrganUse.xml
> +  <InstalledOrgan_Know_Abhorrent_Mood.stages.organ_harvested.description>Кто-то вживил кому-то орган. Тело должно быть неприкосновенным!</InstalledOrgan_Know_Abhorrent_Mood.stages.organ_harvested.des
"Кому-то" здесь не очень уместно. Отчасти потому, что персонаж может может очень хорошо знать и того, кто вживил орган, и того, кому его вживили. Лучше написать так:
```suggestion
  <InstalledOrgan_Know_Abhorrent_Mood.stages.organ_harvested.description>Один из нас вживил человеку орган. Тело должно быть неприкосновенным!</InstalledOrgan_Know_Abhorrent_Mood.stages.organ_harvested.description>

```
Аналогичные случаи ниже и выше тоже надо исправить.

2022-03-13 21:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Pain.xml
> +  <Pain_Idealized.stages.mindshattering_pain.description>Боль делает меня {PAWN_gender ? величественным : величественной}! Я хочу {PAWN_gender ? им : ей} стать!</Pain_Idealized.stages.mindshattering_
Уровни боли уже определены в переводе и устоялись. Ищи их в файле `Core\DefInjected\ThoughtDef\Thoughts_Situation_Special.xml`. Потом копируй их label'ы сюда

2022-03-13 21:38 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Pain.xml
> +  <Pain_Idealized.stages.mindshattering_pain.description>Боль делает меня {PAWN_gender ? величественным : величественной}! Я хочу {PAWN_gender ? им : ей} стать!</Pain_Idealized.stages.mindshattering_
> Боль делает меня {PAWN_gender ? величественным : величественной}! Я хочу {PAWN_gender ? им : ей} стать!

Всё описание абсолютно не годится: оно слишком дословно и надмозгово.

```
Боль превозносит меня! Я хочу стать ей!
```

2022-03-14 08:28 UTC, BlitGaming commented on Ideology/DefInjected/ThoughtDef/Precepts_OrganUse.xml
> +  <!-- Thought_Memory, null. Label: {PAWN}. Description: {PAWN} -->
А как через код игры узнать, какие есть подсимволы?
Кстати, Thought_Memory не соответствует стандарту наименований C#, очень странно, что он есть в коде игры.

2022-03-14 10:05 UTC, BlitGaming commented on Ideology/DefInjected/ThoughtDef/Precepts_OrganUse.xml
> +  <HarvestedOrgan_Abhorrent.stages.harvested_organ.description>Мне пришлось вырезать чей-то орган. Это отвратительное нарушение моей веры.</HarvestedOrgan_Abhorrent.stages.harvested_organ.description
Можно ещё как "Это отвратительное оскорбление всего, во что я верю!" или "Это отвратительное оскорбление моей веры!".
Какой вариант лучше?

2022-03-14 15:47 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_OrganUse.xml
> +  <!-- Thought_Memory, null. Label: {PAWN}. Description: {PAWN} -->
> В классе Thought_Memory есть поле otherPawn с типом Pawn, в комментарии подписано, что можно использовать PAWN, но почему тогда поле называется otherPawn? Просто интересно.

Поля класса и символы доступные в локализации слабо коррелируют друг с другом и точно не одно и тоже. Доступные символы определяются именованными аргументами форматируемой строки. 
Разрабы сделали свой навороченный аналог функции string.Format, где аргументы можно идентифицировать не только числами ({0}, {1}, {2} и т.д.), но и произвольными строками ({PAWN}, {OTHERPAWN}, {DAYS} и т.д.). А в качестве аргумента может выступать только тип, конвертируемый в строку, но и объект целиком. 
К данным такого объекта можно обратиться при помощи подсимволов. Корреляции с полями объекта здесь тоже не будет. Вместо прямого доступа используется самописный лексический анализатор подсимволов.

2022-03-19 15:12 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_OrganUse.xml
> +  <InstalledOrgan_Know_Abhorrent_Mood.stages.organ_harvested.label>вырезан орган</InstalledOrgan_Know_Abhorrent_Mood.stages.organ_harvested.label>
Очевидно же, что в оригинале ошибка
```suggestion
  <InstalledOrgan_Know_Abhorrent_Mood.stages.organ_harvested.label>{PAWN_gender ? вживил : вживила} орган</InstalledOrgan_Know_Abhorrent_Mood.stages.organ_harvested.label>

```

2022-03-19 15:12 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_OrganUse.xml
> +  <TradedOrgan_Know_Abhorrent_Mood.stages.organ_harvested.label>вырезан орган</TradedOrgan_Know_Abhorrent_Mood.stages.organ_harvested.label>
Ещё один косяк разрабов
```suggestion
  <TradedOrgan_Know_Abhorrent_Mood.stages.organ_harvested.label>{PAWN_gender ? продал : продала} орган</TradedOrgan_Know_Abhorrent_Mood.stages.organ_harvested.label>

```

2022-03-19 15:12 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_Pain.xml
> +  <Pain_Idealized.stages.mindshattering_pain.description>Боль делает меня {PAWN_gender ? величественным : величественной}! Я хочу {PAWN_gender ? им : ей} стать!</Pain_Idealized.stages.mindshattering_
label'ы не исправлены!

2022-03-19 15:16 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_OrganUse.xml
> +  <HarvestedOrgan_Abhorrent.stages.harvested_organ.description>Мне пришлось вырезать чей-то орган. Это ужасное надругательство над всем, во что я верю!</HarvestedOrgan_Abhorrent.stages.harvested_orga
```suggestion
  <HarvestedOrgan_Abhorrent.stages.harvested_organ.description>Мне пришлось вырезать человеку орган. Это ужасное надругательство над всем, во что я верю!</HarvestedOrgan_Abhorrent.stages.harvested_organ.description>

```

2022-03-19 15:16 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_OrganUse.xml
> +  <HarvestedOrgan_Horrible.stages.harvested_organ.description>Мне пришлось вырезать чей-то орган. Это ужасное оскорбление моих убеждений.</HarvestedOrgan_Horrible.stages.harvested_organ.description>
```suggestion
  <HarvestedOrgan_Horrible.stages.harvested_organ.description>Мне пришлось вырезать человеку орган. Это ужасное оскорбление моих убеждений.</HarvestedOrgan_Horrible.stages.harvested_organ.description>

```

2022-03-19 15:43 UTC, BlitGaming commented on Ideology/DefInjected/ThoughtDef/Precepts_Pain.xml
> +  <Pain_Idealized.stages.mindshattering_pain.description>Боль делает меня {PAWN_gender ? величественным : величественной}! Я хочу {PAWN_gender ? им : ей} стать!</Pain_Idealized.stages.mindshattering_
Пофиксил адскую боль

2022-03-19 15:48 UTC, merged