#1830 Translate ideo presets and more stuff
Ludeon/RimWorld-ru pull request #1382
Opened 2022-04-17 13:35 UTC by Elevator89

2022-04-23 15:14 UTC, BlitDev requested changes

2022-04-23 17:33 UTC, Elevator89 commented on Ideology/DefInjected/IdeoPresetCategoryDef/IdeoPresetDefs.xml
> +  <Intense.label>радикальные</Intense.label>
Речь об идеологиях во множественном числе
![изображение](https://user-images.githubusercontent.com/21694533/164919617-7541b54c-e667-41c5-ba26-357a26a6d4da.png)

2022-04-23 17:34 UTC, Elevator89 commented on Ideology/DefInjected/IdeoPresetCategoryDef/IdeoPresetDefs.xml
> +  <Mild.label>умеренные</Mild.label>
Ответил выше

2022-04-23 17:38 UTC, Elevator89 commented on Ideology/DefInjected/IdeoPresetCategoryDef/IdeoPresetDefs.xml
> +  <Mild.description>Около-классический геймплей с небольшими вариациями.</Mild.description>
Не согласен. Вариация - вполне употребимое литературное слово. 

А "разнообразие" здесь даже по смыслу не подходит.

2022-04-23 17:38 UTC, Elevator89 commented on Ideology/DefInjected/IdeoPresetCategoryDef/IdeoPresetDefs.xml
> +  <Strong.label>строгие</Strong.label>
Ответил выше

2022-04-23 18:18 UTC, Elevator89 commented on Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
> +  <Domination_Gang.description>Наши убеждения есть закон и истина. Те, кто не принимает наше учение, — гнусные недолюди, которых надо давить.\n\nОткрываются роли специалистов по ближнему бою и стрель
Перед "есть" не ставят тире.

2022-04-24 02:23 UTC, BlitDev commented on Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
> +  <Domination_Gang.description>Наши убеждения есть закон и истина. Те, кто не принимает наше учение, — гнусные недолюди, которых надо давить.\n\nОткрываются роли специалистов по ближнему бою и стрель
> Перед "есть" не ставят тире.

Просто с тире читается лучше. Я не силён в орфографии)

2022-04-24 13:16 UTC, Elevator89 commented on Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
> +  <Domination_Gang.description>Наши убеждения есть закон и истина. Те, кто не принимает наше учение, — гнусные недолюди, которых надо давить.\n\nОткрываются роли специалистов по ближнему бою и стрель
Тире - это про пунктуацию, а не про орфографию ). Надо или с ним, или с "есть". Но с "есть" фраза звучит пафоснее и смысл читается лучше.

2022-04-25 08:31 UTC, kamadz commented on Ideology/DefInjected/IdeoPresetCategoryDef/IdeoPresetDefs.xml
> +  <Mild.description>Около-классический геймплей с небольшими вариациями.</Mild.description>
Я бы перефразировал. 
```suggestion
  <Mild.description>Немного различающиеся разновидности около-классического геймплея.</Mild.description>
```

Если мы говорим о схожих по типу идеолигиях как о вариациях (можно поставить вместо "разновидности", кста) геймлея

2022-04-25 08:32 UTC, kamadz commented on Ideology/DefInjected/IdeoPresetCategoryDef/IdeoPresetDefs.xml
> +  <Mild.description>Около-классический геймплей с небольшими вариациями.</Mild.description>
```suggestion
  <Mild.description>Вариации около-классического геймплея.</Mild.description>
```
Или так

2022-04-25 08:35 UTC, kamadz commented on Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
> +  <Blindness_Cult.description>Слепота открывает внутреннее зрение, а страдание проливает свет истинного восприятия.\n\nОткрывается роль медицинского специалиста. Будут проводиться жертвоприношения, р
Низкий стиль. Одновременно с ожиданием и комфортом нормально перефразировать не могу, предлагаю так.
```suggestion
  <Blindness_Cult.description>Слепота открывает внутреннее зрение, а страдание проливает свет истинного восприятия.\n\nОткрывается роль медицинского специалиста. Будут проводиться жертвоприношения, ритуальные ослепления и шрамирования. Люди будут иметь пониженные требования к комфорту.</Blindness_Cult.description>
```

2022-04-25 08:38 UTC, kamadz commented on Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
> +  <Criminal_Gang.description>Следовать чужим идеям и работать целыми днями — для слабаков. Эта группа людей выживает за счёт грабежа других и сталкивается с самими разными убеждениями.\n\nОткрываются
Неуместная калька. Грабёж всегда направлен как кого-то и что-то другое. 

```suggestion
  <Criminal_Gang.description>Следовать чужим идеям и работать целыми днями — для слабаков. Эта группа людей выживает за счёт грабежа и сталкивается с самими разными убеждениями.\n\nОткрываются роли специалистов по ближнему бою и стрельбе. Будут проводиться гладиаторские дуэли.</Criminal_Gang.description>
```

2022-04-25 08:59 UTC, kamadz requested changes

2022-04-25 08:59 UTC, kamadz commented on Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
> +  <Criminal_Gang.description>Следовать чужим идеям и работать целыми днями — для слабаков. Эта группа людей выживает за счёт грабежа других и сталкивается с самими разными убеждениями.\n\nОткрываются
Не понимаю к чему "contact with diverse ideas", возможно ошибка райтинга. В текущем виде никакой информации не несёт, намного логичнее было бы предположить, что группа выживает за счёт грабежа и пестрит самыми разнообразными личностями (как обычно и бывает).  Предлагаю так;

```suggestion
  <Criminal_Gang.description>Следовать чужим идеям и работать целыми днями — для слабаков. Эта группа людей выживает за счёт грабежа других и пестрит разнообразием убеждений.\n\nОткрываются роли специалистов по ближнему бою и стрельбе. Будут проводиться гладиаторские дуэли.</Criminal_Gang.description>
```

2022-04-25 08:59 UTC, kamadz commented on Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
> +  <Domination_Gang.label>доминаторы</Domination_Gang.label>
А можно мы другое название придумаем?

2022-04-25 08:59 UTC, kamadz commented on Ideology/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
> +  <AllowCarnivore.description>Разрешить складывать сюда еду, подходящую для любителей мяса, но неприемлемую для вегетарианцев. Сюда будут попадать блюда в зависимости от их ингредиентов. Мясо насеком
```suggestion
  <AllowCarnivore.description>Разрешить складывать сюда еду, подходящую для любителей мяса, но неприемлемую для вегетарианцев. Сюда будут попадать блюда в зависимости от ингредиентов, кроме содержащих в себе мясо насекомых и людей.</AllowCarnivore.description>
```

2022-04-25 08:59 UTC, kamadz commented on Ideology/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
> +  <AllowInsectMeat.description>Разрешить складывать сюда еду, содержащую мясо насекомых. Сюда будут попадать блюда в зависимости от их ингредиентов.</AllowInsectMeat.description>
```suggestion
  <AllowInsectMeat.description>Разрешить складывать сюда еду, содержащую мясо насекомых. Сюда будут попадать блюда в зависимости от ингредиентов.</AllowInsectMeat.description>
```

2022-04-25 08:59 UTC, kamadz commented on Ideology/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
> +  <AllowVegetarian.description>Разрешить складывать сюда еду, подходящую для вегетарианцев, но неприемлемую тех, кто есть только мясо. Сюда будут попадать блюда в зависимости от их ингредиентов.</All
```suggestion
  <AllowVegetarian.description>Разрешить складывать сюда еду, подходящую для вегетарианцев, но неприемлемую тех, кто есть только мясо. Сюда будут попадать блюда в зависимости от ингредиентов.</AllowVegetarian.description>
```

2022-04-25 08:59 UTC, kamadz commented on Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
> +  <Feral_People.description>Мы — это животные, а животные — это мы. Мы — это деревья, мы живём рядом с ними и любим их так, как любим себя.\n\nОткрываются роли специалистов: агронома и животновода. У
```suggestion
  <Feral_People.description>Мы — это животные, а животные — это мы. Мы — это деревья, мы живём рядом с ними и любим их так, как любим себя.\n\nОткрываются роли специалистов: агронома и животновода. Улучшаются способности к приручению для всех поселенцев. Вырубка деревьев и забой животных — неприемлемы. Этим людям открыта более глубокая связь с древами Гауранлен.</Feral_People.description>
```

2022-04-25 08:59 UTC, kamadz commented on Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
> +  <Free_Ranchers.description>Община скотоводов, занимающихся охотой и разведением животных для пропитания. Имеют широкие взгляды на другие идеолигии, но не любят есть растительную пищу.\n\nОткрываетс
```suggestion
  <Free_Ranchers.description>Община скотоводов, занимающихся охотой и разведением животных для пропитания. Радушно относятся к другим мировоззрениям, но не любят есть растительную пищу.\n\nОткрывается роль специалиста-животновода.</Free_Ranchers.description>
```

2022-04-25 08:59 UTC, kamadz commented on Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
> +  <Painful_Purists.description>Страдание очищает и облагораживает. Аугментирование тела для облегчения жизни — презренный путь.\n\nОткрывается роль специалиста по медицине. Люди будут иметь пониженны
Как выше

2022-04-25 08:59 UTC, kamadz commented on Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
> +  <Violent_Dominators.label>кровавые доминаторы</Violent_Dominators.label>
аналогично

2022-04-29 13:28 UTC, Elevator89 commented on Ideology/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
> +  <AllowCannibal.description>Разрешить складывать сюда еду, подходящую для каннибалов. Сюда будут попадать блюда в зависимости от их ингредиентов.</AllowCannibal.description>
```suggestion
  <AllowCannibal.description>Разрешить складывать сюда еду, подходящую для каннибалов. Сюда будут попадать блюда в зависимости от ингредиентов.</AllowCannibal.description>
```

2022-04-29 13:28 UTC, Elevator89 commented on Ideology/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
> +  <AllowCarnivore.description>Разрешить складывать сюда еду, подходящую для любителей мяса, но неприемлемую для вегетарианцев. Сюда будут попадать блюда в зависимости от их ингредиентов. Мясо насеком
```suggestion
  <AllowCarnivore.description>Разрешить складывать сюда еду, подходящую для любителей мяса, но неприемлемую для вегетарианцев. Сюда будут попадать блюда в зависимости от ингредиентов. Мясо насекомых и людей сюда не входит.</AllowCarnivore.description>
```

2022-04-29 13:34 UTC, Elevator89 commented on Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
> +  <Domination_Gang.label>доминаторы</Domination_Gang.label>
На ум приходят только "агрессоры"

2022-04-29 14:55 UTC, Elevator89 commented on Ideology/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
> +  <AllowCarnivore.description>Разрешить складывать сюда еду, подходящую для любителей мяса, но неприемлемую для вегетарианцев. Сюда будут попадать блюда в зависимости от их ингредиентов. Мясо насеком
Этот оборот звучит не очень естественно. Я бы оставил разные предложения:
```
Сюда будут попадать блюда в зависимости от ингредиентов. Мясо насекомых, людей и блюда с ними в эту категорию не входят.
```

2022-05-03 13:35 UTC, Elevator89 commented on Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
> +  <Domination_Gang.label>доминаторы</Domination_Gang.label>
```suggestion
  <Domination_Gang.label>завоеватели</Domination_Gang.label>
```

2022-05-03 13:35 UTC, Elevator89 commented on Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
> +  <Violent_Dominators.label>кровавые доминаторы</Violent_Dominators.label>
```suggestion
  <Violent_Dominators.label>кровавые завоеватели</Violent_Dominators.label>
```

2022-05-03 13:37 UTC, Elevator89 commented on Ideology/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
> +  <AllowCarnivore.description>Разрешить еду, подходящую для любителей мяса, но неприемлемую для вегетарианцев. Сюда будут попадать блюда в зависимости от ингредиентов. Мясо насекомых и людей сюда не
```suggestion
  <AllowCarnivore.description>Разрешить еду, подходящую для любителей мяса, но неприемлемую для вегетарианцев. Сюда будут попадать блюда в зависимости от ингредиентов. Мясо насекомых, людей и блюда с ними в эту категорию не входят.</AllowCarnivore.description>
```

2022-05-03 13:38 UTC, merged