#1293 Translate Precepts_IdeoDiversity.xml
Ludeon/RimWorld-ru pull request #1388
Opened 2022-06-20 21:59 UTC by Elevator89

2022-06-21 06:33 UTC, BlitDev requested changes

2022-06-21 06:33 UTC, BlitDev commented on Ideology/DefInjected/ThoughtDef/Precepts_IdeoDiversity.xml
> +  <IdeoDiversity_Abhorrent_ParticipatedInOthersRitual.stages.false_ritual.label>чужой ритуал</IdeoDiversity_Abhorrent_ParticipatedInOthersRitual.stages.false_ritual.label>
Здесь **false ritual** переводится как ***чужой*** и ***ложный*** ритуал. Нужно привести всё к одному варианту.

2022-06-23 21:37 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_IdeoDiversity.xml
> +  <IdeoDiversity_Abhorrent_ParticipatedInOthersRitual.stages.false_ritual.label>чужой ритуал</IdeoDiversity_Abhorrent_ParticipatedInOthersRitual.stages.false_ritual.label>
Действительно. Исправил

2022-06-26 17:30 UTC, kamadz commented on Ideology/DefInjected/ThoughtDef/Precepts_IdeoDiversity.xml
> +  <IdeoDiversity_Abhorrent_Uniform.stages.uniform_thoughts.description>Наша община свободна от недобрых чуждых мыслей, как и должно быть.</IdeoDiversity_Abhorrent_Uniform.stages.uniform_thoughts.desc
```suggestion
  <IdeoDiversity_Abhorrent_Uniform.stages.uniform_thoughts.description>Наша община свободна от дурных помыслов, как и должно быть.</IdeoDiversity_Abhorrent_Uniform.stages.uniform_thoughts.description>
```
Тут не просто про мысли, имхо,, а про мысли, которые потом во что-то результируют, ака помыслы

2022-06-26 18:26 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_IdeoDiversity.xml
> +  <IdeoDiversity_Abhorrent_Uniform.stages.uniform_thoughts.description>Наша община свободна от недобрых чуждых мыслей, как и должно быть.</IdeoDiversity_Abhorrent_Uniform.stages.uniform_thoughts.desc
Я намеренно здесь отошёл от оригинала, чтобы лучше передать остроту эмоциональной окраски неприяния чужих идеолигий.

Сейчас есть такая градация от меньшей ксенофобии к большей:

- IdeoDiversity_Disapproved_Uniform — Наша община свободна от всяких глупостей, как и должно быть.
- IdeoDiversity_Horrible_Uniform — Наше поселение свободно от скверных идей, как и должно быть.
- IdeoDiversity_Abhorrent_Uniform — Наша община свободна от недобрых чуждых мыслей, как и должно быть.

И я думаю, что "дурные помыслы" звучат всё же недостаточно ксенофобно

2022-07-02 12:47 UTC, Elevator89 commented on Ideology/DefInjected/ThoughtDef/Precepts_IdeoDiversity.xml
> +  <IdeoDiversity_Abhorrent_Uniform.stages.uniform_thoughts.description>Наша община свободна от недобрых чуждых мыслей, как и должно быть.</IdeoDiversity_Abhorrent_Uniform.stages.uniform_thoughts.desc
```suggestion
  <IdeoDiversity_Abhorrent_Uniform.stages.uniform_thoughts.description>Наша община свободна от чуждых мыслей, как и должно быть.</IdeoDiversity_Abhorrent_Uniform.stages.uniform_thoughts.description>
```

2022-07-02 12:48 UTC, merged