Translate #1458 Biotech DefInjected Recipe
Ludeon/RimWorld-ru pull request #1522
Opened 2022-12-20 14:09 UTC by UrekMazin0

Close #1458 
Initial commit

2022-12-20 14:13 UTC, UrekMazin0 commented on Biotech/DefInjected/Recipe/Recipes_Food.xml
> +  <Make_BabyFoodBulk.description>Приготовить порцию детского питания, сбалансированного по питательным веществам овощного пюре для младенцев. Детское питание возможно приготовить в больших количества
>> сбалансированного по питательным веществам овощного пюре для младенцев

мне это не нравится, но пока не придумал как переделать

2022-12-20 14:13 UTC, UrekMazin0 commented on Biotech/DefInjected/Recipe/Recipes_MechResurrection.xml
> +  <ResurrectHeavyMech.description>Восстановить дружественного тяжёлого механоида. До тех пор, пока тело механоида не будет уничтожено полностью, оно подлежит восстановлению.</ResurrectHeavyMech.descr
[ressurect](https://dictionary.cambridge.org/ru/translate/) почти везде переводится как "возродить"
я везде вставил "восстановить", что с технической сущностью механоидов, как по мне, выглядит лучше

2023-01-05 22:14 UTC, Elevator89 reviewed
Продолжение следует

2023-01-05 22:14 UTC, Elevator89 commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <ExtractHemogenPack.description>Извлечь пакет с гемогеном из пациента. Операция будет безуспешной, если у пациента недостаточно крови.\n\nПакеты с гемогеном можно вводить другим пациентам, чтобы ум
```suggestion
  <ExtractHemogenPack.description>Получить гемоген-пакет из крови пациента. Этого не удастся сделать, если у пациента недостаточно крови.\n\nГемоген можно переливать другим пациентам для уменьшения последствия кровопотери или насыщения тех, кто питается кровью.</ExtractHemogenPack.description>
```

2023-01-06 20:31 UTC, Elevator89 commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <ImplantIUD.successfullyRemovedHediffMessage>{0} успешно имплантировал спираль в {1}.</ImplantIUD.successfullyRemovedHediffMessage>
Пол врача неизвестен. Подсимвол "_gender" нельзя применить. Придётся выкручиваться вот так:
```suggestion
  <ImplantIUD.successfullyRemovedHediffMessage>{0} успешно имплантирует спираль в {1}.</ImplantIUD.successfullyRemovedHediffMessage>
```

2023-01-06 20:31 UTC, Elevator89 commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <ImplantIUD.description>Имплантировать небольшое металлическое устройство в матку, чтобы предотвратить беременность пациентки. Позже его можно удалить, но есть небольшая вероятность того, что пацие
Тут стоит пояснить
```suggestion
  <ImplantIUD.description>Имплантировать небольшое металлическое устройство — внутриматочную спираль — в матку, чтобы предотвратить беременность пациентки. Позже его можно удалить, но есть небольшая вероятность того, что пациентка навсегда останется бесплодной. Эта операция прерывает беременность в первом триместре.</ImplantIUD.description>
```

2023-01-06 20:31 UTC, Elevator89 commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <RemoveIUD.description>Удалить имплантированную внутриматочную спираль, что обеспечивает возможность беременности. Если операция пройдёт неудачно, пациентка навсегда останется бесплодной.</RemoveIU
```suggestion
  <RemoveIUD.description>Удалить имплантированную внутриматочную спираль, обеспечивая возможность беременности. Если операция пройдёт неудачно, пациентка навсегда останется бесплодной.</RemoveIUD.description>
```

2023-01-06 20:31 UTC, Elevator89 commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <ReverseVasectomy.successfullyRemovedHediffMessage>{0} успешно провёл обратную вазэктомию у {1}</ReverseVasectomy.successfullyRemovedHediffMessage>
```suggestion
  <ReverseVasectomy.successfullyRemovedHediffMessage>{0} успешно проводит обратную вазэктомию у {1}</ReverseVasectomy.successfullyRemovedHediffMessage>
```

2023-01-06 20:31 UTC, Elevator89 commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <Vasectomy.description>Перережьте семявыносящие протоки пациента, чтобы сделать его неспособным к деторождению. Если операция пройдет неудачно, пациент навсегда останется бесплодным.</Vasectomy.des
Мужики и так обычно не рожают детей )
```suggestion
  <Vasectomy.description>Перерезать семявыносящие протоки пациента, чтобы сделать его неспособным к зачатию. Если операция пройдет неудачно, пациент навсегда останется бесплодным.</Vasectomy.description>
```

2023-01-06 20:31 UTC, Elevator89 commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <Vasectomy.successfullyRemovedHediffMessage>{0} успешно провёл вазэктомию у {1}.</Vasectomy.successfullyRemovedHediffMessage>
```suggestion
  <Vasectomy.successfullyRemovedHediffMessage>{0} успешно проводит вазэктомию у {1}.</Vasectomy.successfullyRemovedHediffMessage>
```

2023-01-07 17:29 UTC, Elevator89 commented on Biotech/DefInjected/Recipe/Recipes_Food.xml
> +  <Make_BabyFoodBulk.description>Приготовить порцию детского питания — сбалансированное по питательным веществам овощное пюре для младенцев. Такую еду можно приготовить в больших количествах, но её п
```suggestion
  <Make_BabyFoodBulk.description>Приготовить 4 порции детского питания — сбалансированного по питательным веществам овощного пюре для младенцев. Такую еду можно приготовить в больших количествах, но её пресный вкус и кашеобразную консистенцию в полной мере оценят только младенцы.</Make_BabyFoodBulk.description>
```

2023-01-08 20:46 UTC, kamadz commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <BloodTransfusion.description>Использовать гемоген-пакеты для уменьшения последствия кровопотери. Каждый пакет восстанавливает 35% от общего количества крови. Операция также восстанавливает гемоген
```suggestion
  <BloodTransfusion.description>Использовать гемоген-пакеты для уменьшения последствий кровопотери. Каждый пакет восстанавливает 35% от общего количества крови. Операция также восстанавливает гемоген у гемогеничных существ.</BloodTransfusion.description>
```
Насколько я помню, у кровопотери больше одного последствия

2023-01-08 20:47 UTC, kamadz commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <BloodTransfusion.description>Использовать гемоген-пакеты для уменьшения последствия кровопотери. Каждый пакет восстанавливает 35% от общего количества крови. Операция также восстанавливает гемоген
Аналогично ниже

2023-01-08 21:11 UTC, kamadz commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <ExtractHemogenPack.jobString>Извлекает пакет гемогена</ExtractHemogenPack.jobString>
так пакет гемогена или гемоген-пакет?

2023-01-08 21:16 UTC, kamadz commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <ExtractOvum.description>Извлечь яйцеклетку в капсулу для хранения. Затем яйцеклетка может быть оплодотворена мужчиной и в конечном итоге имплантирована матери для начала беременности.</ExtractOvum
to start a pregnancy - и в оригинале звучит по-ублюдски, зачем дословный перевод?
Беременность нельзя начать, беременной можно стать, беременность может прийти или начаться в конце концов.  В английском аналогично так не работает, райтер совершил грубую ошибку, повторять её не надо.

```suggestion
  <ExtractOvum.description>Извлечь яйцеклетку в капсулу для хранения. Затем яйцеклетка может быть оплодотворена мужчиной и в конечном итоге имплантирована матери для дальнейшего развития.</ExtractOvum.description>
```
Развития яйеклетки в плод, если непонятно.

2023-01-08 21:21 UTC, kamadz commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <ImplantEmbryo.description>Имплантировать эмбрион суррогатной матери, чтобы инициировать беременность.</ImplantEmbryo.description>
Аналогично тому, что сверху. Можно на предложенный вариант ИМХО.

2023-01-08 21:28 UTC, kamadz commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <ImplantIUD.description>Имплантировать небольшое металлическое устройство — внутриматочную спираль — в матку, чтобы предотвратить беременность пациентки. Позже его можно удалить, но есть небольшая
```suggestion
  <ImplantIUD.description>Имплантировать миниатюрную металлическую спираль в матку, чтобы предотвратить беременность пациентки. Позже её можно удалить, но есть небольшая вероятность того, что пациентка навсегда останется бесплодной. Эта операция прерывает беременность в первом триместре.</ImplantIUD.description>
```
Нам правда надо называть металлическую спиральку на куске медицинского силикона "устройством"?

2023-01-08 21:29 UTC, kamadz commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <ImplantXenogerm.description>Вживить ксеносемя в пациента. Эта операция заменяет предыдущие ксеносемя, если оно имелось.</ImplantXenogerm.description>
```suggestion
  <ImplantXenogerm.description>Вживить ксеносемя в пациента. Эта операция заменяет предыдущее ксеносемя, если оно имелось.</ImplantXenogerm.description>
```
Очепятко

2023-01-08 21:30 UTC, kamadz commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <RemoveIUD.description>Удалить имплантированную внутриматочную спираль, обеспечивая возможность беременности. Если операция пройдёт неудачно, пациентка навсегда останется бесплодной.</RemoveIUD.des
```suggestion
  <RemoveIUD.description>Удалить имплантированную внутриматочную спираль, возвращая возможность возникновения беременности. Если операция пройдёт неудачно, пациентка навсегда останется бесплодной.</RemoveIUD.description>
```

2023-01-08 21:39 UTC, kamadz commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <TubalLigation.successfullyRemovedHediffMessage>{0} успешно выполнил перевязку маточных труб у {1}.</TubalLigation.successfullyRemovedHediffMessage>
Перевязка маточных труб - разговорное, максимум коммерческое название процедуры. Если следовать терминологии, это должна быть **стерелизация**.

2023-01-08 21:39 UTC, kamadz commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <RemoveIUD.description>Удалить имплантированную внутриматочную спираль, обеспечивая возможность беременности. Если операция пройдёт неудачно, пациентка навсегда останется бесплодной.</RemoveIUD.des
```suggestion
  <RemoveIUD.description>Удалить имплантированную внутриматочную спираль, возвращая пациентке способность забеременеть. Если операция пройдёт неудачно, пациентка навсегда останется бесплодной.</RemoveIUD.description>
```

2023-01-08 21:42 UTC, kamadz commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <Vasectomy.description>Перерезать семявыносящие протоки пациента, чтобы сделать его неспособным к зачатию. Если операция пройдет неудачно, пациент навсегда останется бесплодным.</Vasectomy.descript
Корректнее будет
```suggestion
  <Vasectomy.description>Удалить фрагменты семявыносящих протоков пациента, чтобы сделать его неспособным к зачатию. Если операция пройдет неудачно, пациент навсегда останется бесплодным.</Vasectomy.description>
```

2023-01-08 21:43 UTC, kamadz requested changes
!

2023-01-09 11:45 UTC, UrekMazin0 commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <TubalLigation.successfullyRemovedHediffMessage>{0} успешно выполнил перевязку маточных труб у {1}.</TubalLigation.successfullyRemovedHediffMessage>
Снизу есть тоже самое, только для мужчин. "Провести вазэктомию". Если оставлять здесь стерелизацию, предлагаю перевести точно так же для мужчин, а описание оставить прежним.

2023-01-09 21:27 UTC, Elevator89 commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <TubalLigation.successfullyRemovedHediffMessage>{0} успешно выполнил перевязку маточных труб у {1}.</TubalLigation.successfullyRemovedHediffMessage>
Пропустил )
```suggestion
  <TubalLigation.label>перевязать маточные трубы</TubalLigation.label>
  <!-- EN: Permanently render a patient sterile and unable to reproduce. -->
  <TubalLigation.description>Навсегда сделать пациентку бесплодной и неспособной к воспроизведению потомства.</TubalLigation.description>
  <!-- EN: performing tubal ligation on TargetA. -->
  <TubalLigation.jobString>Выполняет перевязку маточных труб у TargetA</TubalLigation.jobString>
  <!-- EN: {0} has successfully performed tubal ligation on {1}. -->
  <TubalLigation.successfullyRemovedHediffMessage>{0} успешно выполняет перевязку маточных труб у {1}.</TubalLigation.successfullyRemovedHediffMessage>
```

Делать "стерилизацию" смысле не вижу. Ничего коммерческого в "перевязке маточных труб" нет

2023-01-09 21:46 UTC, Elevator89 commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <ExtractHemogenPack.jobString>Извлекает пакет гемогена</ExtractHemogenPack.jobString>
В глоссарии - "гемоген-пакет". Давайте делать единообразно. В BloodTransfusion.description и ExtractHemogenPack.description надо вернуть "гемоген-пакет"

Конкретно в этой строке имеет смысл сделать, как в лейбле
```suggestion
  <ExtractHemogenPack.jobString>Откачивает гемоген</ExtractHemogenPack.jobString>
```

2023-01-09 21:47 UTC, Elevator89 commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <ExtractHemogenPack.description>Получить пакет гемогена из крови пациента. Этого не удастся сделать, если у пациента недостаточно крови.\n\nГемоген можно переливать другим пациентам для уменьшения
```suggestion
  <BloodTransfusion.description>Использовать гемоген-пакет для уменьшения последствий кровопотери. Каждый пакет восстанавливает 35% от общего количества крови. Операция также восстанавливает гемоген у гемогеничных существ.</BloodTransfusion.description>
  <!-- EN: performing blood transfusion on TargetA. -->
  <BloodTransfusion.jobString>Переливает кровь TargetA</BloodTransfusion.jobString>
  
  <!-- EN: extract hemogen pack -->
  <ExtractHemogenPack.label>откачать гемоген</ExtractHemogenPack.label>
  <!-- EN: Extract a hemogen pack from the target. The operation will fail to produce a hemogen pack if the target does not have enough blood.\n\nHemogen packs can be administered to others to reduce blood loss or to satiate those who feed on blood. -->
  <ExtractHemogenPack.description>Получить гемоген-пакет из крови пациента. Этого не удастся сделать, если у пациента недостаточно крови.\n\nГемоген можно переливать другим пациентам для уменьшения последствия кровопотери или насыщения тех, кто питается кровью.</ExtractHemogenPack.description>
```

2023-01-09 23:15 UTC, kamadz commented on Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml
> +  <ImplantEmbryo.description>Имплантировать эмбрион суррогатной матери, чтобы инициировать беременность.</ImplantEmbryo.description>
```suggestion
  <ImplantEmbryo.description>Имплантировать эмбрион суррогатной матери дальнейшего развития.</ImplantEmbryo.description>
```

2023-01-09 23:39 UTC, merged