Shorten UI, fix typos
Ludeon/RimWorld-ru pull request #1535
Opened 2023-02-12 15:09 UTC by Elevator89

2023-02-13 15:56 UTC, kamadz commented on Core/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
> +  <ColonistBanishedToDie.stages.colonist_banished_to_death.label>поселенец изгнан умирать</ColonistBanishedToDie.stages.colonist_banished_to_death.label>
Предложенный вариант не звучит, к сожалению, вообще. Можно изгнать, можно выгнать, например, на мороз или жару умирать, это разные действия с разным смыслом.

2023-02-13 15:56 UTC, kamadz commented on Core/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
> +  <PrisonerBanishedToDie.stages.prisoner_banished_to_death.label>пленник изгнан умирать</PrisonerBanishedToDie.stages.prisoner_banished_to_death.label>
аналогично

2023-02-13 15:57 UTC, kamadz requested changes
.

2023-02-13 16:01 UTC, kamadz commented on Core/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
> +  <ColonistBanishedToDie.stages.colonist_banished_to_death.label>поселенец изгнан умирать</ColonistBanishedToDie.stages.colonist_banished_to_death.label>
По-английски конструкция тоже звучит коряво, есчо

2023-02-19 16:56 UTC, Elevator89 commented on Core/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
> +  <ColonistBanishedToDie.stages.colonist_banished_to_death.label>поселенец изгнан умирать</ColonistBanishedToDie.stages.colonist_banished_to_death.label>
Первоначальный вариант на UI обрезается до "поселенец изгнан и брошен умир" — не годится.

Предлагай свой вариант

2023-02-25 21:24 UTC, kamadz commented on Core/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
> +  <ColonistBanishedToDie.stages.colonist_banished_to_death.label>поселенец изгнан умирать</ColonistBanishedToDie.stages.colonist_banished_to_death.label>
Под такой маленький лимит по символам не могу ничего разумное предложить. Может, мы оставим первоначальный вариант, но попросим разрабов просто лимит подвинуть?

2023-02-26 15:39 UTC, Elevator89 commented on Core/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
> +  <ColonistBanishedToDie.stages.colonist_banished_to_death.label>поселенец изгнан умирать</ColonistBanishedToDie.stages.colonist_banished_to_death.label>
Просить разрабов что-то подвинуть - тупиковый путь. Они неизвестно когда отреагируют. Плюс, при любых размерах UI найдётся фраза, которая в него не влезет.
Кроме подбора формулировки вариантов нет.
```suggestion
  <ColonistBanishedToDie.stages.colonist_banished_to_death.label>поселенец изгнан на смерть</ColonistBanishedToDie.stages.colonist_banished_to_death.label>
```
```suggestion
  <ColonistBanishedToDie.stages.colonist_banished_to_death.label>поселенец изгнан и умрёт</ColonistBanishedToDie.stages.colonist_banished_to_death.label>
```

2023-02-26 16:40 UTC, kamadz commented on Core/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
> +  <ColonistBanishedToDie.stages.colonist_banished_to_death.label>поселенец изгнан умирать</ColonistBanishedToDie.stages.colonist_banished_to_death.label>
второй вариант отличный, его

2023-02-26 16:48 UTC, Elevator89 commented on Core/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
> +  <PrisonerBanishedToDie.stages.prisoner_banished_to_death.label>пленник изгнан умирать</PrisonerBanishedToDie.stages.prisoner_banished_to_death.label>
```suggestion
  <PrisonerBanishedToDie.stages.prisoner_banished_to_death.label>пленник изгнан и умрёт</PrisonerBanishedToDie.stages.prisoner_banished_to_death.label>
```

2023-02-26 16:49 UTC, merged