Core 1.5: 1611 projects from update 1.5
Ludeon/RimWorld-ru pull request #1612
Opened 2024-04-16 16:53 UTC by xBLOKx

Не переведённые проекты из обновления 1.5

- Книжные полки
- Скрытый кабель
- Светильники (лампочка/факел/прожектор)
- Декоротивная двойная дверь
- Выравнивание/сглаживание поверхностей

2024-04-16 17:03 UTC, xBLOKx commented
С выравниванием поверхности как-то не особо получилось в плане того что их в игре 3 штуки. Одна выравнивает стены и пол, другая только пол и ещё одна только стены. Так и не решил как поступить с одинаковым названием. Возможно стоит заменить "Выровнить поверхность" на "Выровнять пол" или даже "Выровнять рельеф" (хотя последнее по моему не очень)

2024-04-19 11:35 UTC, kamadz requested changes

2024-04-19 11:35 UTC, kamadz commented on Core/DefInjected/ThingDef/Buildings_Power.xml
> +  <HiddenConduit.description>Скрытый провод для передачи электроэнергии. Он прочнее обычного кабеля, но также медленнее в строительстве и дороже.</HiddenConduit.description>
```suggestion
  <HiddenConduit.description>Скрытый провод для передачи электроэнергии. Прочнее обычного кабеля, но дольше строится и дороже.</HiddenConduit.description>
```

2024-04-19 11:35 UTC, kamadz commented on Core/DefInjected/ThingDef/Buildings_Structure.xml
> +  <OrnateDoor.description>Затейливо вырезанная двойная дверь, украшенная золотом. Для функционирования этой большой и тяжёлой двери необходимы прилегающие стены.</OrnateDoor.description>
```suggestion
  <OrnateDoor.description>Украшенная золотом дверь с затейливыми орнаментами. Этой большой и тяжёлой двери необходимы прилегающие стены.</OrnateDoor.description>
```

2024-04-19 11:35 UTC, kamadz commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothWalls>Выровнять стену</DesignatorSmoothWalls>
```suggestion
  <DesignatorSmoothWalls>Выровнять стены</DesignatorSmoothWalls>
```

2024-04-19 11:35 UTC, kamadz commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothWallsDesc>Обозначить необработанную каменную стену для выравнивания.</DesignatorSmoothWallsDesc>
```suggestion
  <DesignatorSmoothWallsDesc>Обозначить необработанные каменные стены для выравнивания.</DesignatorSmoothWallsDesc>
```

2024-04-19 11:35 UTC, kamadz commented on Core/DefInjected/ThingDef/Buildings_Furniture.xml
> +  <BookcaseSmall.label>книжный шкаф</BookcaseSmall.label>
```suggestion
  <BookcaseSmall.label>малый книжный шкаф</BookcaseSmall.label>
```

2024-04-19 11:35 UTC, kamadz commented on Core/DefInjected/ThingDef/Buildings_Furniture.xml
> +  <Bookcase.description>Широкий книжный шкаф для хранения и демонстрации до десяти книг. Книги, хранящиеся здесь, будут пассивно улучшать научную работу, выполняемую рядом, и увеличивать красоту книж
```suggestion
  <Bookcase.description>Широкий книжный шкаф, в который помещается до десяти книг. Хранящиеся в шкафу книги никогда не испортятся, а также будут ускорять изучение технологий поблизости и увеличивать красоту шкафа.</Bookcase.description>
```

2024-04-19 11:35 UTC, kamadz commented on Core/DefInjected/ThingDef/Buildings_Furniture.xml
> +  <BookcaseSmall.description>Узкий книжный шкаф для хранения и демонстрации до пяти книг. Книги, хранящиеся здесь, будут пассивно улучшать научную работу, выполняемую рядом, и увеличивать красоту кни
```suggestion
  <BookcaseSmall.description>Узкий книжный шкаф, в который помещается до пяти книг. Хранящиеся в шкафу книги никогда не испортятся, а также будут ускорять изучение технологий поблизости и увеличивать красоту шкафа.</BookcaseSmall.description>
```

2024-04-19 18:43 UTC, Reiquard commented on Core/DefInjected/ThingDef/Buildings_Furniture.xml
> +  <Bookcase.description>Широкий книжный шкаф для хранения и демонстрации до десяти книг. Книги, хранящиеся здесь, будут пассивно улучшать научную работу, выполняемую рядом, и увеличивать красоту книж
Немного изменил предложенный вариант:
- красота -> [привлекательность](https://github.com/Ludeon/RimWorld-ru/blob/1f9f2205a7228630d5dfdb788716236633a29f57/Core/DefInjected/StatDef/Stats_Basics_General.xml#L4-L5) _(как это отображается в игре)_
- портиться -> [ветшать](https://github.com/Ludeon/RimWorld-ru/blob/1f9f2205a7228630d5dfdb788716236633a29f57/Core/DefInjected/StatDef/Stats_Basics_General.xml#L24-L25)
- перенёс **ветшание** в конец предложения, чтобы разнести _**будут — не будут**_ (можно также вынести в отдельное предложение, как в оригинале)

```suggestion
  <Bookcase.description>Широкий книжный шкаф, в который помещается до десяти книг. Хранящиеся в шкафу книги будут ускорять изучение технологий поблизости и увеличивать привлекательность самого шкафа, а также не будут ветшать.</Bookcase.description>
```

2024-04-19 18:43 UTC, Reiquard commented on Core/DefInjected/ThingDef/Buildings_Furniture.xml
> +  <BookcaseSmall.description>Узкий книжный шкаф для хранения и демонстрации до пяти книг. Книги, хранящиеся здесь, будут пассивно улучшать научную работу, выполняемую рядом, и увеличивать красоту кни
```suggestion
  <BookcaseSmall.description>Узкий книжный шкаф, в который помещается до пяти книг. Хранящиеся в шкафу книги будут ускорять изучение технологий поблизости и увеличивать привлекательность самого шкафа, а также не будут ветшать.</BookcaseSmall.description>
```

2024-04-19 18:43 UTC, Reiquard commented on Core/DefInjected/ThingDef/Buildings_Furniture.xml
> +  <WallLamp.description>Настенный светильник, освещающий помещение с помощью электричества. Она менее мощная, чем обычная лампа, но может крепиться к стене.</WallLamp.description>
обычная лампа -> [торшер](https://github.com/Ludeon/RimWorld-ru/blob/1f9f2205a7228630d5dfdb788716236633a29f57/Core/DefInjected/ThingDef/Buildings_Furniture.xml#L94-L95)
```suggestion
  <WallLamp.description>Настенный светильник, освещающий помещение с помощью электричества. Менее мощный, чем торшер, но может крепиться к стене.</WallLamp.description>
```

2024-04-19 18:44 UTC, Reiquard commented on Core/DefInjected/ThingDef/Buildings_Furniture.xml
> +  <TorchWallLamp.description>Настенный деревянный факел для освещения территории. Он не такой яркий, как обычный факел, но его можно крепить на стены. Выделяет небольшое количество тепла.</TorchWallL
Замена игрового термина
факел -> [лампа-факел](https://github.com/Ludeon/RimWorld-ru/blob/1f9f2205a7228630d5dfdb788716236633a29f57/Core/DefInjected/ThingDef/Buildings_Furniture.xml#L131-L132)
Хотя формулировка `обычный факел` мне и самому больше по душе.

Унификация с представленным выше `настенным светильником` в части крепления к стене.

Кстати, может быть, стоит заменить `может крепиться к стене` на `может быть прикреплён к стене`?
```suggestion
  <TorchWallLamp.description>Настенный деревянный факел для освещения ближайшей области. Не такой яркий, как лампа-факел, но может крепиться к стене. Производит небольшое количество тепла.</TorchWallLamp.description>
```

2024-04-19 18:44 UTC, Reiquard commented on Core/DefInjected/ThingDef/Buildings_Structure.xml
> +  <OrnateDoor.label>декоративная дверь</OrnateDoor.label>
Возможно, так лучше
```suggestion
  <OrnateDoor.label>декорированная дверь</OrnateDoor.label>
```

2024-04-19 18:44 UTC, Reiquard commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothFloors>Выровнять поверхность</DesignatorSmoothFloors>
Конфликт (одинаковое название) с представленным в том же файле [DesignatorSmoothSurface](https://github.com/Ludeon/RimWorld-ru/blob/1f9f2205a7228630d5dfdb788716236633a29f57/Core/Keyed/Designators.xml#L56-L57)
Нужно указать, что это не просто поверхность, а именно горизонтальная _(floor)_ поверхность.

У меня пока идей нет, кроме как так и написать: `Выровнять горизонтальную поверхность`

2024-04-19 18:44 UTC, Reiquard commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothFloorsDesc>Обозначить необработанную каменную поверхность для выравнивания.</DesignatorSmoothFloorsDesc>
Здесь то же замечание, что и выше.

2024-04-19 21:58 UTC, kamadz commented on Core/DefInjected/ThingDef/Buildings_Furniture.xml
> +  <TorchWallLamp.description>Настенный деревянный факел для освещения территории. Он не такой яркий, как обычный факел, но его можно крепить на стены. Выделяет небольшое количество тепла.</TorchWallL
У нас ещё есть darklight torch, так что если под "обычным" подразумевать размещающийся на полу, то пусть лучше будет обычный

2024-04-19 22:01 UTC, kamadz commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothFloors>Выровнять поверхность</DesignatorSmoothFloors>
почему не использовать "пол" или "покрытие"?

2024-04-19 22:02 UTC, kamadz commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothFloors>Выровнять поверхность</DesignatorSmoothFloors>
+, если есть это работает только на каменные полы, почему бы и не написать "выровнять каменный пол"

2024-04-20 01:27 UTC, xBLOKx commented on Core/DefInjected/ThingDef/Buildings_Furniture.xml
> +  <TorchWallLamp.description>Настенный деревянный факел для освещения территории. Он не такой яркий, как обычный факел, но его можно крепить на стены. Выделяет небольшое количество тепла.</TorchWallL
Да, "обычный факел" ссылается имменно на альтернативную версию этого факела на полу. И пожалуй обычный звучит лучше чем торшр или лампа-факел. Но я согласен с [Reiquard]. По тому, что правильнее ссылаться на игровое название хоть и достаточно очивидно, что подразумевается под обычным. Это хорошее замечание.

А вот по поводу "Кстати, может быть, стоит заменить (может крепиться к стене) на (может быть прикреплён к стене)?" - думаю не стоит так как второй вариант звучит так будто может и не быть прикреплён к стене а это не так, он чисто настенный. По крайней мере так для меня выглядит такая формулировка.

2024-04-20 02:14 UTC, xBLOKx commented on Core/DefInjected/ThingDef/Buildings_Structure.xml
> +  <OrnateDoor.label>декоративная дверь</OrnateDoor.label>
Честно вопрос поставил меня в тупик. Я плохо понимаю трактовку этих слов и в чём тут разница. Первоначальный вариант мне нравится больше. Но возможно второй вариант просто более верное описание но гугл мне ситуацию не прояснил по этому вопросу. Так, что хз.

2024-04-20 02:45 UTC, xBLOKx commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothFloors>Выровнять поверхность</DesignatorSmoothFloors>
Коментарием выше я тоже обозначил проблему с именами выравнивания. Но совпадают они лишь у двух из трёх.

Smooth surface - пол и стены
Smooth Walls - стены
Smooth terrain - пол
Вроде так. И в случае (Smooth surface) лучше оставить как есть если нет иных замечаний к тексту. Так как "выровнять поверхность" в этом случае наиболее точный вариант. Со стенами "Smooth Walls" переведено тоже нормально.
А вот "Smooth terrain" действительно вызывает сомнения но не был уверен как лучше обозначить. Выровнять поверхность тоже подходит но учитывая, что выравнивает оно только пол и без стен то выходит не совсем верно а так же повторяется.
По этому лучше заменим на "выровнять пол". Почему не каменный пол? По тому, что тогда она выбивается из "выровнять поверхноть"/"выровнять стены" и придётся всем добавить слово каменные, что на мой взгляд излишне нагружает, лучше всё же иметь более локаничные названия. А про то, что выравниваются каменные поверхности можно прочесть в описании.

2024-04-20 02:49 UTC, xBLOKx commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothFloorsDesc>Обозначить необработанную каменную поверхность для выравнивания.</DesignatorSmoothFloorsDesc>
По моему это то же самое замечание, что и выше но только с более верно указанными строчками. По этому поводу отписался в предыдущем сообщении. Поменяю как только разберусь с тем как это технически реализовать(поспрашиваю в телеграме)

2024-04-20 13:49 UTC, Reiquard commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothFloors>Выровнять поверхность</DesignatorSmoothFloors>
Всё же [пол](https://gramota.ru/poisk?query=пол&mode=slovari&dicts[]=42&dicts[]=48&dicts[]=50) — это настильная часть искусственного сооружения.
Слегка выделяется здесь указанное в словаре словосочетание `земляной пол`, хотя он по-прежнему является частью сооружения.

[Покрытие](https://gramota.ru/poisk?query=покрытие&mode=slovari&dicts[]=42&dicts[]=48&dicts[]=50) (и оно не обязательно горизонтальное) — тоже неподходящий для нас вариант. Даже если отойти от указанных в словаре примеров, покрытие, как и настил, всё равно будет чем-то, что собой покрывает что-то, а это вряд ли применимо к каменному массиву.

В игре на текущий момент можно выровнять только `грубые` и `обтёсанные` горизонтальные поверхности, а также стены из:
- гранита
- известняка
- мрамора
- песчаника
- сланца (шиферного)

Учитывая вышесказанное ("земляной пол" и материал поверхности), в некоторой степени допускаю вариант `каменный пол` с соответствующей заменой **_стен_** на `каменные стены`.

2024-04-20 13:50 UTC, Reiquard commented on Core/DefInjected/ThingDef/Buildings_Structure.xml
> +  <OrnateDoor.label>декоративная дверь</OrnateDoor.label>
Слово [декоративный](https://kartaslov.ru/предложения-со-словом/декоративный) _зачастую_ характеризует предмет как лишённый практического, функционального применения и предназначенный сугубо для украшения.
А [декорированный](https://ru.wiktionary.org/wiki/декорированный) лишь добавляет новое качество к существующим основным.

2024-04-20 14:54 UTC, kamadz commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothFloors>Выровнять поверхность</DesignatorSmoothFloors>
"в некоторой степени допускаю вариант каменный пол с соответствующей заменой стен на каменные стены."
вот давай на этом и остановимся

2024-04-20 16:33 UTC, xBLOKx commented on Core/DefInjected/ThingDef/Buildings_Structure.xml
> +  <OrnateDoor.label>декоративная дверь</OrnateDoor.label>
> Слово [декоративный](https://kartaslov.ru/%D0%BF%D1%80%D0%B5%D0%B4%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F-%D1%81%D0%BE-%D1%81%D0%BB%D0%BE%D0%B2%D0%BE%D0%BC/%D0%B4%D0%B5%D0%BA%D0%BE%D1%80%D0%B0%D1%82%D0%B8%D0%B2%D0%BD%D1%8B%D0%B9) _зачастую_ характеризует предмет как лишённый практического, функционального применения и предназначенный сугубо для украшения. А [декорированный](https://ru.wiktionary.org/wiki/%D0%B4%D0%B5%D0%BA%D0%BE%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9) лишь добавляет новое качество к существующим основным.

Спасибо за пояснение. Тогда действительно "декорированная дверь" правильнее.

"дверь с орнаментом" или "декорированная дверь" Хм... Так то хотелось бы иметь наиболее локаничное название... Но "декорированная" на столько длинное слово, что не влезает рабиваясь на части, что убивает весь смысл. По этому всё же вариант с орнаментом чуть лучше по моему.

2024-04-20 16:36 UTC, xBLOKx commented on Core/DefInjected/ThingDef/Buildings_Structure.xml
> +  <OrnateDoor.label>декоративная дверь</OrnateDoor.label>
```suggestion
  <OrnateDoor.label>дверь с орнаментом</OrnateDoor.label>
```

2024-04-20 17:57 UTC, xBLOKx commented on Core/Keyed/Designators.xml
Заменил названия выравниваний поверхностей.
Добавил слово каменный ко всем 3 пунктмам (хотя на мой взгляд это слово лишнее и просто нагружает интерфейс не особо полезной информацией. На мой взгляд это слово можно убрать для локаничности названий а подробности в описании и так уже достаточно точны)

2024-04-20 18:01 UTC, xBLOKx commented on Core/Keyed/Designators.xml
>    <DesignatorSmoothFloorsDesc>Обозначить необработанную каменную поверхность для выравнивания.</DesignatorSmoothFloorsDesc>
Заменил названия выравниваний поверхностей.
Добавил слово каменный ко всем 3 пунктмам (хотя на мой взгляд это слово лишнее и просто нагружает интерфейс не особо полезной информацией. На мой взгляд это слово можно убрать для локаничности названий а подробности в описании и так уже достаточно точны)

2024-04-20 18:09 UTC, xBLOKx commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothFloors>Выровнять поверхность</DesignatorSmoothFloors>
Заменил названия. Теперь в другом комментарии так как хз как это было сделать в этом.

2024-04-20 18:30 UTC, Reiquard commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothSurfaceDesc>Обозначить необработанную каменную поверхность и стены для выравнивания.</DesignatorSmoothSurfaceDesc>
```suggestion
  <DesignatorSmoothSurfaceDesc>Обозначить необработанные каменные пол и стены для выравнивания.</DesignatorSmoothSurfaceDesc>
```

2024-04-20 18:31 UTC, Reiquard commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothWalls>Выровнять каменную стену</DesignatorSmoothWalls>
```suggestion
  <DesignatorSmoothWalls>Выровнять каменные стены</DesignatorSmoothWalls>
```

2024-04-20 18:32 UTC, Reiquard commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothFloorsDesc>Обозначить необработанную каменную поверхность для выравнивания.</DesignatorSmoothFloorsDesc>
```suggestion
  <DesignatorSmoothFloorsDesc>Обозначить необработанный каменный пол для выравнивания.</DesignatorSmoothFloorsDesc>
```

2024-04-20 20:37 UTC, xBLOKx commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothSurfaceDesc>Обозначить необработанную каменную поверхность и стены для выравнивания.</DesignatorSmoothSurfaceDesc>
```suggestion
  <DesignatorSmoothSurfaceDesc>Обозначить необработанные каменные полы и стены для выравнивания.</DesignatorSmoothSurfaceDesc>
```

2024-04-20 20:40 UTC, xBLOKx commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothWalls>Выровнять каменную стену</DesignatorSmoothWalls>
Тогда по этой логике надо всё переименовывать.
Выровнять каменные поверхности
Выровнять каменные стены
Выровнять каменный полы

По моему как то не очень тогда выглядит?

2024-04-20 20:49 UTC, Reiquard commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothWalls>Выровнять каменную стену</DesignatorSmoothWalls>
Я здесь вернул потерявшееся [изменение](https://github.com/Ludeon/RimWorld-ru/pull/1612#discussion_r1572233204).

2024-04-20 21:00 UTC, Reiquard commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothWalls>Выровнять каменную стену</DesignatorSmoothWalls>
> В игре не используется множественное чисто в названиях без необходимости.

В оригинале `Smooth walls`.

Думаю, правильно будет дождаться ответа @kamadz, это его правка была.

2024-04-20 21:02 UTC, xBLOKx commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothWalls>Выровнять каменную стену</DesignatorSmoothWalls>
> Я здесь вернул потерявшееся [изменение](https://github.com/Ludeon/RimWorld-ru/pull/1612#discussion_r1572233204).

Да, помню о нём, тогда просто согласился, но теперь подумал и кажется такое не совсем правильным.

2024-04-20 21:17 UTC, kamadz commented on Core/Keyed/Designators.xml
> +  <DesignatorSmoothWalls>Выровнять каменную стену</DesignatorSmoothWalls>
Оставляем единственное число.

2024-04-21 18:00 UTC, merged